### ISSUE TITLE
crypto channel: curveCP

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p#10]
> CurveCP is similar to TCP but uses high-speed high-security elliptic-curve cryptography to protect every packet against espionage, corruption, and sabotage. The cryptographic tools used in CurveCP are the same as the cryptographic tools used in DNSCurve. CurveCP was announced at the 27th Chaos Communication Congress on 28 December 2010.

I've been researching and learning about CurveCP and I'm currently trying the actual state of the project. The Alpha was released on Fev 2011 and since then, I haven't find any more updates on it. Is there anyone watching very familiar with the state of the project and who is currently actively contributing to it?

Reference Links:
- http://curvecp.org/
- 1st announcement (with DNSSec intro) http://cr.yp.to/talks/2010.12.28/slides.pdf

**Comment by achingbrain** [comment]
Closing due to (extreme) staleness.  If this is still relevant perhaps it can be picked up by [ResNetLab](https://github.com/protocol/ResNetLab).
