### ISSUE TITLE
npm install fails: 'TS2349: This expression is not callable'

### ISSUE THREAD

**Issue by christroutner** [libp2p/js-libp2p#1019]
- **Version**:

0.33.0

- **Platform**:

Linux trout-dev 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- **Subsystem**:

N/A

#### Severity:

High

#### Description:

Trying to install the `master` branch (commit a335fda) as well as the latest release (v0.33.0) commit, both fail on `npm install`

Node version: v14.17.6
npm version: 7.23.0
OS: Ubuntu 20.4

#### Steps to reproduce the error:

- `git clone` the repository.
- (optional) `git checkout v0.33.0`
- Run `npm install` and notice the following error:

```
npm ERR! code 1
npm ERR! path /home/trout/tmp/js-libp2p
npm ERR! command failed
npm ERR! command sh -c aegir build --no-bundle
npm ERR! [06:03:45] Clean ./dist [started]
npm ERR! [06:03:45] Clean ./dist [completed]
npm ERR! [06:03:45] Generate types [started]
npm ERR! src/nat-manager.js(118,11): error TS2349: This expression is not callable.
npm ERR!   Type 'typeof import("/home/trout/tmp/js-libp2p/node_modules/private-ip/lib/index")' has no call signatures.
npm ERR! [06:03:55] Generate types [failed]
npm ERR! [06:03:55] → Command failed with exit code 1: tsc --build /home/trout/tmp/js-libp2p/tsconfig-types.aegir.json
npm ERR! Command failed with exit code 1: tsc --build /home/trout/tmp/js-libp2p/tsconfig-types.aegir.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trout/.npm/_logs/2021-11-10T14_04_00_258Z-debug.log

```

**Comment by vasco-santos** [comment]
Thanks for reporting this @christroutner 

Likely some dependency creating this issue. I will get it fixed today

**Comment by vasco-santos** [comment]
Temporarily added a ts ignore on our end until `private-ip` module gets fixed
