### ISSUE TITLE
The property 'options.publicKeyEncoding.format' is invalid.

### ISSUE THREAD

**Issue by hnagrath09** [libp2p/js-libp2p#1049]
- **Version**: libp2p -> 0.35.1

- **Platform**: 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

#### Description:
While following the getting started documentation for libp2p js, I got hit by this error when using `node src/index.js` command.

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError [ERR_INVALID_ARG_VALUE]: The property 'options.publicKeyEncoding.format' is invalid. Received 'jwk'
    at new NodeError (node:internal/errors:363:5)
    at parseKeyFormat (node:internal/crypto/keys:268:9)
    at parseKeyFormatAndType (node:internal/crypto/keys:304:18)
    at parseKeyEncoding (node:internal/crypto/keys:332:7)
    at parsePublicKeyEncoding (node:internal/crypto/keys:371:10)
    at parseKeyEncoding (node:internal/crypto/keygen:125:9)
    at createJob (node:internal/crypto/keygen:161:42)
    at generateKeyPair (node:internal/crypto/keygen:75:15)
    at node:internal/util:335:7
    at new Promise (<anonymous>) {
  code: 'ERR_INVALID_ARG_VALUE'
}
```

I switched to `0.34.0` version of `libp2p` and everything seems to be working fine.

#### Steps to reproduce the error:
My `src/index.js` file:

```
const Libp2p = require("libp2p");
const TCP = require("libp2p-tcp");
const { NOISE } = require("libp2p-noise");
const MPLEX = require("libp2p-mplex");

const multiaddr = require("multiaddr");

const main = async () => {
  const node = await Libp2p.create({
    addresses: {
      // add a listen address (localhost) to accept TCP connections on a random port
      listen: ["/ip4/127.0.0.1/tcp/0"],
    },
    modules: {
      transport: [TCP],
      connEncryption: [NOISE],
      streamMuxer: [MPLEX],
    },
  });

  // start libp2p
  await node.start();
  console.log("libp2p has started");

  // print out listening addresses
  console.log("listening on addresses:");
  node.multiaddrs.forEach((addr) => {
    console.log(`${addr.toString()}/p2p/${node.peerId.toB58String()}`);
  });

  // stop libp2p
  await node.stop();
  console.log("libp2p has stopped");
};

main();
```

Received the above error after running `node src/index.js` command.

**Comment by achingbrain** [comment]
Please upgrade to node 16.

**Comment by hnagrath09** [comment]
> Please upgrade to node 16.

Using `node v16.3.0`. I am not seeing this issue in a new project which is using `0.35.2` version of `libp2p`. I guess we can close this issue.

**Comment by TimDaub** [comment]
> Please upgrade to node 16.

I can confirm that this works.

**Comment by vasco-santos** [comment]
Hey folks,

Thanks for reaching out. From `0.35` libp2p is only supported using Node15+ https://github.com/libp2p/js-libp2p/releases/tag/v0.35.0

Per https://nodejs.org/en/about/releases/#releases we are only supporting the Active releases of libp2p. Apologies for the inconvenience and let me know if this is a problem with a newer version of Node. Closing for now, but feel free to reopen
