### ISSUE TITLE
🦊 MetaMask

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p#106]
@kumavis I'm pulling https://github.com/ipfs/js-libp2p-ipfs-browser/issues/127 to here as I've converged all the testing and bundling to this module :) (also added a ton new [examples!](https://github.com/libp2p/js-libp2p/tree/master/examples))

Could you share an update in the state of MetaMask libp2p support? You had an awesome demo a while back, where can I find that video?

**Comment by kumavis** [comment]
I cant see the original issue but I think it was a general libp2p-metamask tracking issue

js-ipfs has been evoilving nicely and i've become more familiar with its internals, so things are moving forward

here is our tracking issue for it https://github.com/MetaMask/eth-ipfs-browser-client/issues/1

my work is now moving up from basic eth-ipfs integration to:
 - eth data availability via a parity bridge
 - advertising eth data availability via ENS / dht / pubsub / topic broadcasting
 - handling eth app interface (eth json rpc) via ipfs lookups

**Comment by kumavis** [comment]
here is a demo that I will show off on the next meeting https://kumavis.github.io/metamask-mesh/

**Comment by diasdavid** [comment]
ref: https://github.com/MetaMask/mesh-testing

**Comment by kumavis** [comment]
Having fun generating topo graphs and crashing the `ws-star` server.
Next goal is visualizing pub-sub message movements across the mesh : )

![image](https://user-images.githubusercontent.com/1474978/37115032-dd808774-21fe-11e8-8b57-a115de29f31b.png)

**Comment by achingbrain** [comment]
Closing due to staleness & the mesh project was abandoned.
