### ISSUE TITLE
tutorial error

### ISSUE THREAD

**Issue by zhaoyiming0803** [libp2p/js-libp2p#1066]
I wrote a demo according to the official guide(https://docs.libp2p.io/tutorials/getting-started/javascript/), but an error occurred in terminal

- **Version**:

``` json
"dependencies": {
    "libp2p": "^0.35.6"
  },
  "devDependencies": {
    "libp2p-mplex": "^0.10.5",
    "libp2p-noise": "^4.0.0",
    "libp2p-tcp": "^0.17.2",
    "multiaddr": "^10.0.1"
  }
```

node.js version: v14.18.2

npm version: v6.14.15

Now, i do not want to upgrade the version of node.js and npm, is there any solution ?

- **Platform**:

``` macOS 11.6```

#### Severity:

High

#### Description:

This is the error by caught in terminal:

``` TypeError [ERR_INVALID_OPT_VALUE]: The value "jwk" is invalid for option "publicKeyEncoding.format"```

#### Steps to reproduce the error:

This is my demo repo:  https://github.com/zhaoyiming0803/test-libp2p

**Comment by TimDaub** [comment]
I get the same error

**Comment by vasco-santos** [comment]
Hey folks,

Thanks for reaching out. From `0.35` libp2p is only supported using Node15+ https://github.com/libp2p/js-libp2p/releases/tag/v0.35.0

Per https://nodejs.org/en/about/releases/#releases we are only supporting the Active releases of libp2p. Apologies for the inconvenience and let me know if this is a problem with a newer version of Node. Closing for now, but feel free to reopen

**Comment by Manwe-777** [comment]
@vasco-santos I am having the exact same error still, on a fresh install of the demo project using node `v16.5.0`, both on Windows and Ubuntu.
Also tested node 17, same result. any clues what might it be?

![image](https://user-images.githubusercontent.com/4711391/147897308-1b8582f5-7204-437d-ac4e-afcdee9f5be4.png)
