### ISSUE TITLE
metamask

### ISSUE THREAD

**Issue by indigofiredragon** [libp2p/js-libp2p#110]
ok i sent a partial coin with my either wallet some how all my coins sent i am not good at metamask they all went it says i dont have a private key and it will not let me trade  eitherdelta this is a compex issue talking to someone would be better for me then tryingto explain this issue
For account,  #################################there is no private key available. You can still transact if you are connected to Ethereum and the account is unlocked. whnei have my ethwallet unlocked and try to deposit eth on to eitherdelta this is the message i get You are connected to MetaMask, but you are either using a non-MetaMask account, or you are not logged into the MetaMask account you have selected. Check this in MetaMask, then refresh and try again.

**Comment by indigofiredragon** [comment]
looking at it my .001 test token went in the right account but the rest went into some other account I need help please seriously my wife has Cancer and we need this money to get her home to see her grandbabby being born if this doesnt happen im done.

**Comment by diasdavid** [comment]
Hi @indigofiredragon, I believe you got the wrong repo, this is not MetaMask's repo.

See:
- https://github.com/metamask
- https://github.com/MetaMask/faq

@kumavis might be able to give a hand :) Closing this issue.

**Comment by indigofiredragon** [comment]
to be honest I do not understand any of this i am new to this i am not a
young man i mad a huge error i cant get into my account and i cant get my
tokens out of either delta this is my life savings. with this one xfer i t
would change my life. my wife has termainal cancer so i am not thinking
right. I believe i xfered this into a new account i dont have the password
a tech fro the ico asked me to reboot  i forgot to save  my  keys on my
notepad i just feel hopeless and lost to all of this i am so crushed i do
not know what to do...... Rolando

**Comment by flyswatter** [comment]
Hi @indigofiredragon, please open an issue on our support center:
http://metamask.consensyssupport.happyfox.com/kb/

**Comment by kumavis** [comment]
@indigofiredragon also please join our slack for live support http://slack.metamask.io

**Comment by ich1baN** [comment]
Kumavis that's sort of a bullshit move to make... there are tons of people who are not apart of the live support that could have benefitted from a historical thread by reading through it.

**Comment by lgierth** [comment]
> Kumavis that's sort of a bullshit move to make

It's not, and please stay civil.
