### ISSUE TITLE
Unable to dial peer when on alternate ip versions

### ISSUE THREAD

**Issue by mubeenghauri** [libp2p/js-libp2p#1197]
- **Version**: `0.36.2`

- **Platform**: Chrome 100.0.4896.75  @ Ubuntu 21.04

- **Subsystem**:  **Dialer**

#### Description:

I am using orbitdb to make a small chat app. Over the internet, i have to ipfs.swarm.connect to reach a peer. This usually works, except for a specif case i.e when i have an ipv4 address and the peer i'm trying to dial (swarm.connect uses libp2p.dial under-the-hood) has an ipv6 address, the dial gives the following error (on either side, which tries to connect):

![image](https://user-images.githubusercontent.com/31207216/165444157-8313ace9-3ab0-497f-b03e-32c7a4ea487a.png)

This happens consistently. When the peer switches to an ipv4 connection, the dial works. So basically the dial works ipv4 => ipv4 and doesnt with ipv4 => ipv6. 

I find it strange, as we are working in the browser, we're dialing via the signaling server. I have also tried giving /dns6/ and /dns4/ multiaddr of signaling with no luck. Haven't tested with ipv6 => ipv6.
 
#### Steps to reproduce the error:
Use Alternate versions of ip between peers

**Comment by mpetrunic** [comment]
@mubeenghauri Could you send us a reproducible example? 

It would be great if you could add it as a test here: https://github.com/libp2p/js-libp2p/blob/master/test/dialing/direct.node.ts

**Comment by BigLep** [comment]
@mubeenghauri : we're going to close for now given don't have a reproducible example.  Feel free to reopen if you're able to provide one.  Thanks.
