### ISSUE TITLE
Delegated Routing

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p#120]
> Following https://github.com/ipfs/pm/pull/492

Tasks:
- [x] Expose findPeers and findProovs in the Gateway
- [x] Create module that exposes:
  - [x] Peer Routing - https://github.com/libp2p/js-libp2p-delegated-peer-routing
  - [x] Content Routing - https://github.com/libp2p/js-libp2p-delegated-content-routing

**Comment by diasdavid** [comment]
@lgierth any update on the first task of the list?

**Comment by diasdavid** [comment]
@lgierth mind updating this issue with what we discussed and the latest developments? Thank you!

**Comment by lgierth** [comment]
Here are my notes:

- expose dht/findpeer, dht/findprovs, swarm/connect, refs commands
  - https://github.com/ipfs/go-ipfs/pull/4595
- implement dht/putpeer command
- issue for "awesome delegated routing" endeavour
- update libp2p interfaces: peer-routing and content-routing
- comment on js-ipfs relay plans
  - announce /p2p-circuit addrs
  - configure static list of ~20 well-known relay nodes, pick 2
- debug /wss connection death bug
  - check out js-ipfs bootstrapper tests

**Comment by diasdavid** [comment]
> A couple more notes.

The Peer Routing flows will use the findPeer call directly. While the Content Routing flow will be:
- for providing:
  - Ask the delegated peer to fetch the content
  - Ask the delegated peer to become a provider (which happens by fetching the content in the first place)
- for finding providers
  - Ask the delegated peer to tell us who is providing
  - Ask the delegated peer to fetch that data
  - Fetch the data from the delegated peer.

**Comment by RangerMauve** [comment]
Where are the specs for this functionality?

**Comment by dignifiedquire** [comment]
Implementations are being done here:

- https://github.com/libp2p/js-libp2p-delegated-peer-routing/pull/1
- https://github.com/libp2p/js-libp2p-delegated-content-routing/pull/1

**Comment by jacobheun** [comment]
Both libp2p/js-libp2p-delegated-peer-routing and libp2p/js-libp2p-delegated-content-routing are about ready for release. I've got a local branch I am working on to integrate those into libp2p. The biggest issue right now is that https://ipfs.io is not working for those two.

I will make sure the local tests aren't hitting external endpoints, but the default peer and content routing won't work until ipfs.io is fixed.

I'll make sure the endpoint is configurable. Do we have any expected eta on a fix or separate url for the ipfs.io delegate?

**Comment by lgierth** [comment]
> The biggest issue right now is that https://ipfs.io is not working for those two.

Ah yeah, there's a branch that needs merging. I'll be on it once the urgent DWeb Summit tasks are done.

**Comment by diasdavid** [comment]
@jacobheun this is shipped, right?

**Comment by jacobheun** [comment]
@diasdavid this will ship with [0.24](https://github.com/libp2p/js-libp2p/issues/249). The go-ipfs work is still not complete, but our support will be there in the next release.

**Comment by daviddias** [comment]
@jacobheun what's the go-ipfs work? @Stebalien can you help with this?

**Comment by jacobheun** [comment]
The outstanding PR in go-ipfs is https://github.com/ipfs/go-ipfs/pull/5565.
Once that is release we can get infra to deploy, https://github.com/ipfs/infrastructure/issues/426.

**Comment by vasco-santos** [comment]
This is done

**Comment by daviddias** [comment]
@vasco-santos is it tested, deployed and monitored?

**Comment by vasco-santos** [comment]
It is implemented, tested and deployed afaik ([ipfs/js-ipfs/ipfs#configuring-delegate-routers](https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs#configuring-delegate-routers)).

Anyway, the scope of this issue seems to be the implementation on `js-libp2p`, which is released and tested. I suggest that we start to create more scoped issues, otherwise there is no visibility on what is done and what is expected from the issue. I am going through the issues on `js-libp2p` and there are several issues on this situation. 

If we want to have this service monitored, it should live under its specific issue
