### ISSUE TITLE
peerstore.peers is undefined

### ISSUE THREAD

**Issue by sneaker1** [libp2p/js-libp2p#1218]
- **Version**:
v0.36.2

- **Platform**:
Ubuntu 22.04 Chrome Version 101.0.4951.54

- **Subsystem**:
peerstore.peers

#### Description:
Since upgrading to v0.36.2 peerstore.peers is undefined.

**Comment by achingbrain** [comment]
That is correct, please see the [PeerStore interface](https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/libp2p-interfaces/src/peer-store/index.ts#L226-L244) for available methods and properties.
