### ISSUE TITLE
Failed to resolve entry for package "libp2p". The package may have incorrect main/module/exports specified in its package.json

### ISSUE THREAD

**Issue by noliveira95** [libp2p/js-libp2p#1242]
- **Version**: libp2p 0.37.3

- **Platform**: macOS Monterey v12.4, Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64, Brave Version 1.39.120 Chromium: 102.0.5005.99 (Official Build) (x86_64)

- **Subsystem**: libp2p-in-the-browser

#### Description: When attempting to run the libp2p-in-the-browser example, I cloned the js-libp2p repository and followed the steps: ran npm install in the root, then cd into ./examples/libp2p-in-the-browser and ran npm install again. When attempting to run with npm start, an error is thrown:

<img width="1440" alt="libp2p-in-the-browser-err" src="https://user-images.githubusercontent.com/87996659/173477467-bc5b2733-0e8e-48d8-ad47-b48567b68479.png">
<img width="1440" alt="libp2p-browser-err-terminal" src="https://user-images.githubusercontent.com/87996659/173477510-be0f3095-e6b8-40fd-8321-8f2b8f2e1ab0.png">

When doing a general web search, there are many links referring to Vite, I feel that this may be causing the problem. [Here is a direct link to a similar error in the ViteJS issues.](https://github.com/vitejs/vite/issues/4160)

**Comment by noliveira95** [comment]
Ran new test, appears to be resolved

**Comment by jellllly420** [comment]
same error on wsl2 :(
wonder how you fix it
just retry?
thank you
