### ISSUE TITLE
Use/create a more intuitive `errcode`

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p#1269]
Current usage of errcode is not intuitive.
example:
```ts
throw new errcode(new Error('error in foo'), ERR_FOO, { foo: bar })
```

Prefer an implementation like:
```ts
export class CodeError<T extends Record<string, any>> extends Error {
  code: string
  props: T

  constructor(message: string, code: string, props?: T) {
    super(message)

    this.code = code
    this.props = props ?? {} as T
  }
}
```

with usage then like:
```ts
throw new CodeError('error in foo', ERR_FOO, { foo: bar })
```

**Comment by achingbrain** [comment]
This is a great first issue that would suit someone looking to get started helping build libp2p!

To complete this:

1. Create a new repo
2. Export `CodeError` class (defined in OP)
3. Write tests
4. Open PRs to `@libp2p/*` repos using the new class

**Comment by tabcat** [comment]
Will look at completing this sometime this week now that CodeError is available.

**Comment by tabcat** [comment]
Tracking PRs needed to close this issue.
Have started by adding all relevant `@libp2p/*` packages like requested.
If changes to the list are needed let me know.

- [ ] @libp2p/crypto@1.0.7
- [ ] @libp2p/daemon-client@3.0.6
- [ ] @libp2p/tcp@5.0.2
- [ ] @libp2p/daemon-server@3.0.5
- [ ] @libp2p/tcp@5.0.2
- [ ] @libp2p/interface-mocks@8.0.1
- [ ] @libp2p/kad-dht@6.0.1
- [ ] @libp2p/record@2.0.3
- [ ] @libp2p/mplex@7.0.0
- [ ] @libp2p/multistream-select@3.1.1
- [ ] @libp2p/peer-id@1.1.16
- [ ] @libp2p/peer-record@4.0.4
- [ ] @libp2p/peer-store@5.0.0
- [ ] @libp2p/pubsub@5.0.0
- [ ] @libp2p/tcp@6.0.2
- [ ] @libp2p/topology@3.0.1
- [ ] @libp2p/utils@3.0.2
- [ ] @libp2p/webrtc-star@5.0.3
- [ ] @libp2p/webrtc-peer@2.0.2
- [ ] @libp2p/websockets@5.0.0

*other dependencies (some are indirect)*

- @achingbrain/nat-port-mapper@1.0.7
- @chainsafe/libp2p-yamux@3.0.3
- @multiformats/multiaddr@11.0.7
- promise-retry@2.0.1
- datastore-core@8.0.2
- go-libp2p@0.0.6
- ipfs-only-hash@4.0.0
- ipfs-unixfs-importer@7.0.3
- ipfs-unixfs@4.0.3
- it-length-prefixed@8.0.3
- multihashing-async@2.1.4

**Comment by tabcat** [comment]
Replacing the imports is very easy.

Here is some naive regex I'm using to replace the implementations for anyone looking to do this. Works for most of the ways errCode is being used currently.

`find: errCode\(new Error\((.*)\), (.*)\)`
`replace: new CodeError($1, $2)`

**Comment by tabcat** [comment]
Have crossed out `webrtc-` `star` and `peer` from list above. These packages look like they will be deprecated; can add them back if necessary.

There is also an issue with replacing err-code with CodeError in the libp2p pr. It has to do with the supplied props being exposed by CodeError from error.props object instead of the error object directly. This could affect code relying on how err-code exposes the props, see more in the pr to the main libp2p repo in the list above.

**Comment by wemeetagain** [comment]
@tabcat thanks, I've started merging these PRs :)
Can you also take a look at these repos?
https://github.com/chainsafe/js-libp2p-noise
https://github.com/chainsafe/js-libp2p-gossipsub
https://github.com/chainsafe/js-libp2p-yamux

**Comment by wemeetagain** [comment]
Also https://github.com/libp2p/js-libp2p-webrtc

Might be worthwhile to go thru this list https://www.npmjs.com/browse/depended/err-code and make sure the `@libp2p/` and `@chainsafe/` packages are all covered here.

**Comment by tabcat** [comment]
I had made a more complete list from the ipfs deps but decided to start with @libp2p/* packages in js-libp2p. Will update the PR list some time today.

**Comment by p-shahi** [comment]
@tabcat looks like all but a few prs remain for this effort. Need some help shepherding those along?

Another module that we likely need this change in is https://github.com/libp2p/js-libp2p-webtransport

**Comment by tabcat** [comment]
I meant to update this thread.

https://github.com/libp2p/js-libp2p-interfaces/pull/334 needs attention. I'm not sure how to bump the `js-libp2p-interfaces` package in `js-libp2p-interfaces/packages/interface-mocks`.

https://github.com/libp2p/js-libp2p/pull/1532 just needs the proper breaking change notice to be added by me

> Another module that we likely need this change in is [https://github.com/libp2p/js-libp2](https://github.com/libp2p/js-libp2p-webtransport)

I'll add it to the list

**Comment by tabcat** [comment]
Adding js-libp2p-keychain to the todo list

**Comment by tabcat** [comment]
It looks like `src/keychain/cms.ts` was completely removed from the keychain as a result of the move from the `js-libp2p` repo. That was the only part resulting in breaking changes to any libp2p repos.

**Comment by tabcat** [comment]
Do you think this can be closed now? @wemeetagain

**Comment by maschad** [comment]
Thanks for all the great work @tabcat! There are some deps which were missing from the list,  I updated [the comment](https://github.com/libp2p/js-libp2p/issues/1269#issuecomment-1371729293) to include them as well as to highlight why some repos were unaffected. Almost there!
