### ISSUE TITLE
No "exports" main defined in <redacted>/node_modules/libp2p/package.json v 0.37.3

### ISSUE THREAD

**Issue by freddi301** [libp2p/js-libp2p#1286]

**Comment by freddi301** [comment]
will commonjs modules be supported?

**Comment by achingbrain** [comment]
CommonJS is supported for `libp2p@0.36.x` and below.  `libp2p@0.37.x` and later is [ESM only](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).
