### ISSUE TITLE
would like to export the keystore

### ISSUE THREAD

**Issue by tabcat** [libp2p/js-libp2p#1295]
#### Severity:
Low - An optional functionality does not work

#### Description:
would like to be able to use the keystore in our project by exporting it from libp2p/src/keystore. this is currently blocked by the package.export field.

**Comment by achingbrain** [comment]
Generally exposing internals like this makes it harder to refactor the code as it exported modules become part of the public API.

Are you using libp2p in your project or just the keystore?

**Comment by achingbrain** [comment]
The libp2p keychain is not exposed directly via `ipfs-http-client` but it's operations are part of the [key API](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/KEY.md) which is callable via the `ipfs-http-client` (with the exception of `key.export` and `key.info`.

**Comment by tabcat** [comment]
I'd still like to be able to import this and use it locally. Will be forking the package until i find a better solution like bypassing the package.exports field.
