### ISSUE TITLE
Allow access to Components/Registrar from DialOptions/ListenerOptions when creating a new transport

### ISSUE THREAD

**Issue by ckousik** [libp2p/js-libp2p#1318]
When creating a new transport, we are unable to register any new streams with the registrar, or fetch handles for any incoming streams. We are also unable to find the list of supported protocols, incoming and outgoing stream limits, and track metrics. Currently, transport implementations implement the `MultiaddrConnection` interface and use the upgrader for muxing, encryption, and handling streams. This is unnecessary when using transports which inherently contain encryption and stream multiplexing (WebRTC, QUIC). Allowing access to the `components` or some subset of it containing the registrar would simplify implementing these transports.

**Comment by achingbrain** [comment]
If your transport implements [Initializable](https://github.com/libp2p/js-libp2p-components/blob/master/src/index.ts#L17-L19) it'll get handed a [Components](https://github.com/libp2p/js-libp2p-components/blob/master/src/index.ts#L43) instance after construction - that'll give you access to the `Registrar` and other libp2p components.

At that point you should be able to do stream/connection gating, encryption, multiplexing, etc in the same way the [upgrader](https://github.com/libp2p/js-libp2p/blob/master/src/upgrader.ts) does for transports that don't have their own versions of these things.

Hopefully that helps?

**Comment by ckousik** [comment]
Yes, thank you! We can close this issue.
