### ISSUE TITLE
@parcel/core: Failed to resolve '@libp2p/logger' 

### ISSUE THREAD

**Issue by PhillyWebGuy** [libp2p/js-libp2p#1327]
I know little about Parcel nor libp2p, so my apologies for not giving more info than the error:

@parcel/core: Failed to resolve '@libp2p/logger' from './node_modules/ipfs-core/src/components/index.js'

What other info can I provide to help troubleshoot this?

**Comment by kalikho** [comment]
Paste your code snippet here or detail the steps to reproduce the error.

**Comment by achingbrain** [comment]
This is because parcel does not support the exports map - please see https://github.com/parcel-bundler/parcel/issues/4155

A possible solution is to switch to a different bundler that does support the exports map like vite or similar.
