### ISSUE TITLE
Tutorial multiaddrs fix

### ISSUE THREAD

**Issue by olimdzhon** [libp2p/js-libp2p#1361]
multiaddrs from this example is undefined. Need to use getMultiaddrs() instead. Also there is no such function as toB58String() but when i used toString() func it seems it was something base58 encoded.

const node = await createNode()

// At this point the node has started
console.log('node has started (true/false):', node.isStarted())
// And we can print the now listening addresses.
// If you are familiar with TCP, you might have noticed
// that we specified the node to listen in 0.0.0.0 and port
// 0, which means "listen in any network interface and pick
// a port for me
console.log('listening on:')
node.multiaddrs.forEach((ma) => console.log(`${ma.toString()}/p2p/${node.peerId.toB58String()}`))

**Comment by kalikho** [comment]
@olimdzhon can you please provide some more details to reproduce the issue. Which script file to execute ? Also please provide screenshot of the error in the console if any.

**Comment by olimdzhon** [comment]
> @olimdzhon can you please provide some more details to reproduce the issue. Which script file to execute ? Also please provide screenshot of the error in the console if any.

it was from Transports readme https://github.com/libp2p/js-libp2p/tree/master/examples/transports. i found solution in 1.js file after. example files was fixed. but not readme itself.

**Comment by mpetrunic** [comment]
@olimdzhon Would you be willing to open PR to fix README?

**Comment by saul-avikar** [comment]
> @olimdzhon Would you be willing to open PR to fix README?

My PR #1379 should resolve this and the other issues related to outdated code in the example READMEs.
