### ISSUE TITLE
Atomic and transactional read/write

### ISSUE THREAD

**Issue by bakhshandeh** [libp2p/js-libp2p#1363]
I want to implement a global lock in Libp2p. Is it possible?
any way to atomically read/write DHT records?

**Comment by achingbrain** [comment]
Could you expand a little more on your use case?  Presumably you'd need to handle failures, rollback, prevent deadlocks, etc.

This isn't something we have planned currently.

**Comment by bakhshandeh** [comment]
> Could you expand a little more on your use case? Presumably you'd need to handle failures, rollback, prevent deadlocks, etc.
> 
> This isn't something we have planned currently.

Something like this:
https://redis.io/commands/setnx/

There is a network with N nodes. One node(N1) can acquire a lock for T seconds to run an operation. While the lock is not expired, other nodes can't acquire the lock.

Deadlocks and rollback could be handled by the application. I just want to know that this use case is feasible or not?

**Comment by achingbrain** [comment]
If you're talking about an application-level lock, it sounds like you'd need to implement a custom protocol that does the lock operations which is totally feasible.

If this is something that would meet your needs, you could look at the [fetch protocol](https://github.com/libp2p/js-libp2p/tree/master/src/fetch) for an example - it's a very simple request/response protocol that [sends](https://github.com/libp2p/js-libp2p/blob/master/src/fetch/index.ts#L92-L159) and [receives](https://github.com/libp2p/js-libp2p/blob/master/src/fetch/index.ts#L168-L202) messages between peers - you'd design your locking protocol to operate in a similar way.
