### ISSUE TITLE
`npm run build` error

### ISSUE THREAD

**Issue by juliangruber** [libp2p/js-libp2p#1364]
- **Version**:
`master`

- **Platform**:
`Darwin Julians-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64`

- **Subsystem**:

#### Severity:
High

#### Description:
```bash
$ npm run build
...
[08:47:45] tsc [failed]
[08:47:45] → Command failed with exit code 1: tsc
```

Full output:

https://gist.github.com/juliangruber/eddb2e9fbc1c96a5f935170c4336d9b5

#### Steps to reproduce the error:
Run `npm run build` with node 16.16.0 and npm 8.11.0

**Comment by juliangruber** [comment]
This error survives `rm -Rf node_modules && npm cache clean --force && npm install && npm run build`

**Comment by mpetrunic** [comment]
Could you delete the package-lock.json file and node_modules before installing dependencies?

**Comment by mpetrunic** [comment]
@juliangruber

**Comment by juliangruber** [comment]
Ah, removing `package-lock.json` fixed it. Thanks!

I was surprised to find it in `.gitignore`, is there a particular reason to ignore it?
