### ISSUE TITLE
Time to expose PubSub as a libp2p primitive on the libp2p Class

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p#140]
I believe it is time to expose PubSub as a core libp2p primitive as well instead of it being an external module that mounts on top of libp2p. Thoughts?

**Comment by richardschneider** [comment]
- Does this imply dropping the experimental status of pubsub?
- Might be premature, still have open pubsusb issues https://github.com/ipfs/js-ipfs/issues/1136, https://github.com/ipfs/js-ipfs/issues/1132 and https://github.com/ipfs/js-ipfs/issues/1129

**Comment by diasdavid** [comment]
> Does this imply dropping the experimental status of pubsub?

It doesn't. PubSub is experimental on IPFS and will continue to be. In libp2p  everything is plug&play/on&off, users could always use it but had to do more work.

**Comment by diasdavid** [comment]
Done on version 0.18.0 :)
