### ISSUE TITLE
Duplicated addresses in _createDialTarget

### ISSUE THREAD

**Issue by dapplion** [libp2p/js-libp2p#1409]
- **Version**: 0.39.2 https://github.com/ChainSafe/lodestar/blob/ca27458b59c66c9d3da7dd95322e479f78407269/packages/beacon-node/package.json#L144

- **Platform**: Linux

- Severity: High

#### Description:
Running local devnets with Lodestar nodes couldn't dial with each other due to this error
```
Oct-05 22:08:39.721[rest]            error: Req req-1 gossipsubAttack error  dial with more addresses than allowed 5 > 4
Error: dial with more addresses than allowed 5 > 4
    at DefaultDialer._createDialTarget (file:///home/lion/Code/eth2.0/lodestar-attack/node_modules/libp2p/src/connection-manager/dialer/index.ts:264:21)
    at DefaultDialer._createCancellableDialTarget (file:///home/lion/Code/eth2.0/lodestar-attack/node_modules/libp2p/src/connection-manager/dialer/index.ts:217:26)
    at DefaultDialer.dial (file:///home/lion/Code/eth2.0/lodestar-attack/node_modules/libp2p/src/connection-manager/dialer/index.ts:179:24)
    at EventTarget.openConnection (file:///home/lion/Code/eth2.0/lodestar-attack/node_modules/libp2p/src/connection-manager/index.ts:521:26)
    at EventTarget.dial (file:///home/lion/Code/eth2.0/lodestar-attack/node_modules/libp2p/src/libp2p.ts:382:12)
```

I manually called dial submitting a single Multiaddr with `/ip4/127.0.0.1/tcp/9000/p2p/16Uiu2HAm6fBRJ3MWKUpVhscGdPkrUJjB943JfG8hbg41k9soaNpw`. But how can there be 5 addresses if I only ever provided a single IP port combo?

Then added a console log to print the multiaddr:
```
Trace: [
  <Multiaddr 047f000001062328a5032700250802122102a6e664edcd4b990208e101fe7486282a205d4a88edae4be6d54ead4257bb1f98 - /ip4/127.0.0.1/tcp/9000/p2p/16Uiu2HAm6fBRJ3MWKUpVhscGdPkrUJjB943JfG8hbg41k9soaNpw>,
  <Multiaddr 047f000001062328a5032700250802122102a6e664edcd4b990208e101fe7486282a205d4a88edae4be6d54ead4257bb1f98 - /ip4/127.0.0.1/tcp/9000/p2p/16Uiu2HAm6fBRJ3MWKUpVhscGdPkrUJjB943JfG8hbg41k9soaNpw>,
  <Multiaddr 04c0a80214062328a5032700250802122102a6e664edcd4b990208e101fe7486282a205d4a88edae4be6d54ead4257bb1f98 - /ip4/192.168.2.20/tcp/9000/p2p/16Uiu2HAm6fBRJ3MWKUpVhscGdPkrUJjB943JfG8hbg41k9soaNpw>,
  <Multiaddr 04c0a802ef062328a5032700250802122102a6e664edcd4b990208e101fe7486282a205d4a88edae4be6d54ead4257bb1f98 - /ip4/192.168.2.239/tcp/9000/p2p/16Uiu2HAm6fBRJ3MWKUpVhscGdPkrUJjB943JfG8hbg41k9soaNpw>,
  <Multiaddr 04c0a802ef062328a5032700250802122102a6e664edcd4b990208e101fe7486282a205d4a88edae4be6d54ead4257bb1f98 - /ip4/192.168.2.239/tcp/9000/p2p/16Uiu2HAm6fBRJ3MWKUpVhscGdPkrUJjB943JfG8hbg41k9soaNpw>
]
    at DefaultDialer._createDialTarget (file:///home/lion/Code/eth2.0/lodestar-attack/node_modules/libp2p/src/connection-manager/dialer/index.ts:264:13)
    at DefaultDialer._createCancellableDialTarget (file:///home/lion/Code/eth2.0/lodestar-attack/node_modules/libp2p/src/connection-manager/dialer/index.ts:217:26)
    at DefaultDialer.dial (file:///home/lion/Code/eth2.0/lodestar-attack/node_modules/libp2p/src/connection-manager/dialer/index.ts:179:24)
    at EventTarget.openConnection (file:///home/lion/Code/eth2.0/lodestar-attack/node_modules/libp2p/src/connection-manager/index.ts:521:26)
    at EventTarget.dial (file:///home/lion/Code/eth2.0/lodestar-attack/node_modules/libp2p/src/libp2p.ts:382:12)
```

so:
- Why are addresses duplicated?
- Why are IPs `192.168.2.20` and `192.168.2.239` added to the targets?

#### Steps to reproduce the error:
On a local devnet
- Start node 1 with dev command
- Start node 2 with dev command
- Call connectPeer API on node 2 with node 1 identity

**Comment by mpetrunic** [comment]
Triage: mdns is not really up to spec: https://github.com/libp2p/js-libp2p-mdns/issues/101
but this looks like bug with duplicates.

**Comment by wemeetagain** [comment]
I think this is a bug here, worth keeping this open to investigate.

It's probably the case that mdns is populating our peerstore with local dns multiaddrs.
Those are then being 'resolved' by the dialer into duplicate ip addresses.

**Comment by mpetrunic** [comment]
> I manually called dial submitting a single Multiaddr with /ip4/127.0.0.1/tcp/9000/p2p/16Uiu2HAm6fBRJ3MWKUpVhscGdPkrUJjB943JfG8hbg41k9soaNpw. But how can there be 5 addresses if I only ever provided a single IP port combo?

Dial obtains peerId from multiaddr and fetches all ma from peerstore connected to that peerId.

I don't think it's possible to store duplicate ma in peerstore as they all end https://github.com/libp2p/js-libp2p-peer-store/blob/master/src/store.ts#L197 and you cannot have duplicate keys.

It seems like that only possibility to create duplicates is here: https://github.com/libp2p/js-libp2p/blob/v0.39.2/src/connection-manager/dialer/index.ts#L346
@dapplion @wemeetagain Could you log what addresses are stored in address book for that peer before dial?

@achingbrain Can we remove this: https://github.com/libp2p/js-libp2p/blob/v0.39.2/src/connection-manager/dialer/index.ts#L262 and just take first `this.maxAddrsToDial` from `supportedAddrs` ?

**Comment by wemeetagain** [comment]
yup, I haven't confirmed, but I think mdns is adding `something.local` dns multiaddrs for found peers, and those are being resolved to duplicate ip addrs.

**Comment by achingbrain** [comment]
> Dial obtains peerId from multiaddr and fetches all ma from peerstore connected to that peerId

The current behaviour is a little confusing - I think if you dial a PeerId it should do this, if you dial one or more multiaddrs it should probably only dial that/those multiaddrs.  If dialing multiple multiaddrs it needs to assert that they all are for the same remote peer as well, since you only get one connection back.

> Can we remove this: [v0.39.2/src/connection-manager/dialer/index.ts#L262](https://github.com/libp2p/js-libp2p/blob/v0.39.2/src/connection-manager/dialer/index.ts?rgh-link-date=2022-11-21T14%3A02%3A50Z#L262) and just take first this.maxAddrsToDial addresses from supportedAddrs ?

I think ignoring seemingly arbitrary addresses might make failures hard to reason about.  The dial request might need to treat maxAddrsToDial as a concurrency limit instead of a hard stop on dialing at all?

**Comment by mpetrunic** [comment]
> > Dial obtains peerId from multiaddr and fetches all ma from peerstore connected to that peerId
> 
> The current behaviour is a little confusing - I think if you dial a PeerId it should do this, if you dial one or more multiaddrs it should probably only dial that/those multiaddrs. If dialing multiple multiaddrs it needs to assert that they all are for the same remote peer as well, since you only get one connection back.
> 

> I think ignoring seemingly arbitrary addresses might make failures hard to reason about. The dial request might need to treat maxAddrsToDial as a concurrency limit instead of a hard stop on dialing at all?

I think there is another option for concurrency called maxParallelDials which is used to obtain tokens but I cannot find where they are used.

I feel like the current setup is some way to refresh old peers with a lot of old addresses but if the user submitted ma to dial, it makes sense to use that one and maybe a few old ones. 

For now I would just add filtering duplicated so we fix this bug and maybe a new issue to reconsider dialing logic, wdyt?

**Comment by achingbrain** [comment]
Yes, filtering duplicate addresses and looking at dialing logic more holistically can be tackled separately.

**Comment by achingbrain** [comment]
`maxParallelDials` is used [here](https://github.com/libp2p/js-libp2p/blob/5e9dcf3d404a975d01ee7171305cc2ab07ea7307/src/connection-manager/dialer/index.ts#L110) to control the number of dial tokens that are available globally in a single libp2p node.

**Comment by mpetrunic** [comment]
> `maxParallelDials` is used [here](https://github.com/libp2p/js-libp2p/blob/5e9dcf3d404a975d01ee7171305cc2ab07ea7307/src/connection-manager/dialer/index.ts#L110) to control the number of dial tokens that are available globally in a single libp2p node.

Yes but I cannot find usage of getTokens and releaseTokens methods

**Comment by achingbrain** [comment]
In the dial request:

[getTokens](https://github.com/libp2p/js-libp2p/blob/0218acfae26fa69475b2ce0678b1c754c7eda605/src/connection-manager/dialer/dial-request.ts#L49)

[releaseToken](https://github.com/libp2p/js-libp2p/blob/0218acfae26fa69475b2ce0678b1c754c7eda605/src/connection-manager/dialer/dial-request.ts#L89)

[releaseToken](https://github.com/libp2p/js-libp2p/blob/0218acfae26fa69475b2ce0678b1c754c7eda605/src/connection-manager/dialer/dial-request.ts#L111)

[releaseToken](https://github.com/libp2p/js-libp2p/blob/0218acfae26fa69475b2ce0678b1c754c7eda605/src/connection-manager/dialer/dial-request.ts#L134)
