### ISSUE TITLE
libp2p-tor/libp2p-onion Transport?

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-libp2p#142]
- **Version**: _does not apply_
- **Platform**: Linux
- **Subsystem**: transports

#### Description: Tor transport for libp2p

Is there a Tor transport for js-libp2p?

A tor transport that can listen on hidden services as well as ephermal hidden services and dial them would be great.

**Comment by paralin** [comment]
https://github.com/OpenBazaar/go-onion-transport

**Comment by mkg20001** [comment]
I'm asking for a JavaScript transport and not one written in Golang.
(I was already aware of that transport anyways...)

**Comment by paralin** [comment]
Just linking to add context to the issue. But, I would say this is going to be pretty difficult if you actually want to run Tor in the browser.

**Comment by diasdavid** [comment]
@mkg20001 this would be really cool! Is there any JS impl we can use?

**Comment by RangerMauve** [comment]
The onion routing could be done using the new relay feature where each hop is encrypted so that only the peer it's for knows where to go next. Of course this wouldn't have interoperability with Tor, but one could have a go node with both relay and the tor transport and use it as a sort of "exit node" that goes to the actual Tor network while using a libp2p-specific onion router before getting to it.

**Comment by robertkiel** [comment]
FYI:
At the moment, I am creating an implementation of an incentivised privacy-preserving onion-encrypted overlay network implementation based on js-libp2p.

The project is called [`hopr`](https://github.com/validitylabs/messagingProtocol). The plan is to present an early implementation of it at EthCC (Ethereum Community Conference) in Paris next week.

There's also a [working group](https://github.com/w3f/messaging) including [Validity Labs](https://validitylabs.org), [Status.im](https://status.im) and [Web3 Foundation](https://web3.foundation) whose goal is to create a reliable privacy-preserving messaging network for the Web3

**Comment by achingbrain** [comment]
This is great - I think there should be a link to `hopr` from the readme somewhere - I've created https://github.com/libp2p/js-libp2p/issues/1408 to track this.
