### ISSUE TITLE
js-libp2p 2022 Q4/2023 Q1 Roadmap

### ISSUE THREAD

**Issue by p-shahi** [libp2p/js-libp2p#1438]
> 🛣🗺 Roadmap document: https://github.com/libp2p/js-libp2p/blob/master/ROADMAP.md

children:
* https://github.com/libp2p/js-libp2p/issues/1463
* https://github.com/libp2p/js-libp2p/issues/1461
* https://github.com/libp2p/js-libp2p/issues/1458

eta: 2023Q2

### Current status of Roadmap
2022-10-20: Accepted. Internal js-libp2p stakeholders have aligned on this roadmap.

### Description
This issue is intended to capture discussion around the [js-libp2p 2022 Q4/2023 Q1 Roadmap](https://github.com/libp2p/js-libp2p/blob/master/ROADMAP.md).

Because GitHub doesn't have any feature to comment on Markdown files, please use this issue to leave any feedback, proposals, etc.

### Roadmap drafts:
1st draft: https://github.com/libp2p/js-libp2p/pull/1412

**Comment by wemeetagain** [comment]
Closing as stale
