### ISSUE TITLE
Can't discover/connect new peers using webrtc-star on `v0.39.5`

### ISSUE THREAD

**Issue by ratik21** [libp2p/js-libp2p#1442]
Peer discovery and connections are not happening with the latest libp2p version (after esm upgrade). 

I have created a failing test for both versions (before & after esm), with screenshots - [https://github.com/ratik21/p2p-webrtc-star-test](https://github.com/ratik21/p2p-webrtc-star-test). Please check it out. Thanks.

Related discussion thread :: [https://discuss.libp2p.io/t/cant-discover-peers-with-webrtc-star-on-js-libp2p-0-37-0/1438](https://discuss.libp2p.io/t/cant-discover-peers-with-webrtc-star-on-js-libp2p-0-37-0/1438)

cc: @MarcoPolo

**Comment by achingbrain** [comment]
You need to configure the peer discovery component of the WebRTCStar transport for it to work:

For `libp2p@0.37.0-0.39.0` and `@libp2p/webrtc-star@4.x.x`:

```js
import { WebRTCStar } from '@libp2p/webrtc-star'
import { createLibp2p } from 'libp2p'
//... other stuff

const webRTC = new WebRTCStar({ ... })

const node = await createLibp2p( {
  transports: [
    webRTC
  ],
  peerDiscovery: [
     webRTC.discovery
  ],
  //... other stuff
})
```

For `libp2p@0.40.0` and `@libp2p/webrtc-star@5.x.x`:

```js
import { webRTCStar } from '@libp2p/webrtc-star'
import { createLibp2p } from 'libp2p'
//... other stuff

const webRTC = webRTCStar({ ... })

const node = await createLibp2p( {
  transports: [
    webRTC.transport
  ],
  peerDiscovery: [
     webRTC.discovery
  ],
  //... other stuff
})
```

The README for v5 is hopefully a bit clearer.

**Comment by ratik21** [comment]
@achingbrain thanks for responding.

With the changes you have suggested the discovery is working (for `libp2p@0.37.0-0.39.0` and `@libp2p/webrtc-star@4.x.x`). But the **connection** is still not happening (sc attached).

<img width="882" alt="image" src="https://user-images.githubusercontent.com/33264364/196638520-95a184ea-fa66-4faf-b753-efd73c09ebfe.png">

I was wondering if this is the case now (for `after-esm` versions)? Because connection is being established for same nodes at `before-esm` version (one at local & one behind NAT -- [reference](https://github.com/ratik21/p2p-webrtc-star-test/tree/main/before-esm#before-esm)).

**Comment by ratik21** [comment]
@achingbrain one more thing (side note), i start getting this influx of discovery logs and it never stops, after discovery (for any transport/peer discovery mechanism)

<img width="816" alt="image" src="https://user-images.githubusercontent.com/33264364/196639571-1ae0631c-30fb-488d-90f5-6a654dd56d19.png">

This is the event handler code (taken from `node1.js` from my repo)
```js
  node.addEventListener('peer:discovery', (event) => {
    const peerInfo = event.detail;
    console.log('Discovered:', peerInfo.id.toString());
  });
```

**Comment by achingbrain** [comment]
Discovered nodes are no longer dialled automatically - please see the upgrade guide - https://github.com/libp2p/js-libp2p/blob/master/doc/migrations/v0.37-v0.40.md#autodial

**Comment by ratik21** [comment]
@achingbrain i tested on `libp2p@0.37.0-0.39.0` :)

**Comment by ratik21** [comment]
Furthur more, if i try to manually dial after discovery, i get this error
```sh
[AggregateError: All promises were rejected] {
  [errors]: [
    AbortError: The operation was aborted
        at file:///Users/ratikjindal/Zero/libp2p-webrtc-star-issue/after-esm/node_modules/@libp2p/webrtc-star/dist/src/index.js:117:26
        at <anonymous> {
      type: 'aborted',
      code: 'ABORT_ERR'
    }
  ]
}
```

Update to source code:

```js
  node.addEventListener('peer:discovery', async (event) => {
    const peerInfo = event.detail;
    console.log('Discovered:', peerInfo.id.toString());

    console.log("dialing..");
    try {
      const ma = new Multiaddr(`/dns4/vast-escarpment-62759.herokuapp.com/tcp/443/wss/p2p-webrtc-star/p2p/${peerInfo.id.toString()}`);
      await node.dial(ma);
    } catch (error) {
      console.log(error);
    }
  });
```

**Comment by ratik21** [comment]
@achingbrain I have upgraded the `js-libp2p` version on [this](https://github.com/ratik21/p2p-webrtc-star-test/blob/main/after-esm/node1.js) test, but I am still getting the same issue as above. 

As an alternative, could you please suggest what protocol to use for connection b/w two peers where one is behind a NAT? Before the esm upgrade webrtc-star servers were working fine. Anyway, can we use circuit relay (v1/v2) now?, i.e `<..>/p2p-circuit/p2p/<..>`? 

Also there is a small bug in the migration guide for `v0.40.0`, I have created a [PR](https://github.com/libp2p/js-libp2p/pull/1467) for it.

**Comment by ratik21** [comment]
@achingbrain -- any update on this?

**Comment by p-shahi** [comment]
@ratik21 We likely won't pursue this issue since we are actively working to support WebRTC transport https://github.com/little-bear-labs/js-libp2p-webrtc/ and deprecate WebRTC-star (and direct) as a result.

**Comment by ratik21** [comment]
@p-shahi Ok, thanks for responding. few questions :-

+ Does [js-libp2p-webrtc](https://github.com/little-bear-labs/js-libp2p-webrtc/) work for server <-> browser, server <-> server as well? Or is it only browser <-> browser?

+ Assuming browser to browser only, will this transport be able to discover & connect to "new" peers (not known peers but peers who join the network), behind NAT's ? It seems there aren't many ways for NAT traversal in `js-libp2p` yet :/

**Comment by p-shahi** [comment]
@ratik21 That implementation (tracked here https://github.com/libp2p/js-libp2p/issues/1478 now) is for browser to server
How it behaves is specified here: https://github.com/libp2p/specs/tree/master/webrtc

The browser to browser aspect is just beginning to get underway. See https://github.com/libp2p/js-libp2p/issues/1462. It's not specified yet but necessary parts like supporting Circuit Relay v2 are being added.

AutoNat support is also being added, hopefully before the end of this year per our roadmap: https://github.com/libp2p/js-libp2p/blob/master/ROADMAP.md#end-of-q4-december

**Comment by ratik21** [comment]
@p-shahi thanks! I will try [js-libp2p-webrtc](https://github.com/little-bear-labs/js-libp2p-webrtc/) for server to server, and browser to browser for new discovery and connections

**Comment by p-shahi** [comment]
@ratik21 I'll close this issue for now.
