### ISSUE TITLE
this example "nat-traversal" behind js-libp2p is still empty, I 

### ISSUE THREAD

**Issue by kotepillar** [libp2p/js-libp2p#145]
- **Version**:
- **Platform**:
- **Subsystem**:

#### Severity:
 Very Low
#### Description:
the nat-traversal example still empty from six months ago
#### Steps to reproduce the error:
https://github.com/libp2p/js-libp2p/tree/master/examples

**Comment by diasdavid** [comment]
@kotepillar true. It's a WIP https://github.com/libp2p/js-libp2p/tree/master/examples/nat-traversal#wip---this-example-is-still-in-the-works :) We will update it there once it is ready.
