### ISSUE TITLE
Failed to upgrade outbound connection Error: missing newline

### ISSUE THREAD

**Issue by dapplion** [libp2p/js-libp2p#1454]
- **Version**: 0.39.2 https://github.com/ChainSafe/lodestar/blob/ca27458b59c66c9d3da7dd95322e479f78407269/packages/beacon-node/package.json#L144

- **Platform**: Linux

- Severity: High

#### Description:

In a local Ethereum beacon chain devnet with 1 Lodestar and 1 Lighthouse, Lodestar is unable to connect to Lighthouse directly erroring with

```
  libp2p:tcp dialing {"family":4,"host":"127.0.0.1","transport":"tcp","port":4000} +0ms
  libp2p:tcp connection opened {"family":4,"host":"127.0.0.1","transport":"tcp","port":4000} +0ms
  libp2p:tcp new outbound connection /ip4/127.0.0.1/tcp/4000/p2p/16Uiu2HAm4ozUmKkLbePSBwTSDdTCQJXPisVQSAP25AHk8ZeKv7Kb +6ms
  libp2p:upgrader Starting the outbound connection upgrade +0ms
  libp2p:upgrader selecting outbound crypto protocol [ '/noise' ] +0ms
  libp2p:mss:select select: write ["/multistream/1.0.0", "/noise"] +0ms
  libp2p:upgrader:error Failed to upgrade outbound connection Error: missing newline
    at read (file:///home/lion/Code/eth2.0/lodestar/node_modules/@libp2p/multistream-select/src/multistream.ts:85:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Module.readString (file:///home/lion/Code/eth2.0/lodestar/node_modules/@libp2p/multistream-select/src/multistream.ts:92:15)
    at Module.select (file:///home/lion/Code/eth2.0/lodestar/node_modules/@libp2p/multistream-select/src/select.ts:30:18)
    at EventTarget._encryptOutbound (file:///home/lion/Code/eth2.0/lodestar/node_modules/libp2p/src/upgrader.ts:588:36)
    at EventTarget.upgradeOutbound (file:///home/lion/Code/eth2.0/lodestar/node_modules/libp2p/src/upgrader.ts:275:11)
    at TCP.dial (file:///home/lion/Code/eth2.0/lodestar/node_modules/@libp2p/tcp/src/index.ts:84:18)
    at EventTarget.dial (file:///home/lion/Code/eth2.0/lodestar/node_modules/libp2p/src/transport-manager.ts:115:14)
    at DialRequest.dialAction (file:///home/lion/Code/eth2.0/lodestar/node_modules/libp2p/src/connection-manager/dialer/index.ts:286:14)
    at file:///home/lion/Code/eth2.0/lodestar/node_modules/libp2p/src/connection-manager/dialer/dial-request.ts:100:18 {
  code: 'ERR_ENCRYPTION_FAILED'
```

Line throwing the error is https://github.com/multiformats/js-multistream-select/blob/6e3d75fe31fa277160aa20b9f248eacb14a17782/src/multistream.js#L79

#### Steps to reproduce the error:

Connect a Lodestar + Lighthouse nodes with their default configurations

Relates to: https://github.com/libp2p/js-libp2p-multistream-select/issues/27

**Comment by p-shahi** [comment]
> Line throwing the error is https://github.com/multiformats/js-multistream-select/blob/6e3d75fe31fa277160aa20b9f248eacb14a17782/src/multistream.js#L79

Did you mean to link to https://github.com/libp2p/js-libp2p-multistream-select/blob/master/src/multistream.ts#L85
The error indicates it's using the TS library
`    at read (file:///home/lion/Code/eth2.0/lodestar/node_modules/@libp2p/multistream-select/src/multistream.ts:85:19)`

**Comment by dapplion** [comment]
> > Line throwing the error is https://github.com/multiformats/js-multistream-select/blob/6e3d75fe31fa277160aa20b9f248eacb14a17782/src/multistream.js#L79
> 
> Did you mean to link to https://github.com/libp2p/js-libp2p-multistream-select/blob/master/src/multistream.ts#L85 The error indicates it's using the TS library ` at read (file:///home/lion/Code/eth2.0/lodestar/node_modules/@libp2p/multistream-select/src/multistream.ts:85:19)`

Yes right

**Comment by mpetrunic** [comment]
@dapplion Could you try with latest version. https://github.com/libp2p/js-libp2p-multistream-select/pull/30 should give us better info in logs.

**Comment by dapplion** [comment]
> @dapplion Could you try with the latest version of multistream select?
> 
> [libp2p/js-libp2p-multistream-select#30](https://github.com/libp2p/js-libp2p-multistream-select/pull/30) should give us better info in logs.

This will log as hex? Not familiar with debug formating internals `log.error('%s', buf.subarray())`

@wemeetagain do we have this version on Lodestar? not yet I imagine

**Comment by mpetrunic** [comment]
I tried in test, and produces [82, 14] but should be easy enough to write a script to convert to utf8 to debug

**Comment by achingbrain** [comment]
Triage: waiting for @dapplion to try with the latest version with enhanced logging

**Comment by p-shahi** [comment]
@dapplion have you had a chance to test this with the latest version yet?

**Comment by achingbrain** [comment]
Triage: after the imminent lodestar release @dapplion will handle upgrading to `libp2p@0.41.x`, then this can be revisited
