### ISSUE TITLE
Docs: use Aegir + TypeDoc to generate and serve documentation in CI

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p#1455]
## Done Criteria
- [ ] Update js-libp2p to use Aegir + TypeDoc
- [ ] Use GitHub actions to serve new documentation on GitHub pages for each new release of js-libp2p and components

### Original issue
Docs: multaddrs property has been replaced with getMultiaddrs
The docs are out of date, the new getter needs documenting: https://github.com/libp2p/js-libp2p/blob/master/doc/API.md#multiaddrs

**Comment by p-shahi** [comment]
@achingbrain are these docs updated manually?
I was poking around and generated this using [Typedoc](https://github.com/TypeStrong/typedoc)
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/50885601/200445932-fcb15ea8-a4ef-4bc6-a2e7-85edb3f10cd9.png">

Is this something you'd want added to js-libp2p?

**Comment by achingbrain** [comment]
Yes please, the typedoc story has always been a bit hit & miss with JSDoc-style typing but it’s much better with pure typescript.

Aegir has a docs command that generates typedocs and uploads them to gh-pages, that’s be the place to do it, then run that in each repo on release.

**Comment by maschad** [comment]
I created a [Draft PR](https://github.com/libp2p/js-libp2p/pull/1476) but it is currently blocked by [an issue](https://github.com/ipfs/aegir/issues/1105) that I created on AEgir.
