### ISSUE TITLE
C. 🔮 Ergonomic Observability

### ISSUE THREAD

**Issue by p-shahi** [libp2p/js-libp2p#1458]
eta: 2022Q4

**Why:** Though we already expose [per-component metrics](https://github.com/libp2p/js-libp2p/issues/1060) in js-libp2p, the overhead of recording metrics is high (excessive object allocation per metric to record). This will be helpful to [our users](https://github.com/chainsafe/lodestar) who record metrics on the order of thousands/second.

**Goal:**
We make the lives of js-libp2p easier by adding an improved metrics API.

#### 1. Ergonomic metrics API
Create an ergonomic, generalized metrics recording interface which addresses current allocation overhead and duplication of information. Do not bloat the browser bundle with [prom-client](https://github.com/siimon/prom-client).

Related Issues/Linked PRs:
#### js-libp2p-tcp
- https://github.com/libp2p/js-libp2p-tcp/pull/223
- https://github.com/libp2p/js-libp2p-tcp/issues/226
- https://github.com/libp2p/js-libp2p-tcp/pull/230

#### js-libp2p-prometheus-metrics
- https://github.com/libp2p/js-libp2p-prometheus-metrics/pull/4
- https://github.com/libp2p/js-libp2p-prometheus-metrics/pull/6

#### js-libp2p-interfaces
- https://github.com/libp2p/js-libp2p-interfaces/pull/310

#### js-libp2p
- https://github.com/libp2p/js-libp2p/pull/1471

#### js-libp2p-kad-dht
- https://github.com/libp2p/js-libp2p-kad-dht/pull/398

#### js-libp2p-tracked-map
- https://github.com/libp2p/js-libp2p-tracked-map/pull/12

#### js-libp2p-noise
- https://github.com/ChainSafe/js-libp2p-noise/pull/246

#### js-libp2p-webtransport
- https://github.com/libp2p/js-libp2p-webtransport/issues/33

#### js-libp2p-webrtc
- https://github.com/little-bear-labs/js-libp2p-webrtc/issues/64

#### js-libp2p-websockets
- https://github.com/libp2p/js-libp2p-websockets/issues/197

#### js-libp2p-gossipsub
- collect metrics from https://github.com/ChainSafe/js-libp2p-gossipsub

- [ ] add docs on how to enable metrics (mention in release notes)
- [ ] add blog post

**Comment by p-shahi** [comment]
@mpetrunic Let's use this tracking issue to help fill out the remaining metrics work

**Comment by BigLep** [comment]
@achingbrain : what's the done criteria for this issue and do we have the list of work items to get there?  For work items, is it the list of related items/links, or are there additional items to add?

**Comment by mpetrunic** [comment]
> @achingbrain : what's the done criteria for this issue and do we have the list of work items to get there? For work items, is it the list of related items/links, or are there additional items to add?

Look at related prs and issues in original description. Seems like only https://github.com/libp2p/js-libp2p-tcp/issues/226 is left and it's waiting to be merged

**Comment by achingbrain** [comment]
`@libp2p/tcp` is leading the charge on the metrics integration, but once it's settled down similar metrics will also need to be added to other transports:

- [@libp2p/websockets](https://github.com/libp2p/js-libp2p-websockets)
- [@libp2p/webtransport](https://github.com/libp2p/js-libp2p-webtransport)
- [@libp2p/webrtc](https://github.com/little-bear-labs/js-libp2p-webrtc)

We should also be collecting metrics from `@chainsafe/gossipsub`, I think that's the only other module with it's own metrics tracking, then I think we can call it done.

**Comment by p-shahi** [comment]
I'm going to close this as done. The main feature has rolled out and we can track the remaining modules seperately
