### ISSUE TITLE
the example readme of "echo" still empty

### ISSUE THREAD

**Issue by kotepillar** [libp2p/js-libp2p#146]
- **Version**:
- **Platform**:
- **Subsystem**:

#### Severity:
Very Low
#### Description:
the example readme of "echo" still empty

**Comment by diasdavid** [comment]
Code is there https://github.com/libp2p/js-libp2p/tree/master/examples/echo/src, wanna test it out and try take a stab at the readme?

**Comment by diasdavid** [comment]
It got filled with #166 check it out! :)
