### ISSUE TITLE
Use DCUtR to synchronize hole punching

### ISSUE THREAD

**Issue by p-shahi** [libp2p/js-libp2p#1460]
- Spec: https://github.com/libp2p/specs/blob/master/relay/DCUtR.md

**Comment by BigLep** [comment]
@p-shahi : I assume this is needed for browsers being able to dial or be dialable by server nodes with WebRTC.  Is that right?

**Comment by SgtPooki** [comment]
related: https://github.com/ipfs/helia/issues/180

**Comment by aschmahmann** [comment]
Related to the linked issue(s) above. If implementing synchronized hole punching via DCUtR is going to take a while, it's probably worth doing the minimal amount of DCUtR that enables dialbacks to nodes that are publicly reachable. 

While it's only a subset, it's likely an easier subset and unlocks js-libp2p nodes (including those in browsers) being reachable by any libp2p node which is itself publicly reachable (on a shared transport). This enables a path forward for users to build systems where their browser nodes are reachable from non-browser nodes.
