### ISSUE TITLE
WebRTC: Browser to Browser

### ISSUE THREAD

**Issue by p-shahi** [libp2p/js-libp2p#1462]
Support WebRTC Browser to Browser as a first class transport in js-libp2p and deprecate [webrtc-star](https://github.com/libp2p/js-libp2p-webrtc-star) and [webrtc-direct](https://github.com/libp2p/js-libp2p-webrtc-direct).

- [x] support Circuit Relay v2: https://github.com/libp2p/js-libp2p/pull/1533
- [x] https://github.com/libp2p/js-libp2p-webrtc/pull/90

**Comment by disarticulate** [comment]
+1

Inspiration https://github.com/yjs/y-webrtc

Monkey patch for buffering https://github.com/yjs/y-webrtc/issues/20

**Comment by p-shahi** [comment]
Marking as closed since this has been released in https://github.com/libp2p/js-libp2p-webrtc/releases/tag/v1.1.0
