### ISSUE TITLE
A. 📺 Universal Browser Connectivity

### ISSUE THREAD

**Issue by p-shahi** [libp2p/js-libp2p#1463]
eta: 2023Q2

**Why**: A huge part of “the Web” is happening inside the browser. As a universal p2p networking stack, libp2p needs to be able to offer solutions for browser users.

**Goal**: js-libp2p supports both WebTransport and (libp2p-) WebRTC protocols, enabled by default. This allows connections between browsers and public nodes, and eventually between browsers and non-public nodes and in between browser nodes.

- [x] https://github.com/libp2p/js-libp2p/issues/1478
- [x] https://github.com/libp2p/js-libp2p/issues/1462
- [x] WebTransport https://github.com/libp2p/js-libp2p-webtransport

**Comment by dhuseby** [comment]
@achingbrain what's the status on the WebTransport subtask?

**Comment by p-shahi** [comment]
This is complete 🎉
