### ISSUE TITLE
identify + identify/push sanity checks

### ISSUE THREAD

**Issue by dapplion** [libp2p/js-libp2p#1469]
Multiple items to protect us:
- Provide an allow list of protocols, ignore all else
- Limit total count of protocols stored per peer (overlaps with above) in peer store
- Limit total count of addresses per peer in peer store
- Modify Identify protobuf decoder to apply limits above at decode time
- Add rate limit for built-in enabled by default protocols, at least identity, identify/push. Rate limit per peer and globally

After reviewing with @wemeetagain 
- 8KB naturally limits OOM
- Most important item is rate limiting to kick peers abusing bandwidth
- Prune peer store for garbage injected by connection spamming

**Comment by maschad** [comment]
>> Prune peer store for garbage injected by connection spamming

The application would has access to the PeerStore and so it can iterate through the PeerStore and determine what it defines as _garbage_ and subsequently prune it.

Closing this as it will be separated into two issues
- Rate limit inbound streams per protocol per connection https://github.com/libp2p/js-libp2p/issues/2093
- Modify Identify protons decoder to apply limits at decode time https://github.com/ipfs/protons/issues/113
