### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED while using libp2p through js-libp2p guide

### ISSUE THREAD

**Issue by sk1122** [libp2p/js-libp2p#1481]
- **Version**:

```json
 "dependencies": {
    "@chainsafe/libp2p-noise": "^10.1.0",
    "@libp2p/mplex": "^7.0.0",
    "@libp2p/tcp": "^6.0.2",
    "libp2p": "0.40.0"
  }
```

- **Platform**:

Ubuntu 22.04 LTS

- **Subsystem**:

#### Severity:

High

#### Description:

I was following libp2p js guide from https://docs.libp2p.io/guides/getting-started/javascript/, tried start node but got this error on first run
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/satyam/Desktop/code/js-libp2p/node_modules/libp2p/package.json`

I expected it to run without any error

#### Steps to reproduce the error:

- Install packages with above versions
- Run code from the guide

I think some packages are breaking and also I tried changing libp2p versions from `0.35.0` to `0.40.0`

**Comment by p-shahi** [comment]
@sk1122 can you trying running `npm update` and see if that resolves your issue?

**Comment by sk1122** [comment]
@p-shahi yeah tried it already

**Comment by p-shahi** [comment]
Can you modify the code snippets in the guide locally per: https://github.com/libp2p/js-libp2p/blob/master/doc/migrations/v0.39-v0.40.md and report back? Looking at the guide, it doesn't account for js-libp2p switching to using dependency injection for constructors

**Comment by achingbrain** [comment]
What version of node are you using?

**Comment by sk1122** [comment]
I am using node v18 and @p-shahi tried that, still same issue, removed node_modules and yarn.lock and reinstalled all the packages, but still not working

**Comment by achingbrain** [comment]
Can you share a small demo repo that has the code you are running please?

**Comment by sk1122** [comment]
@achingbrain  https://github.com/sk1122/js-libp2p-example, let me know if you face same issue

**Comment by T00rk** [comment]
I'm facing the same issue.
I tried using node 16.20, node 18.16 and node 20.3.

Here is my `tsconfig.json`:
```json
{
  "compilerOptions": {
    "declaration": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "rootDir": "./src",
    "skipLibCheck": false,
    "target": "ES2020",
    "module": "ES2020",
    "outDir": "./dist"
  },
  "exclude": [
    "test"
  ],
  "include": ["src/**/*"]
}
```

**Comment by maschad** [comment]
> I'm facing the same issue. I tried using node 16.20, node 18.16 and node 20.3.
> 
> Here is my `tsconfig.json`:
> 
> ```json
> {
>   "compilerOptions": {
>     "declaration": true,
>     "esModuleInterop": true,
>     "moduleResolution": "node",
>     "rootDir": "./src",
>     "skipLibCheck": false,
>     "target": "ES2020",
>     "module": "ES2020",
>     "outDir": "./dist"
>   },
>   "exclude": [
>     "test"
>   ],
>   "include": ["src/**/*"]
> }
> ```

What version Libp2p are you using?  Could you open a new issue using our [issue template](https://github.com/libp2p/js-libp2p/blob/master/.github/ISSUE_TEMPLATE/open_an_issue.md) so that we can debug it properly?

**Comment by T00rk** [comment]
It was an issue related to ts-node-dev.
I'm now using nodemon with ts-node/esm and it works well.

I've fixed some other things.

1 - Updated my `tsconfig.json`qith the values of your `aegir` project like so :

```json
{
  "compilerOptions": {
    "strict": true,
    "allowJs": true,
    "target": "ES2022",
    "module": "ES2022",
    "lib": ["ES2022", "DOM", "DOM.Iterable", "WebWorker"],
    "emitDeclarationOnly": false,
    "declaration": true,
    "removeComments": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true,
    "skipLibCheck": true,
    "stripInternal": true,
    "resolveJsonModule": true,
    "rootDir": "./src",
    "outDir": "./dist"
  },
  "ts-node": {
    "esm": true
  },
  "exclude": [
    "test"
  ],
  "include": ["src/**/*"]
}
``` 

2 - renamed my `*.ts` files `*.mts`
3 - updated my `package.json` like this : 

```json
...
"type": "module",
"exports":
{
  ".":
  {
    "default": "./dist/index.mjs",
    "import": "./dist/index.mjs",
    "require": "./dist/index.mjs",
    "types": "./dist/index.d.mts"
  }
},
...
```

It now works well.
I hope it'll help people who have this issue in the future.
