### ISSUE TITLE
Revisit dialing logic

### ISSUE THREAD

**Issue by mpetrunic** [libp2p/js-libp2p#1490]
> Dial obtains peerId from multiaddr and fetches all ma from peerstore connected to that peerId

The current behaviour is a little confusing - I think if you dial a PeerId it should do this, if you dial one or more multiaddrs it should probably only dial that/those multiaddrs.  If dialing multiple multiaddrs it needs to assert that they all are for the same remote peer as well, since you only get one connection back.

> Can we remove this: [v0.39.2/src/connection-manager/dialer/index.ts#L262](https://github.com/libp2p/js-libp2p/blob/v0.39.2/src/connection-manager/dialer/index.ts?rgh-link-date=2022-11-21T14%3A02%3A50Z#L262) and just take first this.maxAddrsToDial addresses from supportedAddrs ?

I think ignoring seemingly arbitrary addresses might make failures hard to reason about.  The dial request might need to treat maxAddrsToDial as a concurrency limit instead of a hard stop on dialing at all?

_Originally posted by @achingbrain in https://github.com/libp2p/js-libp2p/issues/1409#issuecomment-1323575452_

**Comment by mpetrunic** [comment]
> The current behaviour is a little confusing - I think if you dial a PeerId it should do this, if you dial one or more multiaddrs it should probably only dial that/those multiaddrs. If dialing multiple multiaddrs it needs to assert that they all are for the same remote peer as well, since you only get one connection back.

The submitted ma also get's dialed but we add all addresses from address book and all resolved addresses which can easily exceed max number of addresses
 

> I think ignoring seemingly arbitrary addresses might make failures hard to reason about. The dial request might need to treat maxAddrsToDial as a concurrency limit instead of a hard stop on dialing at all?

I think there is another option for concurrency called maxParallelDials which is used to obtain tokens but I cannot find where they are used.

I feel like the current setup is some way to refresh old peers with a lot of old addresses but if the user submitted ma to dial, it makes sense to use that one and maybe a few old ones. 

_Originally posted by @mpetrunic in https://github.com/libp2p/js-libp2p/issues/1409#issuecomment-1323614331_

**Comment by mpetrunic** [comment]
> The remaining piece here is around peers with more dialable adresses than the `maxAddrsToDial` limit. Currently we refuse to dial them at all. Instead this should probably be a per-peer concurrency limit rather than a dial/don't dial decider.

We already have that: https://github.com/libp2p/js-libp2p/blob/master/src/connection-manager/dialer/index.ts#L70

**Comment by achingbrain** [comment]
So we do! I think this issue can be closed then.
