### ISSUE TITLE
Error: Cannot find module 'readable-stream'

### ISSUE THREAD

**Issue by wangfaguo** [libp2p/js-libp2p#1492]
- **Version**: js-libp2p 0.40.0

- **Platform**: Mac mini (M1, 2020)

- **Subsystem**:  Mac OS 12.5.1  ,Nodejs v18.12.1

#### Description:

I got this error after ` git clone https://github.com/libp2p/js-libp2p.git`  ` cd js-libp2p` ` npm install`

xxxxx@xxxxxdeMac-mini js-libp2p-0.40.0 % npm install
npm ERR! code 1
npm ERR! path /Users/xxxxx/Downloads/js-libp2p-0.40.0/node_modules/go-libp2p
npm ERR! command failed
npm ERR! command sh -c -- node src/post-install.js
npm ERR! node:internal/modules/cjs/loader:998
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module 'readable-stream'
npm ERR! Require stack:
npm ERR! - /Users/xxxxx/Downloads/js-libp2p-0.40.0/node_modules/duplexify/index.js
npm ERR! - /Users/xxxxx/Downloads/js-libp2p-0.40.0/node_modules/peek-stream/index.js
npm ERR! - /Users/xxxxx/Downloads/js-libp2p-0.40.0/node_modules/gunzip-maybe/index.js
npm ERR! - /Users/xxxxx/Downloads/js-libp2p-0.40.0/node_modules/go-libp2p/src/download.js
npm ERR! - /Users/xxxxx/Downloads/js-libp2p-0.40.0/node_modules/go-libp2p/src/post-install.js
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:841:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1061:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:103:18)
npm ERR!     at Object.<anonymous> (/Users/xxxxx/Downloads/js-libp2p-0.40.0/node_modules/duplexify/index.js:1:14)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1159:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1037:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:878:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1061:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/Users/xxxxx/Downloads/js-libp2p-0.40.0/node_modules/duplexify/index.js',
npm ERR!     '/Users/xxxxx/Downloads/js-libp2p-0.40.0/node_modules/peek-stream/index.js',
npm ERR!     '/Users/xxxxx/Downloads/js-libp2p-0.40.0/node_modules/gunzip-maybe/index.js',
npm ERR!     '/Users/xxxxx/Downloads/js-libp2p-0.40.0/node_modules/go-libp2p/src/download.js',
npm ERR!     '/Users/xxxxx/Downloads/js-libp2p-0.40.0/node_modules/go-libp2p/src/post-install.js'
npm ERR!   ]
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.12.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxx/.npm/_logs/2022-11-24T09_52_15_910Z-debug-0.log

**Comment by mpetrunic** [comment]
You didn't clone the tagged version but the latest from the master branch. This error is gone so I will close this. Let us know if this happens again.
