### ISSUE TITLE
node.pubsub.on function got removed, what should I do?

### ISSUE THREAD

**Issue by ruialves35** [libp2p/js-libp2p#1507]
- **Version**: 0.40.0

- **Platform**: GNU/Linux

- **Subsystem**: Pubsub

#### Description:
Hi, 
Im trying to use PubSub of this library, but I saw that the node.pubsub.on(topic, handler) function got removed. On the other hand, this function is still on the documentation. So I don't know if it's normal or not. This function proves to be very useful to define a proper handler for each topic, instead of having a node.pubsub.addEventListener('message', handler) generic to everyone. Am I doing something wrong? Should I use the addEventListener? Im kinda new on this fields of topics and distributed systems so I don't know really well what I should do.  

#### Steps to reproduce the error:
- Create a Node
- Subscribe to a topic
- Try to define the .on function of that topic

**Comment by ruialves35** [comment]
> * **Version**: 0.40.0
> * **Platform**: GNU/Linux
> * **Subsystem**: Pubsub
> 
> #### Severity: High
> #### Description:
> Hi, Im trying to use PubSub of this library, but I saw that the node.pubsub.on(topic, handler) function got removed. On the other hand, this function is still on the documentation. So I don't know if it's normal or not. This function proves to be very useful to define a proper handler for each topic, instead of having a node.pubsub.addEventListener('message', handler) generic to everyone. Am I doing something wrong? Should I use the addEventListener? Im kinda new on this fields of topics and distributed systems so I don't know really well what I should do.
> 
> #### Steps to reproduce the error:
> * Create a Node
> * Subscribe to a topic
> * Try to define the .on function of that topic

On the other hand, the https://github.com/libp2p/js-libp2p/tree/master/examples/pubsub example is not correct since the output is not completed and I'm receiving default messages on 'message' event when discovering new peers, how can I stop receiving those messages?

**Comment by achingbrain** [comment]
PubSub now uses the [EventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget) API instead of node's EventEmitter.

Please see the [upgrade guide](https://github.com/libp2p/js-libp2p/blob/master/doc/migrations/v0.36-v0.37.md#pubsub).

**Comment by ruialves35** [comment]
Thank you for your answer!
What was the reason for this changes? I believe this makes the code harder and we have to filter inside the event for the specific topic that we want to listen, right? That's a bit messy

**Comment by ruialves35** [comment]
Also, should remove the older methods from the docs (I think I saw the right docs :') )
