### ISSUE TITLE
Control inbound/outbound connection limits separately

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p#1508]
Currently the connection manager has settings such as `maxConnections` and `minConnections` - these are applied to both incoming and outgoing connections together.  A user should be able to apply these limits to inbound and outbound connections separately.

Note: when this done we should also update doc/LIMITS.md per https://github.com/libp2p/js-libp2p/pull/1456

**Comment by BigLep** [comment]
@p-shahi : it looks like @maschad is working on this issue.  Can we get him set as the assignee (I assume we need to add him to the org)?

**Comment by maschad** [comment]
> @p-shahi : it looks like @maschad is working on this issue. Can we get him set as the assignee (I assume we need to add him to the org)?

 [the PR ](https://github.com/libp2p/js-libp2p/pull/1511) is ready for review, looks like @p-shahi already requested a review from @achingbrain 👍🏾  Thanks @BigLep

**Comment by maschad** [comment]
Closing this in light of the discussion [here](https://github.com/libp2p/js-libp2p/pull/1511#issuecomment-1421614081)
