### ISSUE TITLE
Content Routing information lost when crash the nodes

### ISSUE THREAD

**Issue by ruialves35** [libp2p/js-libp2p#1512]
- **Version**: 0.40.0

- **Platform**: Linux

- **Subsystem**: PubSub

#### Description:
Hello, 
When I have 2 nodes running and I put content in the content routing, everything goes fine and each node can access the information. Lets say we have node A and B.

A and B are connected. When I Crash node A and try to get information from content routing using node B, everything is fine. If then I start node A again, which connects to node B, and try to get content routing info from node A, it works fine (because it gets the info from node B). Then if I crash node B, the node A is not able to get the information again (that's why I think it gets the info from node B).

Shouldn't the start function get the information of the content routing?

**Comment by achingbrain** [comment]
Ordinarily putting a value to the content routing would ensure that the record is stored on multiple peers to increase redundancy so a two-node test isn't representative of the real world.

The DHT module has a [providers component](https://github.com/libp2p/js-libp2p-kad-dht/blob/master/src/providers.ts) which stores provider records in the datastore, this should mean that node A can recognise node B as a provider of a CID even if it's not on the network, as long as it's got the provider record for the CID either from node B or another node storing that record.

There really need to be three nodes here:

1. First node B runs the provide operation for a CID, it selects node C to store the provider record.
2. Node A does a `GET_PROVIDERS` for the CID and asks node C if it knows which node provides it, node C returns the provider record pointing to node B.
3. Stop node C and run the `GET_PROVIDERS` from node A again, it should contact node B as it already has the provider record in its cache.
4. Stop node A and start it again to clear the cache, the `GET_PROVIDERS` result should still be node B as it should have stored the provider record in its datastore.

Note that the provider record expires after 24 hours.

**Comment by ruialves35** [comment]
The problem here is crashing node B, which was the One storing the information. Isnt there a replication factor so that when a node goes down the content routing is re-arranged?

**Comment by maschad** [comment]
The replication factor is that the DHT storing the provider record for the CID from Node B, if that node is inactive for over 24 hours then that record would expired. The more nodes B is connected to the greater the redundancy.
