### ISSUE TITLE
Fix Flakey Tests on CI for PubSub examples

### ISSUE THREAD

**Issue by maschad** [libp2p/js-libp2p#1540]
#### Severity:

Low

#### Description:

On occasion the [test-example (pubsub)](https://github.com/libp2p/js-libp2p/actions/runs/3861945664/jobs/6583221048#logs) fails with [messages not being received](https://github.com/libp2p/js-libp2p/actions/runs/3861945664/jobs/6583221048#step:5:27) I suspect we could try increasing the delay 

#### Steps to reproduce the error:

Not necessarily easily reproducible as it doesn't happen frequently

**Comment by tabcat** [comment]
I had similar issues and fixed by listening for `subscription-change` events 
https://github.com/opalsnt/welo/commit/3f60808cde11f90f4789a298426e6fdcf9603f98

for some reason even with adding long timeouts some nodes would never peer otherwise

**Comment by achingbrain** [comment]
I think instead of increasing the delay a better fix in the message filtering test might be for `node1` to wait until it sees `node2` and `node3` in it's peer list for the `'fruit'` topic before publishing the messages?

**Comment by maschad** [comment]
I was originally confused by the [logs](https://github.com/libp2p/js-libp2p/actions/runs/3891376024/jobs/6641677031#step:5:25) saying `Error: Not enough banana messages - received 1, expected 2` even though [two _banana_ messages](https://github.com/libp2p/js-libp2p/actions/runs/3891376024/jobs/6641677031#step:5:25) had been received. 

> I think instead of increasing the delay a better fix in the message filtering test might be for `node1` to wait until it sees `node2` and `node3` in it's peer list for the `'fruit'` topic before publishing the messages?

What's interesting is that this approach doesn't seem to work unless `node3` dials `node1` directly,  i.e. `node3` doesn't show up in `node1` 's subscribers  unless `node3` dials `node1` directly (see https://github.com/libp2p/js-libp2p/pull/1543/commits/7a6bff35383c291b27455bf142a1eacf6af7c766#diff-9483cec2def56f6a8975c97c997d70741698e22fb8a971785d83502f7169bbf1R42)
