### ISSUE TITLE
Expose underlying implementation

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p#1567]
In Lodestar, we're forced to do make some little wrapper functions to get the types of the default implementations. (And we're just lucky that the types are exported, despite your intention :joy:) These default implementations are often necessary to fine-tune or inspect data not available in the generic interface types.

Maybe there's a better way to do this?

See:
https://github.com/ChainSafe/lodestar/blob/unstable/packages/beacon-node/src/network/util.ts#L71-L90

**Comment by wemeetagain** [comment]
I'd almost say there's no need to have an interface-connection-manager, interface-registrar, etc if there's not even a way to swap in alternative implementations.

**Comment by maschad** [comment]
> I'd almost say there's no need to have an interface-connection-manager, interface-registrar, etc if there's not even a way to swap in alternative implementations.

Agreed. My understanding is that the Connection Manager and Registrar in particular are apart of the core libp2p stack and are intended to have concrete implementations [according to the spec](https://github.com/libp2p/js-libp2p/issues/744).  Looking at [Go's Base connection manager](https://github.com/libp2p/go-libp2p/blob/da3adbc438b38101802ee32d52789508e66c0a20/p2p/net/connmgr/connmgr.go#L262) , it seems to have been implemented that way (as a `struct` as opposed to an interface).

I would say should there arise a need to have added functionality then a consumer could extend the `ConnectionManager` or `Registrar` classes.

**Comment by maschad** [comment]
https://github.com/libp2p/js-libp2p/issues/1574 should solve some of the issues we where facing in lodestar, but for [this particular method](https://github.com/ChainSafe/lodestar/blob/unstable/packages/beacon-node/src/network/util.ts#L73-L75) which gets **all connections and their associated peer ids** , I don't see why we couldn't modify the [connection manager interface](https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/interface-connection-manager/src/index.ts#L39) to expose that connections map.

**Comment by achingbrain** [comment]
To get all connections, call [libp2p.getConnections()](https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/interface-libp2p/src/index.ts#L324).  Each connection has a [remotePeer](https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/interface-connection/src/index.ts#L149) property that is the PeerId of the remote node.

**Comment by maschad** [comment]
> To get all connections, call [libp2p.getConnections()](https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/interface-libp2p/src/index.ts?rgh-link-date=2023-02-02T17%3A05%3A07Z#L324). Each connection has a [remotePeer](https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/interface-connection/src/index.ts?rgh-link-date=2023-02-02T17%3A05%3A07Z#L149) property that is the PeerId of the remote node.

This would add additional runtime logic which in some cases could be detrimental to performance.
