### ISSUE TITLE
Error: No "exports" main defined in <PATH>/libp2p/package.json

### ISSUE THREAD

**Issue by akp111** [libp2p/js-libp2p#1583]
libp2p version: `0.42.2`
Node version: `16.0.0`
npm version : `7.10.0`

I am trying to use [this](https://github.com/libp2p/js-libp2p/blob/master/examples/discovery-mechanisms/3.js) in typescript to test out. The tsconfig.json I am using:
```ts
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./src",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  },
  "ts-node": {
    "transpileOnly": true,
    "files": true,
    "experimentalResolver": true
  }
}

```

But it gives me the following error while doing :
`import { createLibp2p } from 'libp2p'`

```Error: No "exports" main defined in /Users/ashispradhan/Desktop/Projects/EPNS/push-storage-node/node_modules/libp2p/package.json```

**Comment by Igx22** [comment]
I've created a sample project with a long readme.
It shows all the errors that pop up when I try to use the typescript compiler X libp2p.
https://github.com/Igx22/p2p-test

**Comment by Igx22** [comment]
I've added more details here.

One more test case https://github.com/Igx22/p2p-test#option-2-start-compiled-js-from-distsrcindexjs-on-typescript-49

**Comment by achingbrain** [comment]
I think the fundamental problem here is as you have found, [ts-node does not support ESM](https://github.com/TypeStrong/ts-node/issues/1007).

Until it does, the only solution you have, if you must use ts-node, is to have your project export CJS but load libp2p (and any other ESM-only module) either from a `.mjs` file or from a common js file with a [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import).

In your test project, I make the following changes:

```js
// tsconfig.json
{
"compilerOptions": {
    "module": "commonjs",
    // ... other stuff
}
```

And add a cjs file (I called it `index.cjs`, you can call it `index.js` if you remove `"type": "module"` from your `package.json`):

```js
// src/index.cjs
async function main () {
  await import('./p2p-discovery.mjs')
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
```

Then run it, everything is happy:

```console
% npx ts-node src/index.cjs 
node 1 is listening on:
/ip4/127.0.0.1/tcp/54449/p2p/12D3KooWHaikSqN6i3PVALEVLzCe2uVB7uyRU5n9AAQ29TCF9uWT
/ip4/192.168.1.10/tcp/54449/p2p/12D3KooWHaikSqN6i3PVALEVLzCe2uVB7uyRU5n9AAQ29TCF9uWT
node 2 is listening on:
/ip4/127.0.0.1/tcp/54450/p2p/12D3KooWC85PF1CF68o6HCNEny57bE8kv3rLppPtd4ZRSvuZc9VS
/ip4/192.168.1.10/tcp/54450/p2p/12D3KooWC85PF1CF68o6HCNEny57bE8kv3rLppPtd4ZRSvuZc9VS
Hello p2p world!
```

**Comment by achingbrain** [comment]
Actually, having said that, if I rename `./src/index.cjs` to `./src/test.ts` it breaks:

```console
% npx ts-node ./src/test.ts
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/alex/test/p2p-test/src/p2p-discovery.mjs not supported.
Instead change the require of /Users/alex/test/p2p-test/src/p2p-discovery.mjs to a dynamic import() which is available in all CommonJS modules.
    at /Users/alex/test/p2p-test/src/index-c.ts:2:40
    at async main (/Users/alex/test/p2p-test/src/index-c.ts:2:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

The above message means it's transpiled `await import('./p2p-discovery.mjs')` to `await require('./p2p-discovery.mjs')` which is completely wrong.

I think you need to wait until `ts-node` has it's ducks in a row about ESM.

**Comment by Igx22** [comment]
https://github.com/Igx22/p2p-test/pull/1/files

This fix actually helped.
But now I'm not sure if it's safe to use this in a medium sized established project.
I'll probably try to stick with an older libp2p, a js version.

**Comment by achingbrain** [comment]
> But now I'm not sure if it's safe to use this in a medium sized established project.

What are your concerns around this?

> I'll probably try to stick with an older libp2p, a js version.

This is not recommended, newer features and bug fixes will not be ported to older versions.

**Comment by Igx22** [comment]
>What are your concerns around this?
70% of our code base is made up of commonjs / require etc.

>This is not recommended, newer features and bug fixes will not be ported to older versions.
Fully agree

**Comment by achingbrain** [comment]
For CJS codebases it's safe to use dynamic imports, it's less safe to stick on old versions.

Looks like you solved your problem with the ts-node upgrade & extra config though, so I'm going to close this.
