### ISSUE TITLE
Reconsider usage of "events" package: Maybe remove it from the dependencies

### ISSUE THREAD

**Issue by ukstv** [libp2p/js-libp2p#1601]
`package.json` states that you depend on `events` package `^3.3.0`.

In the following files:
- `src/identify/index.ts`
- `src/ping/index.ts`
- `src/peer-routing.ts`
- `src/circuit/transport.ts`
- `src/fetch/index.ts`
- `src/upgrader.ts`
- `src/connection-manager/index.ts`
- `src/connection-manager/dialer/index.ts`
- `src/connection-manager/dialer/dial-request.ts`
- `src/identify/index.ts`
you use the following import:
```
import { setMaxListeners } from 'events'
```

According to [Node.js resolution algorithm](https://nodejs.org/docs/latest-v18.x/api/esm.html#resolver-algorithm-specification) it means that you use native Node.js `events` module. Thus, there is no need to use `events` package.

Moreover, even if you intend to use `events` package, it has no `setMaxListeners` exported. So, please, remove `events` package from your dependencies. It confuses people and computers alike.

**Comment by achingbrain** [comment]
From memory this is here for the bundler - it can certainly be removed if it is no longer present.  Please open a PR and we can continue the conversation there.

**Comment by achingbrain** [comment]
Closing and awaiting a PR.
