### ISSUE TITLE
Add hop relay listening functionality to the Connection Manager

### ISSUE THREAD

**Issue by maschad** [libp2p/js-libp2p#1610]
Whenever we do not have enough relays, we need to try to listen on available hop relay connections. This should be the responsibility of the connection manager as opposed to the [circuit relay client](https://github.com/libp2p/js-libp2p/blob/593deefe1268e0019354964b87b49fac1a3981ed/src/circuit/client.ts#L257)

**Comment by achingbrain** [comment]
The problem with this is that it requires the connection manager to know about relays and their semantics and configuration which makes it hard to make relay functionality opt-in.

**Comment by achingbrain** [comment]
Closing after triage discussion
