### ISSUE TITLE
Add retry support for listening in Transport Manager 

### ISSUE THREAD

**Issue by maschad** [libp2p/js-libp2p#1614]
In order to build more robust support for [listening on an address in the transport manager](https://github.com/libp2p/js-libp2p/blob/593deefe1268e0019354964b87b49fac1a3981ed/src/transport-manager.ts#L170), we could look at adding a certain amount of retries (using something like [p-retry](https://github.com/sindresorhus/p-retry) since it's already used across the org) to avoid failures due to temporary errors. Once we are listening on at least one address then there need not be any further retries.

**Comment by achingbrain** [comment]
Triage discussion: we want to either succeed or fail as quickly as possible.  If retry logic is desirable it can be added by the user to the application startup process.
