### ISSUE TITLE
Batch dialling

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p#1616]
The `libp2p.dial` method should support dialling multiple multiaddrs - it currently supports dialing a peer id (in which case multiaddrs are retrieved from the peer store) or a single multiaddr.

Since only a single connection is returned from a dial, the multiaddrs being dialled should be checked to ensure they either all contain the same peer id or that none of them contain a peer id.

If they all have the same peer id we are guaranteed to return a connection to the expected remote peer, if none of them contain a peer id then the user did not expect a connection to a specific peer so we are ok to return a connection to whatever remote peer we managed to connect to first.

**Comment by maschad** [comment]
This may be a strange case but how would we handle a situation if they have different `peerIDs` for the multiaddrs? return the one we connect to first?
