### ISSUE TITLE
Duplicate connections can occur when dnsaddr addresses resolve to multiple addresses

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p#1628]
A dnsaddr multiaddr that resolves to, for example, both dns4 and dns6 addresses can result in two connections to the same peer.

For example connecting to `/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa` results in connection to:

* `/dns4/ny5.bootstrap.libp2p.io/tcp/443/wss/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa`
* `/dns6/ny5.bootstrap.libp2p.io/tcp/443/wss/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa`

libp2p should dial all addresses that the original dnsaddr resolves to, but it should only keep one connection open.

**Comment by maschad** [comment]
We should write a test to verify this.

**Comment by SgtPooki** [comment]
<details>
<summary>JS Colo 2024 discussion</summary>

we resolve multiaddrs upfront and then dial them sequentially now, shouldn't be an issue

we could potentially do an optimization when resolving multiaddrs, but we can address later if needed
</details>

Closing as this should no longer be a concern
