### ISSUE TITLE
bug(docs): dialer config instructions incorrect/outdated

### ISSUE THREAD

**Issue by SgtPooki** [libp2p/js-libp2p#1645]
see https://github.com/libp2p/js-libp2p/blob/47c6e8f84f253edcaf113ec7b1d09617fd093c9b/doc/CONFIGURATION.md?plain=1#L546-L585

However, Libp2pInit.dialer doesn't exist: 

![image](https://user-images.githubusercontent.com/1173416/226985202-26c4033f-dc05-481e-9d49-d6da3f4c9a95.png)

**Comment by maschad** [comment]
Thanks for this @SgtPooki the docs are definitely a bit out of date 😓   That being said, all those configurations moved to the [connection manager config](https://github.com/libp2p/js-libp2p/blob/master/src/config.ts#LL24C8-L32C12) during the [conversion to TS PR](https://github.com/libp2p/js-libp2p/pull/1172/files#diff-c3095d5010e65c52737a98a5d618ea24049ebe90c8470752426081d70ed6e012) and I am not sure why. Maybe @achingbrain can explain. 

I actually have an unrelated [PR in draft](https://github.com/libp2p/js-libp2p/pull/1594) which would move them back to the `DialerConfig`

**Comment by achingbrain** [comment]
> Maybe @achingbrain can explain.

As ever, just trying to reduce the number of moving parts that are exposed to consumers.

`libp2p.dial` calls `connectionManager.openConnection`, which calls the dialler.

Internal components also call `connectionManager.openConnection`.

Thus, the connection manager is in charge of opening and closing connections - if you call the dialler directly then the connection manager is no longer in charge of managing connections, so, if you like, the dialler is an internal component of the connection manager, consequently the dialling related settings are passed to the connection manager and the dialler is an internal implementation detail.
