### ISSUE TITLE
Cannot import circuitRelayTransport from "libp2p/circuit-relay"  || How to setup a relay node dialer

### ISSUE THREAD

**Issue by yooooyyooooy** [libp2p/js-libp2p#1655]
- **Version**: ^0.43.2

- **Platform**:
 

- **Subsystem**:

#### Description:

I'm trying to setup a dialer node that dials to a relay node in order to connect to the peer node in private network.
I tried to import { circuitRelayTransport} from 'libp2p/circuit-relay' but then got the error cannot find module libp2p/circuit-relay. 
When I inspect the package.json file of libp2p module at the export, i saw:
```ts
  "exports": {
    ".": {
      "types": "./dist/src/index.d.ts",
      "import": "./dist/src/index.js"
    },
    "./circuit-relay": {
      "types": "./dist/src/circuit/index.d.ts",
      "import": "./dist/src/circuit/index.js"
    },
    "./insecure": {
      "types": "./dist/src/insecure/index.d.ts",
      "import": "./dist/src/insecure/index.js"
    },
    "./pnet": {
      "types": "./dist/src/pnet/index.d.ts",
      "import": "./dist/src/pnet/index.js"
    }
  },
```
which i guess there should be nothing  wrong about  
```ts
import { circuitRelayTransport} from 'libp2p/circuit-relay' 
```
How can I resolve the issue, or are there any alternative ways to set up a relay node dialer?

**Comment by leonwilly** [comment]
I can confirm this as well. The issue is that the directory name is `circuit` however in the `package.json` under exports the path is `circuit-relay`. As a workaround you can modify your package.json and lock it until they fix this.  This should be labeled critical and fixed immediately.

**Comment by p-shahi** [comment]
@maschad is this something you can take on?
