### ISSUE TITLE
pubsub example is not work

### ISSUE THREAD

**Issue by Elvenisboy** [libp2p/js-libp2p#167]
- **Version**: 0.18.0
- **Platform**: linux
- **Subsystem**:

#### Steps to reproduce the error:

first, i write code like this
```
const node = await before()
node.start((error) => {
    if (error) console.log(error)
})

node.once('peer:discovery', (peer) => node.dial(peer, () => {}))
node.pubsub.subscribe('news',
    (msg) => console.log(msg.from, msg.data.toString())
)

publish:
 node.pubsub.publish('news', Buffer.from('Bird bird bird, bird is the word!')
```
And nodejs tell me that 
```
/xxxxx/node_modules/libp2p/src/pubsub.js:59
setImmediate(() => callback())
                         ^

TypeError: callback is not a function
```

then I read the pubsub source, I found that i need to write a callback function, so i add a () => {}
But, I can't get  subscribe in console.

So, I copy the example code, it also don't work. It is also lake a callbak function.
emmmmm, how to make it work? I think a test/demo need not a callback

**Comment by Elvenisboy** [comment]
emmmm, I will complete the example later

**Comment by diasdavid** [comment]
Thanks for reporting @Elvenisboy, just fixed it https://github.com/libp2p/js-libp2p/commit/e531b1bf3dcd412f3c1ae96bc159d1a3cb44a121 :)
