### ISSUE TITLE
content routing example with node1.peerStore.patch won't work anymore because of updates to the peerStore class structure in "libp2p": "0.40.0"

### ISSUE THREAD

**Issue by TimDaub** [libp2p/js-libp2p#1737]
- https://github.com/libp2p/js-libp2p/blob/master/examples/peer-and-content-routing/1.js

await node1.peerStore.patch(node2.peerId, {
    multiaddrs: node2.getMultiaddrs()
  })

I'm pretty sure this won't work because only the store implements these functions now: https://github.com/libp2p/js-libp2p-peer-store/blob/master/src/store.ts

**Comment by achingbrain** [comment]
This will be fixed by the 0.45.x release - https://github.com/libp2p/js-libp2p/pull/1707 - it pulls all these changes together.

**Comment by achingbrain** [comment]
0.45.x has been shipped - please can you update all your `@libp2p/*` deps and try again?

**Comment by p-shahi** [comment]
@TimDaub Were you able to double check?

**Comment by TimDaub** [comment]
nope sorry I won‘t check but thanks for solving
