### ISSUE TITLE
[feature request]: Low-Level Connection Management

### ISSUE THREAD

**Issue by kumavis** [libp2p/js-libp2p#175]
### idea:
some additional controls over establishing/denying connections
- hooks for denying connections before they are established (when possible)
- ConnectionManager configuration that can limit the number of connections per transport

### usecase:
MetaMask is building an Ethereum light client for the browser using libp2p.
We intend to use webrtc which is resource intensive and can only safely support 2-5 active connections.
We need to be able to deny incoming webrtc connection attempts after some threshold.

**Comment by pgte** [comment]
@kumavis that's great feedback, thanks!
Opened these issues on [libp2p-connection-manager](https://github.com/libp2p/js-libp2p-connection-manager/issues).

**Comment by diasdavid** [comment]
@kumavis if you have some spare cycles, test out the connection manager already released in libp2p 0.22 and that will also get released in js-ipfs 0.30 https://github.com/ipfs/js-ipfs/issues/1375

**Comment by jacobheun** [comment]
We are aiming to slot connection gating into the 0.30 release.
