### ISSUE TITLE
when listener handle a protocol, how to deal error?

### ISSUE THREAD

**Issue by Elvenisboy** [libp2p/js-libp2p#176]
- **Version**:0.18.0
- **Platform**:linux
- **Subsystem**:

#### Description:

sometimes, when a listener peer handle, it may get some errors, like dialer offline.
How to deal with these errors? use `console.log(error)`  may be a bad idea. If use hangup, I can't get peerInfo from Connection.

**Comment by vasco-santos** [comment]
With the new version of libp2p, using `async await` and `async iterators`, this should not be a problem anymore

**Comment by Elvenisboy** [comment]
> 在新版本的libp2p中，使用`async await`和`async iterators`，这不再是问题。

sounds good😀
