### ISSUE TITLE
bug: start/stop handler registration is broken 

### ISSUE THREAD

**Issue by SgtPooki** [libp2p/js-libp2p#1787]
I'm making changes to ipld-explorer-components (see https://github.com/ipfs/ipld-explorer-components/pull/360) and trying to reduce how much libp2p is doing behind the scenes with Helia. When I try stopping/starting libp2p, there is some cleanup that is not happening properly:

The changes I recently made that is surfacing this error are in https://github.com/ipfs/ipld-explorer-components/pull/360/commits/95b50babdfca1de00781612f34544b27d7c6f697

And that ultimately results in the following errors (i've seen other similar "already registered" handler errors)

```
react_devtools_backend_compact.js:2367 unable to start libp2p CodeError: Handler already registered for protocol /meshsub/1.1.0
    at DefaultRegistrar.handle (registrar.ts:79:13)
    at index.ts:563:19
    at Array.map (<anonymous>)
    at GossipSub.start (index.ts:562:24)
    at async components.ts:73:11
    at async Promise.all (:5173/index 11)
    at async Proxy._invokeStartableMethod (components.ts:69:5)
    at async Proxy.start (components.ts:83:5)
    at async Libp2pNode.start (libp2p.ts:228:7)
    at async getRawBlock (get-raw-block.ts:101:9)
o
```

Is there something else I'm supposed to be doing? Why isn't this being handled properly?

cc @achingbrain

**Comment by achingbrain** [comment]
Looks like gossipsub registers multicodec handlers in it’s start method but then doesn’t unregister them in it’s stop method.

Does it work if you disable gossipsub or are there other misbehaving modules?

**Comment by SgtPooki** [comment]
> Does it work if you disable gossipsub or are there other misbehaving modules?

I'll attempt a small repro case and put up a repro

**Comment by p-shahi** [comment]
@SgtPooki it's been fixed in https://github.com/ChainSafe/js-libp2p-gossipsub/releases/tag/v8.0.1 can you try that release and see if it fixed?

**Comment by maschad** [comment]
This should be fixed now. Please re-open if you see this is still an issue.
