### ISSUE TITLE
Error: no protocol with code: 56

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-libp2p#179]
- **Version**: libp2p `0.19.0`
- **Platform**: `Linux - 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- **Subsystem**: identify?

#### Steps to reproduce the error: 
[logs.txt](https://github.com/libp2p/js-libp2p/files/1859271/logs.txt)

Just run a node with some protocols missing in the protocols table. (Or use https://libp2p-nodetrust.tk/demo which apparently causes the server to crash after connecting - it restarts)

#### Possible fix:
Just write these errors to stderr or use the debug log to notify the user of that error but PLEASE don't crash the whole thing. (This did happen often in the past, this will happen often in the future)

**Comment by dryajov** [comment]
Hmm, 56 is has been assigned to `/dnsaddr` (changed from 53) in the latest `js-multiaddr` release (3.1.0). Are you running two nodes with different versions of `js-multiaddr` or you happen to have two conflicting versions of it somewhere in your js-ipfs install?

> Just write these errors to stderr or use the debug log to notify the user of that error but PLEASE don't crash the whole thing. (This did happen often in the past, this will happen often in the future)

Agree, this shouldn't crash the node.

**Comment by mkg20001** [comment]
I don't know where it's really coming from. The intent behind opening this issue is to prevent such things from happening again and again (after /p2p-ws-star got created, /dns => /dnsaddr rename - this might be the issue - and many other breaking changes that will follow)
