### ISSUE TITLE
Can I REST over libp2p Connection?

### ISSUE THREAD

**Issue by hubertokf** [libp2p/js-libp2p#181]
I dont know if i can ask this here, but here it go.

I want to make an API with js-libp2p. I know that I can handle a protocol simply using handle function, but it do not give responses. For example: If i make a request to /api/resources/ i want to get a list of resources (ok, i do have procedures to get those resources from database e.g ). I just want to give a json (object) response.

Is there a way to do that?

If its not possible, i was planning to make a kind of handshake to deal with communications between a pair of peers.

**Comment by dryajov** [comment]
Hrm... no. If I understand your question correctly you want to use protocol identifiers as RPC endpoints? In that case, that's not the correct usage. Even tho it might look like an endpoint name, it's not that, `/api/resource` is a multistream protocol name, using it as some sort of RPC endpoint would not be the correct thing to do. 

As for returning a JSON or any other data from your handler, you can but it has to be piped to the provided connection stream.

Take a look here https://github.com/libp2p/js-libp2p/blob/master/examples/echo/src/listener.js or here https://github.com/libp2p/js-libp2p/blob/master/examples/chat/src/listener.js for an example of a `handle` method implementation. 

_Note that we use http://caolan.github.io/async/docs.html and https://pull-stream.github.io/ through the codebase._

**Comment by hubertokf** [comment]
RPC was the keyword!

Apologies about the delay. When i read you talking about RPC, i realized that it is what I need. So I found [libp2p-rpc](https://github.com/beingmohit/libp2p-rpc).

Thank you very much about the tip :+1:

**Comment by diasdavid** [comment]
Great find! https://github.com/beingmohit/libp2p-rpc \o/
