### ISSUE TITLE
(examples) Readme needs updating to v45 api

### ISSUE THREAD

**Issue by DougAnderson444** [libp2p/js-libp2p#1810]
https://github.com/libp2p/js-libp2p/blob/de61ddb4b4505ea04d83eb8738bcebcc5d0f9e3e/examples/pubsub/README.md?plain=1#L66

**Comment by maschad** [comment]
Thanks for raising this @DougAnderson444 , these types of doc issues should be solved once we have https://github.com/libp2p/js-libp2p/pull/1505 merged and https://github.com/libp2p/js-libp2p/issues/1777 resolved.

In the interim would you be able to create a PR to update this?
