### ISSUE TITLE
Feat: Allow cancellation of pending dials in queue 

### ISSUE THREAD

**Issue by maschad** [libp2p/js-libp2p#1822]
Following up from the conversation [here](https://github.com/libp2p/js-libp2p-interfaces/pull/382#issuecomment-1518574606) consider adding a cancel method to remove a pending dial from the queue and reject all promises waiting on it.

**Comment by achingbrain** [comment]
Closing as this hasn't come up again after (almost) a year.  The more common use case is to cancel the operation that caused the dial to get added to the queue, rather than yanking the rug out from under the operation.
