### ISSUE TITLE
Setup connection-manager and expose it

### ISSUE THREAD

**Issue by pgte** [libp2p/js-libp2p#183]
- [x] install [`libp2p-connection-manager`](https://github.com/libp2p/js-libp2p-connection-manager)
- [x] instantiate it and hook it up
- [x] expose it

**Comment by pgte** [comment]
The API still needs to be discussed / reviewed / approved

**Comment by diasdavid** [comment]
Done with https://github.com/libp2p/js-libp2p/pull/184 and getting exposed in js-ipfs 0.30 as well! https://github.com/ipfs/js-ipfs/issues/1375
