### ISSUE TITLE
Point to a released Go version in example

### ISSUE THREAD

**Issue by ddimaria** [libp2p/js-libp2p#1837]
Since the go-libp2p-webrtc PR hasn't been merged, we need to point to @ckousik 's [branch](https://github.com/libp2p/go-libp2p/pull/1655).  Once it's merged, update the reference in [examples/go-libp2p-server/go.mod](https://github.com/little-bear-labs/js-libp2p-webrtc/pull/60/files#diff-b47ec41c6e6188c0140f71b08e4bd01ee2bca264d4beab03bdf17d5bd7ccbeea).

**Comment by wemeetagain** [comment]
closing as stale
