### ISSUE TITLE
test: Investigate inconsistent webRTC Interop Tests 

### ISSUE THREAD

**Issue by maschad** [libp2p/js-libp2p#1846]
WebRTC tests seem flaky to me. I don't think this is a resource issue in CI. Running these tests locally (in compose and npm test) also sometimes fail for me.

Let's remove the webrtc tests for now, and add them back in when they're not flaky.

_Originally posted by @MarcoPolo in https://github.com/libp2p/js-libp2p/issues/1809#issuecomment-1599357723_

**Comment by maschad** [comment]
We should be able to re-enable these tests given the fixes merged in https://github.com/libp2p/js-libp2p/pull/2073

**Comment by achingbrain** [comment]
> at @waku_org we have tests being flaky in a similar way where the peer:identify is not being triggered in the CI 

This should be fixed by https://github.com/libp2p/js-libp2p/pull/2206

**Comment by maschad** [comment]
We can verify once https://github.com/libp2p/test-plans/pull/310 is merged to confirm we have consistent webRTC interoperability

**Comment by maschad** [comment]
Closed by https://github.com/libp2p/test-plans/pull/310
