### ISSUE TITLE
Compliance test cases should be commented

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p#1854]
Failing a compliance test often looks like:
```
AssertionError: expected [] to have a length of 1 but got +0
      + expected - actual

      -0
      +1
```

Not particularly helpful. Debugging involves navigating to the source.

Ideally, each `expect` would be annotated with language relating the expectation

eg:
```
expect(muxer.streams.length, 'muxer.streams should contain a stream blah blah blah').to.equal(1)
```

Or perhaps this issue could be rephrased more broadly to: "Review debugging experience for compliance tests"

**Comment by p-shahi** [comment]
Closing as this task is quite large and though it's labeled as good first issue, it's quite daunting for newcomers.
