### ISSUE TITLE
Remove Stream methods from `Connection` interface

### ISSUE THREAD

**Issue by maschad** [libp2p/js-libp2p#1855]
Following up from the discussion [here](https://github.com/libp2p/js-libp2p/pull/1612#issuecomment-1487181271) the muxers should be ultimately responsible for managing streams as opposed to the connections themselves

**Comment by tabcat** [comment]
I'm going to look a bit closer but seems like this requires moving the functionality of what is currently (add|remove)Stream and putting that on the muxer interface?

**Comment by maschad** [comment]
There wouldn't be any use for adding those methods to the stream muxer interface since we already have the [newStream and close methods](https://github.com/libp2p/js-libp2p/blob/master/packages/interface/src/stream-muxer/index.ts#L35-L40) so these methods just need to be removed from the connection interface.  

 @mmsaki  actually began work on this on https://github.com/libp2p/js-libp2p/pull/1829 but I am not sure what the status of that is now. Perhaps they can provide an update.
