### ISSUE TITLE
Improve Libp2p interface 

### ISSUE THREAD

**Issue by weboko** [libp2p/js-libp2p#1875]
#### Description:
Right now my team faces a problem with types that a coming from Libp2p in case when we want to refer to Libp2p Components. 

Because default interface to refer to libp2p is declared in [@libp2p/interface-libp2p](https://github.com/libp2p/js-libp2p/blob/daeb43d8821d2df1999871797a22fbdf502731f8/packages/interface/src/index.ts#L306) does not have components defined on it when at the same time libp2p [implementation](https://github.com/libp2p/js-libp2p/blob/daeb43d8821d2df1999871797a22fbdf502731f8/packages/libp2p/src/libp2p.ts#L54) has [components](https://github.com/libp2p/js-libp2p/blob/daeb43d8821d2df1999871797a22fbdf502731f8/packages/libp2p/src/components.ts#L19C2-L19C2) declared it created problematic situation for us and forces us to use type casting to keep the possibility to refer to Libp2p components in our TypeScript code.

I'd like to know if was it intentional that [Components](https://github.com/libp2p/js-libp2p/blob/daeb43d8821d2df1999871797a22fbdf502731f8/packages/libp2p/src/components.ts#L19C2-L19C2) are not exported from `libp2p` package? 

If so, what is the reasoning for it?
Otherwise is it possible to export the `Components` interface from the package?

**Comment by maschad** [comment]
This has been previously raised in https://github.com/libp2p/js-libp2p/issues/1567 but the rationale is that _Components_ are the internals of Libp2p and should be obscured from consumers. The [Libp2p node interface](https://github.com/libp2p/js-libp2p/blob/daeb43d8821d2df1999871797a22fbdf502731f8/packages/interface/src/index.ts#L306) seeks to be a simple API that exposes methods a consumer should call without having to know the internals of Libp2p's components, I am curious to see the use cases for utilizing Libp2p components directly in your code, could you please share some examples?
