### ISSUE TITLE
Export Metrics in WebRTCTransport

### ISSUE THREAD

**Issue by justin0mcateer** [libp2p/js-libp2p#1878]
- **Version**:
0.45.9

- **Platform**:
`Linux master 6.3.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 30 May 2023 13:44:01 +0000 x86_64 GNU/Linux`
`Brave Browser 114.1.52.117`

- **Subsystem**:
WebRTC Transport

#### Severity:
Low

#### Description:
When metrics exporting was implemented in the WebRTC module, it appears to have only be implemented in 'WebRTCDirectTransport' and not at all in 'WebRTCTransport'. Is there some reason for this or is it merely an oversight?

https://github.com/libp2p/js-libp2p-webrtc/issues/64

Is there any reason we couldn't just 'port' the implementation from WebRTCDirectTransport to WebRTCTransport?

#### Steps to reproduce the error:
- create an instance of libp2p with WebRTC() for the Transport
- observe that no metrics are produced

**Comment by maschad** [comment]
This is because our metrics library currently [does not support browser metrics](https://github.com/libp2p/js-libp2p-prometheus-metrics/issues/33). Other users have [collected browser metrics ](https://github.com/libp2p/js-libp2p/issues/1764#issue-1716617891) by forking [prom-js](https://github.com/weaveworks/promjs) so you could explore that option.

**Comment by justin0mcateer** [comment]
Yes, we have a Metrics implementation which works in the browser. 

Since the Metrics implementation is injectable/injected, do you see any reason we can't simply port the existing code from WebRTCDirectTransport to WebRTCTransport?

**Comment by maschad** [comment]
You are correct, if your metrics implementation extends the [metrics interface](https://www.npmjs.com/package/@libp2p/interface-metrics) library then it should be possible. Would you like to open a PR?

**Comment by justin0mcateer** [comment]
Indeed, we will.
