### ISSUE TITLE
Circuit isn't working by default

### ISSUE THREAD

**Issue by rmnoff** [libp2p/js-libp2p#188]
- **Version**: 0.20.0
- **Platform**: MacOS 10.12.6
- **Subsystem**: None.

#### Description: Default nodes have no Circuit enabled.
I am using libp2p and same scripts on two different notebooks connected to different networks and I am unable to find one peer by another. While running nodes under same network it works perfectly.
The error I face is here:
```
Error: Circuit not enabled!
    at nextTransport (/Users/macbook/Desktop/development/app/node_modules/libp2p-switch/src/dial.js:103:23)
    at attemptDial (/Users/macbook/Desktop/development/app/node_modules/libp2p-switch/src/dial.js:93:7)
    at Switch.dial (/Users/macbook/Desktop/development/app/node_modules/libp2p-switch/src/dial.js:32:9)
    at _getPeerInfo (/Users/macbook/Desktop/development/app/node_modules/libp2p/src/index.js:258:19)
    at Immediate.setImmediate [as _onImmediate] (/Users/macbook/Desktop/development/app/node_modules/libp2p/src/get-peer-info.js:46:24)
```

#### Steps to reproduce the error:

By running exchangeData() with peerId (QmHash) of another node I clearly see, that node.dial() is working well and there is no error with it, but dialProtocol is saying that Circuit is not enabled.

```JavaScript
const bootstrapers = [
  '/ip4/104.236.176.52/tcp/4001/ipfs/QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z',
  '/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ',
  '/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM',   '/ip4/162.243.248.213/tcp/4001/ipfs/QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm',
  '/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu',
  '/ip4/104.236.76.40/tcp/4001/ipfs/QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64',
  '/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd',
  '/ip4/178.62.61.185/tcp/4001/ipfs/QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3',
  '/ip4/104.236.151.122/tcp/4001/ipfs/QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx',
];

class DefaultNode extends libp2p {
  constructor(peerInfo) {
    const modules = {
      transport: [new TCP()],
      connection: {
        muxer: [SPDY, Mplex],
        crypto: [SECIO]
      },
      discovery: [
        new Railing(bootstrapers),
        new MulticastDNS(peerInfo, { interval: 1000 })
      ]
    };
    super(modules, peerInfo);
  }
}

let createNode = callback => {
  let node;

  waterfall(
    [
      cb => PeerInfo.create(cb),
      (peerInfo, cb) => {
        peerInfo.multiaddrs.add(
          `/p2p-circuit/ipfs/${peerInfo.id.toB58String()}`
        );
        peerInfo.multiaddrs.add('/ip4/0.0.0.0/tcp/0');
        node = new DefaultNode(peerInfo);
        node.start(cb);
      }
    ],
    err => callback(err, node)
  );
};

let exhcangeData = (peerId, node) => {
  PeerInfo.create(new PeerInfo(peerId), async (err, peer) => {
    series([
      cb =>
        node.dial(peer, () => {
          console.log('dialed, now have to transfer information');
          cb();
        }),
      cb =>
        node.dialProtocol(peer, '/exchange', (err, conn) => {
          if (err) {
            throw err;
          }
          pull(pull.values(['hello', ' ', 'lib', 'p', '2', 'p', '!']), conn);
          cb();
        })
    ]);
  });
};
```

**Comment by dryajov** [comment]
That's a misleading message, in reality it means that dialing failed including circuit. Here is a PR that addresses it - https://github.com/libp2p/js-libp2p-switch/pull/250.

Are you sure that the nodes in another network are reachable over the address that is being used? For example, can you dial a node in that network? 

If you want to enable circuit, the node needs to be passed this config options:

```js
    relay: {
      enabled: true,
      hop: {
        enabled: true,
        active: false
      }
    }
```

**Comment by rmnoff** [comment]
@dryajov thank you! Now I have a much better view on the error I receive. Btw, have u found out and work around? I just want to have a good data-transporting channel. I love p2p and I would love to use it rather than any other libraries. I will try to enable circuit the way you proposed and text back here if it won't work or something. I would love to ask you if there is any other more convenient way to contact you personally, so I maybe will have any helpful solutions on the issue. Btw, I used to contribute to IPFS, where same problem forced me to leave the idea I wanted to implement. At that time David Dias was trying to fix it, but nothing helped (js-ipfs v. 0.27 if I am not mistaking).

**Comment by dryajov** [comment]
@rmnoff could you please describe your use case in more detail? 

- you mentioned that the nodes you're trying to connect are in different networks, could you elaborate on that please? 
  - are these nodes able to see each other in any way? 
  - if so, are you able to dial one node over its public address from another node? 

If you want a more real time communication channel, I suggest you join our IRC channels on freenode - #ipfs and #ipfs-dev (the latter being more centered around implementation of the core components them self).

**Comment by dryajov** [comment]
Also, take a look at the https://github.com/ipfs/js-ipfs/blob/master/examples/circuit-relaying/README.md, for a more indepth explanation of circuit relay, make sure you explore the rest of the examples as well, both here in the libp2p repo and ipfs proper.

Cheers!

**Comment by dryajov** [comment]
should be fixed with - https://github.com/libp2p/js-libp2p-switch/pull/250
