### ISSUE TITLE
Should a node be able to dial itself?

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-libp2p#189]
- **Version**: \*
- **Platform**: \*
- **Subsystem**: transport, dialer

#### Steps to reproduce the error:

 1. Create a node and start it
 2. `node.dial(node.peerInfo, () => {}`

Currently a node is able to dial itself.
Problem:
 - What if there are 2 nodes with the same peer-id because someone messed something up... should it only allow dials from and to itself or from any node that has it's id
 - It might be useful for debugging but I don't see any real-world use case where this makes sense (maybe hide it behind a flag like `allowDialToSelf`)

**Comment by diasdavid** [comment]
It shouldn't. Let's catch that on libp2p-switch and return it as a error.
