### ISSUE TITLE
WebRTC Transport creating large number of DataChannels when used with Multiplexer

### ISSUE THREAD

**Issue by justin0mcateer** [libp2p/js-libp2p#1895]
- **Version**:
0.45.9

- **Platform**:

- **Subsystem**:
WebRTC Transport
Yamux / Mplex

#### Severity:
Medium

#### Description:
When connecting two browsers directly via a CircuitRelayV2 server, I am seeing stable signaling (a single WebRTC connection 'stays up'), but a large number (~60) of DataChannels are created, each only sending a very small number of bytes (<100 bytes in nearly all cases). As an additional bit of information, Yamux opens 60 DataChannels and Mplex seems to open 20, but they both continue adding new DataChannels every five minutes. I don't think this would create an real issue in the short-term, but for a long running application (like ours) it will almost certainly be problematic fairly quickly.

According to this article the number of DataChannels supported by the browser are much, much less than the theoretical maximum (as little as 128) for FireFox as of ~2 years ago. Assuming nothing has changed, this would exhaust the number of available DataChannels in several hours.
https://tensorworks.com.au/blog/webrtc-stream-limits-investigation/

~60 DataChannels, mostly created at once:
![image](https://github.com/libp2p/js-libp2p/assets/2607229/7ad1cf75-e309-40b2-b938-ec5db7aee02b)

<100 Bytes sent on each DataChannel:
![image](https://github.com/libp2p/js-libp2p/assets/2607229/ac5de6c2-6d84-430e-99ec-fcb9642c5bb0)

The number of DataChannels continues to grow, in my configuration a new DataChannel is opened approximately every five minutes. All the DataChannels appear to remain open (at least in excess of 15 minutes)

New DataChannels opened every five minutes (exactly):
![image](https://github.com/libp2p/js-libp2p/assets/2607229/1eeb8e52-d7c7-43e7-8c9a-1927fb012e49)

Old DataChannels stay open:
![image](https://github.com/libp2p/js-libp2p/assets/2607229/025624ea-cd13-4264-b2c0-272b4f3e90f3)

#### Steps to reproduce the error:
- Establish a Browser to Browser WebRTC connection with the WebRTC Transport
- Open the 'brave://webrtc-internals' (or 'chrome://webrtc-internals')
- Observe the large and ever growing number of DataChannels

**Comment by justin0mcateer** [comment]
Just as a follow up, left to run overnight, this does hit the maximum number of DataChannels Chrome will allow (512).

**Comment by Marcel-G** [comment]
@justin0mcateer I am reasonable confident that js-libp2p webrtc-transport does not actually close data channels when it's done with them. That seems like a bug and will eventually result in running out of data channels. Chrome throws the following error when it can't create any more:

```
Uncaught (in promise) DOMException: Failed to execute 'createDataChannel' on 'RTCPeerConnection': RTCDataChannel creation failed
```

Could you please try with these changes to `js-libp2p` https://github.com/Marcel-G/js-libp2p/commit/d258b09dda74046c3244050e0434e1da894f312d?

**Comment by justin0mcateer** [comment]
Sorry for the late feedback, I see this has been merged.

I did try this patch and it improved things. However, we ended up also adding the same change on the 'onEnd' handler of incoming connections. I think it is needed it cases where the connection is severed uncleanly.
