### ISSUE TITLE
feat: auto-dialer max queue should allow specifying max queue per transport

### ISSUE THREAD

**Issue by SgtPooki** [libp2p/js-libp2p#1897]
https://github.com/libp2p/js-libp2p/blob/7debe0312f6df68e27dc26410a745c98477abe59/packages/libp2p/src/connection-manager/auto-dial.ts#L122C32-L122C54

WebTransport currently only supports 64 instances: https://github.com/libp2p/js-libp2p/issues/1896

Others may have their own limits (or none) and users should be able to limit `autoDialMaxQueueLength` by transport.

**Comment by SgtPooki** [comment]
related to https://github.com/libp2p/js-libp2p/issues/744#issuecomment-1650555616

**Comment by achingbrain** [comment]
Closing as the problem this proposal attempts to solve actually seems to be a bug in Chrome around WebTransport sessions never leaving the pending state.

This feature may be worth investigating in the future if a requirement surfaces but right now it's not something we need.
