### ISSUE TITLE
Swallowed Error in CircuitRelayV2 if reservations.defaultDataLimit is set to number

### ISSUE THREAD

**Issue by justin0mcateer** [libp2p/js-libp2p#1903]
- **Version**:
0.45.9

- **Platform**:
`Linux master 6.3.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 30 May 2023 13:44:01 +0000 x86_64 GNU/Linux`
`Brave Browser 114.1.52.117`

- **Subsystem**:
CircuitRelayV2

#### Severity:
Low

#### Description:
When configuring 'reservations' on the CircuitRelayServer, there is a very easy landmine to hit. Setting the 'defaultDataLimit' to any number will cause all relay connections to start failing. This is caused because the configuration value is passed directly through to 'countStreamBytes' with no validation.
https://github.com/libp2p/js-libp2p/blob/master/packages/libp2p/src/circuit-relay/utils.ts#L14

While the operation will throw a TypeError due to the mixed types, it will not be seen because of the way countStreamBytes used in a pipeline submitted to queueMicroTask.

#### Steps to reproduce the error:
- create a CircuitRelayServer service
- configure 'reservations.defaultDataLimit' to any number (eg. 131072)
- observe CircuitRelay connections will be setup but fail to upgrade

**Comment by maschad** [comment]
Related https://github.com/libp2p/js-libp2p/pull/1778
