### ISSUE TITLE
"High Severity: Module Not Found Error for 'os' in '@achingbrain/nat-port-mapper' After Upgrading js-libp2p and js-waku"

### ISSUE THREAD

**Issue by danisharora099** [libp2p/js-libp2p#1904]
- **Version**:
0.45.9
- **Platform**:
Darwin Danish-2.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Jun 30 17:50:12 PDT 2023; root:xnu-10002.0.168.505.3~1/RELEASE_ARM64_T6000 arm64

- **Subsystem**:
```
"@achingbrain/nat-port-mapper": "^1.0.9",
```

#### Severity:
High

#### Description:
Upgraded js-libp2p within js-waku (https://github.com/waku-org/js-waku/) and upgraded js-waku within one of our browser examples and then attempted to build.
The build resulted in the error:
```
Module not found: Error: Can't resolve 'os' in '/Users/danisharora099/Developer/status/examples/examples/web-chat/node_modules/@achingbrain/nat-port-mapper/dist/src'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
        - install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "os": false }
```

#### Steps to reproduce the error:
- checkout to this branch: https://github.com/waku-org/js-waku-examples/pull/252
- `npm i && npm run build`

cc @achingbrain

**Comment by achingbrain** [comment]
Could you share a link to where you are configuring libp2p please?

**Comment by achingbrain** [comment]
Are there extra services being passed in [here](https://github.com/waku-org/js-waku/blob/30fcacea84d9aefbe71e7f4b48506a088f2e1bf8/packages/sdk/src/create.ts#L180)?

I ask because webpack is trying to load `@achingbrain/nat-port-mapper` - this is a node.js only module.  The only place it's used is in the uPnPNat service which won't work in browsers.

**Comment by weboko** [comment]
@achingbrain, maybe as a precaution, this would fix any potential problems? 

in `libp2p/package.json` 
```json
"browser": {
    "./dist/src/config/connection-gater.js": "./dist/src/config/connection-gater.browser.js",
    "nat-api": false,
    "@achingbrain/nat-port-mapper": false
  }
```

**Comment by achingbrain** [comment]
I've managed to replicate this in the `web-chat` example from the `js-waku-examples`, but it looks like there are multiple versions of libp2p in the dependency tree:

```console
 % npm ls libp2p
web-chat@0.1.0 /Users/alex/Documents/Workspaces/waku-org/js-waku-examples/examples/web-chat
├─┬ @waku/peer-exchange@0.0.14
│ └─┬ @waku/core@0.0.21
│   └── libp2p@0.45.9
├─┬ @waku/react@0.0.2
│ ├─┬ @waku/relay@0.0.3
│ │ └─┬ @waku/core@0.0.20
│ │   └── libp2p@0.42.2 deduped
│ └─┬ @waku/sdk@0.0.16
│   ├─┬ @waku/core@0.0.20
│   │ └── libp2p@0.42.2 deduped
│   └── libp2p@0.42.2
└─┬ @waku/sdk@0.0.17
  ├─┬ @waku/core@0.0.21
  │ └── libp2p@0.45.9 deduped
  └── libp2p@0.45.9
```

The problem goes away if I manually remove the duplicates and ensure that everything is running `libp2p@0.45.x`
