### ISSUE TITLE
bug(transport-webrtc) Max Message Size differs from Spec

### ISSUE THREAD

**Issue by DougAnderson444** [libp2p/js-libp2p#1908]
https://github.com/libp2p/js-libp2p/blob/a41d25d49696febd7fd903bbdcc95ebaeb5d4b35/packages/transport-webrtc/src/private-to-public/sdp.ts#L136

Hi, I am reviewing the spec as I implement it in https://github.com/libp2p/rust-libp2p/pull/4248 when I noticed this is not in accordance with the spec

```gmf
A MUST set the a=max-message-size:16384 SDP attribute.
```

ref: https://github.com/libp2p/specs/blob/master/webrtc/webrtc-direct.md#browser-to-public-server

I'm not sure what the impact is as I've used js-WebRTC and it seems to work fine, but I wanted to raise the issue nontheless

**Comment by maschad** [comment]
Thanks for spotting this @DougAnderson444 to my understanding it's an oversight, it was even [mentioned on a previous issue where we discussed max message size](https://github.com/libp2p/js-libp2p-webrtc/issues/144#issuecomment-1541306042)
