### ISSUE TITLE
refactor: move services to separate packages

### ISSUE THREAD

**Issue by maschad** [libp2p/js-libp2p#1913]
There are a few internal services such as [identify](https://github.com/libp2p/js-libp2p/blob/master/packages/libp2p/src/identify/README.md) , [Address Manager](https://github.com/libp2p/js-libp2p/blob/master/packages/libp2p/src/address-manager/README.md), [Pnet](https://github.com/libp2p/js-libp2p/blob/master/packages/libp2p/src/pnet/README.md) and others in the [libp2p package](https://github.com/libp2p/js-libp2p/tree/master/packages/libp2p/src) which have their own `README` that contains descriptions about how to configure the services. Because they are buried a few subdirectories down in the libp2p package they have low discoverability and so that information should be extracted to the [top level docs](https://github.com/libp2p/js-libp2p/blob/master/doc/CONFIGURATION.md) as well as their usage should be generated by our [`docs` tooling](https://github.com/ipfs/aegir#clihttps://github.com/ipfs/aegir#cli). This also unnecessarily bloates the libp2p npm package.

Related: https://github.com/libp2p/js-libp2p/pull/1910#pullrequestreview-1555165302

Packages:

```[tasklist]
### Tasks
- [ ] AutoNAT - #2107
- [ ] CircuitRelayServer #2222
- [ ] DCUtR #2220
- [ ] Identify #2219
- [ ] Fetch #2223
- [ ] Insecure / plaintext #2221
- [ ] Ping #2218 
- [ ] UnPnP #2217
- [ ] Pnet - https://github.com/libp2p/js-libp2p/pull/2165
```

**Comment by achingbrain** [comment]
This has been completed in the v1.0.0 release branch.
