### ISSUE TITLE
feat: Expose Metrics for Websockets

### ISSUE THREAD

**Issue by maschad** [libp2p/js-libp2p#1915]
## Done Criteria

Export metrics leveraging the work done in https://github.com/libp2p/js-libp2p/issues/1458

## Motivation

Better observability for performance and benchmarking. See: https://github.com/libp2p/js-libp2p/issues/1458#issuecomment-1323833476

Originally https://github.com/libp2p/js-libp2p-websockets/issues/197

**Comment by SgtPooki** [comment]
@achingbrain @maschad anyone working on this one? we will likely want to enable this so we can get visibility into websocket performance for https://github.com/libp2p/js-libp2p-amino-dht-bootstrapper

**Comment by maschad** [comment]
Not to my knowledge @SgtPooki , feel free to take it on!
