### ISSUE TITLE
refactor: Remove unnecessary async methods in `crypto` package

### ISSUE THREAD

**Issue by maschad** [libp2p/js-libp2p#1949]
I think we now have a load of async functions that don't do any async work - we should remove the async keyword from them to prevent promises being created unnecessarily but that can be done in a follow-up.

_Originally posted by @achingbrain in https://github.com/libp2p/js-libp2p/pull/1939#pullrequestreview-1567754174_

**Comment by tabcat** [comment]
Seems like any async functions with `// eslint-disable-line require-await` are candidates to be changed?

**Comment by maschad** [comment]
That's a good place to start but not all async functions with that comment are necessarily sync such as the [aes-gcm encrypt function](https://github.com/libp2p/js-libp2p/blob/master/packages/crypto/src/ciphers/aes-gcm.browser.ts#L35) which incorrectly has this comment.
