### ISSUE TITLE
Trying to Dial Kubo Node with Web Transport

### ISSUE THREAD

**Issue by TheGreatAlgo** [libp2p/js-libp2p#1951]
Recently upgraded a node to support web transport near end of april and I cannot dial via web transport. Was able to connect at first but seemingly unable to connect or only very limited successes at attempts now. Was attempting to dial `/ip4/45.55.32.80/udp/4001/quic-v1/webtransport/certhash/uEiAM_1-R7yfSAtnm9g_fzzcIccsT1RzKPfXPr5lKfqmVVQ/certhash/uEiAcLZS4mabYQl9V1K0QjWsToU21DtsWarGTjZQzecHFmg/p2p/12D3KooWG7itEPAHut3xsVo7CwyD8sKeQXKgQizotNhPsToCssXQ`

and get this error 
![image](https://github.com/libp2p/js-libp2p-webtransport/assets/37487508/35d83450-4fd6-4ac8-947d-ecd61421b56a)

**Comment by BigLep** [comment]
Transferring this issue from https://github.com/libp2p/js-libp2p-webtransport/issues/82 was requested by dClimate David on behalf of @TheGreatAlgo

**Comment by TheGreatAlgo** [comment]
After upgrading the node we still are having issues with certificate unknown. I am running the latest Helia and Libp2p versions as of yesterday but I suspect this is a kubo thing. How can we ensure the certificates are being rotated? does this mean `/ip4/45.55.32.80/udp/4001/quic-v1/webtransport/certhash/uEiAM_1-R7yfSAtnm9g_fzzcIc...` should change every two weeks? Do we have to just manually pay attention when they update and update on the frontend every single time it updates?

Also I tried `https://github.com/libp2p/js-libp2p/tree/master/examples/libp2p-in-the-browser/webtransport/fetch-file-from-kubo` to at least see if I could get the example working but connections were timing out with the example address.

**Comment by p-shahi** [comment]
This was discussed in today's [js-libp2p maintainers call](https://lu.ma/js-libp2p).

>  Do we have to just manually pay attention when they update and update on the frontend every single time it updates?

Right now the answer is sort of yes. If you've hardcoded the whole multiaddr into your application, then you'll have to pay attention and update manually since the addr will eventually be invalid.
Ideally, instead of hardcoding the multiaddr, it's better to encode the peerid of the nodes to dial and do a peer lookup via the dht.
However, browser dht queries are challenging atm because the whole query will stop when we encounter nodes that don’t have WebTransport addresses.
So the solution of encoding peerid & doing a lookup is limited until more of network supports WebTransport.
What percentage of the network supports WebTransport is something we're looking to get insight into. The ProbeLab team does [network measurements](https://github.com/plprobelab/network-measurements/blob/master/reports/2023/calendar-week-32/ipfs/README.md) but we don't have concrete numbers on WebTransport atm.

**Comment by aschmahmann** [comment]
> Do we have to just manually pay attention when they update and update on the frontend every single time it updates?

Maybe a more flexible answer then the one above is that browser webtransport doesn't want the certificate hashes to be fixed and yet you want fixed addresses so something's got to give. Some examples:
- Use your application as the mutability point and update it every two weeks
- Use the peerID -> multiaddr mapping as the mutability point
  - Find some system to do peer routing for you in a way the browser can access (DHT + Delegated routing, IPNI, etc.)
- Use a non-peerID -> multiaddr mapping as the mutability point
  - For example, DNSLink + DoH resolution in the browser

> However, browser dht queries are challenging atm because the whole query will stop when we encounter nodes that don’t have WebTransport addresses.

Yeah, but then just ask someone else to do it for you 😄. Sure, it'd be nice to do it yourself but for now I don't see why not. There's IPIP https://github.com/ipfs/specs/pull/417 for adding peer routing to the /routing/v1 API that should be better supported going forward, but if you needed something sooner you should be able to use https://github.com/libp2p/js-libp2p-delegated-peer-routing which has been around for a while.

**Comment by TheGreatAlgo** [comment]
@p-shahi I tried upgrading to the latest but now I get this error. Seemingly finding the peer no longer works
![Screenshot 2023-08-16 at 5 44 05 PM](https://github.com/libp2p/js-libp2p/assets/37487508/79d09e47-a6be-47fc-ae54-0687c4d21a87)

**Comment by Faolain** [comment]
If it helps this is the complete config for that node (we were in the middle of attempting to configure it to add publishing to IPNI)

```
{
  "API": {
    "HTTPHeaders": {}
  },
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Announce": [],
    "AppendAnnounce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip4/0.0.0.0/udp/4001/quic-v1",
      "/ip4/0.0.0.0/udp/4001/quic-v1/webtransport",
      "/ip6/::/udp/4001/quic",
      "/ip6/::/udp/4001/quic-v1",
      "/ip6/::/udp/4001/quic-v1/webtransport"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ"
  ],
  "DNS": {
    "Resolvers": {}
  },
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true
    }
  },
  "Experimental": {
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "12D3KooWFqzYkjofVzvo7MdYy4h3cZwixJC1f6NFWGYPELU7yBNy"
  },
  "Internal": {},
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {
    "DownloadSources": [],
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {
    "RemoteServices": {}
  },
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {},
  "Routing": {
    "Methods": {
      "find-peers": {
        "RouterName": "WanDHT"
      },
      "find-providers": {
        "RouterName": "ParallelHelper"
      },
      "get-ipns": {
        "RouterName": "WanDHT"
      },
      "provide": {
        "RouterName": "ParallelHelper"
      },
      "put-ipns": {
        "RouterName": "WanDHT"
      }
    },
    "Routers": {
      "IndexProvider": {
        "Parameters": {
          "Endpoint": "http://127.0.0.1:50617",
          "MaxProvideBatchSize": 10000,
          "MaxProvideConcurrency": 1
        },
        "Type": "http"
      },
      "ParallelHelper": {
        "Parameters": {
          "Routers": [
            {
              "IgnoreErrors": true,
              "RouterName": "IndexProvider",
              "Timeout": "30m"
            },
            {
              "IgnoreErrors": true,
              "RouterName": "WanDHT",
              "Timeout": "30m"
            }
          ]
        },
        "Type": "parallel"
      },
      "WanDHT": {
        "Parameters": {
          "AcceleratedDHTClient": false,
          "Mode": "auto",
          "PublicIPNetwork": true
        },
        "Type": "dht"
      }
    },
    "Type": "custom"
  },
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {},
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "RelayClient": {},
    "RelayService": {},
    "ResourceMgr": {},
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

**Comment by maschad** [comment]
Thanks for sharing the config @Faolain is there a reason why it doesn't contain the peer routing configuration?

> @p-shahi I tried upgrading to the latest but now I get this error. Seemingly finding the peer no longer works

@TheGreatAlgo what version of js-libp2p were you using prior to the upgrade to `0.46.5` ? Also if possible would you be able to [enable the debug logs](https://github.com/libp2p/js-libp2p/blob/master/doc/GETTING_STARTED.md#debugging) as well prior to that error? You can do this by setting the debug flag to `libp2p:delegated-peer-routing`

**Comment by Faolain** [comment]
> Thanks for sharing the config @Faolain is there a reason why it doesn't contain the peer routing configuration?

ofc! and hm, not sure what you mean by this? What should it be instead? (for reference I believe this is the default configuration and I just cross checked with a local kubo config and it seems to be the same)

**Comment by maschad** [comment]
> @p-shahi I tried upgrading to the latest but now I get this error. Seemingly finding the peer no longer works
Screenshot 2023-08-16 at 5 44 05 PM
swarm connecting the peer does work

I may have gotten the error at one point with the session limit

It seems this is an issue related to our kubo rpc client, I've outlined more details in https://github.com/libp2p/js-libp2p/issues/1985

**Comment by maschad** [comment]
> @p-shahi I tried upgrading to the latest but now I get this error. Seemingly finding the peer no longer works ![Screenshot 2023-08-16 at 5 44 05 PM](https://user-images.githubusercontent.com/37487508/261062276-79d09e47-a6be-47fc-ae54-0687c4d21a87.png) swarm connecting the peer does work
> 
> I may have gotten the error at one point with the session limit

It seems this is an issue related to our kubo rpc client, I've outlined more details in https://github.com/libp2p/js-libp2p/issues/1985

**Comment by maschad** [comment]
The issue has now been resolved @Faolain 

>> Current config
```javascript
        // services: {
        //     // the identify service is used by the DHT and the circuit relay transport
        //     // to find peers that support the relevant protocols
        //     identify: identifyService(),
        //     // the DHT is used to find circuit relay servers we can reserve a slot on
        //     dht: kadDHT({
        //         clientMode: true,
        //         validators: {
        //             ipns: ipnsValidator,
        //         },
        //         selectors: {
        //             ipns: ipnsSelector,
        //         },
        //     }),
        // },
        peerRouters: [delegatedPeerRouting(client)],
    });
```
After re-examining @TheGreatAlgo I notice that your `kadDHT`  clientmode is disabled, could you try re-enabling it and seeing if you are no able to find to retrieve the peer info?

**Comment by TheGreatAlgo** [comment]
will look at this soon, just trying to resolve some other issues that are popping up

**Comment by TheGreatAlgo** [comment]
haven't forgotten about this, sorry its taking so long to address
