### ISSUE TITLE
Circuit relay - reconnect to peers we have reservations on

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p#1955]
When we have a reservation on a relay, and we lose connectivity to that relay, we should make an effort to reconnect to the same relay before searching for other relays to make a reservation on.

This is because making a new reservation will change our multiaddrs which impacts things like DHT provider records which will now be out of date just because our WiFi was a bit flaky for a time or we closed our laptop lid.

**Comment by maschad** [comment]
I think this relates to https://github.com/libp2p/js-libp2p/issues/1953 - i.e. as a general rule, if we've successfully dialled the peer recently, but we are no longer connected to them, we should prioritize dialling those peers and conversely if we have dialled a peer but failed recently, then those should be de-prioritized.

**Comment by maschad** [comment]
Closed by https://github.com/libp2p/js-libp2p/pull/2031
