### ISSUE TITLE
feat(@libp2p): Add `protocol-perf` to release workflow.

### ISSUE THREAD

**Issue by maschad** [libp2p/js-libp2p#1964]
Once the [perf workflow is integrated in test-plans](https://github.com/libp2p/test-plans/pull/244) we should run the benchmarks on our [release workflow](https://github.com/libp2p/js-libp2p/blob/master/.github/workflows/main.yml#L210)

Can be added once https://github.com/libp2p/test-plans/pull/280 is merged

**Comment by achingbrain** [comment]
Closing as running a full performance test in CI will not give us much confidence without dedicated testing infrastructure.

A lighter touch such as proposed in #2118 will likely be more useful.
