### ISSUE TITLE
CodeError dialing node using tcp 

### ISSUE THREAD

**Issue by threshold862543** [libp2p/js-libp2p#1980]
**Version**:
0.45.9

**Platform**:
5.15.0-33-generic #.34~20.04.1-Ubuntu (dialer)
5.15.0-78-generic #.85-Ubuntu (dialee)

**Subsystem**:
dialer

#### Severity:
  High - The main functionality of the application does not work, API breakage, repo format breakage, etc.

#### Description:
Node A is dialing node B over the internet (not local) via tcp, using:
`dial(multiaddr(<address>))`
`address` is a string of the format:
`'/dns4/<domain>/tcp/<port>/p2p/<peerid>'`
the error output:

```
CodeError: CodeError: missing newline
    at DefaultUpgrader._encryptOutbound (file:///.../node_modules/libp2p/dist/src/upgrader.js:478:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DefaultUpgrader.upgradeOutbound (file:///.../node_modules/libp2p/dist/src/upgrader.js:205:21)
    at async TCP.dial (file:///.../node_modules/@libp2p/tcp/dist/src/index.js:50:22)
    at async DefaultTransportManager.dial (file://.../node_modules/libp2p/dist/src/transport-manager.js:82:20)
    at async queue.add (file:///.../node_modules/libp2p/dist/src/connection-manager/dial-queue.js:333:42)
    at async file:///.../node_modules/p-queue/dist/index.js:118:36 {
  code: 'ERR_ENCRYPTION_FAILED',
  props: {}

```

#### Steps to reproduce the error:
Attempt to dial a node over the internet via tcp.
This error doesn't occur when dialing nodes at 127.0.0.1 on the same machine via tcp.

**Comment by achingbrain** [comment]
Are both nodes js-libp2p or is the remote running a different implementation?

**Comment by threshold862543** [comment]
Both nodes are running the same version of js-libp2p.

**Comment by p-shahi** [comment]
v0.45.x is known to work and the interoperability tests for tcp are not failing in the interop test suite: https://github.com/libp2p/test-plans/actions/runs/5900727248/attempts/2#summary-16017106749

Can you share the code snippet?

**Comment by threshold862543** [comment]
THe libp2p node is initialized as follows:
```

libp2p: {
	transports: [tcp(), webSockets({filter: all})],
	streamMuxers: [mplex()],
	connectionEncryption: [noise()],
	addresses: {
		listen: [
			'/ip4/127.0.0.1/tcp/9001',
			'/ip4/127.0.0.1/tcp/9002/ws'
		] 
	}
} 
```
Ports 9998 and 9999 are forwarded to 9001 and 9002 respectively via nginx proxy on the node being dialed as follows:
```
server {
        server_name mydomain.com;
        listen [::]:9998 ssl ipv6only=on;
        listen 9998 ssl;
        ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/mydomain.com/chain.pem;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        location / {
                proxy_pass http://127.0.0.1:9001;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }


}

server {
        server_name mydomain.com;
        listen [::]:9999 ssl ipv6only=on;
        listen 9999 ssl;
        ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/mydomain.com/chain.pem;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        location / {
                proxy_pass http://127.0.0.1:9002;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }


}
```

Dialing the tcp node via 
`'/dns4/mydomain.com/tcp/9998/p2p/<peerid>'`
errors while 
`'/dns4/mydomain.com/tcp/9999/wss/p2p/<peerid>'`
successfully connects

**Comment by maschad** [comment]
There seems to be an issue during the encryption handshake [during multi-stream select](https://github.com/libp2p/js-libp2p/blob/ac8a1cac1dc7649e2d948c88277eda4cec75b8d6/packages/multistream-select/src/multistream.ts#L87-L90) which suggest an invalid `ssl_cert` in this case but given you are using https://github.com/dao-xyz/js-libp2p-noise for encryption along with https://github.com/dao-xyz/peerbit 's fork of js-libp2p I would suggest you open an issue against either one of those repos to get further clarity as they may have made modifications to that are not within our codebase.

**Comment by achingbrain** [comment]
It is supposed to work, yes.

Can you please open a new issue with a way to reproduce the error you are seeing?  Some runnable code or a link to a repository.

**Comment by matisalimbene** [comment]
@achingbrain thanks! and donde: https://github.com/libp2p/js-libp2p/issues/2444
