### ISSUE TITLE
bug: KuboClient not returning multiaddrs in `FIND_PEER` event

### ISSUE THREAD

**Issue by p-shahi** [libp2p/js-libp2p#1985]
@p-shahi I tried upgrading to the latest but now I get this error. Seemingly finding the peer no longer works
![Screenshot 2023-08-16 at 5 44 05 PM](https://github.com/libp2p/js-libp2p/assets/37487508/79d09e47-a6be-47fc-ae54-0687c4d21a87)
swarm connecting the peer does work

_Originally posted by @TheGreatAlgo in https://github.com/libp2p/js-libp2p/issues/1951#issuecomment-1680875313_

**UPDATE** 

[the JS RPC Kubo client](https://github.com/ipfs/js-kubo-rpc-client) is currently is returning a successful `FIND_PEER` event despite not having any diall-able addresses, which leads the [delegated-peer-routing findPeer method](https://github.com/libp2p/js-libp2p-delegated-peer-routing/blob/414097861f327db60043e509f3c8faaeea5fb5bb/src/index.ts#L189) to throw a `ERR_NOT_FOUND`

Blocked by https://github.com/ipfs/js-kubo-rpc-client/issues/176

**Comment by p-shahi** [comment]
@maschad mind investigating this?

**Comment by AustinFoss** [comment]
I'm not sure this is a problem anymore. I remember having this same thing a few weeks (maybe a little over a month ago and thought it was something about the kadDHT's client mode not working properly. I now can successfully call `findPeer() ` from a browser node with:

```
      dht: kadDHT({
          clientMode: true
      })
```

libp2p version 0.46.6

**Comment by maschad** [comment]
Thanks for that feedback @AustinFoss but the description may have been a bit misleading, this issue actually is within the context of using [delegated-peer-routing](https://github.com/libp2p/js-libp2p-delegated-peer-routing) which relies on [the JS RPC Kubo client](https://github.com/ipfs/js-kubo-rpc-client) to find peer's on a node's behalf.

For more details you can see https://github.com/ipfs/js-kubo-rpc-client/issues/176

**Comment by SgtPooki** [comment]
related to https://github.com/ipfs/kubo/issues/10117

**Comment by p-shahi** [comment]
Are we reliant on the new Kubo RC to resolve this issue?

**Comment by maschad** [comment]
> You can be defensive in js-kubo-rpc-client or js-libp2p-delegated-peer-routing to turn a no address response into an error.

So that's currently the case in [delegated peer routing](https://github.com/libp2p/js-libp2p-delegated-peer-routing/blob/414097861f327db60043e509f3c8faaeea5fb5bb/src/index.ts#L189) which js-libp2p was propagating here as the `NOT_FOUND` error.

> I suspect the user that filed this bug wants kubo to return their peer's address and let them dial it in js-libp2p though, and if that's not happening then something else is going wrong (e.g. the target node isn't a DHT client, etc.).

Yup you are spot on, it was the DHT client being disabled, thanks @aschmahmann

**Comment by p-shahi** [comment]
@maschad I saw you closed this issue - I know you had a local setup to reproduce the original issue - were you able to apply @AustinFoss 's suggestion and get it working?

**Comment by maschad** [comment]
> @maschad I saw you closed this issue - I know you had a local setup to reproduce the original issue - were you able to apply @AustinFoss 's suggestion and get it working?

That's correct, once clientMode was enabled I was able to retrieve the `peerInfo` via the `findPeer` method,  you can see the example [here](https://github.com/maschad/helia-delegated-routing-example/blob/main/index.js#L77-L86)

**Comment by p-shahi** [comment]
Cool

Thanks for the explanation as well @aschmahmann 🙏
