### ISSUE TITLE
Perf Service Interface

### ISSUE THREAD

**Issue by justin0mcateer** [libp2p/js-libp2p#2000]
- **Version**:
0.46.6

- **Platform**:
`Linux master 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 x86_64 GNU/Linux`
`Google Chrome 116.0.5845.110`

- **Subsystem**:
Perf

#### Severity:
Low

#### Description:
The Perf interface is unnecessarily difficult to use for a variety of reasons:
1) BigInt input for Bytes. Why? Who is going to send more than 9 PetaBytes of data during a Perf test?
   I understand the reasoning for sending a fixed width value over the network; however, this conversion should be done by the library.
2) User provided 'start' time. Why? The library starts sending the bytes _after_ it is called, why does the client need to specify the start time?
3) 'measurePerformance' returns time, instead of Bits per Second. Why would the client care about this? The user can time the function call themselves if so desired. Instead the user has to do the calculation. It should be noted that because timing captures both the sending and receiving, the correct math may not be immediately obvious.
4) Asymmetric bandwidth on client sites. Typically, in home or SMB internet services, the bandwidth is highly (often 10:1) asymmetric between download and upload bandwidths. The transfer time should be captured separately for upload and download and independent measurements returned for upload/send and download/receive.
5) Documentation/example is unhelpful. The documentation claims that 'this will not work in browsers.' I see no reason that this should be the case. The service merely sends bytes over an arbitrary user provided connection. The _tests_ clearly won't work in the browser, as they are implemented using the TCP transport, but that doesn't apply to the service overall. The example usage doesn't provide any example of how to calculate the throughput, which (as I mentioned above) is likely non-obvious to many users.
6) The 'measurePerformance' function accepts 'AbortOptions', but does not utilize it or implement any other form of timeout.
7) Also, the package incorrectly lists a runtime dependency on 'tcp'.

#### Steps to reproduce the error:
Attempt to consume the 'measurePerformance' interface.

**Comment by achingbrain** [comment]
All valid points, hopefully addresses in [@libp2p/perf@2.x.x](https://github.com/libp2p/js-libp2p/releases/tag/perf-v2.0.0) - please can you try this version out?

**Comment by justin0mcateer** [comment]
We will update soon.
