### ISSUE TITLE
discrepancies in webrtc mesage lengths

### ISSUE THREAD

**Issue by DougAnderson444** [libp2p/js-libp2p#2003]
Hello,

I am implementing WebRTC in https://github.com/libp2p/rust-libp2p/pull/4248 and noticed a discrepancy between the Rust impl and the JS Impl, specifically when it comes to `PROTO_OVERHEAD` length

In Rust we have these values:

```rust
// https://github.com/libp2p/rust-libp2p/blob/96213b37c6d7b8ea998d652d245f51b920bb4852/transports/webrtc/src/tokio/substream.rs#L50-L56

const MAX_MSG_LEN: usize = 16384; // 16kiB
/// Length of varint, in bytes.
const VARINT_LEN: usize = 2;
/// Overhead of the protobuf encoding, in bytes.
const PROTO_OVERHEAD: usize = 5;
/// Maximum length of data, in bytes.
const MAX_DATA_LEN: usize = MAX_MSG_LEN - VARINT_LEN - PROTO_OVERHEAD;
```

With the rationale [here in the spec](https://github.com/libp2p/specs/blob/master/webrtc/README.md#faq).

Whereas the javascript is:

https://github.com/libp2p/js-libp2p/blob/9a69e6f76018d2df5c6e51de930557d4b60b2fca/packages/transport-webrtc/src/stream.ts#L43

https://github.com/libp2p/js-libp2p/blob/9a69e6f76018d2df5c6e51de930557d4b60b2fca/packages/transport-webrtc/src/stream.ts#L280

I am looking for the spec so that I can resolve this discrepancy, can you please send me what was used for `js-libp2p`?  Am I missing something as to why there is a difference between rust and js implementations?

**Comment by maschad** [comment]
JS uses the same spec. The discrepancy is likely an oversight, would you like to open a PR to fix this?
