### ISSUE TITLE
Pubsub messages not delivered in libp2p@0.46.7

### ISSUE THREAD

**Issue by sneaker1** [libp2p/js-libp2p#2004]
- **Version**:
"libp2p": "^0.46.7",
"@libp2p/floodsub": "^8.0.6",
"@chainsafe/libp2p-gossipsub": "^10.1.0",

- **Platform**:
Linux

- **Subsystem**:
Pubsub

#### Severity:
  High - The main functionality of the application does not work, API breakage, repo format breakage, etc.

#### Description:
Since libp2p version 0.46.7 i am having problems with pubsub messages not being delivered in my application.
I normally use gossipsub, but i also have the problem with floodsub.
I have tested it on a setup with only 2 nodes involved. Both are on different publicly dialable servers on the internet.

<br/>
<br/>

With **gossipsub** i get the following debug error on the publisher side when sending a message:
```
  libp2p:gossipsub:error Error: The operation was aborted
  libp2p:gossipsub:error     at nextAbortHandler (file:///home/celo/coding/libp2pProj/server/node_modules/abortable-iterator/dist/src/index.js:71:32)
  libp2p:gossipsub:error     at AbortSignal.abortHandler (file:///home/celo/coding/libp2pProj/server/node_modules/abortable-iterator/dist/src/index.js:58:17)
  libp2p:gossipsub:error     at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
  libp2p:gossipsub:error     at AbortSignal.dispatchEvent (node:internal/event_target:678:26)
  libp2p:gossipsub:error     at abortSignal (node:internal/abort_controller:292:10)
  libp2p:gossipsub:error     at Timeout._onTimeout (node:internal/abort_controller:112:7)
  libp2p:gossipsub:error     at listOnTimeout (node:internal/timers:559:17)
  libp2p:gossipsub:error     at processTimers (node:internal/timers:502:7) +0ms
  libp2p:gossipsub connection ended QmSjtK2Xp9FuLXwn3KYdv7pUcjaTr6QQkMChUmDySkasvA +986ms
  libp2p:gossipsub delete peer QmSjtK2Xp9FuLXwn3KYdv7pUcjaTr6QQkMChUmDySkasvA +0ms
```

On the other side nothing is received.

<br/>
<br/>

With **floodsub**, after bootup of the nodes one message gets send and received, but no further messages.
I have attached the debug output from the sender side and the receiver side.
You can see the first message on topic newOffer successfully being delivered. The following messages are sent but not received on the other side.

Regards Sneaker
[Floodsub_Receiver.txt](https://github.com/libp2p/js-libp2p/files/12479587/Floodsub_Receiver.txt)
[Floodsub_Sender.txt](https://github.com/libp2p/js-libp2p/files/12479588/Floodsub_Sender.txt)

**Comment by sneaker1** [comment]
I have done further investigation and found out that commit #1988 caused the issue.
After reversing the changes from this commit, my application delivered the pubsub messages as expected.

**Comment by marcus-pousette** [comment]
#2020  I have the same issue 0.46.7 and up is broken 0.46.6 works
