### ISSUE TITLE
Configure Protocol Muxing sequence

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p#201]
With https://github.com/libp2p/js-libp2p/pull/166/files, the libp2p constructor will be fully refactored and with it comes the option to pass a Protocol Muxing sequence.

My proposal is on communicate this is on https://github.com/libp2p/js-libp2p/pull/166/files#r193032278, however, I'm not married to that solution just yet. Example below:

```
protocolMuxing: {       // Protocol muxing sequence. libp2p uses sane defaults (below). You can override these with:
  transport: {
    secio: {
      spdy: '*',        // '*' means, from this point forward, accept any protocol
      mplex: '*'
    }
  }
}
```

**Comment by jacobheun** [comment]
This is now an array in the config and it will prioritize based on the order, although we currently only support mplex.
