### ISSUE TITLE
RTCPeerConnection closed while testing browser-to-browser example

### ISSUE THREAD

**Issue by HoseinHaqiqian** [libp2p/js-libp2p#2011]
I was implementing browser-to-browser nodes communication. First, I tried to test [this](https://github.com/libp2p/js-libp2p/tree/master/examples/libp2p-in-the-browser/webrtc/browser-to-browser) with the difference of putting a relay node on a server to have a public address.
But connection cannot be established because of : 
`util.ts:54 Uncaught (in promise) Error: RTCPeerConnection was closed
    at pc.<computed> (util.ts:54:24)`

**Comment by maschad** [comment]
Thanks for clarifying, unfortunately, the example code is limited to local browser nodes. I am curious as to whether an active connection is established, I suspect a failure may happen in the SDP exchange as [webrtc with private-to-private](https://docs.libp2p.io/concepts/transports/webrtc/#how-private-to-private-connectivity-works) depends on STUN servers  (in order  to discover it's own public IP address and port in the browser). 

You can configure [a STUN server like this](https://github.com/libp2p/universal-connectivity/blob/main/packages/frontend/src/lib/libp2p.ts#L37-L43) 

Separately, It may be worthwhile to take a look at https://github.com/libp2p/universal-connectivity to see how an example of how to configure a public relay node and establish private to private connectivity.

**Comment by maschad** [comment]
Gossipsub is not required for WebRTC connectivity, as gossipsub is a pub/sub model separate from these transports. I've created [an example](https://github.com/maschad/browser-to-browser-webrtc) that sets up a basic webRTC browser to browser connection that works. I used [ngrok](https://ngrok.com/) to host the remote nodes which I suspect may be different than your setup. Could you try that out and then feel free to [start a discussion](https://github.com/libp2p/js-libp2p/discussions) if you need help in debugging.

I am closing this as I don't there is an issue with the browser-to-browser example.
