### ISSUE TITLE
How to use topology changes with WebRTC connections?

### ISSUE THREAD

**Issue by marcus-pousette** [libp2p/js-libp2p#2036]
- **Version**:

0.46.9 

- **Platform**:

- **Subsystem**:

Registrar. WebRTC transport. 

#### Severity:

Medium

#### Description:

I am making another attempt to make the WebRTC transport to work again with my project..

But I have a problem: 

In my protocol handler I listen for topology changes and look for new connection and open streams to them. 

```
this.components.registrar.register(multicodec, {
	onConnect: (....) => { open stream }
})

```
With WebRTC transport, I will receive 1 signaling connection that is transient which I am ignoring in my protocol handler because that one will close once a direct WebRTC connection has been established (expected).

However, once this direct WebRTC connection has been established (verified by logging and using a debugger in the browser)  I expected the topology again to emit an onConnect event with the non transient connection. However it seems like the change detection  in [registrar](https://github.com/libp2p/js-libp2p/blob/5294f14caa314bb150554afff3a7ff45d2bf17ba/packages/libp2p/src/registrar.ts#L28) does not take into account that the last connection was transient. I never see a `onConnect` event for the WebRTC connection (perhaps since the signaling connection is closing after the WebRTC connection has started?).  (unexpected). 

- What events can I use to effectively listen for new incoming connections that are non-transient for my protocol handler? The topology changes does work when working with other transports but in this case I can no longer rely on it, or there is a bug/unintended behaviour. I could listen to the "connection:open" but that might lead to flakyiness as I don't yet perhaps know if the remote peer is supporting the protocol handler.

**Comment by justin0mcateer** [comment]
I am having the same problem with GossipSub. Since the first connection is transient, the GossipSub protocol is not allowed. Because the WebRTC connection is established prior to closing the relay connection and because the peer is already deemed connected, there is no event to drive GossipSub to re-attempt opening a stream. I am currently working around this with 'directPeers'.

I thought I had was to prevent the 'Identify' protocol from advertising 'non-transient' protocols over transient connections. This wouldn't solve the lack of a subsequent 'peer:connect' event but might still allow the protocol handler to work correctly. I haven't had time to try this approach.

**Comment by maschad** [comment]
If you are not interested in the protocols supported by peers that are connected via a transient connection you could [disable running identify over a transient connection](https://github.com/libp2p/js-libp2p/blob/master/packages/libp2p/src/identify/index.ts#L52)

**Comment by marcus-pousette** [comment]
What is the benefit of having identifyService running by default on transient connections, and what am I missing by not having it? 

Imo, what I am more after is the clearest solution where "topology" changes allows me to track all peers that have opened transient or non-transient connections for a specific protocol. Modifiying the behaviour of the topology change events by manipulating the construction variables of the identifyService feels like a long step. Also if anyone would want to use my protocol handler they also have to make sure they also modify they identifiyService constructor, and perhaps they depend on it to run on transient connections.

**Comment by justin0mcateer** [comment]
I think you need the Identify service to advertise the Webrtc signalling protocol over the transient connection.

When Identify iterates the available protocols, it can see they are transient. I was just thinking of a filter that would filter out non-transient protocol handlers on transient connections.

**Comment by achingbrain** [comment]
> I think you need the Identify service to advertise the Webrtc signalling protocol over the transient connection

This is correct, stopping identify from running on transient connections will break a few things.

Please take a look at #2049 - it changes the behaviour slightly to not notify topologies on transient connections (but adds an option to opt-in if that's useful).

It also fixes another problem in that the topology would only be notified on the first connection so you'd not know if a peer connected via a relay (e.g. transient), then opened a direct (e.g. non-transient) connection - either via WebRTC or DCUtR or something else.

**Comment by marcus-pousette** [comment]
> > I think you need the Identify service to advertise the Webrtc signalling protocol over the transient connection
> 
> This is correct, stopping identify from running on transient connections will break a few things.
> 
> Please take a look at #2049 - it changes the behaviour slightly to not notify topologies on transient connections (but adds an option to opt-in if that's useful).
> 
> It also fixes another problem in that the topology would only be notified on the first connection so you'd not know if a peer connected via a relay (e.g. transient), then opened a direct (e.g. non-transient) connection - either via WebRTC or DCUtR or something else.

that looks like it would solve it, thanks!

**Comment by marcus-pousette** [comment]
or it is a little hard to see whether that fix also makes sure the actual event is emitted for the non transient one. It looks like it just filters out events that are transient?
