### ISSUE TITLE
docs(libp2p): changelog for libp2p out of order

### ISSUE THREAD

**Issue by SgtPooki** [libp2p/js-libp2p#2039]
https://github.com/libp2p/js-libp2p/blob/master/packages/libp2p/CHANGELOG.md lists releases in the following order:

* [0.45.9](https://www.github.com/libp2p/js-libp2p/compare/libp2p-v0.45.8...libp2p-v0.45.9) (2023-06-14)
* [0.46.10](https://www.github.com/libp2p/js-libp2p/compare/libp2p-v0.46.9...libp2p-v0.46.10) (2023-09-10)
* [0.46.9](https://www.github.com/libp2p/js-libp2p/compare/libp2p-v0.46.8...libp2p-v0.46.9) (2023-09-05)

**Comment by maschad** [comment]
This happened as a result of us switching over to [release please](https://github.com/googleapis/release-please) from our previous release manager, they handled parsing the changelog format differently.
