### ISSUE TITLE
Webrtc behind NAT not work

### ISSUE THREAD

**Issue by Sotatek-HocNguyen** [libp2p/js-libp2p#2043]
I use the example in the directory: libp2p/js-libp2p/examples/libp2p-in-the-browser/webrtc/browser-to-browser. If 2 browsers are on the same LAN, they can connect and send messages.

But with 2 devices using 4G or using other wifi, it will not connect.
I have read the libp2p docs and see that AutoNAT and circuitRelayServer have the same support as [TURN](https://webrtc.org/getting-started/turn-server) server relay data. But I didn't find any examples? Can you provide me with an example?

**Comment by Sotatek-HocNguyen** [comment]
.

**Comment by maschad** [comment]
In our [universal connectivity](https://github.com/libp2p/universal-connectivity/blob/main/packages/frontend/src/lib/libp2p.ts) repo we have an example of two browser nodes connecting via a rust relay server which can be hosted remotely. Please take a look there and if you have any further questions related to getting setup or debugging feel free to start a discussion on [our Q&A forum](https://github.com/libp2p/js-libp2p/discussions/categories/q-a)
