### ISSUE TITLE
feat(@libp2p/perf): Continously measure Performance on a Single Connection

### ISSUE THREAD

**Issue by maschad** [libp2p/js-libp2p#2064]
The motivation for the larger effort is documented in https://github.com/libp2p/test-plans/issues/261. 

Instead of downloading an arbitrary amount of  MB multiple times, each on a new connection, establish a single connection and continuously measure the throughput for a fixed duration (60s by default). Perf `stdout` output would be refactored as such : 

 ``` typescript
               interface Data {
                 type: "intermediary" | "final";
                 timeSeconds: number;
                 uploadBytes: number;
                 downloadBytes: number;
               }
```

where every second the client must print the current progress to `stdout`. See example below. Note the `type: "intermediary"`.
         
``` json
               {
                 "type": "intermediary",
                 "timeSeconds": 1.004957645,
                 "uploadBytes": 73039872,
                 "downloadBytes": 0
               }
```
          
Before terminating, the client must print a final summary. See example below. Note the `type: "final"`. Also note that the measurement includes the time to (1) establish the connection, (2) upload the bytes and (3) download the bytes.
      
``` json
               {
                 "type": "final",
                 "timeSeconds": 60.127230659,
                 "uploadBytes": 4382392320,
                 "downloadBytes": 0
               }
```

**Comment by mxinden** [comment]
Thank you @maschad for the help here!

> Instead of downloading x MB multiple times, each on a new connection, establish a single connection and continuously measure the throughput for a fixed duration (60s by default).

Just to avoid confusion, from the perspective of the js-libp2p perf binary, it is still a single connection and a single stream throughout its process lifetime.

**Comment by achingbrain** [comment]
> establish a single connection and continuously measure the throughput for a fixed duration (60s by default)

Just to be clear here, that is not what https://github.com/libp2p/js-libp2p/pull/2067 does.  It transfers a fixed amount of data and once a second (give or take) it logs how much data was transferred during the previous interval.

**Comment by mxinden** [comment]
> > establish a single connection and continuously measure the throughput for a fixed duration (60s by default)
> 
> Just to be clear here, that is not what #2067 does. It transfers a fixed amount of data and once a second (give or take) it logs how much data was transferred during the previous interval.

The 60 seconds are enforced by the [runner](https://github.com/libp2p/test-plans/edit/master/perf/runner/src/index.ts). Detail being that it is actually 20s, not 60s.
