### ISSUE TITLE
interop: rename interop transport test script

### ISSUE THREAD

**Issue by maschad** [libp2p/js-libp2p#2130]
~~With the rename that took place in https://github.com/libp2p/test-plans/pull/308 we should deprecate the previous [npm package](https://www.npmjs.com/package/@libp2p/multidim-interop) and create a new one, as well as~~ [rename the test script](https://github.com/libp2p/js-libp2p/blob/master/interop/package.json?rgh-link-date=2023-10-04T02%3A00%3A37Z#L49)

**Comment by achingbrain** [comment]
Would it be possible to instead have one interop test module that contains multiple tests rather than multiple modules with a single test each?

It's a lot of boilerplate otherwise.

**Comment by maschad** [comment]
Good idea, I suppose we only need rename the script then.
