### ISSUE TITLE
Cannot establish connection between gomobile and browser node using js relay

### ISSUE THREAD

**Issue by HoseinHaqiqian** [libp2p/js-libp2p#2147]
- **Version**: 0.46.9

- **Platform**: android and js inside mac operating system

#### Description:
- I have created a go and browser implementation of libp2p and tried establishing connection between them, and it worked. But  after getting gomobile output of go implementation it only works under condition of communicating between mobile devices and it is not able to find browser node inside dht of js-relay. Also browser only can find browser nodes not mobile nodes. 
- i expected it to find browser node or js finds mobile nodes.

#### Steps to reproduce the error:
1- Use gomobile and browser implementation, connect them to a js relay.
2- Advertise both and try find other one.

they throw following error :
`more peers required, seen: 0  min: 1
`

**Comment by maschad** [comment]
Could you give us a link to a project or share the code so that we could try to reproduce the error?
