### ISSUE TITLE
maConn.abort is not a function

### ISSUE THREAD

**Issue by HoseinHaqiqian** [libp2p/js-libp2p#2148]
- **Version**: 0.46.6
- **Platform**: Mac os

- **Subsystem**: Relay
#### Description:
- Created js relay, connected js nodes through relay
- The relay throughs below error : 
`TypeError: maConn.abort is not a function
    at EventTarget.onAbort (file:///root/projects/js-libp2p-relay/node_modules/libp2p/dist/src/upgrader.js:88:20)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at EventTarget.dispatchEvent (node:internal/event_target:677:26)
    at abortSignal (node:internal/abort_controller:308:10)
    at Timeout._onTimeout (node:internal/abort_controller:115:7)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)`

Relay code : 

```

async function main() {
  const key = await libp2pCrypto.keys.generateKeyPairFromSeed(
    "Ed25519",
    Buffer.from(process.env.RLEAY_ID).subarray(0, 32)
  );

  const mPeerId = await peerIdFromKeys(
    libp2pCrypto.keys.marshalPublicKey({ bytes: key.public.bytes }, "ed25519"),
    libp2pCrypto.keys.marshalPrivateKey({ bytes: key.bytes }, "ed25519")
  );

  const node = await createLibp2p({
    addresses: {
      listen: [
        `/ip4/0.0.0.0/tcp/${process.env.RELAY_PORT}`,
        `/ip4/0.0.0.0/tcp/${process.env.RELAY_PORT + 1}/ws`,
      ]
    },
    peerId: mPeerId,
    transports: [
      tcp(),
      webSockets({
        filter: filters.all,
      }),
    ],
    connectionEncryption: [noise()],
    streamMuxers: [
      yamux({
        maxStreamWindowSize: 131072 * 100,
        initialStreamWindowSize: 131072 * 100,
        maxMessageSize: 131072 * 100,
      }),
      mplex({
        maxStreamBufferSize: 10000000,
        maxMsgSize: 131072 * 100,
      })
    ],
    services: {
      dht: kadDHT({
        allowQueryWithZeroPeers: true,
        clientMode: false,
      }),
      identify: identifyService({
        runOnTransientConnection: true,
        runOnConnectionOpen: true,
      }),
      relay: circuitRelayServer({
        advertise: true,
        reservations: {
          defaultDataLimit: BigInt(131072 * 10),
          applyDefaultLimit: false,
          defaultDurationLimit: 5 * 60 * 1000
        }
      }),
    }
  })
  console.log(`Node started with id ${node.peerId.toString()}`)
  console.log('Listening on:')
  node.getMultiaddrs().forEach((ma) => console.log(ma.toString()))
}

main()



```

**Comment by achingbrain** [comment]
Please can you try [upgrading to v1](https://github.com/libp2p/js-libp2p/blob/main/doc/migrations/v0.46-v1.0.0.md) and ensuring that all modules in your package.json are on the latest versions?

If the problem still persists can you link to a repo that demos the crash?
