### ISSUE TITLE
Network Visualization Tool

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p#215]
We need a libp2p network visualization tool in order to improve our debugging abilities and also for research purposes.

@vasco-santos is going to take the lead on this. There is some previous work worth checking out but it doesn't mean that it should be the base.

- libp2p pubsub testnet - https://github.com/gavinmcdermott/js-libp2p-pstn-stats
- iptb - ipfs testbed - https://github.com/ipfs/iptb

Also:

- @JGAntunes has a direct use for this -- https://github.com/ipfs/notes/issues/266 -- and has been building a network setup tool using mininet.
- @b5 is hosting a session right on this topic https://github.com/libp2p/developer-meetings/issues/8

**Comment by kumavis** [comment]
we've built out own for metamask light client / kitsunet / mustekala research
currently relies on a telemetry server all nodes connect to

has a live updating graph of the topo
![image](https://user-images.githubusercontent.com/1474978/42296266-8ec963e6-7fa8-11e8-9679-c8f8044cf30a.png)
observing + measuring pubsub is next : )

**Comment by lanzafame** [comment]
I would love to see a [hiveplot](http://hiveplot.net) as it would allow for visual comparison between different network topologies.

**Comment by kumavis** [comment]
added a pubsub mode
![image](https://user-images.githubusercontent.com/1474978/42403828-e1b10032-8138-11e8-933d-1718006a699f.png)

**Comment by diasdavid** [comment]
See also notes from a hold wish on having a dashboard for the DHT https://github.com/ipfs/notes/issues/34

**Comment by vitali2y** [comment]
[vis.js](http://visjs.org/network_examples.html) is great ([app example](https://github.com/vitali2y/marketplace/blob/master/docs/marketplace_demo_win10.png)).

**Comment by lanzafame** [comment]
@Kubuxu did you get any decent results out of your exploration into hiveplots?

**Comment by bjzhang** [comment]
Hi, I am interested in this project. Where could I know the recent progress of this project?
Besides, I saw an Network Visualization Tool in filecoin demo in Dwebsummit. Is it the same of relative project?
Thanks.

**Comment by sternhenri** [comment]
Hi everyone, 

Checking in on the state of this project. I'm looking into how we might do better measurements in p2p networks... Was wondering if anything had come out of this push in terms of a good topography viz tool or perf viz tool? :)

**Comment by jacobheun** [comment]
This is still on our Roadmap but we likely won't get to it until next year. https://github.com/libp2p/notes/issues/1 has a good aggregate of the current problem set and options, along with some links to existing tooling.
