### ISSUE TITLE
The APIs dont match: Constructor in readme "(_config)", constructor in src/ "(_modules, _peerInfo, _peerBook, _options)"

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-libp2p#217]
- **Version**: 0.20.4
- **Platform**: Ubuntu 16.04 x64
- **Subsystem**: js-libp2p

#### Steps to reproduce the error:

1. Follow the docs on the README (on npm)
2. Realize the APIs don't match

The example uses the new-style api, yet the old constructor still requires the old stil API. To avoid mass breakage maybe just add a shim that does `if (_modules.peerInfo) {_peerInfo = _modules.peerInfo; _peerBook = _modules.peerBook; _options = _modules.config; _modules = _modules.modules}`

**Comment by diasdavid** [comment]
@mkg20001 you are looking at the README of libp2p 0.22 and using it with libp2p 0.20.4. Simply update to 0.22

**Comment by mkg20001** [comment]
@diasdavid Ok. Noticed my local-npm server was just outdated again...
