### ISSUE TITLE
DHT + WebSocket example/support for libp2p-in-the-browser

### ISSUE THREAD

**Issue by cretz** [libp2p/js-libp2p#220]
Probably already on the roadmap, I just didn't see an issue (but still close this if it's not a worthy request). Specifically, add the experimental KAD DHT like in the `peer-and-content-routing` example in to the `libp2p-in-the-browser` example.

I personally am struggling to `findProviders` when connecting to the DHT. I get immediate response on the JS side (undefined error, empty peer list) and on the Go side, it times out after a minute during `UpgradeInbound`.

**Comment by cretz** [comment]
Ok, I am debugging this issue. The first one was that I had a muxer for version `/mplex/6.3.0` which is default at https://github.com/libp2p/go-libp2p/blob/934606d0f292f265eab890101233d18ffeabfda0/defaults.go#L29 but it's `/mplex/6.7.0` at https://github.com/libp2p/js-libp2p-mplex/blob/bb5b7c03e716001f29c064cd149f8bf40c4f23aa/src/codec.js#L3 and for some reason when it errored at https://github.com/multiformats/js-multistream-select/blob/a59306c2f2c5491b5f6fb69fbfaf57b0c2499fa1/src/dialer/index.js#L74-L77 it didn't bubble up to the node.dial callback. I changed the version number on the Go side (hope that's ok and doesn't cause issues), but I am still getting an immediate empty response on `findProviders`. I'll update when I have debugged that.

**Comment by cretz** [comment]
Ok, I advanced to the next step. I have a single node given to bootstrap. Then the `peer:discovery` event is invoked, but sadly the DHT's routing table still doesn't have the peer. I call dial from in there, but in the callback, sadly the DHT's routing table still doesn't have the peer. I get an event for `peer:connect`, but sadly the DHT's routing table still doesn't have the peer. At some point (after the mux is established I assume), it is added to the routing table, but I see no easy way to know that. I welcome any assistance to know when my DHT has at least one peer in the routing table. I now just attach an `added` handler to `_dht.routingTable.kb` (but I can't do it on construction because kb isn't present yet, so I do it just before dial).

My next issue is that it doesn't understand my peer's custom address protocol. I'm off now to see how to manually add a protocol to https://github.com/multiformats/js-multiaddr at runtime...

**Comment by KrishnaPG** [comment]
Wondering if this has been addressed. Looking for the same: an example on DHT in browser.

**Comment by p-shahi** [comment]
The DHT is supported in the browser. An example can be found here: https://github.com/libp2p/universal-connectivity
