### ISSUE TITLE
Is Circuit Relay V1 Supported?

### ISSUE THREAD

**Issue by christroutner** [libp2p/js-libp2p#2208]
The only JS examples I can find for connecting a libp2p node via circuit relay is [this one](https://github.com/libp2p/js-libp2p-example-circuit-relay). When I try to connect my libp2p node through a v1 Circuit Relay, I get this error:
 - `Failure reason: protocol selection failed`

From looking through the [circuit relay source code for js-libp2p](https://github.com/libp2p/js-libp2p/tree/master/packages/libp2p/src/circuit-relay), it appears that only v2 Circuit Relays are supported?

For my use case, v2 Circuit Relays do not seem to succeed. I need the file passing that only v1 Circuit Relays are capable of. Are there any plan to support v1 Circuit Relays? If they do support v1, how would the config differ from [this example](https://github.com/libp2p/js-libp2p-example-circuit-relay)?

**Comment by christroutner** [comment]
I should clarify: I have some standalone v1 Circuit Relays set up. I'm not trying to create a v1 Circuit Relay with the libp2p node. I'm trying connect two libp2p nodes through a standalone v1 Circuit Relay.

**Comment by achingbrain** [comment]
> For my use case, v2 Circuit Relays do not seem to succeed. I need the file passing that only v1 Circuit Relays are capable of.

The key difference between v1 and v2 is that every v1 relay is an open relay with no limits on connections or data transfer so are open for abuse.

v2 places limits on the amount of data that can be sent so it's only suitable for signalling while establishing a direct connection.

For example if you have a node with a file and it's listening on WebRTC, you'll notice that the reported WebRTC address has a `p2p-circuit` component.

Another node wishing to fetch the file will dial the WebRTC address - this opens a connection to the relay, the relay opens a stream to the node with the file, WebRTC handshake data is exchanged, a direct connection is established between the two nodes and a file transfer can take place.

Are you able to use WebRTC in this fashion?

**Comment by christroutner** [comment]
After digging through Issues and documentation the last week, it dawned on me that WebRTC is getting a lot of attention in the js-libp2p and helia projects. I'm just starting to work on integrating that transport into my project. I'll try that and report back if it doesn't seem to fix the issues.

I'm optimistic that with the combination of v2 Circuit Relays and WebRTC, my project can achieve its goals.
