### ISSUE TITLE
transport and discovery modules: use a function instead of a class

### ISSUE THREAD

**Issue by pgte** [libp2p/js-libp2p#223]
Currently, you can define a transport or discovery module as an instance or a class.
Instead of a class, why not a function call [here](https://github.com/libp2p/js-libp2p/blob/8533936ffa9c56436dfdb6825cd83000b46c853c/src/index.js#L133) and [here](https://github.com/libp2p/js-libp2p/blob/8533936ffa9c56436dfdb6825cd83000b46c853c/src/index.js#L165)? This way, the provider has control over which instance to deliver to libp2p.

Use case: this allows me to solve https://github.com/ipfs-shipyard/peer-star-app/issues/1

**Comment by jacobheun** [comment]
What data would you want to see passed into that function? I assume you are talking about using generators for the transports and discovery modules?

**Comment by pgte** [comment]
Ideally I would like the peerInfo or peerId to be passed in.
This is more about the interface being a function and not a class.
The arguments of this call is being explored in #222.

**Comment by achingbrain** [comment]
This has been refactored.  Closing due to staleness.
