### ISSUE TITLE
bug: Can't auto dial another browser witch only announced /p2p-circuit/webrtc

### ISSUE THREAD

**Issue by revonia** [libp2p/js-libp2p#2231]
- **Version**:

0.46.16

- **Platform**:

Chrome 119.0.6045.123
- **Subsystem**:

@libp2p/webrtc 3.2.5

#### Severity:

Medium
#### Description:

I am attempting to develop a browser-based application and have configured the addresses.announceFilter to exclusively use WebRTC. While testing on my local circuit-relay server after initiating libp2p, I encountered an issue where the application failed to automatically establish connections with other browser nodes. This problem persists unless I remove addresses.announceFilter. Without this configuration, although auto-dialing occurs, the traffic is routed solely through the relay.

After thorough investigation, I discovered that WebRTCTransport.filter utilizes the `WebRTC.exactMatch` filter from @multiformats/multiaddr-matcher. This filter rejects connections with the pattern /dns4/127.0.0.1/tcp/8000/ws/p2p/12DMyRelay/p2p-circuit/webrtc. The solution to this problem involves switching to `WebRTC.matches` from @multiformats/mafmt, which resolves the issue and allows the application to function normally.

https://github.com/libp2p/js-libp2p/blob/17d980c902fa5314e954508255a41c0854416d47/packages/transport-webrtc/src/private-to-private/transport.ts#L109-L111

#### Steps to reproduce the error:

```javascript
import {createLibp2p} from "libp2p";
import {webSockets} from "@libp2p/websockets";
import {webRTC} from "@libp2p/webrtc";
import {circuitRelayTransport} from "libp2p/circuit-relay";
import {noise} from "@chainsafe/libp2p-noise";
import {mplex} from "@libp2p/mplex";
import {yamux} from "@chainsafe/libp2p-yamux";
import {identifyService} from "libp2p/identify";
import {pingService} from "libp2p/ping";
import {kadDHT} from "@libp2p/kad-dht";
import {bootstrap} from "@libp2p/dnsaddr-bootstrap";
createLibp2p({
  addresses: {
    announceFilter: (addrs: Multiaddr[]) => {
      // only webrtc
      return addrs.filter((addr) => addr.protoNames().includes('webrtc'))
    },
    listen: [
      `/webrtc`,
    ]
  },
  transports: [
    webSockets(),
    webRTC(),
    circuitRelayTransport({
      discoverRelays: 10
    })
  ],
  connectionGater: {
  },
  connectionEncryption: [noise()],
  streamMuxers: [mplex(), yamux()],
  peerDiscovery: [
    bootstrap({
      list: [
        '/dns4/127.0.0.1/tcp/8000/ws/p2p/12D3KooWEEkMYYgRta9NGqvUS6xd94ufwqzmJLp8LhmThQq6m86C',
      ]
    })
  ],
  services: {
    identify: identifyService(),
    ping: pingService(),
    dht: kadDHT(),
  },
})
```

**Comment by achingbrain** [comment]
Thanks for opening this, but your setup works for me locally so I'm having trouble replicating the problem.

I see you're using 0.46.16 - have you tried with the latest versions of all modules?  0.46.21 is out and the patch versions have some fixes around dialling WebRTC addresses, this may help.

**Comment by revonia** [comment]
After upgrading libp2p to version 0.46.21 and updating some dependencies, the issue has been resolved. Thank you! 🥳
