### ISSUE TITLE
bug: webrtc-signaling proto ID does not match spec

### ISSUE THREAD

**Issue by SgtPooki** [libp2p/js-libp2p#2238]
https://github.com/libp2p/js-libp2p/blob/9c67c5b3d0ab63c7a1a62f363ae732b300ef6b87/packages/transport-webrtc/src/private-to-private/transport.ts#L25

The spec says to use `/webrtc-signaling`. see https://github.com/libp2p/specs/blob/master/webrtc/webrtc.md#signaling-protocol

Discovered this with @sukunrt when doing some webrtc transport stuff locally. 

### Some notes:

He updated his proto_id to include the `0.0.1` and we were able to fully connect (using local [helia-identify](https://helia-identify.on.fleek.co/)) ran on his address of `/ip6/<blah>/udp/4001/quic-v1/webtransport/certhash/<blah>/certhash/<blah>/p2p/<blah>/p2p-circuit/webrtc/p2p/<blah>`

but we need to find agreement on the protocol id name

**Comment by achingbrain** [comment]
The addition of the version number here seems to be a mistake, but removing it will break compatibility with any deployed js-libp2p nodes.

Given that this is the only shipping implementation of WebRTC private to private, perhaps the simpler solution would be to add the version number [to the spec](https://github.com/libp2p/specs/blob/master/webrtc/webrtc.md#signaling-protocol)?

**Comment by maschad** [comment]
We decided updating the spec would cause less friction https://github.com/libp2p/specs/pull/598
