### ISSUE TITLE
Connection manager is not started

### ISSUE THREAD

**Issue by alanshaw** [libp2p/js-libp2p#224]
I can't see where the connection manager is started! It is instantiated but `start` is never called 😟 

https://github.com/libp2p/js-libp2p/blob/d9059dbad9b33e2c1434b5c13ff500ed34aa348f/src/index.js#L45

refs https://github.com/ipfs/js-ipfs/issues/1435#issuecomment-406113817

**Comment by jacobheun** [comment]
I don't know if this was intentional or not to have it not start by default, but I think it needs to be auto started.
