### ISSUE TITLE
feat: Ensure services indicate their dependencies through identifiers  

### ISSUE THREAD

**Issue by maschad** [libp2p/js-libp2p#2263]
As suggested in https://github.com/libp2p/js-libp2p/discussions/2135 In order for services to indicate their dependencies so that consumers can utilize the libp2p stack effectively, we should have each service return a list of other services it requires, which would be verified on startup.

Related: https://github.com/libp2p/js-libp2p/pull/1762

**Comment by dhuseby** [comment]
related to https://github.com/libp2p/js-libp2p/issues/2263
