### ISSUE TITLE
Error trying to connect to peer node :  'maConn.log is not a function'

### ISSUE THREAD

**Issue by christroutner** [libp2p/js-libp2p#2305]
- **Version**:
"libp2p": "1.0.9"

- **Platform**:
Linux pop-os 6.0.12-76060006-generic #202212290932~1671652965~22.04~452ea9d SMP PREEMPT_DYNAMIC Wed D x86_64 x86_64 x86_64 GNU/Linux

#### Severity:
Low

#### Description:
I'm trying to update my app from js-libp2p v0.46.21 to the latest v1.0.9. I've reviewed the [Migration document](https://github.com/libp2p/js-libp2p/blob/main/doc/migrations/v0.46-v1.0.0.md#identify) and made the required changes to the `identify` and `circuit-relay-v2` libraries. When my node tries to connect to other nodes, it fails with this error:

```
status: Error trying to connect to peer node :  'maConn.log is not a function'
status: Could not connect to Circuit Relay with this multiaddr: /ip4/78.46.129.7/tcp/4001/p2p/12D3KooWLQLZYcH6TDD3uU4aQu1C3o47kdmTyiQ1xo5GnSi6jAyW, reason: maConn.log is not a function

```

[Here is the code I'm running](https://github.com/Permissionless-Software-Foundation/ipfs-service-provider/blob/cd4ec2711e958348d92cbffae2600db8da6fd9cb/src/adapters/ipfs/ipfs.js)

I'm hoping I can get some tips as to how to debug this, track down the source of the issue, and fix it.

The other nodes I'm trying to connect to are running the older v0.46.21 version of libp2p. Is that the issue? Do the changes to libp2p break backward compatibility with other nodes?

**Comment by christroutner** [comment]
Just to cover my bases, I did the following, but still received the same error when starting:
- deleted package-lock.json
- deleted node_modules folder
- deleted the datastore and blockstore.

**Comment by achingbrain** [comment]
You've almost certainly got some old deps in there - `maconn.log` was added for `libp2p@v1` so the object must be coming from an older dependency version - looking at the package.json there are newer versions of `@libp2p/tcp`, `@libp2p/bootstrap`, `@chainsafe/libp2p-noise` and `@chainsafe/libp2p-gossipsub` that were released to work with `libp2p@1.x.x`.

If you also use `helia@next`, it has the `libp2p@1.x.x` upgrade applied too.

**Comment by christroutner** [comment]
You were right @achingbrain. I updated all the libp2p-based dependencies in my package.json file, deleted the package-lock and node_modules/ folder, and reinstalled dependencies. That fixed the issue.
