### ISSUE TITLE
Datastore no longer retains self.data in v1

### ISSUE THREAD

**Issue by christroutner** [libp2p/js-libp2p#2317]
- **Version**:
- 1.0.10

- **Platform**:
- Ubuntu 22.04
- Linux pop-os 6.0.12-76060006-generic #202212290932~1671652965~22.04~452ea9d SMP PREEMPT_DYNAMIC Wed D x86_64 x86_64 x86_64 GNU/Linux

- **Subsystem**:
- datastore

#### Severity:
- high

#### Description:
I recently upgraded libp2p from v0.46.21 to v1.0.10. Every time I start the application, the IPFS node has a new CID identifier. This is problematic as my bootstrap nodes need to retain the same ID. Switching between version, v0.46.21 retains a `self.data` file in its datastore. In v1.0.10, that file is not created.

Here is the package.json files for each version that I'm comparing:
- [v0.46.21 package.json](https://github.com/Permissionless-Software-Foundation/ipfs-service-provider/blob/1783768c32c473b4e7489e318aa0f18c8c3fdbd1/package.json)
- [v1.0.10 package.json](https://github.com/Permissionless-Software-Foundation/ipfs-service-provider/blob/ac3730dbd9adc92a247ba0de6c3243e2cd7dfd3f/package.json)

When I made the switch from v0.46.21 to v1.0.10 I updated all dependencies that were involved with libp2p, including the datastore and blockstore.

**Comment by marcus-pousette** [comment]
Also get the same behaviour. Previously by making the datastore persistant the peerid would persist between if recreating the client from the same directory. The new behaviour is that the peer id is not persisted even if that is the case.

**Comment by christroutner** [comment]
If the solution is to use the [@libp2p/keychain](https://www.npmjs.com/package/@libp2p/keychain) library, I would appreciate a code example on how to generate a key and pass it on to `createLibp2p()`.

If the data is generated by `datastore` or some other part of libp2p, I just need an example of how to find it and extract it. It's easy enough to write a JSON object to file. I just need some idea of how to go about it.

**Comment by wemeetagain** [comment]
> I just need some idea of how to go feeding some persisted private key to createLibp2p()

Right now the private key is attached as part of the peer id and fed in that way.

```ts
const keychain: Keychain = ...

const peerId = (await keychain.exportPeerId('self')) ?? await createEd25519PeerId()

const libp2p = await createLibp2p({ peerId, ... })
```

**Comment by christroutner** [comment]
I appreciate the response @wemeetagain. I tried to follow it, and played with the code for a couple hours, but I'm still struggling. 

I managed to generate a key pair, as well as a `Qm...` ID. But when I try to pass it on to the `createLibp2p()` function, I get an error like: `invalid wire type 4 at offset 1`.

My guess, and I could be wrong about this, is that the peer ID I'm generating does not match the keypair generated by the keychain internal to the libp2p library.



How would you go about importing the `@libp2p/keychain` library and instantiating `keychain`?

**Comment by christroutner** [comment]
I'm cross linking from this Issue to [this post on the discussion forums](https://discuss.libp2p.io/t/how-to-use-js-libp2p-keychain/2171).

**Comment by SgtPooki** [comment]
Does https://github.com/libp2p/js-libp2p/blob/c9ed1c7d62e9af974789eb753d6f8e3c6410df94/doc/migrations/v0.46-v1.0.0.md#keeping-the-same-peerid-after-a-restart not help you guys?

If not, we should update the migration guide.

**Comment by christroutner** [comment]
Man, I thought I was going crazy. I couldn't believe how I missed that section. It turns out it was created 3 weeks ago, and my Issue was opened 6 weeks ago.

Thank you for pointing it out @SgtPooki!

I'll read through this and see if it I can resolve this Issue.

**Comment by christroutner** [comment]
Some feedback on the migration guide:

The [Keeping the same PeerId after restart](https://github.com/libp2p/js-libp2p/blob/c9ed1c7d62e9af974789eb753d6f8e3c6410df94/doc/migrations/v0.46-v1.0.0.md#keeping-the-same-peerid-after-a-restart) code example calls a class called `Key`, which is not defined. Is this an npm library that I can install? I did a quick search on npmjs.org and didn't find anything.

The [keychain] section uses a different way to instantiate the keychain library. In this section it instantiates the `keychain` object from the `'@libp2p/interface/keychain'` library. But in the [Keeping the same PeerId after restart](https://github.com/libp2p/js-libp2p/blob/c9ed1c7d62e9af974789eb753d6f8e3c6410df94/doc/migrations/v0.46-v1.0.0.md#keeping-the-same-peerid-after-a-restart) section, it is instantiated `'@libp2p/keychain'` library. Which one should I use?

**Comment by christroutner** [comment]
I think I figured it out:

- `import {Key} from 'interface-datastore/key'`

The `Key` class comes from the `interface-datastore` npm library. I found that line looking through the js-ipfs code base.

**Comment by christroutner** [comment]
Through a lot of trial and error, it turns out I didn't even need the `Key()` class. But I managed to generate keys, peerIds, persist them to the hard drive, and reload them at startup. [Here is actual working code](https://github.com/Permissionless-Software-Foundation/ipfs-service-provider/blob/050141d31e58da5ad340fb3f64810d172c43b5bc/src/adapters/ipfs/ipfs.js#L114-L130).

I recommend updating the code in the migration guide, as it didn't work and ended up being pretty misleading.

**Comment by achingbrain** [comment]
> I don't understand where the Key class is coming from, how to add it to my project, or how to instantiate it.

Sorry for the confusion.  As part of splitting things out into services all non-network code was ejected from the core, but I think in the case of the keychain DX has suffered a little bit.

In the future if we implement the [service dependencies idea](https://github.com/libp2p/js-libp2p/discussions/2135), we might be able to look at configured services to see if something provides a keychain service and then handle this in the libp2p factory again.

I'm glad you got to the bottom of it though.  As you noticed there was a gap in the docs which has since been filled so hopefully this will be less painful for others going forwards.

> [Here is actual working code](https://github.com/Permissionless-Software-Foundation/ipfs-service-provider/blob/050141d31e58da5ad340fb3f64810d172c43b5bc/src/adapters/ipfs/ipfs.js#L114-L130).

One thing about the solution - it falls back to creating an RSA PeerId.  These are too widespread to be deprecated but you should consider using Ed25519 keys instead because they are small enough to embed the public key in the PeerId itself. 
 
The public keys for RSA PeerIds are too big for this and require extra routing calls (e.g. DHT/HTTP) to locate it if it is not present before peers can work with it.

> The [keychain](https://github.com/libp2p/js-libp2p/blob/c9ed1c7d62e9af974789eb753d6f8e3c6410df94/doc/migrations/v0.46-v1.0.0.md#keychain) section uses a different way to instantiate the keychain library. In this section it instantiates the keychain object from the '@libp2p/interface/keychain' library. But in the [Keeping the same PeerId after restart](https://github.com/libp2p/js-libp2p/blob/c9ed1c7d62e9af974789eb753d6f8e3c6410df94/doc/migrations/v0.46-v1.0.0.md#keeping-the-same-peerid-after-a-restart) section, it is instantiated '@libp2p/keychain' library. Which one should I use, or does it not matter?

The 'keychain' section imports a type from `@libp2p/interface`, the 'Keeping the same PeerId after a restart' section imports the `keychain` function from `@libp2p/keychain` to create a keychain service.

You can't instantiate a type (they are just a compile-time safety check and are removed from the final code) so you should use the value from `@libp2p/keychain`.

**Comment by christroutner** [comment]
Thank you for the clarification @achingbrain. It's good to know about the difference between RSA and Ed25519 keys!
