### ISSUE TITLE
`mss.handle` never resolves when `optimisticSelect`

### ISSUE THREAD

**Issue by marcus-pousette** [libp2p/js-libp2p#2321]
- **Version**:

libp2p: 1.0.10

- **Platform**:

Darwin MacBook-Pro-3 23.0.0 

- **Subsystem**:

multistream-select (?) 

#### Severity:
Critical/High

#### Description:
I am in the process of upgrading to v1 from 0.46.  After upgrading I am no longer able to receive incoming streams in my protocol handler. Something that did work prior to upgrading the libp2p version. 

Specifically, the registrar handle never emits any new incoming streams.
```ts
this.components.registrar.handle(multicodec, this.onIncomingStream, options) 
```

Going through this more, it seems that I get incoming streams, but the code never resolves at ```mss.handle```
https://github.com/libp2p/js-libp2p/blob/ad6f70bf3cb354823380af95462a85654a0e6ab1/packages/libp2p/src/upgrader.ts#L373 

I get the same results when using yamux and mplex. 

These are the logs I get when both nodes attempt to open a stream to the other node at the same time

```sh
libp2p:connection:outbound:2ei1eo1702901551113 starting new stream for protocols [ '/test/0.0.0' ] +5s
  libp2p:yamux:outbound:3 no abort signal was passed while trying to negotiate protocols [ '/test/0.0.0' ] falling back to default timeout +0ms
  libp2p:yamux:outbound:3 selected protocol /test/0.0.0 +0ms
  libp2p:connection:outbound:2ei1eo1702901551113 starting new stream for protocols [ '/ipfs/id/push/1.0.0' ] +5ms
  libp2p:yamux:outbound:5 selected protocol /ipfs/id/push/1.0.0 +0ms
  libp2p:yamux frame for missing stream id=1 +0ms
  libp2p:yamux frame for missing stream id=1 +0ms
  libp2p:yamux frame for missing stream id=1 +0ms
  libp2p:yamux frame for missing stream id=1 +2ms
  libp2p:identify identify completed for peer 12D3KooWPmL3fL7d8kmW643NnM1gppd4rhvCJzHAKHKyotQaULFw and protocols [ '/ipfs/id/1.0.0', '/ipfs/id/push/1.0.0', '/libp2p/circuit/relay/0.2.0/hop', '/test/0.0.0' ] +0ms
  libp2p:identify our observed address is /ip4/127.0.0.1/tcp/60410/p2p/12D3KooWLT7iLouzF7NbAZuV2SHf528RMxZMrg2Dh66JmBkaSBK4 +0ms
  libp2p:identify storing our observed address /ip4/127.0.0.1/tcp/60410/p2p/12D3KooWLT7iLouzF7NbAZuV2SHf528RMxZMrg2Dh66JmBkaSBK4 +0ms
  libp2p:identify received identify from 12D3KooWPmL3fL7d8kmW643NnM1gppd4rhvCJzHAKHKyotQaULFw +0ms
  libp2p:identify received signedPeerRecord from 12D3KooWPmL3fL7d8kmW643NnM1gppd4rhvCJzHAKHKyotQaULFw +0ms
  libp2p:identify patching 12D3KooWPmL3fL7d8kmW643NnM1gppd4rhvCJzHAKHKyotQaULFw with {
  addresses: [
    {
      isCertified: true,
      multiaddr: Multiaddr(/ip4/127.0.0.1/tcp/60409)
    },
    {
      isCertified: true,
      multiaddr: Multiaddr(/ip4/127.0.0.1/tcp/60411/ws)
    }
  ],
  protocols: [
    '/ipfs/id/1.0.0',
    '/ipfs/id/push/1.0.0',
    '/libp2p/circuit/relay/0.2.0/hop',
    '/test/0.0.0'
  ],
  publicKey: <Buffer 08 01 12 20 cf 3c 79 9d 4d b6 76 2a 71 f5 0b 1d 43 ad 86 47 2e 6f b4 ce ee 4c 07 27 10 8d fc c3 a8 51 ed 76>,
  metadata: Map(0) {},
  peerRecordEnvelope: <Buffer 0a 24 08 01 12 20 cf 3c 79 9d 4d b6 76 2a 71 f5 0b 1d 43 ad 86 47 2e 6f b4 ce ee 4c 07 27 10 8d fc c3 a8 51 ed 76 12 02 03 01 1a 49 0a 26 00 24 08 01 ... 133 more bytes>
} +2ms
  libp2p:identify merging 12D3KooWPmL3fL7d8kmW643NnM1gppd4rhvCJzHAKHKyotQaULFw metadata {
  AgentVersion: Uint8Array(31) [
    108, 105, 98, 112,  50, 112,  47,  49,
     46,  48, 46,  49,  48,  32,  85, 115,
    101, 114, 65, 103, 101, 110, 116,  61,
    118,  49, 56,  46,  48,  46,  48
  ],
  ProtocolVersion: Uint8Array(10) [
    105, 112, 102, 115, 47,
     48,  46,  49,  46, 48
  ]
} +1ms
  libp2p:connection:inbound:cuesk11702901551127 incoming stream opened on /ipfs/id/push/1.0.0 +5s
  libp2p:connection:inbound:cuesk11702901551127 starting new stream for protocols [ '/test/0.0.0' ] +4s
  libp2p:yamux:outbound:4 no abort signal was passed while trying to negotiate protocols [ '/test/0.0.0' ] falling back to default timeout +0ms
  libp2p:yamux:outbound:4 selected protocol /test/0.0.0 +1ms
  libp2p:identify received identify from 12D3KooWPmL3fL7d8kmW643NnM1gppd4rhvCJzHAKHKyotQaULFw +4s
  libp2p:identify received signedPeerRecord from 12D3KooWPmL3fL7d8kmW643NnM1gppd4rhvCJzHAKHKyotQaULFw +0ms
  libp2p:identify patching 12D3KooWPmL3fL7d8kmW643NnM1gppd4rhvCJzHAKHKyotQaULFw with {
  addresses: [
    {
      isCertified: true,
      multiaddr: Multiaddr(/ip4/127.0.0.1/tcp/60409)
    },
    {
      isCertified: true,
      multiaddr: Multiaddr(/ip4/127.0.0.1/tcp/60411/ws)
    }
  ],
  protocols: [
    '/ipfs/id/1.0.0',
    '/ipfs/id/push/1.0.0',
    '/libp2p/circuit/relay/0.2.0/hop',
    '/test/0.0.0'
  ],
  metadata: Map(2) {
    'AgentVersion' => Uint8Array(31) [
      108, 105, 98, 112,  50, 112,  47,  49,
       46,  48, 46,  49,  48,  32,  85, 115,
      101, 114, 65, 103, 101, 110, 116,  61,
      118,  49, 56,  46,  48,  46,  48
    ],
    'ProtocolVersion' => Uint8Array(10) [
      105, 112, 102, 115, 47,
       48,  46,  49,  46, 48
    ]
  },
  peerRecordEnvelope: <Buffer 0a 24 08 01 12 20 cf 3c 79 9d 4d b6 76 2a 71 f5 0b 1d 43 ad 86 47 2e 6f b4 ce ee 4c 07 27 10 8d fc c3 a8 51 ed 76 12 02 03 01 1a 49 0a 26 00 24 08 01 ... 133 more bytes>
} +1ms
  libp2p:identify merging 12D3KooWPmL3fL7d8kmW643NnM1gppd4rhvCJzHAKHKyotQaULFw metadata {
  AgentVersion: Uint8Array(31) [
    108, 105, 98, 112,  50, 112,  47,  49,
     46,  48, 46,  49,  48,  32,  85, 115,
    101, 114, 65, 103, 101, 110, 116,  61,
    118,  49, 56,  46,  48,  46,  48
  ],
  ProtocolVersion: Uint8Array(10) [
    105, 112, 102, 115, 47,
     48,  46,  49,  46, 48
  ]
} +1ms
  libp2p:identify handled push from 12D3KooWPmL3fL7d8kmW643NnM1gppd4rhvCJzHAKHKyotQaULFw +1ms
  libp2p:yamux frame for missing stream id=2 +0ms
  libp2p:yamux frame for missing stream id=2 +0ms
  libp2p:yamux frame for missing stream id=2 +0ms
  libp2p:yamux frame for missing stream id=2 +1ms
  libp2p:yamux frame for missing stream id=5 +0ms
  libp2p:yamux discarding data for stream id=5 +0ms
  libp2p:yamux discarding data for stream id=5 +0ms
  libp2p:yamux frame for missing stream id=5 +1ms
  
  ```

I wonder whether https://github.com/libp2p/js-libp2p/pull/2318 is intended to fix this issue. Or some other work related to 'optimistic' stream selection is related to this.

**Comment by marcus-pousette** [comment]
Removing this line https://github.com/libp2p/js-libp2p/blob/ad6f70bf3cb354823380af95462a85654a0e6ab1/packages/multistream-select/src/select.ts#L69

make everything work again

**Comment by achingbrain** [comment]
#2318 resolves a problem where for very short lived streams, where we send a small amount of data and then immediately close the stream, we'd end up closing the stream before negotiation had finished.

Is this similar to what you are doing?  Or something else?  If it's something else can you link me to an example?

**Comment by marcus-pousette** [comment]
> #2318 resolves a problem where for very short lived streams, where we send a small amount of data and then immediately close the stream, we'd end up closing the stream before negotiation had finished.
> 
> Is this similar to what you are doing? Or something else? If it's something else can you link me to an example?

I did try to patch my lib with those changes but where not successful in eliminating the problem. Only by remove the `optimisticSelect` has fixed it so far for me. 

I am doing a similiar thing as to how gossipsub handles and setups new streams, so I am curious how no other have got this problem yet (but it seems that gossipsub project only tests their protocol on a mocked client). 

Here https://github.com/dao-xyz/peerbit/blob/2bb0734e764c58c8c0988f70c76e3786f75a05d0/packages/transport/stream/src/index.ts#L538

usually I receive incoming streams. But no I no longer receive them because `mss.handle` never resolves so the registrar.handle thing events are never emitted. 

Things that might differ from my setup to others: I am using the circuit relay v2 and identify protocol. And both sides tries to open a stream to the other side at the same time once they have successfully established a connection ([on topology changes](https://github.com/dao-xyz/peerbit/blob/2bb0734e764c58c8c0988f70c76e3786f75a05d0/packages/transport/stream/src/index.ts#L551)

**Comment by marcus-pousette** [comment]
I also tried added a 5s delay before opening a stream on a new connection to see whether the issues where related to other protocols needing to go through the `mss.handle` but no success

**Comment by marcus-pousette** [comment]
Here 

https://github.com/libp2p/js-libp2p/blob/ad6f70bf3cb354823380af95462a85654a0e6ab1/packages/multistream-select/src/select.ts#L128

I enter with

 /noise
/mplex/6.7.0
 /ipfs/id/1.0.0
 /test/0.0.0  <-- my protocol handler
 /ipfs/id/push/1.0.0
 
 But I only seem to send protocol for 
 noise
 /mplex/6.7.0
 /ipfs/id/push/1.0.0
 ipfs/id/1.0.0
 
 
 Interestingly at the exact moment my test fail (i.e. it starts to [close the outbound stream](https://github.com/dao-xyz/peerbit/blob/2bb0734e764c58c8c0988f70c76e3786f75a05d0/packages/transport/stream/src/index.ts#L281) of my protocol handler (?)) then it starts to send  /test/0.0.0 because I reach [here](https://github.com/libp2p/js-libp2p/blob/f731f8de1c22abe7f7ecd80fca4c4220bf2082cb/packages/multistream-select/src/select.ts#L201) but fails with the error 
 "Cannot push value onto an ended pushable" (since the stream is to end) 
 
 It is like that "/test/0.0.0"  gets stuck at https://github.com/libp2p/js-libp2p/blob/ad6f70bf3cb354823380af95462a85654a0e6ab1/packages/multistream-select/src/select.ts#L157 somehow

**Comment by marcus-pousette** [comment]
I wonder if the race condition here is that both sides expect the other side to write some data, but no-one starts?

**Comment by marcus-pousette** [comment]
I think I have figured out the issue now: 

Previously a stream (inbound and outbound) could be setup without any data to be written, this allowed one to dial and wait for this to happen without engaging in any activity. This is something I did rely on at various places, since I assumed previously a half-opened stream would be considered, not ready, unwanted or a sign that something has gone wrong. 

The case now is that i have to write data in order to setup a stream fully (read and write). 

I need to understand though if I treat a "stream is 'ready'" requirement only to be that the outbound direction only exist, will not create any problems further down the line. Like that if the inbound stream is never successfully setup, I need a way of treating the whole stream as 'not ready'.  This kind of creates a scenario where I need to write some code to correctly handle the case where a half-open stream never succesfully is able to convert fully open stream, and terminate the stream altogether.

**Comment by achingbrain** [comment]
This sounds like it's getting closer.  From the [recent performance work](https://observablehq.com/@libp2p-workspace/performance-dashboard) it became apparent that round trips are the thing that make opening connections slow.

When there's only a single protocol being negotiated, in the case of open stream & write data, we optimistically write the protocol and the first chunk of data into the transport together, saving a round trip of sending the protocol, reading the response, then sending the data - this is what lowers connection establisment time to around 200ms.  Of course it needs the first data chunk to do this, so negotiation doesn't complete until the stream is interacted with.

In the case of open stream & read data it falls back to send the protocol, read the response, read some data, but only when the caller tries to read from the stream - so again negotiation doesn't complete until the stream is interacted with.

When there are multiple protocols being negotiated it has the older behaviour of immediately writing/reading protocol names/responses until one is agreed upon, since we can't send protocol+data, then send another protocol because the remote will interpret the data as the next protocol to be negotiated.

The intention here is that you open a stream, try to write or read data and deal with any failures as they occur.

If the case is that you need to open streams but do nothing with them, we might need to add an option to allow ensuring they are negotiated fully immediately to support this.

**Comment by marcus-pousette** [comment]
Make sense! 

> If the case is that you need to open streams but do nothing with them, we might need to add an option to allow ensuring they are negotiated fully immediately to support this.

I wonder whether there is a scenario where not doing optimistic protocol selection is faster. Imagine a case where you dial a bunch of peers then, eventually you want to send data to them. In this case, there might be idle time before data is sent, and that time could be used to negotiate the protocols.. If you in this case do protocol selection at the time the first data is sent, the delivery of the first package will be slower than if the negotiation was done prior

I imagine this (pseudo code) to solve both scenarios 

```ts
if (protocols length === 1 )
{
    optimisticProtocolSelection()
   setTimeout(()=>{
       normalSelection()
   },100)
}
```

**Comment by marcus-pousette** [comment]
Another thing, 

this line

https://github.com/libp2p/js-libp2p/blob/e5d433993ec9829af59bf7a00f58cb348ffc24a5/packages/multistream-select/src/select.ts#L201

Seem to always make my code throw/log the error "Cannot push value onto an ended pushable" if have a created a connection but never used it and is terminating it. I expect that there would be no errors thrown if I terminate a connection without sending any data through the streams.

What is the purpose of negotiating the protocols on a stream that is terminating?
