### ISSUE TITLE
@libp2p/webtransport Correct multiaddr format

### ISSUE THREAD

**Issue by sachaw** [libp2p/js-libp2p#2371]
Hi, I have just started a project that requires the use of @libp2p/webtransport
However none of the documented multiaddr formats are working as a listen address.

I have seen the following formats:
/ip4/0.0.0.0/udp/0/quic/webtransport
/ip4/0.0.0.0/udp/0/quic-v1/webtransport

**Comment by achingbrain** [comment]
The WebTransport transport is dial-only at the moment.  When QUIC lands in node.js we'll be able to add it but until then listening is not supported.

I did have a [PR](https://github.com/libp2p/js-libp2p-webtransport/pull/31) that added listener support via [@fails-components/webtransport](https://www.npmjs.com/package/@fails-components/webtransport) but it was never really production-grade.

**Comment by Download** [comment]
@achingbrain I made a PR that adds a note to the Webtransport docs about them supporting dial only. I am currently in the process of learning libp2p and I find that although there is a lot of documentation, it often misses critical details such as these or is hard to find. So I am trying to contribute by making small PRs with small updates to the docs as I go. Hope you find it helpful.

**Comment by achingbrain** [comment]
@Download thanks, yes - it's very helpful!

**Comment by achingbrain** [comment]
Fixed by #2411
