### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in \node_modules\libp2p\package.json

### ISSUE THREAD

**Issue by leon37084762** [libp2p/js-libp2p#2392]
i use Node.js v19.8.1 to build a libp2p test code , i got this error,why this issue happen an how to fix it:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in \node_modules\libp2p\package.json
[90m    at new NodeError (node:internal/errors:399:5)[39m
[90m    at exportsNotFound (node:internal/modules/esm/resolve:266:10)[39m
[90m    at packageExportsResolve (node:internal/modules/esm/resolve:546:13)[39m
[90m    at resolveExports (node:internal/modules/cjs/loader:579:36)[39m
[90m    at Module._findPath (node:internal/modules/cjs/loader:648:31)[39m
[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:1076:27)[39m
[90m    at Module._load (node:internal/modules/cjs/loader:934:27)[39m
[90m    at Module.require (node:internal/modules/cjs/loader:1157:19)[39m
[90m    at require (node:internal/modules/helpers:119:18)[39m
    at Object.<anonymous> [90m(\[39mindex.js:1:16[90m)[39m {
  code: [32m'ERR_PACKAGE_PATH_NOT_EXPORTED'[39m
}

**Comment by achingbrain** [comment]
libp2p is an [ESM-only](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) module, it cannot be `require`d, it must be `import`ed.

If you cannot use ESM in your project, you can use [dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) to load libp2p.

If you are using TypeScript, please ensure your `tsconfig.json` is set to output ESM - `"target"` and `"module"` should be set to `"ES2020"` at least.
