### ISSUE TITLE
Add documentation for crypto.supportedKeys

### ISSUE THREAD

**Issue by TJKoury** [libp2p/js-libp2p#2415]
- **Version**:
1.0.0

- **Platform**:
Linux pop-os 6.2.6-76060206-generic #202303130630~1685473338~22.04~995127e SMP PREEMPT_DYNAMIC Tue M x86_64 x86_64 x86_64 GNU/Linux

- **Subsystem**:

crypto

#### Severity:

Low

#### Description:

Add documentation for [crypto.supportedKeys](https://libp2p.github.io/js-libp2p/variables/_libp2p_crypto.keys.supportedKeys.html). Specifically, [marshalling and unmarshalling keys](https://github.com/libp2p/js-libp2p/blob/fb7c51c3c03c462ac4d2b42b32be95cd008c81fc/packages/crypto/test/keys/secp256k1.spec.ts#L78).

#### Steps to reproduce the error:

N/A

**Comment by achingbrain** [comment]
Thanks for opening this - would you like to open a PR that adds the missing documentation?

**Comment by tabcat** [comment]
I believe this was closed by https://github.com/libp2p/js-libp2p/pull/2660 . It removed `crypto.supportedKeys` and added util functions like `publicKeyToProtobuf`, `publicKeyFromProtobuf` and others..

**Comment by achingbrain** [comment]
Very true, I'm going to close this.
