### ISSUE TITLE
AutoDial retries creeps up CPU usage over time

### ISSUE THREAD

**Issue by mkykadir** [libp2p/js-libp2p#2418]
- **Version**: 1.2.3

- **Platform**: `Linux 7e698928f50f 5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023 aarch64 Linux`

- **Subsystem**: Connection manager

**Comment by abuvanth** [comment]
set in config

```javascript
connectionManager: {
      minConnections: 5
    },
```

**Comment by mkykadir** [comment]
yes I already did that as a temporary fix but I don't think this auto dialing feature should creep up memory and cpu usage over time; its really hard to mitigate and identify the exact root cause

**Comment by abuvanth** [comment]
> yes I already did that as a temporary fix but I don't think this auto dialing feature should creep up memory and cpu usage over time; its really hard to mitigate and identify the exact root cause

yes
