### ISSUE TITLE
Websocket connection error

### ISSUE THREAD

**Issue by ajayrao80** [libp2p/js-libp2p#245]
#### Description: When a node is disconnected from the internet, when internet comes back, it shows the below error. Obviously because it can't open a webscoket connection with another node. But my question is, can we catch it?

```
WebSocket connection to 'ws://127.0.0.1:8081/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
module.exports @ F:\classwork\madnet\node_modules\pull-ws\client.js:18
dial @ F:\classwork\madnet\node_modules\libp2p-websockets\src\index.js:26
timeout @ F:\classwork\madnet\node_modules\libp2p-switch\src\limit-dialer\queue.js:79
(anonymous) @ F:\classwork\madnet\node_modules\async\timeout.js:86
(anonymous) @ F:\classwork\madnet\node_modules\async\internal\initialParams.js:11
_dialWithTimeout @ F:\classwork\madnet\node_modules\libp2p-switch\src\limit-dialer\queue.js:86
_doWork @ F:\classwork\madnet\node_modules\libp2p-switch\src\limit-dialer\queue.js:41
DialQueue.queue.queue @ F:\classwork\madnet\node_modules\libp2p-switch\src\limit-dialer\queue.js:25
(anonymous) @ F:\classwork\madnet\node_modules\async\queue.js:10
process @ F:\classwork\madnet\node_modules\async\internal\queue.js:175
(anonymous) @ F:\classwork\madnet\node_modules\async\internal\queue.js:82
(anonymous) @ F:\classwork\madnet\node_modules\async\internal\setImmediate.js:27
runCallback @ timers.js:789
tryOnImmediate @ timers.js:751
processImmediate @ timers.js:722

```

**Comment by jacobheun** [comment]
It would be good to wrap the code in `libp2p-websockets`, https://github.com/libp2p/js-libp2p-websockets/blob/f59cf88cc237a34b0024e25392d7323ff6129c6b/src/index.js#L26-L31, with a try-catch and return the error via the callback. 

With the variety of transports libp2p has, we should have them each conform to not throwing errors and instead returning them via callbacks to make the dial handler code in libp2p-switch more uniform.

I've created an issue, https://github.com/libp2p/js-libp2p-websockets/issues/77, to track this. If you're up for submitting a PR that would be much appreciated!

**Comment by achingbrain** [comment]
Closing as this is specific to the websocket transport - please see https://github.com/libp2p/js-libp2p-websockets/issues/77 to continue.
