### ISSUE TITLE
autonat and upnp-nat both detect external IP address, but neither updates announced addresses.

### ISSUE THREAD

**Issue by MichaelJCole** [libp2p/js-libp2p#2454]
- **Version**:
├── @libp2p/autonat@1.0.13
├── @libp2p/upnp-nat@1.0.14
├── libp2p@1.3.0

- **Platform**:
linux

- **Subsystem**:
addressManager, AutoNAT, and UPNP.

#### Severity:

Considering js-libp2p as the transport layer for a peer-to-peer app running on a personal computer, and how users expect to configure p2p apps like bittorrent.

  High - The main functionality of the application does not work, API breakage, repo format breakage, etc.
  Medium - A non-essential functionality does not work, performance issues, etc.

#### Description:

Most peer-to-peer apps are run on personal computers instead of servers.  Consider Bittorrent clients like qbittorrent, utorrent, vuze, etc.
These allow users to change the address, port, and upnp settings while the application is running.  

Both autonat and upnp-nat detect a nodes public ip, but neither update the announce addresses in addressManager or candidates used by autonat.

This means an application using js-libp2p must detect these through other means or manage a restart of libp2p.

autonat detects them from peers and updates [addressManager's observedAddrs](https://github.com/libp2p/js-libp2p/blob/59a97b61b3e46f6d4b459ae94f7a6db534d4bca2/packages/interface-internal/src/address-manager/index.ts#L18), but it doesn't appear to update the candidates with the new IP address.

upnp-nat gets  [client.externaIp()](https://github.com/libp2p/js-libp2p/blob/59a97b61b3e46f6d4b459ae94f7a6db534d4bca2/packages/upnp-nat/src/upnp-nat.ts#L97) and [updates observed addrs](https://github.com/libp2p/js-libp2p/blob/59a97b61b3e46f6d4b459ae94f7a6db534d4bca2/packages/upnp-nat/src/upnp-nat.ts#L119) but my client's `libp2p.getMultiaddrs()` never update.

Maybe I'm missing something but I don't see a way to use this information to reconfigure the js-libp2p other than to:
1. start it with a known incomplete config
2. add a timer to let these async processes complete (60s timeout for upnp-nat)
3. interrogate the libp2p client using undeclared interfaces to get addressManager
4. stop the client and reconfigure listen addresses and restart.

The statically configured listen addresses are already templates 0.0.0.0 and port 0 are replaced with local interfaces.  It would be great if libp2p could do this with announce addresses as well.

What I'd like is to configure libp2p with these options: 

```
services: {
  autoNAT: autoNAT({ autoAnnounce true }),
  upnp: uPnPNAT({ autoAnnounce true })
}
```
When autoNAT observes an externalIP, it calls `addressManager.autoAnnounce(ip)`.  
addressManager iterates transports to create addresses.  These are then verified by autoNAT.

When uPnPNAT observes an externalIP/port it calls `addressManager.autoAnnounce(ip, port)`
addressManager iterates transports to create addresses.  These are then verified by autoNAT.

If addressManager remembers it's announced IP's, it could also do a port change with `addressManager.autoAnnounce(undefined, port)`

This would be a large change and may or may not be wanted. 

#### Steps to reproduce the error:

Look at how other peer-to-peer applications configure their networking

https://vpn.ac/images/tutorials/socks5/qbittorrent1.png
https://www.bolehvpn.net/images/utorrent1.jpg
https://imgur.com/MQ4zkcA

**Comment by MichaelJCole** [comment]
This is discussed here: https://github.com/libp2p/js-libp2p/blob/07b9f49d3aa3ca51727355fecb5c88f127236def/packages/libp2p/src/address-manager/README.md#dynamic-address-modifications

**Comment by achingbrain** [comment]
When confirming an observed address, the AutoNAT protocol requires several confirmations from a diverse range of network peers.  This is by design to make it harder to trick your node into thinking it's listening on addresses that it is not.

> my client's libp2p.getMultiaddrs() never update.

How long did you leave the node running when you observed this?  It can take a little while before the address is confirmed.
