### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by twoeths** [libp2p/js-libp2p#2477]
- **Version**:
v1.1.1

- **Platform**:
`Linux 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

- **Subsystem**:

#### Severity:
Medium

#### Description:
Refer to the profile taken by a lodestar beacon-node [here](https://github.com/ChainSafe/lodestar/pull/6556#issuecomment-2043250725)

There are > 15k of objects retained belonging to these classes:
- Socket
- ConnectionImpl
- Timeout
- XXHandShake
- MPlexStreamMuxer

#### Steps to reproduce the error:
Run a lodestar mainnet node and leave it for a long time, then monitor heap size of network thread

**Comment by tuyennhv** [comment]
I found all Sockets have a timeout and they're all destroyed
<img width="987" alt="Screenshot 2024-04-11 at 14 39 33" src="https://github.com/libp2p/js-libp2p/assets/10568965/22b0e147-7005-4cd2-af49-b8552202e1a5">

all connection statuses are also "closed"
<img width="989" alt="Screenshot 2024-04-11 at 14 40 39" src="https://github.com/libp2p/js-libp2p/assets/10568965/70b5ef72-2f34-40ee-b70d-017d0385fa1e">

also there are socket events attached during the `MultiaddrConnection.close()` function, especially the "drain" one

<img width="989" alt="Screenshot 2024-04-11 at 14 42 36" src="https://github.com/libp2p/js-libp2p/assets/10568965/bda8efd0-ed40-4f80-9984-706f032e88a4">

it seems to me the `MultiaddrConnection.close()` was called, but somehow it still keep some resources especially the socket listeners

**Comment by SgtPooki** [comment]
@tuyennhv slightly off-topic but is there any chance you could share the grafana dashboard json you use over at lodestar so we can use it in ipfs-shipyatd/helia-http-gateway ?

**Comment by tuyennhv** [comment]
@SgtPooki here's the libp2p dashboard in lodestar https://github.com/ChainSafe/lodestar/blob/unstable/dashboards/lodestar_libp2p.json

<img width="1660" alt="Screenshot 2024-04-11 at 19 54 28" src="https://github.com/libp2p/js-libp2p/assets/10568965/dd0aedcd-a271-4375-b09e-499ce7350ba5">

<img width="1666" alt="Screenshot 2024-04-11 at 19 54 46" src="https://github.com/libp2p/js-libp2p/assets/10568965/72e9cb58-e2b2-4c4d-a96b-dc36f35313b6">

**Comment by tuyennhv** [comment]
reopen until it's confirmed this is fixed in lodestar, waiting for a new release of `transport-tcp`

**Comment by achingbrain** [comment]
@tuyennhv did you manage to test the new release?

**Comment by tuyennhv** [comment]
@achingbrain we tested v9.0.22 and found it does not resolve the memory leak issue. It also introduced some performance impact that caused node to forward less gossip messages to mesh peers, I'm not sure if it links to `libp2p-tcp` specifically or other libs during the upgrade to have to rollback in our release

see https://github.com/ChainSafe/lodestar/pull/6701/files

**Comment by tuyennhv** [comment]
I think we need to upgrade all libp2p dependencies to the latest versions and evaluate again cc @wemeetagain 
need to take a new profile with leaked memory for `libp2p-tcp` >= v9.0.22 to move this forward

**Comment by achingbrain** [comment]
> I think we need to upgrade all libp2p dependencies to the latest versions

Please do, there was a small leak fixed by `@libp2p/utils@5.3.1` so that's a good idea in general.

**Comment by tuyennhv** [comment]
in progress PR by @wemeetagain : https://github.com/ChainSafe/lodestar/pull/6711
