### ISSUE TITLE
New link for js-libp2p maintainers call?

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p#2490]
It seems the zoom link listed at https://lu.ma/js-libp2p is broken
is there a new link?

**Comment by achingbrain** [comment]
@p-shahi I don't seem to have edit permissions on lu.ma - can you please grant them to me and also remove or update the link:

<img width="723" alt="image" src="https://github.com/libp2p/js-libp2p/assets/665810/ccec18c5-d83f-424b-a096-f1102b0d586d">

**Comment by p-shahi** [comment]
@achingbrain you should already be an admin, I made this change a while ago
<img width="879" alt="image" src="https://github.com/libp2p/js-libp2p/assets/50885601/8cbd15d8-e1b2-4a5d-af76-7b028f530eac">

I also made the change to use google meet last week https://lu.ma/js-libp2p:
<img width="1015" alt="image" src="https://github.com/libp2p/js-libp2p/assets/50885601/3b520896-8d7c-4d47-9727-e55ceafa0beb">

Can you confirm you see it updated on your end?

**Comment by achingbrain** [comment]
It's updated now, all good.

> you should already be an admin

I can see myself in the "Hosts" list, but I don't get the "Manage Event" button:

<img width="1015" alt="image" src="https://github.com/libp2p/js-libp2p/assets/665810/75a54327-6cd6-4795-a066-b63870b18dbf">

**Comment by wemeetagain** [comment]
Thanks :)
