### ISSUE TITLE
Enable relay by default (not hop)

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#253]
Replicating [go-libp2p#440](https://github.com/libp2p/go-libp2p/issues/440) here as I think we should do it.

Enabling circuit relay by default would be a great, quick win for improved connectivity for libp2p nodes. Since interop was resolved in August, https://github.com/ipfs/interop/pull/27, I think it's reasonable for us to move forward with this change.

This should just involve updating the default config value, readme and tests.

We should leave hop off by default as this could negatively impact performance for nodes and should be opt-in.

I also noticed that the IPFS [default libp2p bundles](https://github.com/ipfs/js-ipfs/blob/v0.32.2/src/core/runtime/libp2p-browser.js) aren't using relay by default and they probably should.

**Comment by jacobheun** [comment]
@vasco-santos @diasdavid does this seem reasonable to you?

**Comment by vasco-santos** [comment]
I believe that it would be an improvement for our users. So +1 on that

Finally, I completely agree that IPFS should also be using it by default

**Comment by jacobheun** [comment]
I opened up #254 to add this. I think this would be good to add in the 0.24 release (#249).
