### ISSUE TITLE
Finding Circuit Relay V2 servers

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p#2545]
The existing approach is for Circuit Relay v2 servers to publish provider records for a pre-determined CID, then would-be relay clients look up providers of this CID.  As the query travels through several nodes one of them may be a relay so will respond as a provider, otherwise the original provider records will be found which will return nodes functioning as relay servers.

This has some downsides:

1. Only js-libp2p nodes do this.
    This was unilaterally implemented by js-libp2p four(ish) years ago and no other implementations followed suit, so there are a limited number of nodes publishing these records
2. Large routing tables limit it's effectiveness
    As routing tables grow, the number of hops needed to locate the closest peers to the KAD-ID of the CID decreases so you are less likely to discover intermediate nodes as relays
3. 20 nodes get overloaded
    As every js-libp2p node is publishing provider records for the same CID, the same 20 nodes should (in theory) be hosting all provider records for every js-libp2p node on the network.  This is not scalable and is open to abuse.

Instead we will perform a random walk of the content routing and dial encountered peers.  After identify has run we will discover relays in a more scalable way, at the cost of opening more connections.

This will work for node without much issue though browsers may need some further tweaking as they are sometimes limited in the number of connections they can open e.g. https://issues.chromium.org/issues/40069954

**Comment by dhuseby** [comment]
Created awesome browser extension to debug this...
