### ISSUE TITLE
Ensure all libp2p packages have lead maintainters

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#259]
The current list of libp2p packages, https://github.com/libp2p/js-libp2p/blob/3226632d83e8684e32b00eeb398b21158b94586d/README.md#packages, is missing lead maintainers for many of the packages.  We need to ensure there is a lead maintainer in place to keep them well maintained.

Reference: https://github.com/libp2p/js-libp2p/pull/258

For posterity, once lead maintainer assignment is complete, ensure the table is complete for libp2p at https://github.com/ipfs/pm/issues/600#issuecomment-385674334

**Comment by jacobheun** [comment]
Notes from a quick chat @vasco-santos and I had:

Interface-libp2p : Deprecate?
Interface-connection : Jacob
Interface-transport: Jacob
Libp2p-utp: Vasco (already)
Libp2p-udp: Not Implemented
Libp2p-udt: Not Implemented
Libp2p-websockets: Jacob (already)
Libp2p-websockets-star-rendezvous:  Jacob (already)
Libp2p-secio: Friedel (already). (Maybe change this)
Interface-stream-muxer: Jacob
Interface-peer-discovery: Vasco
Libp2p-rendezvous: Vasco
Libp2p-mdns: Jacob (already)
Libp2p-nat-mgr: Jacob (in progress)
Peer-info: Pedro
Interface-peer-routing: Vasco
Interface-content-routing: Vasco
Interface-record-store: Vasco
Libp2p-record: Vasco
Libp2p-connection-manager: Vasco
libp2p-crypto-secp256k1: Friedel
libp2p-floodsub: Vasco
Libp2p-ping: Jacob (switch)
p2pcat: (not implemented)

**Comment by diasdavid** [comment]
@vasco-santos can you finalize https://github.com/libp2p/js-libp2p/pull/265 asap so that we have a clear way to glance through all the packages and see the ones that miss a Lead Maintainer?
