### ISSUE TITLE
private ipv6 address identified as public

### ISSUE THREAD

**Issue by marcus-pousette** [libp2p/js-libp2p#2623]
- **Version**:
1.8.1

- **Subsystem**:
dialer, defaultAddressSort

#### Severity:
Low

#### Description:
Address 
```ts
const address = '/ip6/::ffff:7f00:1/tcp/52498/p2p/12D3KooWFp4Uq323R3rF1ukZouXhmai37TejRJwMmsRg9fMM2jjY/p2p-circuit/p2p/12D3KooWPv7ef6tF1PjK1vFzjxW11rpcxp2rHjowtSLU4Xt2CNWP'
```
evaluates 
```ts
import { isPrivate } from './multiaddr/is-private.js';
```

```ts
isPrivate(address) 
```

is `false`,  but expected `true`?

This makes the default address sorter to prefer this address over other addresses

This one 
```
/ip4/127.0.0.1/tcp/52493/ws/p2p/12D3KooWFp4Uq323R3rF1ukZouXhmai37TejRJwMmsRg9fMM2jjY/p2p-circuit/p2p/12D3KooWPv7ef6tF1PjK1vFzjxW11rpcxp2rHjowtSLU4Xt2CNWP
```

evaluates to as private correctly

**Comment by achingbrain** [comment]
Reading [RFC4291](https://datatracker.ietf.org/doc/html/rfc4291), the address `::ffff:7f00:1` is an [IPv4-Mapped IPv6 Address](https://datatracker.ietf.org/doc/html/rfc4291#section-2.5.5.2).

So the `::ffff` part marks it as this type of address and the final 32 bits are an IPv4 address.

Add the omitted zeroes and split the octets, and `7f00:1` becomes `7f.00.00.01`, which in base 10 is `127.0.0.1`.

I think we need to add an extra check in [isPrivateIp](https://github.com/libp2p/js-libp2p/blob/main/packages/utils/src/private-ip.ts#L58-L59) for this type of address, then convert the final 32 bits to an IPv4 address and test that like the others.

Would you like to open a PR?

**Comment by marcus-pousette** [comment]
already did :)
