### ISSUE TITLE
Websocket server yield nullpointer exception if address is missing

### ISSUE THREAD

**Issue by marcus-pousette** [libp2p/js-libp2p#2631]
- **Version**:
1.8.1

- **Platform**:
Darwin MacBook-Pro-3.local 23.0.0 Darwin Kernel Version 23.0.0: 
Node 20

- **Subsystem**:
@libp2p/websocket

#### Severity:
Medium

#### Description:
Sometimes if I start and close nodes randomly and connect them simultaneously I get a null pointer exception inside the `it-ws` lib. I create a issue for that [here](https://github.com/alanshaw/it-ws/issues/114).  I wonder though if it is something on the libp2p side of things that is triggering this or we have to wait for an update to land to `it-ws` before that. The culprit is that the `@types/ws` are wrong and does not match the actual return types of `ws` lib.
 
#### Steps to reproduce the error:
Don't know yet since this is hard to reproduce accuretly

**Comment by achingbrain** [comment]
https://github.com/alanshaw/it-ws/pull/118 has shipped so this should be fixed now, please re-open if you're still seeing problems.
