### ISSUE TITLE
Exported subpaths of @libp2p/crypto

### ISSUE THREAD

**Issue by 0xmemorygrinder** [libp2p/js-libp2p#2637]
- **Version**:

4.1.6

- **Platform**:

Mac OS latest version + linux (docker) in github codespace, both in node.js

- **Subsystem**:

Crypto package

#### Severity:

Hesitate between high and medium, depending on the scope

#### Description:
When installing the package `@libp2p/crypto` in my (nestjs) project, I cannot import any of the package exports so I am unable to use the functions.
I get the following error at runtime : 
```Error: Package subpath './keys' is not defined by "exports" in ...```
But if I go in the package.json, it is well exported. I note, however, that there is no `main` field in the package.json wich disable the "root" usage (without subpath after the package name)

I first though that my configuration was broken in my codebase so I created another project, simple typescript index.ts setup this time and I get the same error. I get exactly the same issue in a codespace too (so it doesn't seem to come from my machine).

How can I use this package in a node.js project ?

#### Steps to reproduce the error:

- Create a basic typescript project with only a package.json, tsconfig.json and a index.ts file
- Install @libp2p/crypto package using your package manager
- Put this content in the index.ts :
```typescript
import { generateKeyPair } from "@libp2p/crypto/keys";

const kpr = generateKeyPair('Ed25519');

console.log(kpr)
```
- Compile and run the project

**Comment by tabcat** [comment]
This is likely the result of 'require' being used instead of 'import' by the compiled typescript.

https://nodejs.org/api/packages.html#conditional-exports

**Comment by 0xmemorygrinder** [comment]
> This is likely the result of 'require' being used instead of 'import' by the compiled typescript.
> 
> https://nodejs.org/api/packages.html#conditional-exports

@tabcat The import is there : https://github.com/libp2p/js-libp2p/blob/a82ff82211f187e6ad6eef2f73e3221f6fc7b444/packages/crypto/package.json#L60

**Comment by achingbrain** [comment]
Can you post your `tsconfig.json` please?  You may be compiling to CJS instead of ESM.  Otherwise can you please share a link to your project?

**Comment by 0xmemorygrinder** [comment]
@achingbrain I am indeed compiling to CJS but I cannot change this (changing to ESM break everything in nestjs app) Is it possible to add require exports instead ? I am sure I am not the only one with this case.

**Comment by achingbrain** [comment]
This is an ESM-only module so adding `require` exports will not work, since they'd be pointing to ESM files.

There's an example of [how to use Helia with nestjs](https://github.com/ipfs-examples/helia-nestjs) - it uses libp2p so has all the config you need to get it working.

The other option you have is using [dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) to load ESM, though you'll need to make sure your transpiler doesn't change `import('libp2p')` into `require('libp2p')`.

**Comment by 0xmemorygrinder** [comment]
I'll check that, thank you for all your quick answers
