### ISSUE TITLE
discovery mechanism in the example can't show discovery mechanism.. it itself cannot discover

### ISSUE THREAD

**Issue by gitGksgk** [libp2p/js-libp2p#264]
- **Version**: 0.23.1
- **Platform**: win10
- **Subsystem**: unkown

#### Description:  
O' I've no idea how to make this work, but the discovery mechanism example isn't really discovering. there're two mechanisms in the example. 
    1.js uses bootstraper and just keep telling "discovered sth", which after comparison, is sth already in the bootstraper' s list. 
    2.js uses MDNS, spawns two nodes and discovers each other over and over again even after connected to another node. the third node is a ipfs node which has already have discovered machines in a private network.

#### Steps to reproduce the error:
1. download and npm install. navigate to example dir -> discovery mechanism 
2. node 1.js or 2.js as written in readme.md
3. `node 1.js` will print a lot of CIDs discovered. compare them to the bootstraper list in 1.js
4. `node 2.js` just print two node's CID over and over again
5. connect them to a go-ipfs node which has already connected to many nodes in private net, use node.dial and listen at node.on(peer:connect) to prove successful connection.
6. repeat 3, 4 . See nothing new...

Here's the `ipfs swarm peers` list in that go-ipfs node.
```
/ip4/139.23.21.110/tcp/4001/ipfs/QmXMpFhVzWBydEeTVxR2cXz56sy6GL7D8uHq9r235Zzes7
/ip4/132.16.1.155/tcp/4001/ipfs/QmchNvc8pzooE951zE5fZLZ7MU6MH9dJH4MjrfbHu3ADR6
/ip4/132.16.1.159/tcp/4001/ipfs/QmTJq4XGuz3Uf4jAEAgB26wD6sjvHfqRqXBA8E8DMGydGe
/ip4/132.16.1.161/tcp/64727/ws/ipfs/QmWDpzVrFgThzJnf9Y1XT4bkgeKibH22BbX1fqK6Vzyc
ch
/ip4/132.16.1.170/tcp/4001/ipfs/QmYV8tMHxzymR1NNRhfUxvWtHou3YHExd6AZt5tdMcH9Wa
/ip4/132.16.1.170/tcp/9999/ws/ipfs/QmT4VwzboofohmQoSCC3qWiF9yKB2tiwi8vTTD7Y5uXW8
s
/ip4/132.16.1.188/tcp/4001/ipfs/QmW99tybNzTrrj5SC8JSEWxB7L1H6CSCY8n4XgpQijPERe
/ip4/132.16.1.197/tcp/34364/ws/ipfs/QmdnQzHDzfehAb2KpRg5vzNYSScwbyZm5QihLiK9g2YG
25
/ip4/132.16.1.225/tcp/4001/ipfs/QmctJZHM6zogj77QHaGgfD4rY3BdnvXTEBbovVpj3XiVHL
```
using pnet for private net protector.

**Comment by gitGksgk** [comment]
tried remove private part and switch to public net, set up two nodes connected to each other. Then use `node 1.js` and tried to connect to them. same behavior. connection to one of the two node is successful but cannot discover the other.

**Comment by jacobheun** [comment]
Is there something specific you're trying to do, I'm not really clear on what your goal is? Are you trying to setup discovery for a private network?

In regards to the example, it's working as intended. The two discovery libraries being used are `libp2p-bootstrap` and `libp2p-mdns`.

`libp2p-bootstrap` just takes a list of multiaddrs and converts them into `PeerInfo` which is emitted as discovery, so they can then be dialed by the node. It doesn't do anything beyond that, so just seeing the bootstrap addresses is expected. You could simply dial all the bootstrap addresses when your node starts as an alternative approach, but you'd end up with both startup and discovery dial logic. `libp2p-bootstrap` is used to keep everything in the discovery dial flow; discover a peer, decide whether or not to dial, then take that action.

`libp2p-mdns` currently polls for peers on interval. Every peer it knows about is emitted. This logic will likely change in the future as we make that module more performant and conform to mdns standards, but that's how it behaves today. Your node needs to handle the logic of what to do on peer discovery. Depending on the peer discovery mechanism you use, it's likely you'll discover peers you already know about and are possibly connected to, so you should handle that logic as appropriate for you application.

**Comment by gitGksgk** [comment]
@jacobheun  thanks for your reply. Yes I'm setting up discovery in browser node for a private network, during which I find that js-ipfs's discovery seems not to functioning correctly. The expected result is, when node A connected to node B in a private net, node A automatically discovers and connects to other nodes "known" by node B.

**Comment by jacobheun** [comment]
@gitGksgk DHT will be a good route to go for now. There are some other things in progress that will help mitigate the need for dht in the browser in the future, such as leverage delegated routing from the browser to a go-ipfs node https://github.com/libp2p/js-libp2p/blob/master/examples/delegated-routing/src/libp2p-bundle.js (go still needs to release support for this).  There is also a rendezvous spec in progress that will help with discovery without the dht https://github.com/libp2p/specs/pull/56/files.

For setting up the DHT you can check out the custom libp2p example in the js-ipfs repo.(https://github.com/ipfs/js-ipfs/blob/master/examples/custom-libp2p/index.js#L93) . You likely won't need everything that's enabled in the libp2p bundle there, but it should help get you running.

**Comment by gitGksgk** [comment]
@jacobheun thanks for your guide! it helps a lot. I tried to dig into these examples. However, both rendezvous and delegated-routing requires setting up sth besides the two nodes willing to connect each other..  sth like "connect agent"...

**Comment by gitGksgk** [comment]
successfully get browser node discover other peers. closing~
