### ISSUE TITLE
Can libp2p.dial be used to send arbitrary messages?

### ISSUE THREAD

**Issue by klueq** [libp2p/js-libp2p#267]
Is it possible to use this API to send arbitrary messages to a chosen peer id?

**Comment by jacobheun** [comment]
In order to send/receive messages the libp2p nodes need to use a specific protocol. This allows them each to register a handler for that protocol so they know how to process the messages. In that chat example, https://github.com/libp2p/js-libp2p/blob/master/examples/chat/src/listener.js#L30, the handler is for text.  You can make the handler do anything for your specific protocol, including the handling of arbitrary messages, but a protocol is needed to perform communication.

Is there something more specific you're trying to do that we can help with?

**Comment by klueq** [comment]
I want to implement a basic idea of a "distributed shared folder" where each user keeps a copy, maybe partial, of the folder and they sync the list of files between each other. In more detail:

https://github.com/klueq/shared-folder-ipfs/blob/master/docs/sync.md

The chat example looks very promising. How efficient is this mechanism compared to sending a UDP message, if we could do that in JS? For example, if two nodes want to sync their lists of files and they need to exchange with 20 messages, how much time will it take?

**Comment by klueq** [comment]
How do I connect to a peer by its id?

```js
  let peer = 'QmXcBNGp2SBzbogsbEnHxdrokw6te9y2RU9rKYD1sQc1km';
  ipfs._libp2pNode.dialProtocol(peer, '/chat/1.0.0' (...args) => {
    console.log(...args);
  });
```

It returns a `Error: multiaddr "QmXcBNGp2SBzbogsbEnHxdrokw6te9y2RU9rKYD1sQc1km" must start with a "/"`.

**Comment by klueq** [comment]
I've figured out this part: the `peer` argument needs to be one of the values from `libp2p.peerInfo.multiaddrs.toArray()` on the remote peer.

Now I'm trying to send a message thru this esoteric `Connection` object. It doesn't seem to have a simple `send` method, but is rather meant to be used within the pull/pushable/stream/etc. wizardry. Is there a way to avoid all that setup and just send a message?

It looks like the pull/pushable stuff is an attempt to mimic the stream `>>` and `<<` operators from C++.

**Comment by klueq** [comment]
How can I get a `PeerInfo` object for a peer id that I got over email, for instance? I'd need to do a lookup with `ipfs dht findpeers <peed-id>`, right?

I understand that the p2p send/recv API isn't public and can change at any moment. But for the lack of other options, I'd rather use the undocumented API than try to set up by own WebRTC DataChannel, which would involve complicated signaling, ICE/NAT/STUN/TURN mess and so on.

**Comment by jacobheun** [comment]
Yes, if you have just the peer id string you'd need to query the dht. `ipfs dht findpeer` will query the libp2p peer routers. If someone sends you their addresses from `ipfs id` then you could dial those directly.

You really dont need to mess with the internals to do straight sends, but right now a simple method would require creating a custom node with some helper methods and your custom protocol handlers.  If you want to extend libp2p to do that within js-ipfs, you could extend the libp2p class then use that custom libp2p within js-ipfs https://github.com/ipfs/js-ipfs/tree/master/examples/custom-libp2p.

**Comment by achingbrain** [comment]
Closing due to staleness.  Please ask further "how do I"-type questions on https://discuss.libp2p.io/
