### ISSUE TITLE
Update reference to wss0.bootstrap.libp2p.io to be node0.preload.ipfs.io

### ISSUE THREAD

**Issue by klueq** [libp2p/js-libp2p#268]
I'm getting "invalid cert" errors in the console:

```
WebSocket connection to 'wss://wss0.bootstrap.libp2p.io/' failed:
Error in connection establishment: net::ERR_CERT_COMMON_NAME_INVALID
```

https://websocket.org/echo.html also says that wss0.bootstrap.libp2p.io doesn't work.

However js-ipfs connects to the ipfs network and can download a file.

See a small demo at https://klueq.github.io

**Comment by jacobheun** [comment]
Yes, it's been changed to wss://node0.preload.ipfs.io. Both point to the same node, however the certificate is only valid for node0.preload.ipfs.io, so the connection fails for the old url.

The reference to this needs to get removed from the repo, I think it's only in the browser example at the moment.

**Comment by sriharrsha** [comment]
I'm on 0.33.1 

![error](https://user-images.githubusercontent.com/5179687/50440217-c8f5c500-08ba-11e9-8abc-d5de7f41fe9d.png)

Never used wss1 or wss0 but somewhere the dependency libraries are hardcoded calling these servers.

Any Help?

**Comment by achingbrain** [comment]
Closed as complete, please open a new issue if the problem persists.
