### ISSUE TITLE
The documentation is total shit

### ISSUE THREAD

**Issue by a1003584293** [libp2p/js-libp2p#2703]
I don't know which expert wrote your documentation, I spent a day studying your documentation and example code, the result of the documentation is very fragmented, write a little useful here, write a little useful there, not coherent at all, complete shit. 

Not only that, but even the example code only realizes the function of the client connecting to the server, and does not realize how to peer to peer connection after two peers connect to the server. 

Even the api documentation does not fully show all apis. If you can't write documentation, check out the peer-js, vue, antd, and react api documentation. 

I know a lot of people have made great contributions to this project, but why is the documentation so rubbish and unsightly

**Comment by a1003584293** [comment]
I think this is also why, such a good project, the contribution of so many people, but the number of downloads is so small, because the documentation is shit

**Comment by p-shahi** [comment]
@a1003584293 there is absolutely no reason to be so rude and use this sort of language. Be respectful.
You clearly have constructive feedback on how docs can improve but to resort to using foul language distracts from your constructive feedback, violates the [contributor code of conduct](https://github.com/libp2p/js-libp2p?tab=coc-ov-file), and does not create an environment where maintainers and you can have a honest discussion in good faith. Do better next, here and elsewhere when you're communicating your frustrations. If you have ideas on how docs and examples can be improved for beginners, make a separate issue and list them out. You are also free to open pull requests. I'm closing this issue.
