### ISSUE TITLE
chore: export error codes from subpackages

### ISSUE THREAD

**Issue by SgtPooki** [libp2p/js-libp2p#2704]
### Discussed in https://github.com/libp2p/js-libp2p/discussions/2669

<div type='discussions-op-text'>

<sup>Originally posted by **mkermani144** August 18, 2024</sup>
There are numerous error codes available in `libp2p` package, in `packages/libp2p/src/errors.ts`. Is there a reason these error code are not exported neither in the `interface` package, nor in the `libp2p` package itself?  
Currently there is no way to check caught error type against these codes other than duplicating the needed ones inside codebases using libp2p.  
I also know that these codes are [going to be refactored to error names](https://github.com/libp2p/js-libp2p/issues/2634) in the future, but it doesn't make any difference. When the refactor occurs, the names should be exported the same way.</div>

**Comment by mkermani144** [comment]
The discussion has two new comments, I think we may close this one as a result.

**Comment by wemeetagain** [comment]
Thanks, closing
