### ISSUE TITLE
Make error parameter of `stream.abort` optional

### ISSUE THREAD

**Issue by mkermani144** [libp2p/js-libp2p#2716]
https://github.com/libp2p/js-libp2p/blob/abc7e66f76bb2564aaea1eedc9dc7d172fc1498b/packages/interface/src/connection/index.ts#L128-L131

It's stated that source will throw if error is passed, and will return otherwise. But the parameter is not optional, and it's not possible not to pass an error to `abort`.

**Comment by achingbrain** [comment]
That's a mistake in the docs.  If you want to close a connection gracefully (e.g. wait for all data to be sent), call `conn.close()`, if you want to close immediately, call `conn.abort(err)` and pass the reason.

In the future that error will get [turned into an error code](https://github.com/libp2p/specs/issues/479) and sent to the remote peer so they know what went wrong.

**Comment by mkermani144** [comment]
Cool, maybe we can fix the doc in the future.
