### ISSUE TITLE
Equivalent of `ipfs dht findprovs`?

### ISSUE THREAD

**Issue by klueq** [libp2p/js-libp2p#272]
How can I find providers of a certain file by its CID? In go-ipfs I can do something like this:

```
$ ipfs dht findprovs QmeomffUNfmQy76CQGy9NdmqEnnHU9soCexBnGU3ezPHVH
QmRoTJFngpJxWcYVFxR7zw9CCv8sMNmtSKNQ63cxBBNDE5
QmREdUzUz8Xe4CemvijdJo5Tfu7U8rZobetYL1QU6JAwCA
QmRJgS7y7eRyKk5xndo8LZwWZexPaTP1xPqnHUU1KWp8hd
```

**Comment by diasdavid** [comment]
@klueq that would be the contentRouting.findProviders call, see this example: https://github.com/libp2p/js-libp2p/tree/master/examples/peer-and-content-routing#2-using-content-routing-to-find-providers-of-content
