### ISSUE TITLE
Uncaught ECONNRESET somewhere in our code base

### ISSUE THREAD

**Issue by TimDaub** [libp2p/js-libp2p#2744]
Hi,

a node operator on Kiwi News always reports the following error:

![2024-10-02 10 45 21](https://github.com/user-attachments/assets/2db4216e-7046-4238-a25f-66b483692291)

We don't know where this is coming from, but we think it is libp2p. Before opening an issue, I asked in the libp2p TG if someone could help us find the cause of this, but it was suggested that I open an issue: https://t.me/c/2109810685/11/818

- **Version**: We use libp2p v0.40.0 https://github.com/attestate/kiwistand/blob/41aa70347eb8786f1cefa6746aa700a563c053c1/package.json#L83 we don't really have budget to upgrade this ATM

- **Platform**: Ubuntu

- **Subsystem**: I'm not sure. But we use a variety of libp2p packages where this could originate from, see this part of the package.json: https://github.com/attestate/kiwistand/blob/41aa70347eb8786f1cefa6746aa700a563c053c1/package.json#L47-L55

**Comment by 2color** [comment]
Version 0.40.0 of js-libp2p is around 2 years old. Since then there have been some significant changes and fixes to js-libp2p including some fixed memory leaks. 

One thing you could try is enabling more verbose logging from libp2p by setting the `DEBUG` env var to `*,*:debug` to get everything and then narrow down.

**Comment by achingbrain** [comment]
I would strong advise upgrading to the latest libp2p, we simply do not have the capacity to support older versions.

There are [detailed migration guides](https://github.com/libp2p/js-libp2p/tree/main/doc/migrations) to make this as painless as possible.

The TCP transport has had several changes made to it in recent releases which make it more resilient, improves error handling and fixes a number of memory leaks.

Please upgrade and report back if this is still happening.
