### ISSUE TITLE
pubsub: how to protect from flooding (single origin)

### ISSUE THREAD

**Issue by pgte** [libp2p/js-libp2p#276]
(I'm posting this here because I think that, even though flooding in the current implementation of floodsub is more serious, I'm wondering whether pubsub protections should generally exist for pubsub.)

Is there any protection in place against one node (maliciously or due to a bug) flooding other peers with messages?

In the case of the app I'm describing, a simple protection could be something along these lines:

For a given topic, be able to define the maximum frequency with which we're accepting a message from a single origin.

Thoughts?

**Comment by achingbrain** [comment]
Gossipsub has much better protection against misbehaving peers and bad actors on the network.  Floodsub should not be used as it does not have these things.

For interested readers, see the [Gossipsub spec](https://github.com/libp2p/specs/tree/master/pubsub/gossipsub).
