### ISSUE TITLE
Access to fetch at node0.preload.ipfs.io has been blocked by CORS policy

### ISSUE THREAD

**Issue by klueq** [libp2p/js-libp2p#277]
`ipfs.version: 0.33.0`

Access to fetch at 'https://node0.preload.ipfs.io/api/v0/refs?r=true&arg=QmXXtHtDwXFbCTzMDjacZxid6CCNY4m5oM6MgBhyPVT3Tr' from origin 'https://klueq.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by jacobheun** [comment]
The preload nodes and api calls are specific to IPFS and don't leverage libp2p. Closing this, feel free to open the issue with IPFS.

**Comment by alanshaw** [comment]
You can track this here https://github.com/ipfs/infrastructure/issues/447
