### ISSUE TITLE
`peerIdFromString` doesn't accept CID encoded PeerIDs

### ISSUE THREAD

**Issue by 2color** [libp2p/js-libp2p#2772]
### Description

Since https://github.com/libp2p/js-libp2p/pull/2660, an undocumented breaking change was introduced, whereby the `peerIdFromString` function in `@libp2p/peer-id` throws an error when a base36 encoded PeerID CID is passed.

This can be attributed specifically to https://github.com/libp2p/js-libp2p/pull/2660/files#diff-03404c4c2b9d68fdd3cc5903cbdc0958a10b3a89c8070f1b498e60492fe6a20dL264.

There are to parts to this problem:
1. The default composed decoders for from multiformats have been removed. 
2. Even when a base36 decoder is passed in, the function throws for base36 encoded PeerID CIDs, since it attempts to parse it as a multihash (rather than a CID)

The older version would first try to decode the binary digest as a multihash and if that fails, attempt to decode it as a CID:

https://github.com/libp2p/js-libp2p/blob/e42da78f34af8f610a6804785100f0fe7f79d7fb/packages/peer-id/src/index.ts#L264-L303

### Proposed solutions & suggestions

1. Update the [example](https://github.com/libp2p/js-libp2p/blob/c5bbb2596273d2503e1996169bab2411546fe674/packages/peer-id/src/index.ts#L10) to be working
2. Update the function to handle CIDs

**Comment by achingbrain** [comment]
Ah, that's interesting.  Where this function is used in the libp2p codebase, the string that's being decoded is a always a multibase encoded multihash, not a CID.

Do you have a situation where the strings you have might be CIDs or might be multibase encoded multihashes?

**Comment by 2color** [comment]
> Do you have a situation where the strings you have might be CIDs or might be multibase encoded multihashes?

This is where this popped up: 
https://github.com/ipfs/helia-verified-fetch/blob/aede17f0a0941722f6b1d2bc3582551592d33f40/packages/verified-fetch/src/utils/parse-url-string.ts#L180

But it's also in the example: https://github.com/libp2p/js-libp2p/blob/c5bbb2596273d2503e1996169bab2411546fe674/packages/peer-id/src/index.ts#L10

**Comment by achingbrain** [comment]
IPNS is a bit wonky like that, the [spec for the value field](https://specs.ipfs.tech/ipns/ipns-record/#value-bytes) is very loose.

The question here is, do we want to push that complexity down to the libp2p level or can we contain it somewhere IPNS-related?

One of the goals of #2660 was to reduce the complexity and guesswork in the `peerIdFromXXX` methods - trying to be explicit in what `XXX` is (for example, replacing `...FromBytes` with `...FromMultihash`, `...FromPublicKey`, `...FromCID`, etc) - perhaps it didn't go far enough with `...FromString`.

> it's also in the example

Yes, I think this is a symptom of the problem - when you're dealing with opaque strings, the compiler cannot help you.

**Comment by 2color** [comment]
> The question here is, do we want to push that complexity down to the libp2p level 

Probably not. But we should update the upgrade guide to account for this breaking change.
