### ISSUE TITLE
Error: peer type not recognized

### ISSUE THREAD

**Issue by alanshaw** [libp2p/js-libp2p#280]
Seen here: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs/detail/PR-1704/3/pipeline/55

```console
  1) circuit relay
       A <-> R <-> B
         should connect:
     Error: peer type not recognized
      at setImmediate (node_modules/libp2p/src/get-peer-info.js:51:42)
      at Immediate._onImmediate (node_modules/async/internal/setImmediate.js:27:16)
      at process.topLevelDomainCallback (domain.js:121:23)
```

**Comment by jacobheun** [comment]
That is one heck of a call stack! I'm not sure what's happening but my best guess is somehow the address filtering is returning undefined as the address cannot be found. If we attempt to dial with undefined it would return that error.

I'm working on an update to that circuit relay test in js-ipfs, the test is wrong. I'm also looking at improving `get-peer-info` to be more helpful with error responses.

**Comment by vasco-santos** [comment]
With the latest refactor, we don't have the `get-peer-info` anymore. As this should not be a problem anymore, I am closing it.
