### ISSUE TITLE
Errors connecting to WebRTC-direct multiaddrs

### ISSUE THREAD

**Issue by 2color** [libp2p/js-libp2p#2805]
## Description

Problems connecting to public peers with WebRTC-direct in Chrome, Firefox, and Safari. I tried with known peers such as the public bootstrappers and still got errors. Both 

In Chrome, the error I get is:

```
WebRTC transport error: [stream: data] data channel error: Data channel was never opened: state: connecting
```

In Firefox:

```
libp2p:connection-manager:dial-queue:error dial failed to /ip4/147.28.186.157/udp/9095/webrtc-direct/certhash/uEiAPnDhaUxscuBMco2KQMGUxtpGZin9vP7UV2S6KJMtShA/p2p/12D3KooWFhXabKDwALpzqMbto94sB7rvmZ6M28hs9Y9xSopDKwQr +0ms WebRTC/DataChannelError: WebRTC transport error: [stream: data] data channel error: Data channel was never opened: state: connecting
```

Safari:

```
WebRTC/DataChannelError: WebRTC transport error: [stream: data] data channel error: Data channel was never opened: state: connecting
```

## Specific multiaddrs with problems

```
// ([go-libp2p universal-connectivity peer](https://github.com/libp2p/universal-connectivity/tree/main/go-peer))
/ip4/147.28.186.157/udp/9095/webrtc-direct/certhash/uEiAPnDhaUxscuBMco2KQMGUxtpGZin9vP7UV2S6KJMtShA/p2p/12D3KooWFhXabKDwALpzqMbto94sB7rvmZ6M28hs9Y9xSopDKwQr 

// (Kubo bootstrapper)
/ip4/147.75.87.27/udp/4001/webrtc-direct/certhash/uEiCrpessP8HCV-35Z4PrH8GByhOCHGZ5KNRDkU5xgsoE2g/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb 

// (Rust bootstrapper)
/ip4/139.178.91.71/udp/4001/webrtc-direct/certhash/uEiCob71FRmYEoCvDCnsMS1g-Za67dM4Q7tjpK9QTf59_YQ/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN 
```
#### Steps to reproduce the error

- Run [this branch of helia-identify](https://github.com/ipfs-shipyard/www-helia-identify/tree/dont-dial-anyone-by-default) locally alternatively, open the [universal connectivity app](https://universal-connectivity.on.fleek.co/)
- Try to connect to the multiaddrs above

**Comment by 2color** [comment]
Interop tests are passing for WebRTC-direct between go-libp2p and Chrome:
https://github.com/libp2p/test-plans/actions/runs/11470308248/job/31919229144#step:3:2470

I was also able to successfully open a connection to a localhost webrtc-peer (https://github.com/libp2p/universal-connectivity/tree/main/go-peer)

**Comment by 2color** [comment]
Related: https://github.com/libp2p/go-libp2p/pull/3040/

**Comment by achingbrain** [comment]
Fixed in https://github.com/libp2p/go-libp2p/releases/tag/v0.37.1
