### ISSUE TITLE
QUIC in JS for libp2p

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p#287]
Found out today thanks to @sericaia that there is already a QUIC implementation for Node.js made by @fidm

- https://www.npmjs.com/package/quic
- https://github.com/fidm/quic

Super cool! We should try it out and see if it is interoperable with @marten-seemann go-quic impl and use it in libp2p :)

**Comment by jacobheun** [comment]
There is also some discussion around implementing QUIC as a native node module, https://github.com/nodejs/node/issues/23064, potentially starting early next year.

**Comment by sericaia** [comment]
There's also this one https://github.com/rmarx/quicker/tree/draft-15 that is worth taking a look (note that it uses an old Node version)

**Comment by p-shahi** [comment]
closing in favor of https://github.com/libp2p/js-libp2p/issues/1459
