### ISSUE TITLE
add awaitStart() to API

### ISSUE THREAD

**Issue by dirkmc** [libp2p/js-libp2p#290]
I often find myself writing code like this:
```Javascript
function awaitLibp2pStart() {
  return new Promise(resolve => libp2p.isStarted() ? resolve() : libp2p.once('start', resolve))
}

async function doSomething() {
  await awaitLibp2p2Start()
  libp2p.dial(...)
}
```
It would be nice if this were part of the API instead (same goes for js-ipfs)

**Comment by pgte** [comment]
Suggestion:
We could take advantage of allowing idempotent starts like this:

```js
await libp2pNode.start() // ok
await libp2pNode.start() // also ok, returns immediately
```

Example of implementing this in peer-star:
https://github.com/ipfs-shipyard/peer-star-app/blob/master/src/app.js#L26-L70

**Comment by jacobheun** [comment]
The latest libp2p state machine additions (0.24.0) include idempotent starting and stopping, so you can just do:
```js
function awaitLibp2pStart() {
  return new Promise(resolve => libp2p.start(resolve))
}
```

We're looking at the async/await API changes as part of the [async iterator initiative](https://github.com/libp2p/js-libp2p/issues/266).

This would result in an api like @pgte [mentions above](https://github.com/libp2p/js-libp2p/issues/290#issuecomment-443730269).

For async code I've been extending libp2p to test out possible api changes:
```js
class AsyncLibp2p extends Libp2p {
  start () {
    return new Promise((resolve, reject) => {
      super.start((err) => {
        if (err) return reject(err)
        resolve()
      })
    })
  }
  // ...
}
```

If it's being used in conjunction with IPFS it would need to handle fallback support for the callback.

**Comment by vasco-santos** [comment]
We switched to `async await` now, and it is possible to just do `await libp2p.start()`. So, I am closing this issue
