### ISSUE TITLE
Awesome Endeavor: Libp2p Core Documentation

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#308]
One of our goals for this quarter, is to audit the libp2p core modules and ensure the docs and examples are up to date and that they exist; [Q1 2019 OKR](https://docs.google.com/spreadsheets/d/11GKG1DBRIIAiQnHvLD7_IqWxDGsVdaZFpxJM6NWtXe8/edit#gid=1271182838).

The following table will be used to track the status of documentation across the core modules of libp2p. Some modules may have adequate examples and the README may already be up to date, but this will allow us to appropriately audit those. If examples do exist, they should be audited for correctness, and we should ensure they are running properly.

Note, some of the packages below may be very low priority, due to either pending deprecation or the module is not yet released.

All contributions are welcome! Let us know if you have questions, and fill free to claim a module by commenting :)

* 🍎= Not started
* 🍋= Very low priority
* 🍊= In progress
* 🍏= Complete

| Status | Package | Owner |
| ---------|---------|--------- |
| 🍊| [`js-libp2p-interfaces`](https://github.com/libp2p/js-libp2p-interfaces) |  |
| 🍊| [`js-libp2p`](//github.com/libp2p/js-libp2p) | |
| 🍅| [`js-libp2p-bootstrap`](//github.com/libp2p/js-libp2p-bootstrap) | |
| 🍅| [`js-libp2p-crypto`](//github.com/libp2p/js-libp2p-crypto) | |
| 🍅| [`js-libp2p-crypto-secp256k1`](//github.com/libp2p/js-libp2p-crypto-secp256k1) | |
| 🍅| [`js-libp2p-delegated-content-routing`](//github.com/libp2p/js-libp2p-delegated-content-routing) | |
| 🍅| [`js-libp2p-delegated-peer-routing`](//github.com/libp2p/js-libp2p-delegated-peer-routing) | |
| 🍅| [`js-libp2p-floodsub`](//github.com/libp2p/js-libp2p-floodsub) | |
| 🍅| [`js-libp2p-kad-dht`](//github.com/libp2p/js-libp2p-kad-dht) | |
| 🍅| [`js-libp2p-mdns`](//github.com/libp2p/js-libp2p-mdns) | |
| 🍅| [`js-libp2p-mplex`](//github.com/libp2p/js-libp2p-mplex) | |
| 🍅| [`js-libp2p-record`](//github.com/libp2p/js-libp2p-record) | |
| 🍊| [`js-libp2p-rendezvous`](//github.com/libp2p/js-libp2p-rendezvous) | |
| 🍅| [`js-libp2p-tcp`](//github.com/libp2p/js-libp2p-tcp) | |
| 🍋| [`js-libp2p-webrtc-star`](//github.com/libp2p/js-libp2p-webrtc-star) | |
| 🍋| [`js-libp2p-webrtc-direct`](//github.com/libp2p/js-libp2p-webrtc-direct) | |
| 🍋| [`js-libp2p-websockets`](//github.com/libp2p/js-libp2p-websockets) | |
| 🍅| [`js-peer-id`](//github.com/libp2p/js-peer-id) | |

**Comment by jacobheun** [comment]
Module: **js-libp2p**
Related Issues: https://github.com/libp2p/js-libp2p/issues/231, https://github.com/libp2p/js-libp2p/issues/237, https://github.com/libp2p/js-libp2p/issues/350

For js-libp2p we need to audit, improve and standardize on our language. Once we've done that we should ensure, as a part of this effort, that the other libp2p modules conform to that.

**Comment by vasco-santos** [comment]
We should revisit this issue after the next release, as things are now much better :D

**Comment by maschad** [comment]
Closing due to staleness
