### ISSUE TITLE
Use KadTools instead of reimplementing Kademlia?

### ISSUE THREAD

**Issue by prestwich** [libp2p/js-libp2p#31]
KadTools is very mature, and used by at least one production system. It includes several useful additions like basic Pub/sub and NAT traversal strategies.

https://github.com/kadtools

**Comment by diasdavid** [comment]
Interesting, thank you for pointing to this, will investigate :)

**Comment by sigma67** [comment]
fyi, this project has migrated to https://gitlab.com/deadcanaries/kadence

**Comment by achingbrain** [comment]
This looks like a closed project now and we have https://github.com/libp2p/js-libp2p-kad-dht so there's nothing left to do here.
