### ISSUE TITLE
[WIP] First use: feedback

### ISSUE THREAD

**Issue by mikeal** [libp2p/js-libp2p#314]
I’m diving into libp2p for a quick side project and I’m going to write notes up as I go in order to provide some usability feedback.

1. Getting a node up and running requires quite a lot of boiler. Luckily I already wrote 
https://github.com/mikeal/libp2p-simple
2. All the API’s only take callbacks so I’m going to end up wrapping a lot of promises around instance methods which are a little annoying to bind :(
3. After I start the node it doesn’t keep the node process alive. Even after I provide something to content discovery, the process exits without staying open :(

I’ll keep adding to this thread as I work through more of the API.

**Comment by mikeal** [comment]
4. Unlike most JS API’s the options object of libp2p.contentRouting.findProviders is not actually optional, so if you don’t send at least an empy object as the second argument you get an error.
5. The following code produces an error about the DHT. It’s not clear how to resolve this error.

```javascript
const libp2p = require('libp2p-simple')

let node = libp2p()

node.start(() => {
  node.contentRouting.provide(Buffer.from('test'), () => {
    console.log('testing')
    node.contentRouting.findProviders(Buffer.from('test'), {}, (...args) => {
      console.log(args)
    })
  })
})
```

produces this error:

```
testing
[ Error: DHT is not available
      at Object.findProviders (/root/dropup-cli/node_modules/libp2p/src/content-routing.js:7:25)
      at node.contentRouting.provide (/root/dropup-cli/index.js:10:25)
      at Object.provide (/root/dropup-cli/node_modules/libp2p/src/content-routing.js:14:16)
      at node.start (/root/dropup-cli/index.js:8:23)
      at /root/dropup-cli/node_modules/async/internal/parallel.js:39:9
      at /root/dropup-cli/node_modules/async/internal/once.js:12:16
      at replenish (/root/dropup-cli/node_modules/async/internal/eachOfLimit.js:61:25)
      at iterateeCallback (/root/dropup-cli/node_modules/async/internal/eachOfLimit.js:50:17)
      at /root/dropup-cli/node_modules/async/internal/onlyOnce.js:12:16
      at /root/dropup-cli/node_modules/async/internal/parallel.js:36:13 ]
```

**Comment by mikeal** [comment]
BTW, `libp2p-simple` is using this libp2p configuration 
https://github.com/ipfs/js-ipfs/blob/master/src/core/runtime/libp2p-nodejs.js

**Comment by jacobheun** [comment]
This is very helpful feedback, thanks for documenting this as you go! I will take a look at these as they come in and create tickets for the individual issues.

**Comment by jacobheun** [comment]
> 3\. After I start the node it doesn’t keep the node process alive. Even after I provide something to content discovery, the process exits without staying open :(

@mikeal are you adding multiaddrs to the peerInfo before starting libp2p? I'm thinking that perhaps no transports are listening which could cause the process to shutdown.

**Comment by achingbrain** [comment]
This issue is quite stale, the API has been refactored, everything has types now and things like enabling the DHT is a lot more straightforward.

Please reopen with feedback on the current version.
