### ISSUE TITLE
make actionable error messaging when DHT not enabled

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#320]
If no content/peer router is running, such as the DHT, and a user attempts to make a content or peer routing request the error is not particularly helpful as detailed at https://github.com/libp2p/js-libp2p/issues/314#issuecomment-458802548. 

For errors like this, where the system needs to be added/started via configuration, we should add an actionable message to the error to allow the user to better fix the problem. In the error linked above, this could be a link to the DHT configuration section of the readme.

cc: @vasco-santos

**Comment by vasco-santos** [comment]
Having a reference to the `README` seems a cool idea!

**Comment by maschad** [comment]
Closing as this is no longer relevant, we now return a more [informative error](https://github.com/libp2p/js-libp2p/blob/91842c93b216a51b65bc79b5248f8e459a646b51/packages/libp2p/src/content-routing/index.ts#L53)
