### ISSUE TITLE
All APIs that accept Buffer should also support ArrayBuffer

### ISSUE THREAD

**Issue by mikeal** [libp2p/js-libp2p#331]
I’m building a pubsub demo on `js-ipfs` and I’m not using a framework or a compiler to try and keep things simple to understand, but I’m currently blocked on this line 
https://github.com/libp2p/js-libp2p/blob/de84ee473c5b095134a20361f0c0a808405083d2/src/pubsub.js#L62

Requiring the Buffer API means that you **must** use a compiler, since Buffer isn’t a browser API and there isn’t a polyfill that works without a compile chain.

IMO, any API that requires a Buffer should also accept an ArrayBuffer and just convert it using the built in polyfill.

**Comment by grassias** [comment]
So up until now all those APIs that make use of Buffer objects are not available for browser builds? Could the use of a lib like https://github.com/feross/buffer be an appropriate solution?

**Comment by achingbrain** [comment]
All APIs now accept `Uint8Array`s so this is complete.
