### ISSUE TITLE
js-ipfs pubsub messaging "works", but not immediately...

### ISSUE THREAD

**Issue by aphelionz** [libp2p/js-libp2p#332]
- **Version**: js-ipfs 0.34 dist
- **Platform**: node.js and browser
- **Subsystem**: pubsub

#### Description:

I'm creating an app where peers need to exchange metadata information upon connecting with each other. I'm thinking pubsub is the right tool for this. The code I've written (summarized below) seems to work intermittently only after minutes of waiting for messages to be received. Is there anything else I can do to expedite the messages?
 
#### Steps to reproduce the error:

At the simplest version, imagine two nodes running this code. When they connect to each other, they _should_ exchange messages, and often do - but it consistently takes a while for it to happen.

```javascript
var node = new IPFS({
  relay: { enabled: true, hop: { enabled: true, active: true } },
  EXPERIMENTAL: { pubsub: true },
});

node.on("ready", async () => {
    this.node.libp2p.on("peer:connect", handlePeerConnected)
    await this.node.pubsub.subscribe(nodeInfo.id, console.log)
}

async handlePeerConnected(peer) {
  const ipfsId = peer.id._idB58String;
  message = this.node.types.Buffer("testing")
  await this.node.pubsub.publish(ipfsId, message)
}
```

**Comment by raulk** [comment]
CC @alanshaw for visibility.

**Comment by aphelionz** [comment]
It looks like I have some luck with adding a setTimeout to `handlePeerConnected`. I don't love this solution as it's still not 100% reliable, but it's better...

```javascript
handlePeerConnected(peer) {
  setTimeout(async () => {
    const ipfsId = peer.id._idB58String;
    message = this.node.types.Buffer("testing")
    await this.node.pubsub.publish(ipfsId, message)
  }, 1000)
}
```

**Comment by aphelionz** [comment]
Even more info! I updated the code once more:

```diff
handlePeerConnected(peer) {
  setTimeout(async () => {
+   console.log(peer.multiaddrs._multiaddrs.forEach(multiaddr => console.log(multiaddr.toString())))
    const ipfsId = peer.id._idB58String;
    message = this.node.types.Buffer("testing")
    await this.node.pubsub.publish(ipfsId, message)
  }, 1000)
}
```

I am testing with a node.js IPFS node and a browser node. If I clear all local storage inside the browser and try to connect to the peer **manually**, that will log something like this. Pubsub _will_ work better, but still not in an acceptably reliable way.

```plain
/ipfs/QmXG8yk8UJjMT6qtE2zSxzz3U7z5jSYRgVWLCUFqAVnByM
/p2p-circuit/ipfs/QmXG8yk8UJjMT6qtE2zSxzz3U7z5jSYRgVWLCUFqAVnByM
```

However, if I refresh the page and run the same code, two things change:

1. The node connects to the peer automatically instead of manually
2. The list of addresses is much longer.

```plain
/p2p-websocket-star/ipfs/QmXG8yk8UJjMT6qtE2zSxzz3U7z5jSYRgVWLCUFqAVnByM
/ip4/127.0.0.1/tcp/4002/ipfs/QmXG8yk8UJjMT6qtE2zSxzz3U7z5jSYRgVWLCUFqAVnByM
/ip4/10.1.10.128/tcp/4002/ipfs/QmXG8yk8UJjMT6qtE2zSxzz3U7z5jSYRgVWLCUFqAVnByM
/ip4/172.17.0.1/tcp/4002/ipfs/QmXG8yk8UJjMT6qtE2zSxzz3U7z5jSYRgVWLCUFqAVnByM
/ip4/127.0.0.1/tcp/4003/ws/ipfs/QmXG8yk8UJjMT6qtE2zSxzz3U7z5jSYRgVWLCUFqAVnByM
/p2p-circuit/ipfs/QmXG8yk8UJjMT6qtE2zSxzz3U7z5jSYRgVWLCUFqAVnByM
/p2p-circuit/p2p-websocket-star/ipfs/QmXG8yk8UJjMT6qtE2zSxzz3U7z5jSYRgVWLCUFqAVnByM
/p2p-circuit/ip4/127.0.0.1/tcp/4002/ipfs/QmXG8yk8UJjMT6qtE2zSxzz3U7z5jSYRgVWLCUFqAVnByM
/p2p-circuit/ip4/10.1.10.128/tcp/4002/ipfs/QmXG8yk8UJjMT6qtE2zSxzz3U7z5jSYRgVWLCUFqAVnByM
/p2p-circuit/ip4/172.17.0.1/tcp/4002/ipfs/QmXG8yk8UJjMT6qtE2zSxzz3U7z5jSYRgVWLCUFqAVnByM
/p2p-circuit/ip4/127.0.0.1/tcp/4003/ws/ipfs/QmXG8yk8UJjMT6qtE2zSxzz3U7z5jSYRgVWLCUFqAVnByM
```

This **works** entirely and has the effect that I'm looking for.

I hope this is helpful and can help provide enough information to at least gain some guidance. I guess what I'd love is for that full list of addresses to be available right off the bat.

**Comment by jacobheun** [comment]
Thanks for the additional info @aphelionz. I'm looking into an issue that I think may be related with how incoming circuit relay peers are handled. I think that's related to what's happening here. The peers discover one another over the circuit relay and connect via it. Then when you refresh, the browser establishes a direct connection with the peer, so you get publishes quickly. 


> I'm creating an app where peers need to exchange metadata information upon connecting with each other.

If your goal is to just exchange metadata when the nodes connect, you may want to go with a more direct approach, such as (untested):

```js
var node = new IPFS({
  relay: { enabled: true, hop: { enabled: true, active: true } },
  EXPERIMENTAL: { pubsub: true },
});

node.on("ready", async () => {
    this.node.libp2p.on("peer:connect", handlePeerConnected)
    this.node.libp2p.handle('/my-metadata-exchange/1.0.0', (protocol, conn) => {
      let message = this.node.types.Buffer("testing too")
      pull(
        pull.values([message]),
        conn,
        pull.collect((values) => {
          console.log('Their metadata', values)
        })
      )
    })
}

handlePeerConnected(peer) {
  this.node.libp2p.dialProtocol(peer, '/my-metadata-exchange/1.0.0', (err, conn) => {
    if (err) return console.error(err)
    
    let message = this.node.types.Buffer("testing")
    pull(
      pull.values([message]),
      conn,
      pull.collect((values) => {
        console.log('Their metadata', values)
      })
    )
  })
}
```

This uses a custom protocol, `/my-metadata-exchange/1.0.0`, to exchange information. As long as both peers have registered that protocol via `.handle`, `libp2p.dialProtocol` will provide a connection that you can execute a pull-stream through. Since the peers are already actually connected, `.dialProtocol` should just give you back a new stream on the existing connection.

**Comment by aphelionz** [comment]
Very cool, thank you! I'll give this a shot. I didn't know about this feature of libp2p.
