### ISSUE TITLE
Finding Peer and content

### ISSUE THREAD

**Issue by hubertokf** [libp2p/js-libp2p#344]
- **Version**: "^0.24.4"
- **Platform**: Linux core-VirtualBox 4.18.0-16-generic #17~18.04.1-Ubuntu SMP Tue Feb 12 13:35:51 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Subsystem**: libp2p-kad-dht ( ^0.14.9 )

#### Description: 
This is my scenario:
Got two distinct Networks, conected by a router. Running on [Core emulator](https://www.nrl.navy.mil/itd/ncs/products/core
) as you can see on this image:
![image](https://user-images.githubusercontent.com/5043263/55084085-5d6eef80-5083-11e9-81f4-85ed4788d3ea.png)

Each host has one node running, where n4 can discover n5 using libp2p-mdns AND n5 can discover n7 using libp2p-bootstrapers.

What i'm trying is to make n4 find n7 using n5, like is saying on [this libp2p example](https://github.com/libp2p/js-libp2p/tree/master/examples/peer-and-content-routing).

Actually, in this example, node1 has access to node3 peerInfo, but in my case I dont have. So once I know n7 ID, I can create peerID manually on n4 using: 
`peerid = PeerId.createFromB58String("<string id from n7>")`
then find peer using:
```
node.peerRouting.findPeer(peerid, (err, peer) => {
                if (err) { throw err }
            
                console.log('Found it, multiaddrs are:')
                peer.multiaddrs.forEach((ma) => console.log(ma.toString()))
            })
```
What happens then is "Error: No peer found". 
![image](https://user-images.githubusercontent.com/5043263/55085371-4d580f80-5085-11e9-8020-1a181f839588.png)
The order of execution is: n7, n5, n4
If you want, the code can be found [here](https://github.com/hubertokf/p2pEXEHDA) on teste1.js (n4), teste2.js (n5) and teste3.js (n7)

I'm using libp2p-rpc from [my fork](https://github.com/hubertokf/libp2p-rpc), where i'm updating this lib to work with newer version of libp2p.

Well, I don't know if i'm making mistakes, or if what i want is actually possible. Thats why i'm asking for help. Maybe you can guide me through this.

EDIT: I've tried using contentRouting.findProviders, but no success aswell.

Thanks

**Comment by hubertokf** [comment]
I bet my problem is on bootstrapers list

**Comment by jacobheun** [comment]
> ok, i can get network-ip, but which port it uses?

TCP will replace the addresses of `node.peerInfo.multiaddrs` when it starts. So if you wait for the node to start you should be able to get a list of its up to date addresses from there.

> How can i define my node addres, I mean: /ip4//tcp//<ipfs ?>/

These are being added via libp2p-rpc, https://github.com/hubertokf/libp2p-rpc/blob/36ac829628e8193d4e7a140fd387e79e438bf4c3/index.js#L73-L74. Once libp2p starts `node.peerInfo.multiaddrs` will have all of your addresses.

You are likely having a connection issue. Either the nodes you need aren't actually connected, or peer discovery is happening before they are.

Libp2p currently doesn't dial to peers it discovers (unless it's actively crawling the DHT), so you will need to add the dial logic on the peer discovery event.

**Comment by wemeetagain** [comment]
Closing stale issue
