### ISSUE TITLE
Typescript: partial declaration files

### ISSUE THREAD

**Issue by IwraStudios** [libp2p/js-libp2p#346]
Hey all,

I've recently been experimenting with libp2p in typescript and have created declaration files for libp2p and some related modules. You are free to use these.
https://gist.github.com/IwraStudios/eecd07e060cf49145a974ec160c775ec

I'm posting this here because this is an incomplete declaration for some modules.

Cheers

**Comment by vasco-santos** [comment]
Closing this as we shipped `libp2p@0.30` with typescript declaration files generated on release.
