### ISSUE TITLE
Dont discover self

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#356]
Original issue: https://github.com/libp2p/js-libp2p-switch/issues/331.

On peer discovery, if the peer happens to be us, we should avoid adding ourselves to the PeerBook and emitting a `peer:discovery` event.

**Comment by mkg20001** [comment]
Additionally maybe log a warning like "WARN: Discovery module $NAME caused this peer to discover itself. This is a bug and should be reported at $URL" (url could be read from package.json, as npmjs.com currently does)
The warning should be shown just once. possibly also print a line to debug log everytime this happens so user knows how frequently this is occurring

**Comment by jacobheun** [comment]
> Additionally maybe log a warning like "WARN: Discovery module $NAME caused this peer to discover itself.

While I think this is valuable I think having the warning code always be present might be unncessary. I think if we log an error we'll at least have the stack trace of where it came from and the frequency it happens.  Additionally I think the right thing to do would be to add self discovery tests to https://github.com/libp2p/interface-peer-discovery (along with the other tests it should have), and get that added to each of the discovery service test suites. @mkg20001 what do you think about that approach?

**Comment by mkg20001** [comment]
@jacobheun Tests sound great, should also be mandatory. About log: Put it in debug log. That should be enough, so developers know it's happening and can report bugs

**Comment by jacobheun** [comment]
> About log: Put it in debug log. 

I added the error to debug for `libp2p:error` in https://github.com/libp2p/js-libp2p/pull/357.

> Tests sound great, should also be mandatory.

I'll create an issue over at interface-discovery to track this.
