### ISSUE TITLE
libp2p-in-browser Example is not working

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p#364]
See the published version at https://github.com/libp2p/js-libp2p/tree/master/examples/libp2p-in-the-browser. It throws

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/1211152/58232132-03b03c00-7d39-11e9-9468-c96a6792b17b.png">

**Comment by jacobheun** [comment]
We are doing some libp2p infrastructure inventory and it looks like the webrtc signaling server wasn't clearly documented. We'll work on getting that back up and documented appropriately.

**Comment by jacobheun** [comment]
The server is back up. I ran the example and everything is running as expected.

**Comment by daviddias** [comment]
Thank you @jacobheun :D
