### ISSUE TITLE
issue with communicating over internet. Can libp2p provide communication over nodes located across internet

### ISSUE THREAD

**Issue by thanusreemohan** [libp2p/js-libp2p#366]
- **Version**:
- **Platform**:
- **Subsystem**:

**Comment by thanusreemohan** [comment]
I am trying to connect nodes across the internet using LibP2p.
Does libp2p allow communication over the internet for nodes located behind the phone internet (wifi).

**Comment by jacobheun** [comment]
The libp2p forums are a better place to ask general libp2p questions like this, https://discuss.libp2p.io. 

Yes, libp2p does allow this through various things. We're working on improving NAT traversal in JS but current available options include using Relays and transports like https://github.com/libp2p/js-libp2p-webrtc-star that have built in hole punching. If you're looking to run a node longer term on a home network you might want to look into setting up port mapping or UPnP on your router to improve your nodes connectivity to the network. Once we role out the NAT Manager in JS it will attempt to punch through the NAT automatically, but if you don't have this set up on your router it won't work and you'll have to fallback to other, less efficient options, like Relays.

**Comment by thanusreemohan** [comment]
Thanks so as i understand with the current setup in webrtc-star the home networks (phone internet wifi) cannot communicate with each other. Once NAT manager is rolled out this would be addressed ?

**Comment by jacobheun** [comment]
> Once NAT manager is rolled out this would be addressed?

To a degree, with hole punching, but that's not 100% effective. We're working on improving this as much as we can with various techniques, but looking into updating your routers configuration to forward ports for your application is a more immediate and effective approach.

**Comment by thanusreemohan** [comment]
Thank you! when can we expect NAT manager rollout in nodeJS or GO language?

**Comment by jacobheun** [comment]
Go has some NAT Traversal support already. NAT traversal in JS is higher on my priority list. I'm hoping to get some dedicated time next month to work on it and the AutoNAT protocol (automatic nat discovery and address announcing via connected peers) in JS.

**Comment by suutaku** [comment]
NAT traversal is really important and without it p2p will not going to work in some country . like China.

**Comment by p-shahi** [comment]
The larger hole punching effort is tracked here: https://github.com/libp2p/js-libp2p/issues/1461
AutoNat has landed: https://github.com/libp2p/js-libp2p/issues/1005
hole punching in the browser is possible via private-to-private/browser-to-browser https://github.com/libp2p/js-libp2p-webrtc
