### ISSUE TITLE
JS and Go cannot connect when using non-RSA keys

### ISSUE THREAD

**Issue by tobowers** [libp2p/js-libp2p#373]
- **Version**: JS: 0.25.4, GO: 0.2.0
- **Platform**: JS & GO interplay
- **Subsystem**: Just connection, so I suppose Swarm?

#### Description:

See description here: https://discuss.libp2p.io/t/browser-go-bootstrap-and-connect/175 .

Javascript and GO cannot connect over websockets when using non-RSA keys.

#### Steps to reproduce the error:
I'm sorry to not have a minimal reproduction already established, but you need a running go node using an ecdsa key and then javascript will not be able to connect to it over web sockets.

**Comment by aknuds1** [comment]
I'm looking into solving this.

**Comment by vasco-santos** [comment]
This seems to not be the case anymore, since the interop tests are doing it now.
