### ISSUE TITLE
Issues on the documentation

### ISSUE THREAD

**Issue by guicunha** [libp2p/js-libp2p#375]
I found some problems on the documentation site and tutorials. Is there a specific thread for it? When or how can I send fixes and suggestions to documentation?

**Comment by jacobheun** [comment]
@guicunha are you referring to https://docs.libp2p.io? If so, the site code is over at https://github.com/libp2p/docs.

**Comment by vasco-santos** [comment]
Closing this for lack of answer. @guicunha feel free to reopen this if it is till relevant
