### ISSUE TITLE
Add dialBest to the API

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#376]
#### Description:

There are use cases where we want to leverage libp2p to dial other peers using a specific protocol, but fallback to another one if that peer does not support the initial attempt. With the current API we need to do a cascade of dials, in order to do this, while libp2p could offer this in its API. 

One example of this is in the Gossipsub implementation [ChainSafe/gossipsub-js#34](https://github.com/ChainSafe/gossipsub-js/pull/34), where we intend to fallback to floodsubs if the peer does not support gossipsub.

We should have a utility to handle multi protocol negotiation, receiving a list of protocols and trying to dial by its order. An example could be:

```js
const protocolPreferences = [gossipsubMulticodec, floodsubMulticodec]
libp2p.newStream(peerInfo, protocolPreferences, callback)
// or
libp2p.dialBest(peerInfo, protocolPreferences, callback)
```

This was discussed with @jacobheun in the Gossipsub PR

**Comment by dirkmc** [comment]
Sounds like a good improvement to me 👍 

Should this just be an option on the `dialProtocol()` method? ie clients would specify either a string or an array as the second argument

**Comment by vasco-santos** [comment]
We could support an array of protocols, but in these type of APIs I usually prefer to be more specific. The naming would not suit greatly receiving an array

**Comment by wemeetagain** [comment]
dialProtocol accepts an array of protocols
