### ISSUE TITLE
Unsupported engine for @condenast/bundlesize@0.18.1 on install 

### ISSUE THREAD

**Issue by AcidLeroy** [libp2p/js-libp2p#379]
LibP2P Version: 0.25.5
Platform: Mac OS Mojave
Node Version: 10.16.0
npm version: 6.9.0
nvm version: 0.34.0

#### Description:
Cannot install dependencies  without getting the following error: 
![image](https://user-images.githubusercontent.com/249048/61347330-b5d82180-a819-11e9-94b3-a654e5fab6a2.png)

Installing an older version of npm doesn't work because the project requires that npm >= 6 be installed. I'm using the same exact configuration from the output of travis CI, but I am not having any luck. Could this be related to running on OS X, maybe there is a conflict with some system package? Bundlesize is complaining becuase of this line: 

https://github.com/conde-nast-international/bundlesize/blob/master/package.json#L36

Is it possible to use multiple npms for this?  Because in libp2p you specify an incompatible version with bundlesize: https://github.com/libp2p/js-libp2p/blob/master/package.json#L42-L43

#### Steps to reproduce the error:

1. `git clone git@github.com:libp2p/js-libp2p.git`
2. `cd js-libp2p` 
3. `npm install`

**Comment by jacobheun** [comment]
I'm not able to reproduce this with the nodejs and npm versions specified. I am also running mojave.

Can you run `npm config get` and see if `engine-strict` is set? It should be off by default.

**Comment by AcidLeroy** [comment]
@jacobheun Thanks for the response. Yes, `engine-strict` is enabled. I'll disable it and see if I have better luck.

**Comment by AcidLeroy** [comment]
@jacobheun Yeah that was the issue. I am going to close this issue out now. Thanks for the help!
