### ISSUE TITLE
Merge js-libp2p-{core pieces} into js-libp2p repo

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p#384]
Following https://github.com/ipfs/js-ipfs/issues/2222, the proposal is to:

Merge into js-libp2p, the following modules:
- [x] [js-libp2p-connection-manager](https://github.com/libp2p/js-libp2p-connection-manager)
- [x] [js-libp2p-identify](https://github.com/libp2p/js-libp2p-identify)
~~- [ ] [js-libp2p-keychain](https://github.com/libp2p/js-libp2p-keychain)~~
~~- [ ] [js-libp2p-nat-mngr](https://github.com/libp2p/js-libp2p-nat-mngr)~~
- [x] [js-libp2p-pnet](https://github.com/libp2p/js-libp2p-pnet)
- [x] [js-libp2p-ping](https://github.com/libp2p/js-libp2p-ping)
- [x] [js-libp2p-switch](https://github.com/libp2p/js-libp2p-switch) https://github.com/libp2p/js-libp2p/pull/388
- [x] [js-libp2p-circuit](https://github.com/libp2p/js-libp2p-circuit)

### NPM Deprecation Notice
- [x] https://www.npmjs.com/package/libp2p-circuit
- [x] https://www.npmjs.com/package/libp2p-connection-manager
- [x] https://www.npmjs.com/package/libp2p-identify
- [x] https://www.npmjs.com/package/libp2p-pnet
- [x] https://www.npmjs.com/package/libp2p-ping
- [x] https://www.npmjs.com/package/libp2p-switch

### Readme Deprecation Notice
- [x] [js-libp2p-circuit](https://github.com/libp2p/js-libp2p-circuit)
- [x] [js-libp2p-connection-manager](https://github.com/libp2p/js-libp2p-connection-manager)
- [x] [js-libp2p-identify](https://github.com/libp2p/js-libp2p-identify)
- [x] [js-libp2p-pnet](https://github.com/libp2p/js-libp2p-pnet)
- [x] [js-libp2p-ping](https://github.com/libp2p/js-libp2p-ping)
- [x] [js-libp2p-switch](https://github.com/libp2p/js-libp2p-switch)

### Github Archival
Description replacement: `[DEPRECATED]: now part of the https://github.com/libp2p/js-libp2p repo`
- [x] [js-libp2p-circuit](https://github.com/libp2p/js-libp2p-circuit)
  - [x] Update description
- [x] [js-libp2p-connection-manager](https://github.com/libp2p/js-libp2p-connection-manager)
  - [x] Update description
- [x] [js-libp2p-identify](https://github.com/libp2p/js-libp2p-identify)
  - [x] Update description
- [x] [js-libp2p-pnet](https://github.com/libp2p/js-libp2p-pnet)
  - [x] Update description
- [x] [js-libp2p-ping](https://github.com/libp2p/js-libp2p-ping)
  - [x] Update description
- [x] [js-libp2p-switch](https://github.com/libp2p/js-libp2p-switch)
  - [x] Update description

**Comment by jacobheun** [comment]
I put together a Draft PR of this, https://github.com/libp2p/js-libp2p/pull/388, for just `libp2p-switch` so we can chat about the approach there.

**Comment by jacobheun** [comment]
@daviddias each module has been deprecated on npm, and the readme's all include the notice and a link to js-libp2p. I added TODOs to the issue description, https://github.com/libp2p/js-libp2p/issues/384#issue-470661287, to **archive** and **update the description** of each repo. If you could help with that, it would be much appreciated! ❤️

**Comment by daviddias** [comment]
@jacobheun done! Thank you for making it super simple :)

**Comment by vasco-santos** [comment]
Can we close this?

**Comment by jacobheun** [comment]
Yes!

**Comment by daviddias** [comment]
PR to follow for those interested https://github.com/libp2p/js-libp2p/pull/525
