### ISSUE TITLE
WebCrypto

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p#4]
# webcrypto

https://github.com/diasdavid/webcrypto

WebCryptoAPI polyfil to work in Node.js in the Browser (so that you don't have to be concerned about moving crypto code between a browser and server side app)

Context: https://github.com/nodejs/node/issues/2833
# How can you help
- The module is still being made, if someone wants to take the lead, it would be great :) 

For reference, here is the old issue: https://github.com/ipfs/js-ipfs/issues/27

**Comment by rmhrisk** [comment]
https://github.com/PeculiarVentures/node-webcrypto-ossl

**Comment by diasdavid** [comment]
We moved to WebCrypto and now we are having two issues:

- https://github.com/libp2p/js-libp2p-crypto/issues/31
- https://github.com/libp2p/js-libp2p-crypto/issues/38

@rmhrisk thoughts? Let's follow up on those issues :)
