### ISSUE TITLE
Two links in CONTRIBUTING document are broken

### ISSUE THREAD

**Issue by a1300** [libp2p/js-libp2p#402]
- **Version**:
- **Platform**:
- **Subsystem**:

#### Description:

Two links in [CONTRIBUTING.md](https://github.com/libp2p/js-libp2p/blob/master/CONTRIBUTING.md) are broken.

#### Steps to reproduce the error:
1. Open your browser
2. Navigate to [CONTRIBUTING.md](https://github.com/libp2p/js-libp2p/blob/master/CONTRIBUTING.md)
3. Click on link **standard IPFS Community contributing guidelines** -> broken
4. Click on link **IPFS JavaScript Community contributing guidelines** -> broken

**Comment by jacobheun** [comment]
Fix at https://github.com/libp2p/js-libp2p/pull/403
