### ISSUE TITLE
Update configuration validation (remove superstruct)

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#406]
Currently we use superstruct for config validation. This isn't really necessary and in most instances the validation is very loose. It also doesn't give us support for deep merge of default values, so default values may not get passed to the given module unless they are all explicitly defined.

Rather than restricting validation of the config, we should focus on providing defaults that are sane, and will be deeply merged into any passed configuration. We should do the minimum validation needed for libp2p to run, and create helpful error messages for users about how to correct their configuration.

**Comment by vasco-santos** [comment]
Closing this as we are not using `superstruct` anymore
