### ISSUE TITLE
Any way to cancel a dial call?

### ISSUE THREAD

**Issue by rmisio** [libp2p/js-libp2p#411]
Let's say you fire off a `dial` call and part way through you no longer need it. Is there any way currently to cancel that call?

I believe IPFS-go takes a `context` which allows you to cancel, but I'm not seeing anything similar in JS.

**Comment by jacobheun** [comment]
Not yet, but as a part of our move to async/await, the transports will be getting support for passing an AbortController which will allow this. https://github.com/libp2p/interface-transport#canceling-a-dial

**Comment by vasco-santos** [comment]
FYI, `js-libp2p` now supports abortable dials, you can check the API docs. If you have any further questions, feel free to re-open the issue
