### ISSUE TITLE
[conn-manager] Detecting slow/stale connections

### ISSUE THREAD

**Issue by dryajov** [libp2p/js-libp2p#413]
Currently, there is no mechanism to detect if a connection has become stale (other side died) or slow/unresponsive. I've been thinking of ways to solve it, and a couple come to mind.

### 1) Ping/pong mechanism

Implement a ping/pong mechanism and if latency is too high or no response has been received within a time period, then disconnect/cleanup.

Pros:

- No ambiguity to weather the connection is stale, if we don't see a response for the ping we can be certain the other side is unreachable.

Cons:

- Needs a specialized (but very simple) proto
- Generates constant traffic
- Not sure where this sits in the stack
  - does it require a multiplexer to work, or can we just use it on top of the raw connection?

### 2) Detecting idle connections

Measure if any data has been sent/received within a time frame, if not then close/cleanup the connection.

Pros:

- doesn't require any specialized protocols/implementations 
- can be added directly to connection manager
- doesn't generate any additional traffic

Cons:

- no way to tell if the other side has gone stale or its just idle
  - the counter point being that, if the connection isn't being used anymore, then we don't need to keep it around in most cases (with a few exceptions, notably circuit)

### 3) Use both of the above options

Track a connection, and if we detect it as idle, then start a ping, if the ping fails the clean it up.

**Comment by p-shahi** [comment]
This might be better left to the underlying transport to handle (i.e. TCP read timeout, WebRTC and WebTransport also handle this with onConnection event listeners.)
The reason to not lift it out of the transport is that these mechanisms are expensive. Closing for now.
