### ISSUE TITLE
[conn-manager] internal values and preservation

### ISSUE THREAD

**Issue by pgte** [libp2p/js-libp2p#414]
Currently, the connection manager delegates entirely to the application the definition of values for each peer. This is not optimal, since some peers may have value to internal subsystems in libp2p, like, for instance, the DHT, where, for instance, it may be important to keep some connections around so that the DHT is well connected.

**Comment by wemeetagain** [comment]
This should be resolved with peer tagging and the default sorting function for disconnecting peers
