### ISSUE TITLE
[conn-manager] internal peer value

### ISSUE THREAD

**Issue by pgte** [libp2p/js-libp2p#415]
Wisely brought up by @dryajov [here](https://github.com/libp2p/js-libp2p-connection-manager/issues/10#issuecomment-383755530), there are peers that provide value to certain protocols (namely DHT) that perhaps should see the value reflected.

If so, how do we expose that internally? How do we combine this value with the user-defined value? Should we generalize this to other protocols? ...

**Comment by wemeetagain** [comment]
Now that we have peer tagging, any protocol or application can add arbitrary values
