### ISSUE TITLE
[conn-manager] peer value should be HOP-aware

### ISSUE THREAD

**Issue by pgte** [libp2p/js-libp2p#416]
A connection to another peer can host connections to other peers through the HOP transport.
When disconnecting from a peer, the value of that connections shouldn't be only the single value of that peer, but also should contain the value of all the peers that are connected through it.

First discussed [here](https://github.com/libp2p/js-libp2p-connection-manager/issues/2#issuecomment-382306181).

**Comment by wemeetagain** [comment]
This feature is available thru peer tagging. We prioritize / sort peers based on peer tag values for autoconnect / disconnect.
