### ISSUE TITLE
[conn-manager] prevent flapping

### ISSUE THREAD

**Issue by pgte** [libp2p/js-libp2p#417]
In some circumstances, these events might happen in a lopp:

* a measure is slightly above a threshold
* that triggers a preemptive disconnect
* the measure goes down to slightly below the threshold
* a new connection is accepted
* repeat

To prevent this,  dampening should be reflected on the measure. In some cases, it already is.

By default, some statistics (like data sent and received) uses the moving average over one minute, which already produces a dampening effect.

The problem is that the other statistics are a snapshot taken at a given point in time, like the number of connected peers. In my opinion, this value, like the moving averages, should be continuous. Let me illustrate:

This peer is connected to 3 other peers. A new peer connection happens. The internal number of connected peers does not suddenly become 4. It gradually raises to 4, over a continuum.

This should prevent flapping.

**Comment by maschad** [comment]
Closing due to staleness
