### ISSUE TITLE
[conn-manager] denying connections before they're established

### ISSUE THREAD

**Issue by pgte** [libp2p/js-libp2p#418]
Allow hooks for denying connections before they are established.

First (and wisely)  requested by @kumavis [here](https://github.com/libp2p/js-libp2p/issues/175).

**Comment by wemeetagain** [comment]
This was implemented with the ConnectionGater feature

- See https://github.com/libp2p/js-libp2p/pull/1142
- See https://github.com/libp2p/js-libp2p/blob/master/packages/interface/src/connection-gater/index.ts
