### ISSUE TITLE
[identify] Add support for identify/delta

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#419]
In the context of [libp2p/specs#176](https://github.com/libp2p/specs/pull/176), support for `identify/delta` needs to be added.

Note: there is also a draft PR for adding support for `identify/push` [libp2p/js-libp2p-identify#53](https://github.com/libp2p/js-libp2p-identify/pull/53)

**Comment by p-shahi** [comment]
Identify delta was removed from go-libp2p: https://github.com/libp2p/go-libp2p/pull/1975
The spec effort was also closed: https://github.com/libp2p/specs/pull/176#issuecomment-1384186017

Closing this issue
