### ISSUE TITLE
[circuit-relay] In-browser NAT traversal via js-libp2p-circuit

### ISSUE THREAD

**Issue by davepuchyr** [libp2p/js-libp2p#423]
Hi, @jacobheun,

Would you be so kind as to add an in-browser example for js-libp2p-circuit similar to https://github.com/libp2p/js-libp2p/tree/master/examples/libp2p-in-the-browser?  I have a libp2p dependent app that works perfectly when the (browser) nodes have public ip addresses, but fails when NAT is involved and I can't figure out how to incorporate js-libp2p-circuit in the mix.

Kind regards,

Dave

**Comment by maschad** [comment]
Closing as we have a few different [js-libp2p in the browser examples](https://github.com/libp2p/js-libp2p/tree/master/examples/libp2p-in-the-browser)
