### ISSUE TITLE
[switch] Have dial backoffs be multiaddr specific instead of peer specific

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#426]
Currently when we are not able to dial a peer we blacklist the peer with an exponential backoff. Really we should be backing off on multiaddrs. It's very possible that we can learn new, dialable multiaddrs for a peer after they've been blacklisted and we should be able to immediately attempt those dials.

Context: https://github.com/ipfs/interop/pull/70#issuecomment-497475187

**Comment by maschad** [comment]
Closing due to staleness
