### ISSUE TITLE
[switch] Identify should replace peer addresses

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#427]
Replicated from go, https://github.com/libp2p/go-libp2p/issues/579. 

We currently do an additive `PeerBook.put()` on identify, https://github.com/libp2p/js-libp2p-switch/blob/v0.42.9/src/connection/manager.js#L201. We should replace the addresses we have for the peer as they may be out of date.

It may be better to simply use the replace logic of `PeerBook.put()` to do this, `PeerBook.put(peerInfo, true)` as we'll likely also want to ensure we have the latest list of correct protocols of a peer. If peers in the future ever dynamically enable things like the DHT, keeping an accurate, non-additive list will be increasingly important.

**Comment by vasco-santos** [comment]
This is already implemented with the PeerStore implementation.
