### ISSUE TITLE
[switch] Connection manager and PeerBook report different numbers of connected peers

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#428]
Logging out some stats on a running node, eventually the number of peers reported as connected via the `Connection Manager` and `PeerBook` starts to differ pretty dramatically. In this instance almost 160 peers. 

> Connection manager is tracking 409 peers
PeerBook has 578 connected peers

The `Connection Manager` connections are taken directly from the `_peers` map in the connection manager. The mapping is updated anytime a muxed connection is created or ends. 

The `PeerBook` connections are determined by the `PeerInfo` instances in `PeerBook` that return an address from `PeerInfo.isConnected()`. These numbers should match. If not, the connection manager might not be pruning connections at the correct high water mark.

**Comment by vasco-santos** [comment]
This should not be a problem anymore as only the connectionManager stores connections now.
