### ISSUE TITLE
[switch] Get peer protocol list at the connection start

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#429]
The protocols a peer supports are being added to the `PeerInfo` instance when a muxed connection occurs on dial as of https://github.com/libp2p/js-libp2p-switch/pull/307. The protocol `ls` should be happening at the beginning of the connection, after potential connection privatization, to maximize handshake efficiency for crypto and muxer selection.

Depends on https://github.com/multiformats/js-multistream-select/issues/47

Follow up of libp2p/js-libp2p-switch#304 
Reference: https://github.com/libp2p/js-libp2p-switch/pull/307#discussion_r262880396

**Comment by vasco-santos** [comment]
This is done and the protocols are now stored on the ProtoBook
