### ISSUE TITLE
[switch] Clear dialing queues when switch is shutting down

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#432]
Currently when the switch is shutting down the dialing queues are not cleared. When the switch is shutting down we should clear the pending dials queue, and then abort all in progress dials. This will help prevent unwanted behavior when a node is shutting down / "stopped".

Depends on https://github.com/libp2p/interface-transport/issues/43, aborting in progress dials.
Relates to https://github.com/libp2p/js-libp2p-switch/issues/281

**Comment by wemeetagain** [comment]
This should be resolved
