### ISSUE TITLE
[switch] Support multiple crypto modules

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#437]
As mentioned at https://github.com/libp2p/js-libp2p-switch/pull/278#issuecomment-427147407 we don't currently support multiple crypto modules in Switch, even though multiple modules can be given. While the listener will select the proper crypto module via multistream-select, the dialer only ever uses a single crypto module.

The dialer and listener need to be able to negotiate which crypto they want to use. While libp2p currently only has the `libp2p-secio` module, once the TLS1.3 module is created (likely some time next year) we will need to support this properly.

Depends on https://github.com/libp2p/js-libp2p-switch/pull/278

**Comment by vasco-santos** [comment]
Closing this, as we now support multiple crypto modules and `libp2p-noise` is being used in examples together with `libp2p-secio`.
