### ISSUE TITLE
Roadmap for the relay protocol

### ISSUE THREAD

**Issue by JustinDrake** [libp2p/js-libp2p#44]
`go-libp2p` has implemented a [relay protocol](https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/relay/relay.go) for a node to relay traffic between two directly connected nodes. Are there plans to implement this relay protocol in `js-libp2p`?

**Comment by diasdavid** [comment]
It is 2014 Q4 - https://github.com/libp2p/libp2p/blob/master/ROADMAP.md#milestone---write-libp2p-relay-spec :)

**Comment by JustinDrake** [comment]
Thanks! (Actually 2016 Q4.)
