### ISSUE TITLE
[switch] Filter out matching IP:PORT pairs in Identify

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p#445]
Once Identify is completed, before we update the info we have about one node, we have to filter out the IP:PORT pairs that are the same as ours (for example, when two nodes are in different networks but both announce `127.0.0.1:5002`), this currently causes a bug because the nodes will try to dial to themselves and then the secio handshake fails, since the public key isn't going to hash to the same.

**Comment by p-shahi** [comment]
The prescribed behavior by this issue isn't in accordance with the identify spec: https://github.com/libp2p/specs/tree/master/identify#identifypush

Closing this for now
