### ISSUE TITLE
[switch] idea: multihandshake for 0-RTT handshakes

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p#448]
Right now, for each type of `connection upgrade`, we perform a multistream handshake in order to be able to support several protocols on top of the same transport. This adds a considerable amount of RTT's  to the connection before it is ready, which might represent a problem for slow links. 

0 handshake can bring considerable amounts performance for streaming scenarios. What if we take the multistream handshake and make a special case for a multihandshake such that we send: `/multihandshake/all/the/protocols/that/will/be/stacked/` as one message, instead of handshaking each at all times. This adds the problem that by narrowing down the number of protocols + versions we are interested in talking (muxer1 vs muxer2 or encryptedChannel1 vs encryptedChannel2), we can miss a successful handshake, but for previous known peers, it should work like a charm.

**Comment by p-shahi** [comment]
We have a spec for inlined muxer negotiation which will save 1 RTT: https://github.com/libp2p/specs/blob/master/connections/inlined-muxer-negotiation.md
Perhaps we can move to that. Closing this issue for now
