### ISSUE TITLE
Merge peer-id & peer-info into one, Merge peer-book into js-libp2p

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p#453]
We've talked this in a PR but creating a issue so that we don't miss it.

- [ ] Merge peer-id & peer-info into one
- [x] Merge peer-book into js-libp2p

**Comment by daviddias** [comment]
While at it, rename the module name to be `libp2p-peer`

**Comment by jacobheun** [comment]
I think what I'd really like to see is for peer-info to go away altogether. What it does could and should, imo, be managed by the peer-book (PeerStore, which would be great to rename as part of pulling this into libp2p to avoid confusion with go and the specs). Everything ultimately gets housed in the PeerStore anyway, so fully centralizing it there would be ideal, and it would remove a layer of complexity.

cc: @vasco-santos

**Comment by vasco-santos** [comment]
I agree with jacob here! Peerbook should own the responsibilities of `peer-info`.

+1 on renaming this to `PeerStore` and I want to get this work done as a groundwork to get to [libp2p/specs#164](https://github.com/libp2p/specs/issues/164)

**Comment by daviddias** [comment]
> I think what I'd really like to see is for peer-info to go away altogether. What it does could and should, imo, be managed by the peer-book

Just note that there are multiple modules that require the concept of a `Peer` but they don't need to know about a `PeerStore`. That said, I suggest to give it a try and see how viable it is on the refactor to remove the _Class_ `Peer` (prev peer-info) altogether, I might be missing some nuances that might make it nicer.

> (PeerStore, which would be great to rename as part of pulling this into libp2p to avoid confusion with go and the specs).

👍🏽

**Comment by daviddias** [comment]
Now that PeerStore is becoming part of js-libp2p with the async await refactor. Can we also get peer-id and peer-info merged as well?

**Comment by vasco-santos** [comment]
Yes, I have on my list to tackle that soon :)
