### ISSUE TITLE
Improve libp2p config

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p#46]
Right now, it is impossible to signal through the config if we want to use a transport just for dialing and not for listening, in fact, go-ipfs makes the hard decision of disabling any dialing from a transport from where we are not listening. 

The issue is that with this design, we have to make something hacky/hard coded to enable the WebSockets transport within libp2p-swarm for dialing in the browser.

https://github.com/libp2p/js-libp2p/blob/master/src/index.js#L97-L102

Ideas:
- Have a `dialer` multiaddr addr to signal that no listener should be started, but it should be considered to dial anyway
- Have a more config option within the config.json that informs swarm to do that.

**Comment by diasdavid** [comment]
Please review proposal here https://github.com/libp2p/js-libp2p/pull/166

**Comment by jacobheun** [comment]
With #166 merged I think we could add transport configuration for something like `isDialer` and then push all dialer only transports into the switch transports after startup. This could be enabled by default, as that is already a set expectation with web sockets.

**Comment by diasdavid** [comment]
@jacobheun related, see https://github.com/libp2p/js-libp2p/issues/201

**Comment by diasdavid** [comment]
DONE \o/ :D
