### ISSUE TITLE
Getting multiaddrs from peer id

### ISSUE THREAD

**Issue by guoliu** [libp2p/js-libp2p#465]
#### Type: Question

Peers have to get the `multiaddrs` of other peers to establish connection. Can peers find out each others' `multiaddrs` from peer id, e.g. via DHT?

In the peer routing example, peers have to [dial each other by `peerInfo`](https://github.com/libp2p/js-libp2p/blob/master/examples/peer-and-content-routing/1.js#L63) first. However, this does not seem to work when peers don't have each others' `peerInfo` and have to [rely on peer id string](https://github.com/hypha-publication/hypha-desktop/blob/feature/p2p-message/src/common/p2p.js#L68). Is there anyway to get around this?

**Comment by jacobheun** [comment]
> Peers have to get the multiaddrs of other peers to establish connection. Can peers find out each others' multiaddrs from peer id, e.g. via DHT?

Yes. Peer records are stored in the DHT with their known `multiaddrs`. When you run `findPeer` on the DHT with the id, if the peer is found, you should get back its addresses as well.

**Comment by guoliu** [comment]
My misunderstanding. Peers can successfully call `findPeer` without dialing each other first. Closing this issue now. Thanks for your explanation @jacobheun !
