### ISSUE TITLE
Peer Routing and Content Routing (DHT)

### ISSUE THREAD

**Issue by AlexFreeland** [libp2p/js-libp2p#51]
Apologies if this is not the right place for this... still trying to wrap my head around the myriad repositories tied up with this project!

I'm just wondering if there is a roadmap (or similar) for the js-libp2p DHT functionality.  I've had a bit of a poke around and discovered the -kad-routing and -kad-record-store modules, but these only provide a subset of the overall functionality described in the whitepaper, and the record store depends on the (seemingly deprecated) js-merkledag-store.  Some cursory googling turns up the recently created js-libp2p-dht repo, which it seems natural to assume is the successor to these modules, but I've not found any sort of official indication that this is so.

Is this assumption correct?  Will js-libp2p-kad-routing and js-libp2p-kad-record-store be superseded by js-libp2p-dht, and if so: is there a target timeframe in which to roll this out?  And what areas (if any) would benefit from having more hands on deck?

Finally: just wanted to say that IPFS and libp2p are among the most exciting, and certainly the most potentially transformative pieces of emerging tech on my radar.  Great stuff, everyone :)

**Comment by diasdavid** [comment]
Hi @AlexFreeland, thank you for your feedback, it is highly appreciated

We know it is a little confusing at the moment, but there is a key reason for it. The simple answer is, the DHT present in go-ipfs, will be available in JavaScript at https://github.com/libp2p/js-libp2p-dht and that is going to be the 'first DHT'.

The 'second DHT', comes from the separation of concerns of Peer Routing and Content Routing, the explanation (and the realization) and can be found described here: https://github.com/ipfs/specs/issues/1

libp2p spec presents some design decisions (https://github.com/libp2p/specs), getting the spec up to date is one of the goals of Q1 this year :)

**Comment by AlexFreeland** [comment]
Thanks for the response @diasdavid

So to clarify: the "second DHT" will entail separate peer and content routing modules, somewhat analogous to the division of responsibilities between https://github.com/libp2p/js-libp2p-kad-routing and https://github.com/libp2p/js-libp2p-kad-record-store?  Is the intention to update or supersede these repositories?

On a related note: I notice that implementations of the first DHT use the "/ipfs/kad/1.0.0" (and historically "/ipfs/dht") protocol; am I correct in assuming that the second DHT will employ separate protocols for peer and content routing?

**Comment by diasdavid** [comment]
Hi @AlexFreeland, got an update for you :) Check:
https://github.com/libp2p/js-libp2p/tree/master/examples/peer-and-content-routing

Note, consider the current implementation as `⍺` :)
