### ISSUE TITLE
[Documentation] Community sample code list?

### ISSUE THREAD

**Issue by mcclure** [libp2p/js-libp2p#512]
I ported the "libp2p-in-the-browser" example from the js-libp2p repo to use Preact. I intend to release this Preact version as sample code for others.

I asked if in your IRC channel if it would be helpful for me to submit this modified sample code "upstream" anywhere, and @vasco-santos said:

> I think it would be nice if we have a list of examples/projects created by the community, which would reference those projects so that other people could collaborate or learn from them

I think having a list of community-supported js-libp2p examples, or a libp2p/js-libp2p-examples repo people could submit PRs to, would be neat.

**Comment by jacobheun** [comment]
> libp2p/js-libp2p-examples repo people could submit PRs to, would be neat

I really like this idea. We do have [js-libp2p-examples](https://github.com/libp2p/js-libp2p-examples) that currently just has an in depth chat example. I think transitioning that into a community driven examples repo is a great idea.

**Comment by vasco-santos** [comment]
I slept on this and I drafted a proposal for this. The goal is to create a `js-libp2p-community` repo with a similar concept to the `*-awesome` repos.

## js-libp2p-community

A catalog of libp2p awesomeness from the community to the community

## Structure

This catalog is divided into 4 main categories: examples, protocols, presentations and articles

### Examples

Examples section should contain code examples using `js-libp2p` for all types of purposes. This list can include references to other github repositories and codesandbox projects. If a github repository is referenced for an "in browser" example, it is suggested that the example also link to a codesandbox project.


### Protocols

List of protocols implemented on top of libp2p.

- `js-ipfs-bitswap`

### Presentations

List of relevant presentations

### Articles

List of relevant articles

---

If you feel this is a good idea, I can create the repo and move this proposal to a `README.md` so that we can iterate it. 

With this, we should rename `js-libp2p-examples` into `js-libp2p-workshop-ipfs-camp`, or similar and add to this.

**Comment by daviddias** [comment]
I like the general way this is headed, a few thoughts:

- What about reusing https://github.com/ipfs/awesome-ipfs as awesome-libp2p?
- "we should rename js-libp2p-examples into js-libp2p-workshop-ipfs-camp" -> 👍🏽
- Caveat: You will destroy the onboarding experience if you throw new users into an ocean of examples. Keep a few (3~5) powerful tutorials of things built with libp2p close to the implementation, those will expose new users to the ways of doing things with libp2p and encourage them to experiment.

**Comment by vasco-santos** [comment]
> * What about reusing https://github.com/ipfs/awesome-ipfs as awesome-libp2p?

I did not know that repo. I think we should definitely get ideas from there! Thanks 👍 

> * Caveat: You will destroy the onboarding experience if you throw new users into an ocean of examples. Keep a few (3~5) powerful tutorials of things built with libp2p close to the implementation, those will expose new users to the ways of doing things with libp2p and encourage them to experiment.

Yes, with this I intended to keep the current examples within this repo, and also integrate CI with them

**Comment by mcclure** [comment]
> Caveat: You will destroy the onboarding experience if you throw new users into an ocean of examples

I think @vasco-santos's solution to this problem "I intended to keep the current examples within this repo, and also integrate CI with them" is good. However, a related suggestion:

I think you should be very intentional about versioning when you put together this repo. Libp2p seems to have some API churn. I have seen libraries where they have long lists of examples or addon libraries on their web page but the lists are useless because many of the items support only older versions of the libraries and it is not clear which ones are which. Possible solutions to this are to either version the -community repo so if you go to the 0.26 branch you get a list of only 0.26 compatible stuff, or keeping one list but tagging each item in the list which which version(s) it supports.

**Comment by jacobheun** [comment]
> - What about reusing https://github.com/ipfs/awesome-ipfs as awesome-libp2p?
> - "we should rename js-libp2p-examples into js-libp2p-workshop-ipfs-camp" -> 👍🏽

> Possible solutions to this are to either version the -community repo so if you go to the 0.26 branch you get a list of only 0.26 compatible stuff, or keeping one list but tagging each item in the list which which version(s) it supports.

👍 

I think a catalogue approach is the way to go. As @mcclure mentioned, making sure that it's not difficult to find pertinent information for the version of libp2p they want to use is important. I like the tagging approach for resolving this. PRs for examples, protocols, etc, into the `awesome-libp2p` repo could include semver ranges along with other tagging metadata. This would make it easier for users to filter/search on the site for particular versions.

Given this feedback, as I integrate the new version of libp2p into the `js-libp2p-workshop-ipfs-camp` (pending name change) repo, I'll create a branch for the 0.26 line and have master be 0.27 with readme links to the various versions supported.

**Comment by vasco-santos** [comment]
Thanks for the feedback.

I intend to work on a more concrete proposal next week

**Comment by raulk** [comment]
Excited for this! One solution to detect breakage of examples promptly is to use dependabot with an automatic merge policy on the samples repo + CI to build and test on every dependency upgrade.

Alternatively we could make the package.json point the master branches of all libp2p upstreams. But if we do that, we’ll need to sort out a way of triggering a build every time any master branch slides.

**Comment by wemeetagain** [comment]
Closing this as we have many examples, are willing to accept more in PRs. We have tests and the monorepo ensures that everything stays in sync.
