### ISSUE TITLE
It is confusing to get the docs of the Latest Release

### ISSUE THREAD

**Issue by shresthagrawal** [libp2p/js-libp2p#540]
Enhancement

#### Severity:
Low

#### Description:
The doc in the master branch consist of changed API also from the pre-release. This might be confusing for a dev to find the write documentation.

For eg: it took me some time to realise `createLibp2p()` is replaced with `create()` in the pre release. Using the latest release from the npm I would still use the `createLibp2p()` but the master doc says to use the `create()`.

#### Possible Solution
In the readme add the following line
```
The doc linked in the master branch are for pre-release.
If you are looking for the docs for the latest release, then (head here)[link to npm docs]
```

Thanks @vasa-develop

**Comment by jacobheun** [comment]
Fixed in #541
