### ISSUE TITLE
Unable to discover the peers

### ISSUE THREAD

**Issue by kottackalsulvin** [libp2p/js-libp2p#555]
Hi,
I am trying to implement a libp2p webcam application. In-order to discover and connect to the other peers in the same network, i tried the below libp2p code but it didn’t worked for me(Actually it didn't displays any error, but the console log is not printing). Please help me to resolve this issue.

```
node . on ( ‘peer:discovery’ , ( peer ) => {
console.log(‘Discovered:’)
})
```

**Environment**
Npm version: 6.13.4
Node version: 10.18.1
Os:Ubuntu 18.04
webpack : 3.11.0
libp2p-webrtc-star: 0.13.2
libp2p-websockets: 0.12.2

**App.js**

    const node = new Node ({ peerInfo })

    node.start((err) => {

    if (err) callback(err)

    callback(null, node)

    })

    ...

    ...
 const SIGNAL_SERVER = '/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/:peer-id'

    class Node extends libp2p {

    constructor (peerInfo, peerBook, options) {

    options = options || {}

    const wstar = new WebRTCStar()

    const defaults = {

    modules: {

    transport: [ new WS(), wstar ],

    streamMuxer: [ mplex ],

    connEncryption: [ secio ],

    peerDiscovery: [wstar.discovery ]

    }

    }
    super(defaultsDeep(defaults,peerInfo,peerBook,options))

    }

    }

**Comment by jacobheun** [comment]
The signaling server requires the `libp2p-websocket-star` transport which only works with js-libp2p versions older than 0.27. A webrtc-star signaling server is required in order for webrtc-star signaling to work
