### ISSUE TITLE
[PeerStore] Add ability to record latency information

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#556]
@dignifiedquire commented on [Sat Apr 01 2017](https://github.com/libp2p/js-peer-book/issues/34)

---

@jayarjo commented on [Wed Apr 03 2019](https://github.com/libp2p/js-peer-book/issues/34#issuecomment-479407532)

Why do you folks keep issues for merged fixes open?

---

@JustMaier commented on [Sun Jun 02 2019](https://github.com/libp2p/js-peer-book/issues/34#issuecomment-497985231)

Doesn't look like this has been implemented yet, which appears to mean that the js peer-book isn't at parity with the go peer-book.

---

@tapaswenipathak commented on [Sat Jul 27 2019](https://github.com/libp2p/js-peer-book/issues/34#issuecomment-515694553)

Hi folks: Can I take the ticket?

---

@JustMaier commented on [Mon Jul 29 2019](https://github.com/libp2p/js-peer-book/issues/34#issuecomment-516084591)

@tapaswenipathak that'd be awesome!

**Comment by vasco-santos** [comment]
FYI we now have the PeerStore decoupled into AddressBook, ProtoBook, KeyBook and MetadataBook. We can easily move forward with this issue

**Comment by wemeetagain** [comment]
Closed as implemented. An application can record latency information in the metadata section of the peer store
