### ISSUE TITLE
node.start() - callback is not a function

### ISSUE THREAD

**Issue by kawmaiparis** [libp2p/js-libp2p#569]
PeerId.createFromJSON(require("./ids/moonId"), async (err, peerId) => {
    const peerInfo = new PeerInfo(peerId);
    peerInfo.multiaddrs.add("/ip4/127.0.0.1/tcp/10333");
    const nodeListener = new Node({ peerInfo });

    await nodeListener.start(err => {
        console.log("here");
        if (err) {
            console.log(err);
        }
    });
...

Code is failing on nodeListener.start() and I don't know why.

(node:21867) UnhandledPromiseRejectionWarning: TypeError: callback is not a function
    at EventEmitter.listener.getAddrs (/home/paris/Desktop/DeFi/hello-libp2p/node_modules/libp2p-tcp/src/listener.js:140:5)
    at TransportManager.getAddrs (/home/paris/Desktop/DeFi/hello-libp2p/node_modules/libp2p/src/transport-manager.js:102:40)
    at P2PNode._onStarting (/home/paris/Desktop/DeFi/hello-libp2p/node_modules/libp2p/src/index.js:377:44)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async P2PNode.start (/home/paris/Desktop/DeFi/hello-libp2p/node_modules/libp2p/src/index.js:201:7)
    at async /home/paris/Desktop/DeFi/hello-libp2p/src/moon.js:23:5
(node:21867) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21867) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

version = 
 "libp2p": "^0.27.3",

**Comment by vasco-santos** [comment]
Hello @kawmaiparis 

First of all, unrelated to the issue you are having, you are providing a callback to `nodeListener.start()`, which will not do anything, as start does not receive any parameters after `0.27.*`, as you can see on https://github.com/libp2p/js-libp2p/blob/master/doc/API.md#start

Regarding the issue, I think you are using an older version of `libp2p-tcp`. Per the stack trace I see it on [libp2p/js-libp2p-tcp/blob/v0.13.2/src/listener.js#L140](https://github.com/libp2p/js-libp2p-tcp/blob/v0.13.2/src/listener.js#L140), that it the `0.13.2` version of `libp2p-tcp`, which was using the older `js-libp2p` codebase with callbacks. If you update `libp2p-tcp` to `0.13.*` this should be solved.

Let me know if this solved your issue.

**Comment by kawmaiparis** [comment]
Thanks! I was using 0.26.3.
