### ISSUE TITLE
Add configuration option for address listen error tolerance

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#575]
## Problem
Currently if libp2p is provided a list of multiaddrs and there are no valid transports configured for those multiaddrs, libp2p will throw an error on startup and shutdown.

Additionally, if mulitaddrs for an existing transport are provided but listening fails for all multiaddrs for that transport, such as a webrtc-star/etc server being down, libp2p will thrown an error and shutdown.

## Solution
We should support the configuration of this tolerance. For some applications it could be perfectly acceptable for nodes to start in dial only mode if all multiaddrs failed for a given transport, or all transports. While libp2p is currently more aggressive with its errors to favor transparency of issues, it shouldn't be restricted to this.

Refs:
- https://github.com/libp2p/js-libp2p-websocket-star/issues/61
- https://github.com/ipfs/js-ipfs/issues/2779

**Comment by vasco-santos** [comment]
Closing since #643 and this is being released on `libp2p@0.28.0`
