### ISSUE TITLE
Document libp2p node flows for different use cases

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#583]
Aiming to improve `js-libp2p`, we want to gather its flows for the different use cases we have.

This effort can enable the libp2p team to define better priorities, as well as improve user experience and documentation/examples relevant for the use cases.

Examples:

- A browser application joining the network and finding other peers of the same application

**Comment by wemeetagain** [comment]
Superseded by https://github.com/libp2p/js-libp2p/issues/2083
