### ISSUE TITLE
[question] How to saturate all CPU cores ?

### ISSUE THREAD

**Issue by corporatepiyush** [libp2p/js-libp2p#641]
How to saturate all CPU cores by having different NodeJS process and also load balancing the connections and making them stick to process ?

Something like this :- https://stackoverflow.com/questions/51301126/nodejs-clustering-with-sticky-session 

Is it already supported by default ? if not, an example would be great to have in documentation.

**Comment by SgtPooki** [comment]
We don't explicitly support multi-threading/clustering. Performance-maximizing strategies will vary depending on where your process is CPU bound. 

With the latest js-libp2p, you can manage the work handing off to other clusters/threads/workers via your a custom service you pass to the "services" property when configuring js-libp2p.
