### ISSUE TITLE
Checking for WebSockets constructor name fails under uglification

### ISSUE THREAD

**Issue by jackkleeman** [libp2p/js-libp2p#65]
Currently to add the WebSockets transport index.js does a check for the constructor.name being 'WebSockets'. This fails under uglification unless 'WebSockets' is made a reserved word in the uglify config, as constructor names are one of the things uglify removes. I recommend that either this is documented, or a different solution is devised; there is already a TODO in the code suggesting that this is found. For example, we could standardise some kind of boolean flag in a transport class which tells libp2p to include it even if there are no listening addresses. That wouldn't be websocket-specific, and wouldn't require checking the name against a string.

**Comment by dignifiedquire** [comment]
This is unfortunate, we use this pattern in a couple of places. I guess we need to find a new way to do these kinds of detections.

**Comment by diasdavid** [comment]
Trying to come up with an elegant solution and I always end up in making something that looks too complicated. The crux of this problem is the fact that we might handle several versions of the same module that are compatible with each other, but because of the dependency tree, they coexist.

Seems that we need to go 🦆 typing all the way, which isn't the best, but will suffice for the majority (if not all) the cases.

**Comment by mqzry** [comment]
_Warning: I did not look at the code yet._
Can't you just specify a regex to the mangle-regex option of uglify that matches functions starting with a capital? You do get a dependency on how the transpiler picks the prototype.name for some constructor.name.

Can you explain the crux of the problem a bit more? I might try to solve this issue

**Comment by dryajov** [comment]
Actually `libp2p` (as well as `libp2p-swarm`) uses the `.tag` property as the primary way to determine the name of the transport, it uses `.constructor.name` only as a fallback, so it should be possible to just set the `.tag` as the name of the transport. I like this solution and I explicitly set `.tag` to `Circtuit` in the `libp2p-circuit`, for example.

**Comment by diasdavid** [comment]
@fsdiogo is handling this.

**Comment by fsdiogo** [comment]
PR https://github.com/libp2p/js-libp2p/pull/182 fixes this.

**Comment by fsdiogo** [comment]
Check https://github.com/ipfs/js-ipfs/issues/1321 for more info.
