### ISSUE TITLE
Gossipsub v1.1

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#652]
https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md

## Background

Gossipsub is a pubsub router implementation that succeeded Floodsub as the default pubsub router for libp2p and IPFS. Over the last months, the IPFS/libp2p teams have been working on extending the initial version of gossipsub to improve bootstrapping and protocol attack resistance. The extensions change the algorithms that prescribe local peer behaviour and are fully backwards compatible with v1.0 of the protocol. Peers that implement these extensions, advertise v1.1 of the protocol using /meshsub/1.1.0 as the protocol string.

References: 

- https://github.com/ChainSafe/js-libp2p-gossipsub/issues/73

## Milestones

| Milestone | Issue | PR |
|----------|:-------------:|------:|
| `0) Refactor Pubsub base protocol` | N/A | [ChainSafe/js-libp2p-gossipsub#74](https://github.com/ChainSafe/js-libp2p-gossipsub/pull/74) |
| `1) Support topic validators` |  N/A | [ChainSafe/js-libp2p-gossipsub#75](https://github.com/ChainSafe/js-libp2p-gossipsub/pull/75) |
| `2) Full gossipsub v1.1 implementation` |  N/A | TODO |
| `3) Integrate signed peer records` | TODO | TODO |
| `4) Integration on libp2p and ipfs, with interop tests running` |  N/A | TODO |

https://github.com/libp2p/js-libp2p-pubsub/issues/67

**Comment by vasco-santos** [comment]
cc @wemeetagain

I created this Issue to track the gossipsub update work and provide visibility for the `libp2p@0.29` release work. Feel free to change/decouple milesones if it is easier for your side. Meanwhile, we are going to start working on the signed peer records as we need this to gossipsub and rendezvous (#651).

**Comment by jacobheun** [comment]
Done and released in 0.29 🎉
