### ISSUE TITLE
Signed Peer Records

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#653]
https://github.com/libp2p/specs/pull/217

## Background

A libp2p node shares its data publicly (e.g through the DHT) or relies on potentially untrustworthy intermediaries to relay information. This might have consequences as the peer data can be tempered by a third party.

A Signed Peer Record is an all-purpose data container that includes a signature of the data, so we can verify that the data came from a specific peer and that it hasn't been tampered with.

## Milestones

| Milestone | Issue | PR |
|----------|:-------------:|------:|
| `1) Implementation of Signed Peer Records` |  N/A | #681 |
| `2) Identify protocols use Signed Peer Records` |  N/A | #682  |
| `3) Certified Address Book` |  N/A | #683 |
| `4) Pubsub routers use Signed Peer Records` |  N/A | TODO |

**Comment by jacobheun** [comment]
Done and released in 0.29!
