### ISSUE TITLE
libp2p-in-the-browser example: npm install problem

### ISSUE THREAD

**Issue by marcoippolito** [libp2p/js-libp2p#667]
In downloaded the files in https://github.com/libp2p/js-libp2p/tree/master/examples/libp2p-in-the-browser

I get these errors during the installation of npm packages:

    (base) marco@pc01:~/webMatters/vueMatters/libp2p-in-the-browser$ npm install
    npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not 
    recommended for usage due to the number of issues. Please, upgrade your dependencies to the 
    actual version of core-js@3.
    npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar
    3 with 15x less dependencies.
    npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using 
    insecure binaries. Upgrade to fsevents 2.
    npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com
    /request/request/issues/3142
    npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    npm ERR! code ENOLOCAL
    npm ERR! Could not install from "../.." as it does not contain a package.json file.

   npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/marco/.npm/_logs/2020-06-11T16_01_35_213Z-debug.log

Other info:

    Ubuntu 18.04..4 Desktop

    Google Chrome: Version 83.0.4103.97 (Official Build) (64-bit)

    node v14.3.0

    packages already installed:

    "libp2p": "^0.28.0",
    "libp2p-bootstrap": "^0.11.0",
    "libp2p-noise": "^1.1.1",
    "libp2p-webrtc-star": "^0.18.4",
    "libp2p-websockets": "^0.13.6"

**Comment by jacobheun** [comment]
The example assumes you are inside the js-libp2p repo locally. If you change https://github.com/libp2p/js-libp2p/blob/master/examples/libp2p-in-the-browser/package.json#L19 to `"libp2p": "^0.28.0",` it should fix the install error

**Comment by jacobheun** [comment]
Closing this due to lack of response, feel free to open a new issue if you're still having problemss.
