### ISSUE TITLE
Pubsub appears to be opening multiple streams and not closing them

### ISSUE THREAD

**Issue by Stebalien** [libp2p/js-libp2p#668]
On the preload nodes, I'm noticing ~500 connections to js-libp2p peers, but 22K open streams to these peers, most of them inbound pubsub streams. It looks like js-libp2p-pubsub is opening multiple streams per connection and not closing them.

**Comment by Stebalien** [comment]
Hm. This behavior appears to be limited to a few peers. But we should still verify that we're closing streams when done (@jacobheun couldn't find where this was happening).

**Comment by vasco-santos** [comment]
I did a small experiment with a test https://github.com/libp2p/js-libp2p/commit/9f07273d60c6527ac57aee117ac9a593803c9bef
It seems that the stream is being closed after sending messages in the current code for js <-> js with floodsub and gossipsub.

Having js older peers with bidirectional streams talking with js with unidirectional streams could cause issues, but on the preload nodes I still did not understand what might be the issue

**Comment by Stebalien** [comment]
It looks like it's just a few peers with a ton of streams. I'm not sure what's going on there. Could be an old bug, could be a malicious peer, could be anything.

**Comment by vasco-santos** [comment]
@Stebalien do you have any logs or any other information that I can look at?

**Comment by jacobheun** [comment]
@vasco-santos my best guess is that for some reason we're getting multiple connect calls to a peer, https://github.com/libp2p/js-libp2p-pubsub/blob/v0.5.2/src/index.js#L194-L201, and instead of checking for an existing Peer/stream, we're creating a new one to them.

The particular version of libp2p might be hard to track down but we should make sure that pubsub doesn't create new streams for a peer if it already has one.

**Comment by vasco-santos** [comment]
FYI, I created a PR to guarantee that we do not open a new stream if we already have one. However, we should guarantee that the `onConnect` is not called multiple times.

**Comment by jacobheun** [comment]
This should be fixed in the latest pubsub.
