### ISSUE TITLE
Archive deprecated repos

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#670]
Over the last 2 releases significant refactors happened in `js-libp2p` and a few modules were deprecated and will no longer be supported.

Considering that there are some users still using older libp2p versions we will be archiving the repos over time. The ETAs are specified next:

**libp2p@0.27**

| module | deprecation | archive |
|---|---|---|
| [js-libp2p-websocket-star](https://github.com/libp2p/js-libp2p-websocket-star) | 10.06.2020 | 31.07.2020 |
| [js-libp2p-websocket-star-multi](https://github.com/libp2p/js-libp2p-websocket-star-multi) | 10.06.2020  | 10.06.2020  |
| [js-libp2p-websocket-star-rendezvous](https://github.com/libp2p/js-libp2p-websocket-star-rendezvous) | 10.06.2020 | 10.06.2020 |

**libp2p@0.28**

| module | deprecation | archive |
|---|---|---|
|[js-libp2p-stardust](https://github.com/libp2p/js-libp2p-stardust) | 12.06.2020  | 31.07.2020  |
| [js-peer-info](https://github.com/libp2p/js-peer-info) | 12.06.2020  | 31.07.2020  |
| [js-libp2p-keychain](https://github.com/libp2p/js-libp2p-keychain) | 12.06.2020  | 31.07.2020  |

**Comment by vasco-santos** [comment]
@jacobheun now that we released `0.29`, let's go ahead and archive all these repos?

**Comment by jacobheun** [comment]
All have been archived.
