### ISSUE TITLE
Dialer.connectToPeer fails badly if no addrs

### ISSUE THREAD

**Issue by dthorpe** [libp2p/js-libp2p#672]
Version: package.json version or the commit you have installed.
Platform: output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows). If using in a Browser, please share the browser version as well.
Subsystem: if known, please specify affected core module name (e.g Transports, SECIO, etc).

If possible, please provide code that demonstrates the problem, keeping it as
simple and free of external dependencies as you are able.
-->

- **Version**: 0.28.2
- **Platform**: Darwin Kernel Version 17.7.0: Wed May 27 17:00:02 PDT 2020; root:xnu-4570.71.80.1~1/RELEASE_X86_64 x86_64
- **Subsystem**: libp2p/dialer

#### Description:
calling Dialer.connectToPeer with a peer that has no addresses fails with 
> Unhandled Rejection (TypeError): Cannot read property 'length' of undefined

#### Steps to reproduce the error:
```
const peer = new PeerId(Buffer.from("QmfEa1LrSt2R7KiZ31yPo3TT8ipfyDfrMRkaQix3rcXXXX"))
await dialer.connectToPeer(peer)
```

**Comment by jacobheun** [comment]
Fixed by https://github.com/libp2p/js-libp2p/pull/715
