### ISSUE TITLE
ConnectionManager events

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#675]
Creating this per discussion on https://github.com/ChainSafe/js-libp2p-gossipsub/pull/87#discussion_r441104564

There are currently a few inconsistencies with the ConnectionManager events that need to be solved:

> it seems that there are some problems with our current approach of updating IPs, and it seems the events currently emitted by the connection manager are not sufficient for tracking IPs to open connections for peers with scores.
> issue 1: ConnectionManager doesn't emit on closed connections. ConnectionManager#_maybeDisconnectOne, doesn't emit when a connection is closed, more generally, ConnectionManager isn't tracking/emitting on manually closed connections, but rather only on calls to ConnectionManager#onDisconnect.
> issue 2: ConnectionManager emits peer:connect event before storing the emitted connection.
The current approach is to use ConnectionManager#getAll on each peer:connect event for a list of current IPs, but since the event is triggered before the new connection is stored, the call to getAll will not include the new connection unless the event handler awaits the ConnectionManager#onConnect finishing in its entirety. But that potentially also runs into issues re issue 1.

cc @wemeetagain

**Comment by vasco-santos** [comment]
Added this to the #655 Epic issue for `0.30`

**Comment by vasco-santos** [comment]
This should be part of #744 and will be moved to `0.31`

**Comment by wemeetagain** [comment]
ConnectionManager has since been refactored. Closing as stale
