### ISSUE TITLE
UnhandledPromiseRejectionWarning related to StreamHandler

### ISSUE THREAD

**Issue by oed** [libp2p/js-libp2p#679]
- **Version**: 0.27.8
- **Platform**: nodejs linux

#### Description:
We're seeing an unhandled promise rejection in the libp2p circuit code. The error looks like this:
```
(node:21) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
at ClassIsWrapper._onProtocol (/3box-pinning-server/node_modules/libp2p/src/circuit/index.js:45:21)
(node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
```

Looking into the libp2p code it seems to be because `request` variable is undefined: https://github.com/libp2p/js-libp2p/blob/0.27.x/src/circuit/index.js#L45
Observing the `StreamHandler` it appears that if `msg.value` is undefined the method will not reach a return statement, which is likely what is causing the error: https://github.com/libp2p/js-libp2p/blob/0.27.x/src/circuit/circuit/stream-handler.js#L31-L42

Looks like this code is the same in `0.28.x`.

#### Steps to reproduce the error:
Unfortunately I don't yet know how to reproduce the issue. I've seen it a few times in our production environment.

Not really sure how sever this might be (we are currently investigating some service degradation, but this might be unrelated).

**Comment by jacobheun** [comment]
Circuit needs some improved error handling, I'm seeing a few other areas we need to be catching errors.

Not sure on the underlying issues yet. Since `msg.value` is undefined the read stream _should_ have ended, so there might be a stream being opened without any request being send.

**Comment by geolffreym** [comment]
same over here
```
(node:90237) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
    at ClassIsWrapper._onProtocol (.../node_modules/libp2p/src/circuit/index.js:46:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Comment by vasco-santos** [comment]
This second issue should be fixed by https://github.com/libp2p/js-libp2p-websockets/pull/118

**Comment by vasco-santos** [comment]
With the upcoming `libp2p@0.31` this will be fixed as with the types work the optional request value is validated before crashing on `type` of undefined. Relevant change on: https://github.com/libp2p/js-libp2p/blob/v0.31.0-rc.2/src/circuit/transport.js#L61

**Comment by vasco-santos** [comment]
This should be fixed with the new released we just fixed 🎉  If it is not the case, please reopen the issue
