### ISSUE TITLE
Preserve PeerInfos discovered

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p#68]
As brought up here: https://github.com/libp2p/js-libp2p/pull/64/files#r108192190

With the DHT, we will want to preserve PeerInfos discovered. This is also the start of having a way to add info about each Peer we know for statistics.

**Comment by dignifiedquire** [comment]
I would suggest using the `peerBook` to keep a record of all peers and details we have seen. In addition keeping a simple map `peers` or `connectedPeers` which are only `{[id: PeerIdString]:  Multiaddr}` and record the information about current connections

**Comment by diasdavid** [comment]
Another feature to add is the ability to dump to disk the PeerBook, so that we can shutdown and boot the node and get back almost every connection

**Comment by dignifiedquire** [comment]
yes, that should be easy to do now that we have the datastore

**Comment by dignifiedquire** [comment]
we could actually move the peerbook to be a direct wrapper round reading and writing to the datastore instead of in memory that way we consume less memory and it's directly backed up

**Comment by diasdavid** [comment]
@dignifiedquire that would be quite nice! As long as there is some queueing for the writes, so that we don't stress with a 'good to have but not strictly necessary' operation that does lot of IO

**Comment by dignifiedquire** [comment]
I can easily write datastore wrapper that batches ops if many come in at once :) but those read and writes to leveldb/indexedb are pretty cheap as well.

**Comment by dignifiedquire** [comment]
Though warning, it will make the whole peerbook api async

**Comment by diasdavid** [comment]
@dignifiedquire we can keep it sync, with an interval that flushes it.

**Comment by diasdavid** [comment]
@dignifiedquire on repo open, it should just load all the peerBook into memory.

**Comment by diasdavid** [comment]
This has been done \o/
