### ISSUE TITLE
Programmatically set agentVersion in Identify

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#686]
## Overview

When handling Identify requests we are just sending a static, constant `agentVersion` of `'js-libp2p/0.1.0'`. This is unhelpful and should be dynamic. The agentVersion can be set to any string. What we should be doing is specifying the package name and package version in the agentVersion. This can enable us to better identify applications on the network and see how the public network is upgrading over time.

## Proposed Changes
- Specify a default `agentVersion` of `js-libp2p/<libp2p.version>` ex: (`js-libp2p/0.28.3`)
- When used in another application, such as a js-ipfs daemon, specify an `agentVersion` of `<package.name>/<package.version>` ex: (`ipfs/0.47.0`)
- When running in Node.js, append the node version. ex: (`js-libp2p/<libp2p.version> UserAgent=<process.version>`)
- When running in browser, append the browser UserAgent. ex: (`js-libp2p/<libp2p.version> UserAgent=<navigator.userAgent>`)

go-libp2p already does this for Identify, without the UserAgent information. At a minimum we should include the app name and version name, but the UserAgent would also be useful.

**Comment by vasco-santos** [comment]
This was partially on https://github.com/libp2p/js-libp2p/pull/800 we should add the UserAgent though
