### ISSUE TITLE
Unclear setup/instructions for rendezvous server behind SSL

### ISSUE THREAD

**Issue by 0xjjpa** [libp2p/js-libp2p#692]
- **Version**: `0.27.x`
- **Platform**: `nodejs`

#### Type:
Enhancement

#### Severity:
Very Low

#### Description:
See https://github.com/libp2p/js-libp2p-webrtc-star/issues/238, https://github.com/libp2p/js-libp2p-webrtc-star/issues/180. In short, for being able to quickly start with the [libp2p-in-the-browser](https://github.com/libp2p/js-libp2p/tree/0.27.x/examples/libp2p-in-the-browser) demo, one needs to start a signaling start server. Locally, these instructions are pretty clear, but on any other setup (i.e. online demo like Stackblitz or Glitch), this is not obvious, particularly when behind SSL. A warning label in the README would be enough, in addition to the URLs of the existing servers ready to use.

As anadditional note, it would be useful to have a status dashboard for the existing servers (i.e. https://wrtc-star2.sjc.dwebops.pub/, https://wrtc-star1.par.dwebops.pub/) as to know the status of these ones for running demos online.

#### Steps to reproduce the error:

1. Clone https://github.com/libp2p/js-libp2p and switch to branch `0.27.x`
2. Go to the [libp2p in the browser example](https://github.com/libp2p/js-libp2p/tree/0.27.x/examples/libp2p-in-the-browser).
3. Change the start function inside `package.json` from `parcel index.html` to `parcel index.html --https`
4. Run signaling server with `npm run server` and application with `npm run start`
4. Open browser and see mixed content error.

**Comment by jjperezaguinaga** [comment]
@jacobheun @vasco-santos I've described in https://github.com/libp2p/js-libp2p-webrtc-star/issues/238 how to deploy a `wrtc-signaling-star` server behind SSL, which can then be used by an online application. To demonstrate this, I went ahead and created a [Glitch demo](https://glitch.com/edit/#!/libp2p-browser-demo?path=package.json%3A29%3A39) with the `libp2p-browser-demo` code in this repo using `0.27.x`. You can see it running on https://libp2p-browser-demo.glitch.me/ (takes a bit to load, cloud stuff doing p2p stuff, yay).

Glitch has some cool features, like their Remix button which looks something like this:

[![Remix on Glitch](https://cdn.glitch.com/2703baf2-b643-4da7-ab91-7ee2a2d00b5b%2Fremix-button.svg)](https://glitch.com/edit/#!/remix/libp2p-browser-demo)

Clicking on that one will allow anyone in Glitch to create their own “fork” of the project, bringing the “time for demo” to seconds. This setup can likely be replicated in Stackblitz and Codesandbox, but I haven't tried those. I know that @xpepermint from [0xcert](https://0xcert.org/) used those some time ago (see one of their [examples](https://stackblitz.com/edit/atomic-order-example)). Maybe we could have more `libp2p` online demos for beginners?

**Comment by maschad** [comment]
Closing as these transports have been deprecated, please migrate to the https://github.com/libp2p/js-libp2p/tree/master/packages/transport-webrtc transport
