### ISSUE TITLE
Production Infrastructure docs

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#696]
## Background

IPFS/libp2p projects provide own infrastructure for enabling their users to learn the introductory concepts first and experiment with its functionalities.

These infrastructure pieces should not be used in production and only for experimentation. This issue should track the creation of several documents to guide users on the road from experimenting to production.

## Proposal

Create an `INFRASTRUCTURE.md` document with guides for setting up own infrastructure for each type of deployment needs, such as:

- [ ] `webrtc-star` signalling servers
- [ ] delegate routers
- [ ] relay server nodes
- [ ] rendezvous server nodes

References:

- https://github.com/libp2p/js-libp2p/pull/507
- https://github.com/libp2p/js-libp2p/pull/706
- https://discuss.libp2p.io/t/cant-connect-to-webrtc-star-with-ssl/522
- https://github.com/ipfs/js-ipfs/issues/2779

**Comment by vasco-santos** [comment]
cc @jacobheun

**Comment by maschad** [comment]
The components mentioned in this stack have been deprecated or are discouraged from use. Please explore:

- https://github.com/libp2p/js-libp2p/tree/master/packages/transport-webrtc
- https://cid.contact/

as substitutes
