### ISSUE TITLE
[discovery] Add support for AutoRelay

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#699]
AutoRelay enables libp2p nodes to dynamically find and bind to relays on the network. Once binding (listening) is done, the node can and should advertise its addresses to the network, allowing any other node to dial it over its bound relay(s). While direct connections to nodes are preferable, it's not always possible to do so due to NATs.

##### A connected relay
The Circuit Relay module has the ability to ask connected nodes if they support the relay `HOP` protocol. If they do, the libp2p node can bind to that relay as a listener. A node **should** record a list of relays and use only a subset of those to avoid binding to a large number of relays, as this is not considerate to those relays.

1. When a node connects to a peer that announces support for the relay protocol, `/libp2p/circuit/relay/0.1.0`, it may ask that node if it support `HOP`.
1. If the peer supports `HOP`, libp2p should add it to its list of known relays.
1. When a known relay is added, libp2p should check to see if it needs a/another relay (to meet some min threshold). If below that threshold, libp2p should bind to that relay and add it to its announced addresses.
   1. When adding announced addresses, libp2p **SHOULD** avoid adding private addresses of the relay, such as `/ip4/127.0.0.1/tcp/4001`.
   1. If libp2p does not have enough known relays, it should [query the network](#remote-relays) if possible.
1. When libp2p updates its addresses, it should update the network.

##### Remote Relays

When a node with AutoRelay enabled boots, it should search the network for the relay protocol, `/libp2p/relay`. This search may be done via one of several options leveraging `libp2p.contentRouting.findProviders()`. Depending on what features are turned on this may include: the DHT, Delegate Routing, and/or the Rendezvous Protocol (WIP).

If a node does not have enough known relays connected, and is unable to connect to other known relays, it should query the network for more relays. This should be done with a backoff to avoid spamming queries.

**References**:
- [Cant connect to /p2p-circuit peers](https://github.com/ipfs/go-ipfs/issues/7433#issuecomment-656410330)
- [go-libp2p AutoRelay](https://github.com/libp2p/go-libp2p/blob/v0.10.0/p2p/host/relay/autorelay.go)

**Comment by vasco-santos** [comment]
After discussing with @jacobheun I am planning on dividing this effort in a set of PRs as follows:

| Milestone | PR | State |
|----------|:-------------:|------:|
| `1) Relay topology - initial implementation` |  #723  | WIP |
| `2) Avoid announcing private addresses` |  #723  | WIP |
| `3) Identify push integration` |  #723  | WIP |
| `4) Connection keep alive + remote listener drop` |  #723  | WIP |
| `5) Query the network for relays` |  #723  | WIP |

WIP NOTES:

## Milesone 1

- When a node connects to a peer that announces support for the relay protocol, /libp2p/circuit/relay/0.1.0, it may ask that node if it support HOP.
- If the peer supports HOP, libp2p should add it to its list of known relays.
- `maxListeners`

## Milesone 2

- Avoid announcing private addresses

## Milestone 3

- Identify push with multiaddrs update

## Milestone 4

-  connection keep alive + remote listener drop
(We should make sure that we eventually are reconnecting to nodes we're listening on (relays and webrtc))

## Milestone 5

- If libp2p does not have enough known relays, it should query the network if possible.

**Comment by vasco-santos** [comment]
This is partially implemented from `0.30`. We do need to improve the logic around finding remote relays on the network:

> If a node does not have enough known relays connected, and is unable to connect to other known relays, it should query the network for more relays. This should be done with a backoff to avoid spamming queries.

**Comment by maschad** [comment]
Close as CircuitRelay v2 has an equivalent auto relay feature built-in.
