### ISSUE TITLE
transport: µTP

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p#7]
> [Micro Transport Protocol or µTP (sometimes also uTP) is an open UDP-based variant of the BitTorrent peer-to-peer file sharing protocol intended to mitigate poor latency and other congestion control issues found in conventional BitTorrent over TCP, while providing reliable, ordered delivery](https://en.wikipedia.org/wiki/Micro_Transport_Protocol)

Following [libp2p implementation in Go](https://github.com/ipfs/go-libp2p) and [go-ipfs](https://github.com/ipfs/go-ipfs) supporting utp as a transport. @masylum has initiated the work to build the [libp2p-utp](https://github.com/diasdavid/js-libp2p-utp) shim that enables libp2p to use [multiaddr](ub.com/jbenet/mu) instead of ip:port pairs and @mafintosh [is working on the single uTP implementation available in JS](https://github.com/mafintosh/utp)

How can you help:
- Contributing to https://github.com/mafintosh/utp -> TODO: https://github.com/mafintosh/utp/blob/master/TODO

Reference links:
- Original uTP implementation (C++) - https://github.com/bittorrent/libutp
- Low Extra Delay Background Transport LEDBAT http://tools.ietf.org/html/rfc6817 (note: Details of the µTP implementation are different from Spec: http://forum.bittorrent.org/viewtopic.php?pid=753#p753 - currently being unable to access )

**Comment by diasdavid** [comment]
# here
https://github.com/libp2p/js-libp2p-utp

**Comment by jollysean** [comment]
Does this work on cellular network of 3G/4G?
Any tests done yet. Please let me know if I can build one

**Comment by montassarBoukraine** [comment]
libp2p doesn't work with 3g/4g .
