### ISSUE TITLE
[tests] fix flakey pubsub test

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#709]
One of the pubsub tests intermittently fails with timeout issues, we need to correct this. Here is the log of the failing test:

```log
Pubsub subsystem operates correctly
       pubsub with intermittent connections
         should handle quick reconnects with a delayed disconnect:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/build/libp2p/js-libp2p/test/pubsub/operation.node.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

**Comment by vasco-santos** [comment]
@jacobheun can you replicate this locally?
I have never seen that test failing and I just tried it out locally several times running only the pubsub tests

**Comment by jacobheun** [comment]
No, i've just seen it in CI. The latest run was linux node 10 here, https://github.com/libp2p/js-libp2p/runs/869245153. We likely just need the test to be more thorough with when events are happening.

**Comment by vasco-santos** [comment]
I could not replicate it yet. Let me know if you see this in CI again. https://github.com/libp2p/js-libp2p/pull/698 might also help with this

**Comment by vasco-santos** [comment]
I got it now, it is stil la valid issue: https://travis-ci.com/github/libp2p/js-libp2p/jobs/361764759
