### ISSUE TITLE
Memory leak with usage of Pubsub

### ISSUE THREAD

**Issue by Strernd** [libp2p/js-libp2p#712]
- **Version**: ^0.28.7
- **Platform**: 18.7.0 Darwin Kernel Version 18.7.0, replicated on AWS EC2 Linux machines
- **Subsystem**: Not sure, but I think Gossipsub/Pubsub

#### Steps to reproduce the error:
I created a [repository](https://github.com/Strernd/libp2p-example) to examine the problem. The readme includes the necessary steps. 
It launches a docker environment with 4 nodes, that send pubsub messages every 100-200ms each. A fifth node can be launched out of docker to attach an inspector. 

Here are two screenshots from the inspector. The first one is taken right at the start and the second one two minutes after that.
![Screenshot 1](https://i.imgur.com/ET9OWJX.png)
![Screenshot 2](https://i.imgur.com/mLu8AMu.png)

**Comment by vasco-santos** [comment]
@Strernd

Thanks for reporting this. Did you experiment it with the DHT disabled as well?

**Comment by Strernd** [comment]
Not yet. I will run another test with DHT disabled now.

**Comment by Strernd** [comment]
Seems like it doesn't change anything.
I set dht.enabled to false and dht.randomWalk.enabled to false.

**Comment by Strernd** [comment]
https://upload.clinicjs.org/public/81df76fc586c28088b678e53cdf083b025c9fd3baa7d1496de5d6849842b9b08/17509.clinic-doctor.html

**Comment by jacobheun** [comment]
@Strernd can you check if updating `stream-to-it` resolves the problem? It looks like your lock file is at 0.2.0. There were some memory leaks there affecting transports. Can you upgrade `stream-to-it` to 0.2.2 and see if that resolves the issue?

**Comment by Strernd** [comment]
Whew, looks much better now. I'll patch this to my main service where I noticed the problem initially, but so far it seems solved.

**Comment by Strernd** [comment]
Looks pretty good right now. Sorry for the false alarm and thanks very much for the quick support.
