### ISSUE TITLE
[keychain] support rotating keychain passphrase

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#728]
It should be possible to rotate/update your keychain passphrase. This should require the old and new passphrase. All keys should be imported with the old passphrase and then exported and stored with the new passphrase.

**Comment by zeim839** [comment]
@jacobheun I've been working on a possible implementation that looks somewhat like this:
```js
var newKeychain = new Keychain(this._options.keychain.datastore, { pass: newPassword })
var oldKeychain = await this.keychain.listKeys();
oldKeychain.forEach(async key => {
    if (key.name != "self"){
        var data = await this.keychain.exportKey(key.name, oldPassword)
        await this.keychain.removeKey(key.name)
        await newKeychain.importKey(key.name, data, newPassword)
     }
})
this.keychain = newKeychain;
```
However, it seems that the keys/passwords are somehow bound together in the datastore, meaning I can't import keys into the new keychain with the new password (I'm getting the `Error: Cannot read the key, most likely the password is wrong` error).

There's also the issue of how to operate on the "self" key, as the `importKey()` (and other) functions deem it an "invalid key name". See [here](https://github.com/libp2p/js-libp2p/blob/master/src/keychain/index.js#L408) for example.

Let me know your thoughts/suggestions.

**Comment by zeim839** [comment]
Seems I was confused on how the the keychain and crypto functions work (`keychain.importKey()` vs `crypto.keys.import` and etc.). Anyway, I've come up with a rough solution that looks like this:

```js
async changeKeychainPassword(oldPassword, newPassword){
    if (typeof oldPassword !== 'string' || typeof newPassword !== 'string') {
      throw new Error(`Invalid pass type '${typeof oldPassword}'`);
    }
    if (newPassword.length < 20) {
      throw new Error('pass must be least 20 characters')
    }
    // TODO: Need to decide on how to import/generate opts
    const newDek = newPassword
      ? crypto.pbkdf2(
        newPassword,
        this.opts.dek.salt,
        this.opts.dek.iterationCount,
        this.opts.dek.keyLength,
        this.opts.dek.hash)
      : ''
    const oldDek = privates.get(this).dek
    privates.set(this, { "dek":newDek })
    var keys = await this.listKeys()
    await keys.forEach(async key =>{
      // TODO: Decide how to handle deleting and importing the "self" key. 
          // importKey and removeKey throw an error when handling "self"
      if (key.name != "self"){
        var keyAsPEM = await this._getPrivateKey(key.name)
        await this.removeKey(key.name)
        this.importKey(key.name, keyAsPEM, oldDek)
      }
    })
  }
```
[src/keychain/index.js](https://github.com/zeim839/js-libp2p/blob/keychain-rotating-passphrase/src/keychain/index.js#L507)

What's left is to decide how to handle the "self" key (`this.importKey()` throws an error on "self") and how to handle changing passwords in the context of src/index.js (see [here](https://github.com/zeim839/js-libp2p/blob/keychain-rotating-passphrase/src/index.js#L209)). I'm trying to be cautious/minimal with the changes I make so I'd appreciate some suggestions on how to proceed.

**Comment by vasco-santos** [comment]
This was shipped on https://github.com/libp2p/js-libp2p/releases/tag/v0.31.6
