### ISSUE TITLE
[upgrader] onOutboundStream handler feature

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#732]
- **Version**: N/A
- **Platform**: N/A
- **Subsystem**: Upgrader/Muxer

#### Description:

Some libp2p subsystems might need to track their own streams, like the libp2p pubsub implementations. When this is a need for libp2p users, the current libp2p upgrader provides an `onStream` handler that allows subsystems to get notified of a new inbound stream in a connection. However, users cannot be informed when and outbound stream is created.

Libp2p should provide a mechanism for users to track what is happening in their protocols. An handler `onOutbandStream` should be provided by libp2p upgrader for this context.

#### Steps to reproduce:

Taking into account the pubsub subsystem (from `0.7`), when an inbound pubsub stream is opened the previous inbound stream in that connection (if exists) will be replaced by the new one. However, the same will not happen for outbound streams. This can cause issues like the following:

If two libp2p pubsub nodes do more than one `libp2p.dialProtocol` between them (with the same open connection), the second time only the inbound stream is properly updated. As a consequence, nodes will not be able to properly exchange messages between them. This is an edge case and it should not be done, but it should be protected in case it happens.

cc @wemeetagain

**Comment by jacobheun** [comment]
We shouldn't look at adding this as a peer feature to `onStream`. The `onStream` logic in the upgrader is explicitly for protocol handling.

> If two libp2p pubsub nodes do more than one libp2p.dialProtocol between them (with the same open connection), the second time only the inbound stream is properly updated

While I think there is merit in supporting listeners for inbound and outbound streams, the problem mentioned in this description is a logic bug, as a second outbound stream shouldn't be created. `libp2p.dialProtocol` should really never be used outside of the application implementing that protocol as it leads to problems like this.

**Comment by vasco-santos** [comment]
I have found another scenario.
I did not debug it yet, but these [2 tests](https://github.com/libp2p/js-libp2p/blob/master/test/pubsub/operation.node.js#L193-L321) are failing due to the abort in https://github.com/libp2p/js-libp2p-pubsub/blob/v0.6.x/src/peerStreams.js#L110
There is no `dialProtocol` afaik in the flows of these tests.
