### ISSUE TITLE
Listening on TCP and WS causes TypeError

### ISSUE THREAD

**Issue by AuHau** [libp2p/js-libp2p#737]
- **Version**: libp2p@0.28.10, libp2p-websockets@0.14.0
- **Platform**: Darwin MacyOne.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
- **Subsystem**: TCP/WS, MDNS

#### Description:

If I will specify two multiaddrs to listen on as follow:
```
addresses: {
  listen: [
    "/ip4/127.0.0.1/tcp/6030",
    "/ip4/127.0.0.1/tcp/6031/ws"
  ]
}
```

Then `libp2p.start()` crashes with:

```
Using ts-node version 8.10.2, typescript version 3.9.7
(node:86749) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'byteLength' of undefined
    at equals (/Users/adam/Projects/iovlabs/rif-communications-pubsub-node/node_modules/uint8arrays/equals.js:15:26)
    at ClassIsWrapper.equals (/Users/adam/Projects/iovlabs/rif-communications-pubsub-node/node_modules/libp2p-tcp/node_modules/multiaddr/src/index.js:366:10)
    at /Users/adam/Projects/iovlabs/rif-communications-pubsub-node/node_modules/libp2p/src/index.js:359:50
    at Array.findIndex (<anonymous>)
    at /Users/adam/Projects/iovlabs/rif-communications-pubsub-node/node_modules/libp2p/src/index.js:359:19
    at Array.filter (<anonymous>)
    at Libp2p.get multiaddrs [as multiaddrs] (/Users/adam/Projects/iovlabs/rif-communications-pubsub-node/node_modules/libp2p/src/index.js:357:8)
    at new MulticastDNS (/Users/adam/Projects/iovlabs/rif-communications-pubsub-node/node_modules/libp2p-mdns/src/index.js:23:42)
    at setupService (/Users/adam/Projects/iovlabs/rif-communications-pubsub-node/node_modules/libp2p/src/index.js:552:30)
    at Libp2p._setupPeerDiscovery (/Users/adam/Projects/iovlabs/rif-communications-pubsub-node/node_modules/libp2p/src/index.js:567:7)
```

If I specify two `TCP` multiaddrs or two `WS` multiaddrs then it work as expected.

Maybe it is caused by inconsistent versions of multiaddr dependencies (Buffer vs. Uint8Array) across the stack as if `npm ls multiaddr` I get:

<details>
<summary>List of multiaddr versions</summary>
```
├─┬ @rsksmart/rif-communications-pubsub@0.1.0-dev.7
│ ├─┬ libp2p-bootstrap@0.11.0
│ │ └── multiaddr@7.5.0  deduped
│ ├─┬ libp2p-kad-dht@0.20.1
│ │ ├─┬ libp2p-interfaces@0.4.1
│ │ │ └── multiaddr@8.0.0  deduped
│ │ └── multiaddr@8.0.0 
│ ├─┬ libp2p-mdns@0.14.3
│ │ └── multiaddr@7.5.0  deduped
│ ├─┬ libp2p-secio@0.13.1
│ │ ├─┬ libp2p-interfaces@0.4.1
│ │ │ └── multiaddr@8.0.0  deduped
│ │ └── multiaddr@8.0.0 
│ ├─┬ libp2p-tcp@0.15.1
│ │ ├─┬ libp2p-utils@0.2.0
│ │ │ └── multiaddr@8.0.0  deduped
│ │ ├─┬ mafmt@8.0.0
│ │ │ └── multiaddr@8.0.0  deduped
│ │ └── multiaddr@8.0.0 
│ ├─┬ libp2p-webrtc-star@0.18.6
│ │ └── multiaddr@7.5.0  deduped
│ └─┬ libp2p-websockets@0.14.0
│   ├─┬ libp2p-utils@0.2.0
│   │ └── multiaddr@8.0.0  deduped
│   ├─┬ mafmt@8.0.0
│   │ └── multiaddr@8.0.0  deduped
│   ├── multiaddr@8.0.0 
│   └─┬ multiaddr-to-uri@6.0.0
│     └── multiaddr@8.0.0 
└─┬ libp2p@0.28.10
  ├─┬ libp2p-interfaces@0.3.2
  │ ├─┬ libp2p-tcp@0.14.6
  │ │ └── multiaddr@7.5.0  deduped
  │ └── multiaddr@7.5.0  deduped
  ├─┬ libp2p-utils@0.1.3
  │ └── multiaddr@7.5.0  deduped
  ├─┬ mafmt@7.1.0
  │ └── multiaddr@7.5.0  deduped
  └── multiaddr@7.5.0 
```
</details>

**Comment by vasco-santos** [comment]
Hello @AuHau 
We are working on updating dependencies for the next libp2p release `libp2p@0.29`. You are using `libp2p-websockets@0.14.0` which should not be used by `libp2p@0.28` as it has breaking changes across the stack that are being coordinated for `libp2p@0.29`. We have released `libp2p-websockets@0.14.0` with a `beta` tag https://www.npmjs.com/package/libp2p-websockets
You need to use the latest tag `libp2p-websockets`.

**Comment by AuHau** [comment]
Hey @vasco-santos 

Thanks a lot from prompt reply! You are right! I have downgraded the versions and it works as expected :-) 

Interesting thing is that dependabot apparently does not respect NPM tags and that is the reason why we ended up with these versions... 

I am closing this issue and one more thanks!

**Comment by vasco-santos** [comment]
> Interesting thing is that dependabot apparently does not respect NPM tags and that is the reason why we ended up with these versions...

Thanks for letting me know that. Perhaps it looks into the releases in github. I will make sure we evaluate that before a new release happens to avoid these issues
