### ISSUE TITLE
Event `peer:disconnect`

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/js-libp2p#74]
I need to detect the event of peers disconnecting on the DHT. Proposed api

```js
libp2p.on('peer:disconnect', (peer) => {
})
```

**Comment by dignifiedquire** [comment]
cc @diasdavid

**Comment by diasdavid** [comment]
there is a `peer-mux-closed` event that is exactly what you are asking, bitswap uses it: https://github.com/ipfs/js-ipfs-bitswap/blob/master/src/components/network/index.js#L41

I'm happy to rename it.

**Comment by dignifiedquire** [comment]
@diasdavid that's on the swarm level, with the new api we have the nice `libp2p.on('peer')` that's why I was suggesting this

**Comment by diasdavid** [comment]
Ah, but that is peer discovered, not peer connected. We could move to:

- `libp2p.on('peer:discovery')` (current just 'peer')
- `libp2p.on('peer:connect')` (current just 'peer')
- `libp2p.on('peer:disconnect')` (current just 'peer')

**Comment by dignifiedquire** [comment]
I like that, the current setup is confusing (at least it was for me)

**Comment by diasdavid** [comment]
A CR my kind sir 🎩

- [ ] https://github.com/libp2p/js-libp2p/pull/75
- [ ] https://github.com/ipfs/js-ipfs-bitswap/pull/133
- [ ] https://github.com/ipfs/js-ipfs/pull/818
