### ISSUE TITLE
"Chat" example prints errors

### ISSUE THREAD

**Issue by mcclure** [libp2p/js-libp2p#754]
Tested with
MacOS 10.13.6
node v14.10.1
Tested with v2.29.0

Steps: As examples/chat/README instructs, I run npm install in the root, then run listener.js in one window and dialer.js in the other.

When either window receives its first message— there are no errors at boot, but when a message comes in, on the first of those messages— It prints first an error message, then an error message about how the error message was handled.

```
Pearl:src mcc$ node listener.js 
Listener ready, listening on:
/ip4/127.0.0.1/tcp/10333/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm
/ip4/127.51.68.120/tcp/10333/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm
/ip4/192.168.68.113/tcp/10333/p2p/QmcrQZ6RJdpYuGvZqD5QEHAv6qX4BrQLJLQPQUrTrzdcgm
connected to:  Qma3GsJmB47xYuyahPZPSadh1avvxfyYQwk8R3UnFrQ6aP
(node:50617) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "input" argument must be an instance of ArrayBuffer or ArrayBufferView. Received an instance of BufferList
    at TextDecoder.decode (internal/encoding.js:410:15)
    at toString (/Users/mcc/work/h/tempt/tmp/zdocs/js-libp2p/node_modules/uint8arrays/to-string.js:37:24)
    at /Users/mcc/work/h/tempt/tmp/zdocs/js-libp2p/examples/chat/src/stream.js:32:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:50617) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:50617) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Severity: Probably not high, but this could indicate something more problematic?

(I tried to test with master fb4b2734d3 but am hitting some kind of problem with `npm install` printing zillions of ENOENTs on lodash with that commit so have not yet been able to run the test. It seems to be an npm issue so I am debugging that.)

**Comment by mcclure** [comment]
Tested with master fb4b2734d3ce15. Did **not** reproduce the error message[s]. I guess you can close this.

**Comment by mcclure** [comment]
Tested 0.30.x branch commit bd26bde876bf8ec, did **not** reproduce there either.

**Comment by jacobheun** [comment]
One of the Uint8Array conversions in the example we made for the release was incorrect, it was fixed in https://github.com/libp2p/js-libp2p/pull/742.

Thank you for submitting these issues as you find them! ❤️
