### ISSUE TITLE
[docs] Add configuration example in docs for Bootstrap

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p#756]
We currently don't have any docs in the configuration readme on how to setup libp2p-bootstrap. Additionally the readme in that repo doesn't provide a useful example of how to use it with libp2p.

We should:
1. Update https://github.com/libp2p/js-libp2p/blob/master/doc/CONFIGURATION.md to include a configuration code snippet for Bootstrap
2. Update the https://github.com/libp2p/js-libp2p-bootstrap#usage section in `libp2p-bootstrap` to show how it's actually configured in `libp2p`.

**Comment by a1300** [comment]
Relates to #807
