### ISSUE TITLE
Address Manager should be responsible for create/update self peer record

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#759]
The AddressManager should be responsible both for creating and updating the self peer record over time, as listen addresses or announce/nonAnnounce  are updated.

This functionality currently lives on the TransportManager, which should only be responsible for the listeningAddresses.

The AddressManager should also be responsible for tracking the peer's observed addresses.

References:
- https://github.com/libp2p/js-libp2p/pull/748

**Comment by maschad** [comment]
Closing as this has been implemented
