### ISSUE TITLE
Failed Peer Discovery

### ISSUE THREAD

**Issue by kottackalsulvin** [libp2p/js-libp2p#777]
Hi,

I am working on a webcam app using libp2p. Inorder to connect the peers, I tried the below libp2p code but it didn’t worked for me. 

**App.js Code**

```
const SIGNAL_SERVER = '/ip4/127.0.0.1/ws/p2p-webrtc-star/ipfs/:peer-id'

const node = new Node({peerInfo})

// start libp2p

node.start((err) => {
console.log("in start node");
if (err) callback(err)
callback(null, node)
})

...........
............

class Node extends libp2p {

//The options to use when generating the libp2p node

constructor (peerInfo, peerBook, options) {  
options = options || {}
const wstar = new WebRTCStar({ wrtc })

// The libp2p module

const defaults = {
modules: {
transport: [ new WS(), wstar ],
streamMuxer: [ mplex ],
connEncryption: [ secio ],
peerDiscovery: [wstar.discovery ],
}
}
super(defaultsDeep(defaults,
}
}
.............
.................
node.on('peer:discovery', (peerInfo) => {
console.log('Peer Discovered:')
})
```

It didn’t displays any error but the peers are not discovering each other.Please help me to resolve this issue.

**Environment**

Npm:6.13.4
Node:10.18.1
Libp2p:0.25.4
libp2p-webrtc-star: 0.13.2
libp2p-websockets: 0.12.2

**Comment by jacobheun** [comment]
Have you tried upgrading to libp2p 0.29? There have been some significant updates since 0.25

**Comment by kottackalsulvin** [comment]
@jacobheun Thanks for your reply. 
I upgraded to libp2p 0.26.2, but nothing changed. The below error is shown, when upgraded to 0.29.0 

```
ERROR in ./node_modules/abortable-iterator/index.js
Module parse failed: Unexpected token (13:17)
You may need an appropriate loader to handle this file type.
|   signals = signals.map(({ signal, options }) => ({ signal, options: options || {} }))
| 
|   async function * abortable () {
|     let nextAbortHandler
|     const abortHandler = () => {
 @ ./node_modules/libp2p-utils/src/stream-to-ma-conn.js 3:18-47
 @ ./node_modules/libp2p/src/circuit/index.js
 @ ./node_modules/libp2p/src/index.js
 @ ./app/backend/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 ./app/backend/app.js
```

**Comment by kottackalsulvin** [comment]
**webpack.config.js**

```
module: {
    rules: [
      {
      test: /\.js$/,
             exclude: {
          test: /(node_modules|bower_components)/,
         not: [/libp2p/,/p-queue/,/orbit-db-access-controllers/]
        },
      use: {
        loader: 'babel-loader',
        options: {
          presets: [
            [
              'env',
              {
                targets: {
                  node: '10.18.0'
                }
              }
            ]
          ],
          plugins: [
            'transform-object-rest-spread',
            'transform-class-properties'
          ]
        }
      }
    }
  ]
  },

  node:{
    dgram:'empty',
    fs:'empty',
    net:'empty',
    tls:'empty'
  }
```

**Comment by jacobheun** [comment]
The error from 0.29 is because you need to use a modern JS preset for babel like https://babeljs.io/docs/en/babel-preset-env, to handle the async generators. See the js-ipfs webpack example for reference https://github.com/ipfs/js-ipfs/blob/ipfs%400.50.2/examples/browser-webpack/webpack.config.js#L36

**Comment by kottackalsulvin** [comment]
@jacobheun Thank you, that resolved my issue in webpack. But while running the app, below error is shown

`Uncaught TypeError: Cannot read property 'toB58String' of undefined`

**App.js**

```
const PeerId = require('peer-id');
const PeerInfo = require('peer-info');

startOwnPeerfn: function () { 
const startOwnPeer = (callback) => {
PeerId.create((err, peerId) => { 
if (err) callback(err)

const SIGNAL_SERVER = '/ip4/127.0.0.1/ws/p2p-webrtc-star/ipfs/:peer-id' 

const peerInfo = new PeerInfo(peerId)
const peerBook = new PeerBook()
const mh1 = Multiaddr(SIGNAL_SERVER.replace(':peer-id', peerId.toB58String()))
const peerIdd = mh1.getPeerId()
peerInfo.multiaddrs.add(mh1);

const node = new Node({peerInfo})

node.start((err) => {
console.log("in start node");
if (err) callback(err)
callback(null, node)
})
})
}

startOwnPeer((err, node) => {
console.log("in window start own peer");
})
}
```

**Comment by vasco-santos** [comment]
@kottackalsulvin From an initial perspective this seems related to using `peer-info`, which was deprecated in `libp2p@0.28`. You can see how to change this in [libp2p/js-libp2p/doc/migrations/v0.27-v0.28.md#migrating-from-peer-info](https://github.com/libp2p/js-libp2p/blob/master/doc/migrations/v0.27-v0.28.md#migrating-from-peer-info).

It also seems you are still using callbacks and peerBook, which are also not used anymore. I highly recommend you check the migration guides [available](https://github.com/libp2p/js-libp2p/tree/master/doc/migrations) while updating to 0.29

**Comment by kottackalsulvin** [comment]
@vasco-santos How to connect peers in the browser? Peers are discovered but cannot dial to other peers.

**App.js**

startOwnPeerfnVideo: function () { 

//const wstar = new WebRTCStar({ wrtc })

;(async () => {
const node = await libp2p.create({
addresses: {
listen: [
'/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star',
'/dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star' 
] 
},
modules: {
transport: [WS, WebRTCStar],
connEncryption: [secio],
streamMuxer: [mplex],
// peerDiscovery:[wstar.discovery]​
}

}) 

node.on('peer:discovery', (peerId) => {
console.log('Discovered:', peerId.toB58String()) //peers discovered
})

node.connectionManager.on('peer:connect', (connection) => {
console.log('Connection established to:', connection.remotePeer.toB58String()) 
})
await node.start()
})();
},

**Comment by vasco-santos** [comment]
This seems good. Perhaps version issues.

Please check this [example](https://github.com/libp2p/js-libp2p/blob/master/examples/libp2p-in-the-browser/index.js). You can remove the bootstrap module in it. The remaining code seems the same as yours. Double check the example versions and yours

**Comment by kottackalsulvin** [comment]
Do we need any peer mechanisms like mdns or kadDHT for connecting peers?

**Comment by vasco-santos** [comment]
> Do we need any peer mechanisms like mdns or kadDHT for connecting peers?

webrtc-star offers a peer discovery module, that is automatically used if provided as a transport. Also, the `autoDial` option is true by default, which makes libp2p automatically dial discovered peers.

`mdns` does not work in the browser and `libp2p-kad-dht` needs to be improved. So, you should be good with `webrtc-star` and `bootstrap`. But, it might depend on your use case.

**Comment by kottackalsulvin** [comment]
@vasco-santos Thank you so much for your help. I tried to replicate the webcam example [https://github.com/prcolaco/webcam-stream-libp2p] and have used ‘it-pipe’ to stream data to other connected peers. But am getting the below error. I can’t figure out where am wrong. 

` Error: no protocol with name: QmWFRVjz8GRUXesYbwbEUCWpftg31QyHAD7Jv9bfjqnFvP`

**App.js**
```
node.on('peer:discovery', (peerId) => {
console.log('Discovered:', peerId.toB58String())
const id = peerId.toB58String()
node.connectionManager.on('peer:connect', (connection) => {
console.log("Connected to "+connection.remotePeer.toB58String())
const listenerMultiaddr = '/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star/' + connection.remotePeer.toB58String()
;(async () => {
const { stream } = await node.dialProtocol(listenerMultiaddr, '/ipfs/bitswap/1.1.0')
await pipe(
['my own protocol, wow!'],
stream,
async function (source) {
for await (const data of source) {
console.log("inn stream");
console.log(data.toString())
// Create a canvas for this peer
// App.createCanvas(id);
}
}
)
})();
})
})
```

**Comment by vasco-santos** [comment]
Hey @kottackalsulvin 

Your issue is on the listenerAddr: It is throwing on https://github.com/multiformats/js-multiaddr/blob/master/src/protocols-table.js#L15 . So, you are mising the `/p2p/` part before the peerId. An example would be: `/dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star/p2p/QmcvtvDS2fPcXmgcq87D4Ny1yxzmonFNEffEhsBazouKqr`

**Comment by kottackalsulvin** [comment]
**Error**


```
Uncaught (in promise) AggregateError: 
    Error: protocol selection failed
```
Didn't resolved.

**Comment by vasco-santos** [comment]
Can you push the code somewhere I can test it with instructions?
If not, I need more information to replicate this: Module versions, logs (in the browser do `localStorage.debug = 'libp2p.*'`) and flow that lead to this

**Comment by kottackalsulvin** [comment]
![IMG_20201014_003151](https://user-images.githubusercontent.com/40980270/95904683-78b06580-0db5-11eb-8cbb-472b24ea0fb0.jpg)
![IMG_20201014_003218](https://user-images.githubusercontent.com/40980270/95904695-7b12bf80-0db5-11eb-9989-bdb3feda9bd6.jpg)
![IMG_20201014_003249](https://user-images.githubusercontent.com/40980270/95904704-7c43ec80-0db5-11eb-9a0f-5c778e077dd0.jpg)

**Comment by kottackalsulvin** [comment]
**App.js**

```
startOwnPeerfnVideo: function () { 
const createNode = async () => {
const node = await libp2p.create({
addresses: {
listen: [
'/dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star' 
] 
},
modules: {
transport: [WS, WebRTCStar],
connEncryption: [NOISE],
streamMuxer: [mplex]
},
}) 
const myID = node.peerId.toB58String();
console.log('Your ID: ' + myID)
//App.createCanvas(myID);
App.listenAndConnectToPeers(node);
await node.start()
return node
}
;(async () => {
const node = await createNode()
console.log('node has started (true/false):', node.isStarted())
console.log('listening on:')
node.multiaddrs.forEach((ma) => console.log(`${ma.toString()}/p2p/${node.peerId.toB58String()}`))
})();
},

listenAndConnectToPeers:function(node){
node.on('peer:discovery', (peerId) => {
const id = peerId.toB58String()
node.connectionManager.on('peer:connect', (connection) => {
console.log("Ccconnected to "+connection.remotePeer.toB58String())
;(async () => {
const { stream } = await node.dialProtocol(`${node.multiaddrs}/p2p/${id}`, '/ipfs/bitswap/1.1.0')
// await pipe(
// ['node 1 dialed to node 2 successfully'],
// stream
// )
})();
})
})
}
```

**Comment by vasco-santos** [comment]
Thanks, I think I got the issue.

You are trying to open a stream using IPFS's bitswap protocol which the other peer is not running.
Do you want to use bitswap? If yes, I recommend using IPFS directly. If not and you were just experimenting, I recommend you create your own protocol for testing.

To create a new protocol, you will need your peers to have an handler for the protocol (imagine a REST API handler) and then open a stream from another one. You should check this [example](https://github.com/libp2p/js-libp2p/tree/master/examples/chat). It has a simple chat protocol where the listener has the handler. In your case, I believe all your peers will be listeners and dialers.

One more thing, considering that you are opening the stream within the `node.connectionManager.on('peer:connect', (connection) => {}`, I recommend leveraging the connection itself: https://github.com/libp2p/js-libp2p-interfaces/tree/master/src/connection#create-a-new-stream

**Comment by kottackalsulvin** [comment]
@vasco-santos thanku for your fast reply. Error still exist.Is it because of any encryption method(https://discuss.libp2p.io/t/error-protocol-selection-failed/472/2)? But I have already used secio for encryption.

**App.js**

```
startOwnPeerfnVideo: function () { 
const createNode = async () => {
const node = await libp2p.create({
addresses: {
listen: [
'/dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star' 
] 
},
modules: {
transport: [WS, WebRTCStar],
connEncryption: [NOISE],
streamMuxer: [mplex]
},
}) 
await node.start()
return node
}
;(async () => {
console.log('node has started (true/false):', node.isStarted())
console.log('listening on:')
node.multiaddrs.forEach((ma) => console.log(`${ma.toString()}/p2p/${node.peerId.toB58String()}`))
const myID = node.peerId.toB58String();
App.createCanvas(myID);
App.listenAndConnectToPeers(node);
await node.handle('/echo/1.0.0', async ({ stream }) => {
App.stdinToStream(stream);
App.streamToConsole(stream);
})
})();
},

listenAndConnectToPeers:function(node){
node.on('peer:discovery', (peerId) => {
const id = peerId.toB58String()
node.connectionManager.on('peer:connect', (connection) => {
console.log("Ccconnected to "+connection.remotePeer.toB58String())
;(async () => {
node.connectionManager.on('peer:connect', (connection) => {
console.log("Ccconnected to "+connection.remotePeer.toB58String())
;(async () => {
// const listenerMa = multiaddr(`/ip4/127.0.0.1/tcp/10333/p2p/${id}`);
// const { stream } = await node.dialProtocol(listenerMa, '/chat/1.0.0')
// await pipe(
// ['node 1 dialed to node 2 successfully'],
// stream
// )
const {stream}= await connection.newStream('/echo/1.0.0');
App.stdinToStream(stream);
App.streamToConsole(stream);

})();
})
})();
})
})
},
stdinToStream:function(stream) {
pipe(
stream.source, 
stream.sink
)
},

streamToConsole:function(stream) {
pipe(
['hey'],
stream,
async function (source) {
for await (const data of source) {
console.log('received echo:', data.toString())
}

}
)
},
```
![IMG_20201014_164446](https://user-images.githubusercontent.com/40980270/95981950-1dc25100-0e3d-11eb-8ce3-6512d8eacb37.jpg)

**Comment by kottackalsulvin** [comment]
Anyone please help me to resolve this issue? I am stuck at this point.

**Comment by kottackalsulvin** [comment]
Can we use pipe for video streaming?

**Comment by kottackalsulvin** [comment]
@vasco-santos Thanku for your help.That resolved my issue when I changed the protocol.
Can you tell how to store all the peers that is connected to a particular peerId. I didn't found any documents related to it.

**Comment by kottackalsulvin** [comment]
@vasco-santos Thanku for your help.That resolved my issue when I changed the protocol.
 How to know if a particular peerId is connected or not in libp2p 0.29?

**Comment by vasco-santos** [comment]
> @vasco-santos Thanku for your help.That resolved my issue when I changed the protocol.

Good to hear

> How to know if a particular peerId is connected or not in libp2p 0.29?

https://github.com/libp2p/js-libp2p/blob/master/doc/API.md#connectionmanagerget

**Comment by kottackalsulvin** [comment]
Will pull-pushable works in libp2p 0.29? I am working on video streaming. I am not getting 'data' from below code.

**App.js**

```
const pushable = require('pull-pushable')

node.connectionManager.on('peer:connect', (connection) => {
;(async () => {
const {stream}= await connection.newStream('/print');
const p=pushable();
await pipe(p,stream)
 })();
})

...............................
..................................
node.handle('/print, ({ stream }) => {
pipe(
stream,
async function (source) {
for await (const data of source) {
const dataToRender = new ImageData(new Uint8ClampedArray(data), SIZES.width, SIZES.height)
canvas.putImageData(dataToRender, 0, 0);//The ImageData() constructor returns a newly instantiated ImageData object built from the typed array given and having the specified width and height.
}
}
)
})
```
**Error**

`Uncaught (in promise) DOMException: Failed to construct 'ImageData': The input data has zero elements.`

**Comment by kottackalsulvin** [comment]
I have used 'it-pushable' instead of 'pull-pushable' but nothing changed.Anyone please help me to resolve this issue.

Do you have any documents related to video streaming using 'it-pipe'?

**Comment by kottackalsulvin** [comment]
@vasco-santos Do you have any documents related to video streaming using 'it-pipe'?
I can connect to other peers but cannot send data to other connected peers.I have used 'it-pushable' instead of 'pull-pushable' but nothing changed.Anyone please help me to resolve this issue.


**App.js**

```
const pushable = require('it-pushable')

node.connectionManager.on('peer:connect', (connection) => {
;(async () => {
const {stream}= await connection.newStream('/print');
const p=pushable();
await pipe(p,stream)
 })();
})

...............................
..................................
node.handle('/print, ({ stream }) => {
pipe(
stream,
async function (source) {
for await (const data of source) {
const dataToRender = new ImageData(new Uint8ClampedArray(data), SIZES.width, SIZES.height)
canvas.putImageData(dataToRender, 0, 0);//The ImageData() constructor returns a newly instantiated ImageData object built from the typed array given and having the specified width and height.
}
}
)
})
```
![IMG_20201018_153629](https://user-images.githubusercontent.com/40980270/96364527-abad7d00-1158-11eb-9e3e-3f470fe963df.jpg)

**Comment by kottackalsulvin** [comment]
How to stream video using 'it-pipe'? I am getting the above error while using it-pipe.

**Comment by kottackalsulvin** [comment]
Can anyone figure out why the above error happens?

**Comment by kottackalsulvin** [comment]
Is it because of the protocol am used?

**Comment by kottackalsulvin** [comment]
I am stuck in this point. Able to connect to peers but cannot stream data to connected peers.Anyone please help me to resolve this issue. Here is my full code:

**App.js**

```
startOwnPeerfnVideo: function () { 
const createNode = async () => {
const node = await libp2p.create({
addresses: {
listen: [
'/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star',
'/dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star'
] 
},
modules: {
transport: [WS, WebRTCStar],
connEncryption: [secio,NOISE],
streamMuxer: [mplex],
peerDiscovery: [],
dht: undefined
},
}) 
await node.start()
// Create the multiaddr to the Bootstrap node
const targetAddress = multiaddr('/dns4/sjc-1.bootstrap.libp2p.io/tcp/443/wss/ipfs/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN')
try {
await node.dial(targetAddress)
} catch (err) {
console.error(err)
}
return node
}

;(async () => {
const node = await createNode()
console.log('node has started (true/false):', node.isStarted())
const myID = node.peerId.toB58String();
console.log('Your ID: ' + myID)
App.createCanvas(myID);
App.listenAndConnectToPeers(node);

node.handle('/ipfs/bitswap/3.0.0', ({ stream }) => {
console.log("enter in peer:"+connpeer)
pipe(
stream,
async function (source) {
for await (const data of source) {
if (connpeer !== undefined) {
const canvas = App.getCanvas(connpeer);
console.log("Message:"+data)
if (canvas !== undefined) {
const dataToRender = new ImageData(new Uint8ClampedArray(data), SIZES.width, SIZES.height)
canvas.putImageData(dataToRender, 0, 0);//The ImageData() constructor returns a newly instantiated ImageData object built from the typed array given and having the specified width and height.
}
}
}
}
)
})

// Check if webcam is supported
if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
// Request webcam permissions
navigator.mediaDevices.getUserMedia({ video: true,audio: true }).then(function (stream) {
video.srcObject=stream;
video.play()
})
}
// Delay for sending
const SEND_EACH_MS = 100
function drawAndSend() {
// If we don't have our own canvas yet, is because camera has yet to init
const myCanvas = App.getCanvas(myID)
if (myCanvas !== undefined) {
// Write video feed into canvas
myCanvas.drawImage(video, 0, 0, SIZES.width, SIZES.height)
// Get image data from canvas
const data = myCanvas.getImageData(0, 0, SIZES.width, SIZES.height)
// Convert data into buffer and send to each open connection
const bufferToWrite = toBuffer(data.data)
console.log("in buffer to write draw and sent:"+data.data);
// For each open connection we have
Object.keys(_OPEN_CONNECTIONS).forEach((id) => {
const stream = _OPEN_CONNECTIONS[id]
// Write image data to the pull-stream
stream.push(bufferToWrite)
})
}
// Repeat this as fast as possible but with delay of 100ms
setTimeout(drawAndSend, SEND_EACH_MS)
}
//Start recursive function
drawAndSend()
})();
},

listenAndConnectToPeers:function(node){ 
node.on('peer:discovery', (peerId) => {
console.log('Discovered:', peerId.toB58String())
const id = peerId.toB58String()
if (_OPEN_CONNECTIONS[id] === undefined) {
node.connectionManager.on('peer:connect', (connection) => {
console.log("Ccconnected to "+connection.remotePeer.toB58String())
connpeer=connection.remotePeer.toB58String();
;(async () => {
const {stream}= await connection.newStream('/ipfs/bitswap/3.0.0');
const p=pushable();
pipe(p,stream)
_OPEN_CONNECTIONS[id] = p;
App.createCanvas(connection.remotePeer.toB58String());
})();
})
} else {
console.log('Already connected to peer', id)
}
})
// When connection to a peer closes, remove the canvas
node.connectionManager.on('peer:disconnect', (connection) => {
console.log("Disconnected from"+connection.remotePeer.toB58String())
App.removeCanvas(connection.remotePeer.toB58String())
})
},

getCanvas: function(id){
// Mutable global with references to all canvases we have created
if (id === undefined) throw new Error('ID needs to be defined')
return _CANVASES[id]
},

removeCanvas: function(id){
if (id === undefined) throw new Error('ID needs to be defined')
_CANVASES[id].canvas.remove();
},

createCanvas: function(id){
if (id === undefined) throw new Error('ID needs to be defined')
if (_CANVASES[id] !== undefined) throw new Error('Already had a canvas for ID:'+id)
const canvas = document.createElement('canvas')
canvas.setAttribute('width', SIZES.width)
canvas.setAttribute('height', SIZES.height)
const ctx = canvas.getContext('2d')
_CANVASES[id] = ctx
// Write some text on the canvas while we get the first frame
ctx.font='15px Verdana'
ctx.fillText('Loading video', 15, 70)
document.getElementById('feeds').append(canvas)
},
```
![Screenshot from 2020-10-19 12-15-46](https://user-images.githubusercontent.com/40980270/96411403-03ee8880-1206-11eb-9ab6-3240fa70fa13.png)

**Comment by jacobheun** [comment]
Pasting unformatted code makes it really difficult to figure out what's going on, please post formatted code in the future. As far as I can tell based on your logs you **are** sending and receiving data. I'm not very familiar with canvas, but my best guess is that the data going into the render on the receiving side is not correct.

Also, you should NOT make your custom protocol `/ipfs/bitswap/3.0.0` as it's not Bitswap. You should namespace this to your application.

I'm going to close this issue as the original problem has been solved and there isn't an underlying issue with libp2p here. Support requests should be made on the forums, https://discuss.libp2p.io/, we're happy to help there.
