### ISSUE TITLE
Replicate Orbit-db in another browser

### ISSUE THREAD

**Issue by kottackalsulvin** [libp2p/js-libp2p#778]
Hi,
I am trying to replicate my orbitdb in another browser using the below address

`const db= await orbitdb.docs('orbitdb/zdpuAnBgAoZ3CUNkicsdqzCtz6nubD3ubRG1feU72oKhMqoxz/Tom jane@gmail.com');`

If I try to open this address in a new tab in the same browser,then it can be accessible. But in another browser,it is not accessible. Please help me to resolve this. Am getting an orbit db ‘id’ as below, when am using the above address in another browser.

`id: "/orbitdb/zdpuB37ifQdj2RVmBqyxpauYJDU2xUvDKUZpuMgeSYham6jps/orbitdb/zdpuAnBgAoZ3CUNkicsdqzCtz6nubD3ubRG1feU72oKhMqoxz/Tom jane@gmail.com"`

**App.js**

```
ipfs = new IPFSS({
start: true, 
EXPERIMENTAL: {
pubsub: true
},
preload: { 
enabled: false 
},
config: {
Addresses: {
Swarm: [
'/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star'
]
}
}
})


ipfs.on('ready', async () => {
const identity = await Identities.createIdentity({ id: 'local-id' })

// Create OrbitDB instance

const orbitdb = await OrbitDB.createInstance(ipfs, { identity: identity })

const defaultOptions = { accessController: { write: [orbitdb.identity.id] }}

const docStoreOptions = {
defaultOptions,
indexBy: 'wallet',
}

const db = await orbitdb.docs(orbitdbname,docStoreOptions);
await db.load();
})

```

**Environment**

Npm: 6.13.4
Node: 10.18.1
libp2p : 0.26.2
libp2p-webrtc-star: 0.13.2
libp2p-websockets: 0.12.2

**Comment by jacobheun** [comment]
I'm going to close this as it's a question for orbitdb and looks like you've added an issue there, https://github.com/orbitdb/orbit-db/issues/843. If there's an underlying problem with libp2p that comes our of that discussion we can create a bug here.
