### ISSUE TITLE
Libp2p Bootstrap node

### ISSUE THREAD

**Issue by kottackalsulvin** [libp2p/js-libp2p#784]
I am trying to implement a dapp application using libp2p 0.29. Now my peerid is connecting to all global peers. But I want to connect only to the bootstrap peers. Should i need to use pubsub for that?

**Comment by jacobheun** [comment]
Can you clarify what you mean? Are you just looking for a 1:1 connection and no peer discovery?

**Comment by kottackalsulvin** [comment]
@jacobheun I want to connect only to those peers who are interested in the topic/room.

**Comment by jacobheun** [comment]
If you want to control who you dial to you can set `autoDial` to false, https://github.com/libp2p/js-libp2p/blob/master/doc/CONFIGURATION.md#customizing-peer-discovery, and then manually dial to those peers. This will give you more control of your connection logic. This won't prevent inbound connections from other peers though.

We will eventually add connection gaters to control inbound and outbound connections and move away from `autoDial`, but you should be able to manually control that for now.

**Comment by jacobheun** [comment]
Closing this, if you have more issues we can reopen.
