### ISSUE TITLE
documentation needs care

### ISSUE THREAD

**Issue by mh-cbon** [libp2p/js-libp2p#786]
several examples in the documentation are not fully functional or slightly buggy. This fact coupled with error logging difficulties as described in #785 generates bad user exeprience for the lambda developer that would like to learn more about all the p2p world.

I believe this is an important improvement to work on in order to increase project popularity.

**Comment by jacobheun** [comment]
> several examples in the documentation are not fully functional or slightly buggy.

Can you specify which examples you're having problems with, aside form issues you've already referenced? That would help us better target what needs improving.

**Comment by jacobheun** [comment]
Closing for now, if you have more information to help guide us please feel free to reopen
