### ISSUE TITLE
[Feature Request] - Content Routing Events

### ISSUE THREAD

**Issue by HexaField** [libp2p/js-libp2p#794]
I'm looking to add events for my application that uses libp2p with the Kad DHT. I would like to be able to be notified of when an entry in the local DHT datastore changes, and act upon that information.

For example
```javascript
libp2p.contentRouting.on('dht:add', (key, value, peerID) => { 
   console.log('Added ' + key + ': ' + value + ' from ' + peerID) 
})
```
```javascript
libp2p.contentRouting.on('dht:change', (key, oldValue, newValue, peerID) => { 
   console.log(key + ' changed from ' + oldValue + ' to ' + newValue) 
})
```
```javascript
libp2p.contentRouting.on('dht:remove', (key, peerID) => { 
   console.log(key + ' removed') 
})
```

Thanks.

**Comment by vasco-santos** [comment]
Thanks for reaching out @HexaField 

Any reason for not considering pubsub for this type of real time events?
A particular libp2p DHT node might not have the information of a dht value changed/added/removed on the network. As an example, when the DHT tries to get a value, it will get the value for a given key from a set of different peers and select the best one (that is, the most recent). As a consequence, your node would not have visibility of what is going on to emit the events unless it crawls the network.

**Comment by HexaField** [comment]
> Any reason for not considering pubsub for this type of real time events?

I am wanting to use the DHT as a data storage utility, using the built in propagation and redundancy native to the DHT. My understanding is that pubsub would by default send information to all nodes under a specific topic, whereas I am looking to use an actual DHT (as opposed to IPFS or OrbitDB, since I am just looking for a low level mutable decentralised key/value store separate from the IPFS ecosystem, though thinking about this now I may reconsider).

> As a consequence, your node would not have visibility of what is going on to emit the events unless it crawls the network.

Sorry, I should have clarified. I am only looking to see changes in the peer's local instance/slice (I'm not familiar with the proper terminology sorry) of the DHT. I believe all that is needed is to determine changes to entries specific to content routing (non peer routing) in libp2p.datastore

This would effectively be analogous to `libp2p.connectionManager.on('peer:connect')` or `libp2p.connectionManager.on('peer:discovery')`  only for content.

Thanks.

**Comment by vasco-santos** [comment]
Thanks for the extended explanation. One more questions:
- Do you expect the events to be emitted if a value changes through a put from other node (which sent a message to the peer informing of the change)? or only local operations?

I am still trying to figure out if this should really live on the content routing layer. Other content routing modules like delegated content routing would not leverage this.

**Comment by HexaField** [comment]
> Do you expect the events to be emitted if a value changes through a put from other node (which sent a message to the peer informing of the change)? or only local operations?

Yes, I would want changes from other nodes (hence the peerID fields returned in the emitter listener in the original post).

I suppose we can also talk about the purpose and functionality of the DHT more generally (perhaps on the forum), since there is high utility in it for decentralised apps. What are the intentions for a full implementation of the DHT? Will it support custom queries (for implementing eg. content searches)? Can we implement a `delete` method in contentRouting (I know this goes against the methodology of IPFS, furthermore if the DHT is intended to be immutable)? Is there a purpose to `provide` and `findProvider` outside of IPFS if the record CID is not returned from `put`? I haven't yet looked at the go implementation, so I apologise if these things are obvious.

**Comment by vasco-santos** [comment]
> Yes, I would want changes from other nodes (hence the peerID fields returned in the emitter listener in the original post).

Ok, with all the above in mind, I do not think this should be part of the content routing events. This can be part of the DHT and you can access the events via `libp2p._dht` as an initial solution. I will take this use case in mind when we refactor the content routing interface, which we have in the pipeline for a while.

For now, if you are interested in trying to PR this feature in [libp2p/js-libp2p-kad-dht](https://github.com/libp2p/js-libp2p-kad-dht) for change/add, it would be nice.

> I suppose we can also talk about the purpose and functionality of the DHT more generally (perhaps on the forum), since there is high utility in it for decentralised apps. 

Creating a broader discussion in the forum would be the way to go, yes :)

FYI the GO implementation of the DHT had a big overhaul over this year. At this moment, a spec is being written taking into account all the improvements and learnings from GO, so that other languages update their DHT implementations. As a consequence, we intend to update and improve the JS implementation as soon as the new spec is out.

**Comment by vasco-santos** [comment]
Added event handlers in the DHT to enable this. Closing the issue. Thanks for adding the support @HexaField
