### ISSUE TITLE
create react app: pubsub does not work when served from HTTPS origins

### ISSUE THREAD

**Issue by OR13** [libp2p/js-libp2p#797]
- **Version**:
```
     "libp2p": "^0.29.3",
    "libp2p-bootstrap": "^0.12.1",
    "libp2p-gossipsub": "^0.6.4",
    "libp2p-mplex": "^0.10.1",
    "libp2p-noise": "^2.0.1",
    "libp2p-webrtc-star": "^0.20.1",
    "libp2p-websockets": "^0.14.0",
```
- **Platform**: macOS
- **Subsystem**: Google Chrome 86.0.4240.183 (Official Build) (x86_64)

#### Description:

In browser PubSub only works when one peer is running on localhost.

If both peers are running on pages hosted over https (like github pages), while the can discover eachothers peer ids, they cannot dial / listen for topics... but if 1 is localhost and the other is hosted on https origin, they can consume / produce events on the topics successfully. 

#### Steps to reproduce the error:

https://github.com/OR13/webrtc-pub-sub-example

https://or13.github.io/webrtc-pub-sub-example/
^ open 2 tabs of this URL.

Copy the peer id of one of the tabs and set this URL: `https://or13.github.io/webrtc-pub-sub-example/?peers=["QmTUQLwNFpMPA8eEmQaDJRrz3bHtQEbxJ2QQT5b2Ua1JvD"]` and refresh.

(replacing peer id with the copied value)

see console for Error: "peer unavailable".

Run the project locally and use a local tab for 1 peer and a hosted tab for another peer... observe no error.

The same exact code works perfectly when run on local host, but fails when exposed over https (using ngrok).

It says that the test servers MUST NOT be used for production, is it possible that what is really meant is that they DO NOT SUPPORT https origins?

**Comment by jacobheun** [comment]
I was able to get this to work on Chrome and Brave on macOS using the url you gave. I didn't see the failure log and was able to verify the connection to the target peer in the `libp2p.connections` map via the console.

Can you turn on debugging for the webrtc-star transport to see if there is a clear error there? Setting `localStorage.debug="libp2p:webrtc-star:*"` in the browser console and refreshing should start logging.

My assumption is that the webrtc hole punch or ICE connections are failing for some reason.

**Comment by OR13** [comment]
<img width="1003" alt="Screen Shot 2020-11-09 at 2 35 10 PM" src="https://user-images.githubusercontent.com/8295856/98593563-ee1a3380-2298-11eb-82a7-a0849979cf2c.png">
<img width="999" alt="Screen Shot 2020-11-09 at 2 36 05 PM" src="https://user-images.githubusercontent.com/8295856/98593566-efe3f700-2298-11eb-90b0-0b040cc9117f.png">

@jacobheun I tried:

```
localStorage.debug="libp2p:webrtc-star:*";
```

but did not see any errors.

**Comment by OR13** [comment]
nvm, it just took a second to work... now I am seeing this:

<img width="982" alt="Screen Shot 2020-11-09 at 2 40 41 PM" src="https://user-images.githubusercontent.com/8295856/98593974-96c89300-2299-11eb-8082-c9fc8af13e7a.png">

**Comment by OR13** [comment]
downloaded and tested in brave, seeing the same error there.

**Comment by OR13** [comment]
hmm based on: https://github.com/libp2p/js-libp2p-webrtc-star/issues/258

I removed: `'/dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star'`

And that appears to have resolved the issue, will do a deployment to confirm.

**Comment by OR13** [comment]
confirmed its working now, this was the fix:
```

    const libp2p = await Libp2p.create({
        addresses: {
          listen: [
            '/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star',
            // '/dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star'
          ]
        },
        modules: {
          transport: [Websockets, WebRTCStar],
          connEncryption: [NOISE],
          streamMuxer: [Mplex],
          peerDiscovery: [Bootstrap],
          pubsub: Gossipsub
        },
        config: {
          peerDiscovery: {
            [Bootstrap.tag]: {
              enabled: true,
              list: [
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp',
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa',
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt'
              ]
            }
          }
        }
      })
```
