### ISSUE TITLE
Preferred way to instantiate Libp2p bundle? Inherit or static create?

### ISSUE THREAD

**Issue by a1300** [libp2p/js-libp2p#811]
- **Version**: 0.29.3
- **Platform**: Linux
- **Subsystem**:

#### Type: Question

I found in the examples both the `new Libp2p()` and `Libp2p.create()` methods. In the [API](https://github.com/libp2p/js-libp2p/blame/master/doc/API.md) documentation only the `new Libp2p()` way is shown.

Are they the same? Is it safe to inherit from `Libp2p` and add extra methods?

Example with `Libp2p.create()`
https://github.com/libp2p/js-libp2p/blob/d0a9fada32677ee3b810d5c2fb8d5e2c4f5a9fef/examples/discovery-mechanisms/1.js#L24-L27 

Example with `new Libp2p()`
https://github.com/libp2p/js-libp2p/blob/d0a9fada32677ee3b810d5c2fb8d5e2c4f5a9fef/examples/chat/src/dialer.js#L16-L21

**Comment by vasco-santos** [comment]
Hello @a1300 

The preferred way to instantiate Libp2p is using `Libp2p.create`. When you create Libp2p via its constructor a PeerId must be provided, while create is a more out of the box solution that can receive the peerId or not. If you would like to PR the example dialer to use `Libp2p.create`, it would be welcome.

Regarding the docs, we actually have both documented in https://github.com/libp2p/js-libp2p/blob/master/doc/API.md#create . The `new Libp2p` is documented in a toggle that says alternative, as we really don't want people to use that. However, the class being exported enables some use cases where we want to create a Libp2p node but extend it with some behaviour.

**Comment by a1300** [comment]
Hi @vasco-santos 
thanks for the fast answer! Didn't saw the alternative toggle. I think the alternative example (`new Libp2p)`) is missing a comment that specifies that a `peerId` is required. 

Will send a PR for the dialer example

**Comment by vasco-santos** [comment]
> I think the alternative example (new Libp2p)) is missing a comment that specifies that a peerId is required.

If you would like to also PR this change, feel free to do it :)

**Comment by a1300** [comment]
Update docs examples in PR: #814
