### ISSUE TITLE
Markdown gets not correctly rendered in API.md

### ISSUE THREAD

**Issue by a1300** [libp2p/js-libp2p#815]
- **Version**: v0.29.3
- **Platform**:
- **Subsystem**:

#### Description: A `|` symbol in a markdown table cell messes the markdown up

This markdown

![image](https://user-images.githubusercontent.com/11912239/100387816-45eec380-3029-11eb-8abc-821e04c7f2f2.png)

Gets rendered as
![image](https://user-images.githubusercontent.com/11912239/100387884-6b7bcd00-3029-11eb-9123-f410e4f7fbf6.png)

Affects
- **dialProtocol** https://github.com/libp2p/js-libp2p/blob/master/doc/API.md#dialprotocol
- **peerStore.addressBook.get** https://github.com/libp2p/js-libp2p/blob/master/doc/API.md#peerstoreaddressbookget
- **peerStore.addressBook.getMultiaddrsForPeer** https://github.com/libp2p/js-libp2p/blob/master/doc/API.md#peerstoreaddressbookgetmultiaddrsforpeer

**Comment by vasco-santos** [comment]
This is super weird. On vscode Markdown preview it shows up correctly. Did you understand the issue behind this?

**Comment by a1300** [comment]
This is seems like a Github/Gist Markdown issue. I created an issue on the unofficial github bug repository https://github.com/isaacs/github/issues/1875 

According to [submitting-bug-reports-for-github-com](https://github.community/t/submitting-bug-reports-for-github-com/10207) I also will send a Bug report

**Comment by a1300** [comment]
Bug report on github.community
https://github.community/t/bug-markdown-inline-code-blocks-with-pipe-symbols-within-a-table-cell-destroy-the-table/145896

**Comment by vasco-santos** [comment]
Thanks for looking into this @a1300  ❤️

**Comment by wemeetagain** [comment]
API.md no longer has tables
