### ISSUE TITLE
Can dial myself

### ISSUE THREAD

**Issue by a1300** [libp2p/js-libp2p#817]
- **Version**: v0.29.3
- **Platform**: Linux
- **Subsystem**:

#### Steps to reproduce the error:

Reproduction gist
```bash
git clone https://gist.github.com/a1300/74706c0a7119e0fce1a1cc2366779f1c libp2p-dial-myself
cd libp2p-dial-myself
npm install
node index.js
```

Output
```
[0.0.0.0] I am peer "QmZUaDLvgtmaTYgwRcyvd7vXkAEQDXdKhimab6BVwjD7p4"
[0.0.0.0] peer:discovery peer "QmZUaDLvgtmaTYgwRcyvd7vXkAEQDXdKhimab6BVwjD7p4"
(node:27430) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time
[0.0.0.0] peer:connect peer "QmZUaDLvgtmaTYgwRcyvd7vXkAEQDXdKhimab6BVwjD7p4
[0.0.0.0] peer:connect peer "QmZUaDLvgtmaTYgwRcyvd7vXkAEQDXdKhimab6BVwjD7p4
connections: 1
```

**Comment by a1300** [comment]
Related to #356 #274

**Comment by vasco-santos** [comment]
Well, this was introduced by storing the self peer in the AddressBook. We should get this fixed and verify on the auto dial if we are trying to dial self

**Comment by vasco-santos** [comment]
Looking into this, we already protect the discovery of self. So, after I checked the provided code I noticed that this is a manual dial to self and not a subsequent dial from discovery.

We should just need to add a check into the dialer connect
