### ISSUE TITLE
Inlined `latency-monitor` code

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p#825]
- **Version**: master
- **Platform**: *
- **Subsystem**: connection-manager

#### Description:

In reviewing / investigating https://github.com/ChainSafe/js-libp2p-gossipsub/issues/86, I'd remembered that the libp2p connection manager contained some sort of "latency monitoring" which might be used to resolve this issue.
Upon further review, it became clear that the code from the [`latency-monitor`](https://github.com/mlucool/latency-monitor) package/repo had been inlined in this repo in https://github.com/libp2p/js-libp2p/pull/587, possibly to reduce the bundle size.

Should this library be inlined? (Are there other libraries also inlined?)
Should libp2p rely on the upstream library?

**Comment by vasco-santos** [comment]
I am not really sure about the reasoning for this. 

@jacobheun @hugomrdias can you help here?

**Comment by hugomrdias** [comment]
This package is mostly unmaintained and should actually be refactored or removed, at the time of #587 pushing the changes needed upstream would be unlikely so we decided to just inline. But this should not be our general approach to external dependencies.

**Comment by lidel** [comment]
I believe https://discuss.libp2p.io is a better place for asking questions (keeping github limited to actionalble  issues/bug reports)
