### ISSUE TITLE
[Types] CIDs typings incompability

### ISSUE THREAD

**Issue by AuHau** [libp2p/js-libp2p#839]
CID version `1.1.0` introduced typings generated with `aegir` which changed the structure of typings as before this release it was placed in `/src/` folder. With version `1.1.4` ts compile now fails with:

```
node_modules/libp2p/dist/src/content-routing.d.ts:86:19 - error TS2307: Cannot find module 'cids/src/' or its corresponding type declarations.

86 type CID = import("cids/src/");
                     ~~~~~~~~~~~


Found 1 error.
```

With version `1.0.0` of CID the problem is not present.

**Comment by AuHau** [comment]
Hmm in the generated typings I see:

```
type CID = import("cids/src/");
```

But the original JSDoc import does not have it: https://github.com/libp2p/js-libp2p/blob/master/src/content-routing.js#L12 😳

Maybe it is related to the version of CID that was used when the typings were released? 🤔

**Comment by vasco-santos** [comment]
Thanks for reporting this @AuHau 
We had some regressions with the `cids`. I will need to have a deeper look into this

**Comment by AuHau** [comment]
Sure thing! Just FYI. downgrading `cids` to `1.0.2` "solved" the problem...

**Comment by hugomrdias** [comment]
@AuHau which ts version are you using?

**Comment by vasco-santos** [comment]
@hugomrdias this is one of the cases that the aegir typecheck is not catching errors. If you build libp2p and check `/dist/src/content-routing` vscode also reports this error. It was not happening before though

**Comment by Gozala** [comment]
I'm afraid problem is that TS has a bug that incorrectly resolves module paths https://github.com/microsoft/TypeScript/issues/41284. As to why TS rewrites imports to things like `cids/src/` I am pretty clueless, but this has came up before & think the most reasonable solution is to workaround TS issues as per   https://github.com/ipfs/aegir/pull/703

**Comment by ryanio** [comment]
I have the same problem here https://github.com/ethereumjs/ethereumjs-vm/pull/1027#issuecomment-753249479

**Comment by vmx** [comment]
@ryanio thanks for pointing to the PR. It helped me to verify that the fix in js-cid actually works. No workarounds for that should be needed if you use cids v1.1.5.

**Comment by vasco-santos** [comment]
thanks @vmx and @hugomrdias 

@AuHau this should be fixed, feel free to re-open if you have further issues
