### ISSUE TITLE
Active relay option support

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#852]
Libp2p nodes can be configured to be an active relay. However, this feature is not yet implemented.

An active relay node can dial other peers even if it does not know about those peers. When the relay gets a request, reads the destination peer's multiaddr from the connection stream and if its a valid address tries to dial it.

https://github.com/libp2p/js-libp2p/blob/v0.30.0/src/circuit/circuit/hop.js#L73

**Comment by mpetrunic** [comment]
https://github.com/libp2p/js-libp2p/blob/master/src/config.ts#L72
