### ISSUE TITLE
In an electron app just importing libp2p in main.ts causes "self is not defined"

### ISSUE THREAD

**Issue by raphael10-collab** [libp2p/js-libp2p#873]
In in electron app just importing libp2p in main.ts : 

    const Libp2p = require('libp2p');

causes this error:

    A JavaScript error occurred in the main process
    Uncaught Exception:
    ReferenceError: self is not defined
        at Object../node_modules/multihashing-async/src/sha.browser.js (/home/marco/webMatters/electronMatters/OnlyLibp2p
    /.webpack/main/index.js:34203:16)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/OnlyLibp2p/.webpack/main/index.js:21:30)
        at Object../node_modules/libp2p-crypto/src/keys/rsa-class.js (/home/marco/webMatters/electronMatters/OnlyLibp2p
    /.webpack/main/index.js:19523:13)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/OnlyLibp2p/.webpack/main/index.js:21:30)
        at Object../node_modules/libp2p-crypto/src/keys/index.js (/home/marco/webMatters/electronMatters/OnlyLibp2p/.webpack
    /main/index.js:19074:8)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/OnlyLibp2p/.webpack/main/index.js:21:30)
        at Object../node_modules/peer-id/src/index.js (/home/marco/webMatters/electronMatters/OnlyLibp2p/.webpack
    /main/index.js:58259:20)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/OnlyLibp2p/.webpack/main/index.js:21:30)
        at Object../node_modules/libp2p/src/index.js (/home/marco/webMatters/electronMatters/OnlyLibp2p/.webpack
    /main/index.js:24403:16)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/OnlyLibp2p/.webpack/main/index.js:21:30)

tsconfig.json : 

    {
      "compilerOptions": {
        "jsx": "react",
        "allowJs": true,
        "target": "ES6",
        "module": "ESNext",
        "skipLibCheck": true,
        "esModuleInterop": true,
        "noImplicitAny": false,
        "sourceMap": true,
        "baseUrl": ".",
        "outDir": "dist",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "paths": {
          "*": ["node_modules/*"],
          "@app/*": ["./src/app/*"],
          "@static/*": ["./src/static/*"],
          "@src/*": ["./src/*"]
        }
      },
      "include": ["src/**/*"]
    }

devDependencies : 

    "@electron-forge/cli": "6.0.0-beta.53",
    "@electron-forge/maker-deb": "6.0.0-beta.53",
    "@electron-forge/maker-rpm": "6.0.0-beta.53",
    "@electron-forge/maker-squirrel": "6.0.0-beta.53",
    "@electron-forge/maker-zip": "6.0.0-beta.53",
    "@electron-forge/plugin-webpack": "6.0.0-beta.53",
    "electron": "^11.2.1",
    "typescript": "^4.0.2",
    "webpack": "4"

dependencies:

    "libp2p": "^0.30.4",
    "libp2p-kad-dht": "^0.20.6",

- node version: v14.5.0
- O.S. : Ubuntu 18.04.4 Desktop

I discovered that this happens also when importing another libp2p library:

    //const Libp2p = require('libp2p');
    const KadDHT = require('libp2p-kad-dht');

Here I've put the simple repo, so you can check yourself and easily spot the problem: https://github.com/raphael10-collab/OnlyLibp2p

Just git clone it ----> yarn ---> yarn start

**Comment by vasco-santos** [comment]
This is related to the electron app using the browser implementation of `multihashing-async` https://github.com/multiformats/js-multihashing-async/blob/master/src/sha.browser.js 

@hugomrdias can I have your input here?

**Comment by hugomrdias** [comment]
@raphael10-collab why are you bundling your main with renderer target?

**Comment by raphael10-collab** [comment]
@hugomrdias in a renderer process I cannot use require. This is why I tried `const Libp2p = require('libp2p');`
in main.ts.

Please just tell me how to proceed, and I will be happy to close the issue

**Comment by raphael10-collab** [comment]
Using import instead of require in the renderer process resolve the issue:

    import Libp2p from 'libp2p';
    import KadDHT from 'libp2p-kad-dht';

**Comment by raphael10-collab** [comment]
@hugomrdias 
Following the "libp2p in the browser" example: https://github.com/libp2p/js-libp2p/blob/master/examples/libp2p-in-the-browser/index.js

I'm getting the "require is not defined" error.

In the renderer : /src/app/components/App.tsx :  

    import Libp2p from 'libp2p'
    import Websockets from 'libp2p-websockets'
    import WebRTCStar from 'libp2p-webrtc-star'
    import { NOISE } from 'libp2p-noise'
    import Mplex from 'libp2p-mplex'
    import Bootstrap from 'libp2p-bootstrap'

The following are the lines causing the error:

    const createNode = async () => {
      const node = await Libp2p.create({
        addresses: {
          listen: ['/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star']
        },
      })
    }


![image](https://user-images.githubusercontent.com/70313067/106128709-e5325300-615f-11eb-9040-d816402c53eb.png)


    ERROR in src/app/components/App.tsx:25:36
    TS2345: Argument of type '{ addresses: { listen: string[]; }; }' is not assignable to parameter of type 'Libp2pOptions &     
    CreateOptions'.
      Type '{ addresses: { listen: string[]; }; }' is missing the following properties from type 'Libp2pOptions': modules, peerId
        23 | 
        24 | const createNode = async () => {
     > 25 |   const node = await Libp2p.create({
           |                                    ^
      > 26 |     addresses: {
           | ^^^^^^^^^^^^^^^^
      > 27 |       listen: ['/ip4/0.0.0.0/tcp/0']
           | ^^^^^^^^^^^^^^^^
      > 28 |     },
           | ^^^^^^^^^^^^^^^^
      > 29 |   })
           | ^^^^
        30 | }
        31 | 
        32 |

**Comment by hugomrdias** [comment]
@raphael10-collab 
Renderer:
you need to either enable `nodeIntegration` or change the webpack renderer config target to `web`
Main: 
i can't replicate your error you should check your webpack config because its trying to load browser files. 
tried a clean electron-forge webpack setup and both require and import work.

@vasco-santos 
two issues i found with electron-forge setup:
- we should see if we can make libp2p work without node integration or webpack target: 'web' probably not but might be possible 
  - with the default target `events` is being marked as external by webpack and its still webpack 4
- libp2p-noise doesnt work with electron-forge default webpack template because of the native modules
  - something to do with this package https://github.com/vercel/webpack-asset-relocator-loader#readme needs further investigation

**Comment by raphael10-collab** [comment]
@hugomrdias For security reasons I must keep nodeIntegration disabled. 

Even if it seems that for Electron apps the webpack renderer config target should be 'electron-renderer' : 
    https://webpack.js.org/configuration/target/
 I tried to set it as 'web'  in /tools/webpack/webpack.renderer.js

But again, these lines in /src/app/components/App.tsx 

    const createNode = async () => {
      const node = await Libp2p.create({
        addresses: {
          listen: ['/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star']
        },
      })
    }

cause this error:


    ERROR in src/app/components/App.tsx:15:36
    TS2345: Argument of type '{ addresses: { listen: string[]; }; }' is not assignable to parameter of type 'Libp2pOptions &     
    CreateOptions'.
      Type '{ addresses: { listen: string[]; }; }' is missing the following properties from type 'Libp2pOptions': modules, peerId
        13 | 
        14 | const createNode = async () => {
      > 15 |   const node = await Libp2p.create({
           |                                    ^
      > 16 |     addresses: {
           | ^^^^^^^^^^^^^^^^
      > 17 |       listen: ['/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star']
           | ^^^^^^^^^^^^^^^^
      > 18 |     },
           | ^^^^^^^^^^^^^^^^
      > 19 |   })
           | ^^^^
        20 | }

What do you mean as clean electron-forge webpack setup?
How to make it clean? https://github.com/raphael10-collab/OnlyLibp2p/tree/master/tools/webpack

**Comment by hugomrdias** [comment]
i just used this https://www.electronforge.io/templates/webpack-template

that error is a TS error and its telling you that you are missing some properties, add those options to the config and it will go way.

**Comment by vasco-santos** [comment]
@raphael10-collab  it seems that there is a bug in the types as the `PeerId` should not be required. I will soon look into that. The modules are mandatory though. Please look into https://github.com/libp2p/js-libp2p/blob/master/doc/GETTING_STARTED.md

For now, you can be unblocked by creating the PeerId.

```js
const PeerId = require('peerId')

// ...
const peerId = await PeerId.create()
const libp2p = await Libp2p.create({
  peerId,
  modules,
  addresses
})
```

**Comment by raphael10-collab** [comment]
Using as reference the webpack configuration that comes out from here: 
  my-new-app: https://www.electronforge.io/templates/webpack-template  , 

I tried to comment the parts of the webpack config which are not present in my-new-app: 

- webpack.main.js  :  

  Commenting this extra part:

      //resolve: {
        //extensions: ['.js', '.ts', '.jsx', '.tsx', '.css', '.json'],
        //alias: require('./webpack.aliases'),
      //},
      // https://github.com/electron/electron/issues/9920
      //target: 'electron-renderer'

  doesn't resolve the error messages: 

    ERROR in src/app/components/App.tsx:15:36
    TS2345: Argument of type '{ addresses: { listen: string[]; }; }' is not assignable to parameter of type 'Libp2pOptions &     
    CreateOptions'.
      Type '{ addresses: { listen: string[]; }; }' is missing the following properties from type 'Libp2pOptions': modules, peerId
        13 | 
        14 | const createNode = async () => {
      > 15 |   const node = await Libp2p.create({
           |                                    ^
      > 16 |     addresses: {
           | ^^^^^^^^^^^^^^^^
      > 17 |       listen: ['/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star']
           | ^^^^^^^^^^^^^^^^


- the loaders in webpack.rules.js but, as foreseen, it complains that without loaders it cannot load and read ts and css files.

    A JavaScript error occurred in the main process
    Uncaught Exception:
    Error: Module parse failed: Unexpected token (30:8)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See     
    https://webpack.js.org/concepts#loaders
    | 
    | 
    > declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
    | declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
    | 
        at Object../src/main.ts (/home/marco/webMatters/electronMatters/OnlyLibp2p/.webpack/main/index.js:97:7)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/OnlyLibp2p/.webpack/main/index.js:21:30)
        at Object.0 (/home/marco/webMatters/electronMatters/OnlyLibp2p/.webpack/main/index.js:108:18)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/OnlyLibp2p/.webpack/main/index.js:21:30)
        at /home/marco/webMatters/electronMatters/OnlyLibp2p/.webpack/main/index.js:85:18
        at Object.<anonymous> (/home/marco/webMatters/electronMatters/OnlyLibp2p/.webpack/main/index.js:88:10)
        at Module._compile (internal/modules/cjs/loader.js:1152:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
        at Module.load (internal/modules/cjs/loader.js:992:32)
        at Module._load (internal/modules/cjs/loader.js:885:14)


- webpack.renderer.js  : 
I also realized that what activates, but I don't think "causes", the error message:

    ERROR in src/app/components/App.tsx:15:36
    TS2345: Argument of type '{ addresses: { listen: string[]; }; }' is not assignable to parameter of type 'Libp2pOptions &     
    CreateOptions'.
      Type '{ addresses: { listen: string[]; }; }' is missing the following properties from type 'Libp2pOptions': modules, peerId
        13 | 
        14 | const createNode = async () => {
      > 15 |   const node = await Libp2p.create({
           |                                    ^
      > 16 |     addresses: {
           | ^^^^^^^^^^^^^^^^
      > 17 |       listen: ['/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star']
           | ^^^^^^^^^^^^^^^^
      > 18 |     },
           | ^^^^^^^^^^^^^^^^
      > 19 |   })
           | ^^^^
        20 | }

is this line in webpack.renderer.js :  

    extensions: ['.js', '.ts', '.jsx', '.tsx', '.css'],

but commenting this line produces this error:

![image](https://user-images.githubusercontent.com/70313067/106144367-64318680-6174-11eb-99f0-56c6bea7bc6b.png)



So I do not think that the webpack configuration that I took from here: https://github.com/codesbiome/electron-react-webpack-typescript-2021 , and which respects all the webpack rules: https://v4.webpack.js.org/configuration/, and that I've been using without any problems for electron-react-typescript apps, is the main cause of this error:


    ERROR in src/app/components/App.tsx:15:36
    TS2345: Argument of type '{ addresses: { listen: string[]; }; }' is not assignable to parameter of type 'Libp2pOptions &     
    CreateOptions'.
      Type '{ addresses: { listen: string[]; }; }' is missing the following properties from type 'Libp2pOptions': modules, peerId
        13 | 
        14 | const createNode = async () => {
      > 15 |   const node = await Libp2p.create({
           |                                    ^
      > 16 |     addresses: {
    ERROR in src/app/components/App.tsx:15:36
    TS2345: Argument of type '{ addresses: { listen: string[]; }; }' is not assignable to parameter of type 'Libp2pOptions &     
    CreateOptions'.
      Type '{ addresses: { listen: string[]; }; }' is missing the following properties from type 'Libp2pOptions': modules, peerId
        13 | 
        14 | const createNode = async () => {
      > 15 |   const node = await Libp2p.create({
           |                                    ^
      > 16 |     addresses: {
           | ^^^^^^^^^^^^^^^^
      > 17 |       listen: ['/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star']
           | ^^^^^^^^^^^^^^^^
      > 18 |     },
           | ^^^^^^^^^^^^^^^^
      > 19 |   })
           | ^^^^
        20 | }
           | ^^^^^^^^^^^^^^^^
      > 17 |       listen: ['/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star']
           | ^^^^^^^^^^^^^^^^
      > 18 |     },
           | ^^^^^^^^^^^^^^^^
      > 19 |   })
           | ^^^^
        20 | }

**Comment by vasco-santos** [comment]
@raphael10-collab have you seen my previous comment? Did you update the config to have all its required properties?

**Comment by vasco-santos** [comment]
FYI the `peer-id` being required by the types is not an issue anymore. You just need to provide the required modules as you can see in the Getting started document or API document.

Closing this issue, feel free to re-open if this is still a problem

**Comment by raphael10-collab** [comment]
@vasco-santos I realized that without `target: 'web'` in webpack.renderer.js I get the error: 

    'require is not defined'

![image](https://user-images.githubusercontent.com/70313067/106177092-6279ba00-6198-11eb-9c75-36d0ec49bfdd.png)

Is there a specific reason why for libp2p the target in webpack.renderer.js has to be set as 'web'?

**Comment by vasco-santos** [comment]
> Is there a specific reason why for libp2p the target in webpack.renderer.js has to be set as 'web'?

There are two possibilities here. Or you need to enable nodeIntegration or use target to web, in order to properly create your build.
