### ISSUE TITLE
Electron forge setup problems

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#874]
For better visibility.

---

by @hugomrdias in #873 

two issues i found with electron-forge setup:

- we should see if we can make libp2p work without node integration or webpack target: 'web' probably not but might be possible
  - with the default target events is being marked as external by webpack and its still webpack 4
- libp2p-noise doesnt work with electron-forge default webpack template because of the bcrypto native modules
  - something to do with this package https://github.com/vercel/webpack-asset-relocator-loader#readme needs further investigation

---

also cc @mpetrunic

**Comment by dmitryame** [comment]
have you found a solution to your problem? I'm running into similar issues.

**Comment by mpetrunic** [comment]
libp2p-noise should work now as we dropped bcrypto

**Comment by maschad** [comment]
Closing as fixed as referenced by [@mpetrunic 's comment](https://github.com/libp2p/js-libp2p/issues/874#issuecomment-1182175361)
