### ISSUE TITLE
Property 'autoDial' is missing in type '{ [x: number]: { enabled: true; list: string[]; }; }' but required in type 'PeerDiscoveryOptions'

### ISSUE THREAD

**Issue by raphael10-collab** [libp2p/js-libp2p#876]
In an Electron-Typescript-React app I'm getting this error:

    ERROR in src/app/components/App.tsx:29:7
    TS2741: Property 'autoDial' is missing in type '{ [x: number]: { enabled: true; list: string[]; }; }' but required in type  
    'PeerDiscoveryOptions'.
        27 | 
        28 |     config: {
      > 29 |       peerDiscovery: {
           |       ^^^^^^^^^^^^^
        30 |         // The `tag` property will be searched when creating the instance of your Peer Discovery service.
        31 |         // The associated object, will be passed to the service when it is instantiated.
        32 |         [Bootstrap.tag]: {

This is the code in /src/app/components/App.tsx :  

    import Libp2p from 'libp2p'
    import Websockets from 'libp2p-websockets'
    import WebRTCStar from 'libp2p-webrtc-star'
    import { NOISE } from 'libp2p-noise'
    import Mplex from 'libp2p-mplex'
    import Bootstrap from 'libp2p-bootstrap'

    const createNode = async () => {
      const node = await Libp2p.create({
        addresses: {
          listen: [
            '/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star',
            '/dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star'
          ]
        },
        modules: {
          transport: [Websockets, WebRTCStar],
          connEncryption: [NOISE],
          streamMuxer: [Mplex],
        },

        config: {
          peerDiscovery: {
            // The `tag` property will be searched when creating the instance of your Peer Discovery service.
            // The associated object, will be passed to the service when it is instantiated.
            [Bootstrap.tag]: {
              enabled: true,
              list: [
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp',
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa',
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt'
              ]
            }
          }
        }
      })
    }

/tools/webpack/webpack.renderer.js  :  

    const rules = require('./webpack.rules');
    const plugins = require('./webpack.plugins');
    const aliases = require('./webpack.aliases');

    module.exports = {
      // https://github.com/electron/electron/issues/9920
      //target: 'electron-renderer',
      target: 'web',
      module: {
        rules,
      },
      plugins: plugins,
      resolve: {
        extensions: ['.js', '.ts', '.jsx', '.tsx', '.css'],
        alias: {
          // React Hot Loader Patch
          'react-dom': '@hot-loader/react-dom',
          // Custom Aliases
          ...aliases,
        },
      },
    };

/tools/webpack/webpack.rules.js :  

    const inDev = process.env.NODE_ENV === 'development';

    module.exports = [
      {
        // Add support for native node modules
        test: /\.node$/,
        use: 'node-loader',
      },
      {
        // Webpack asset relocator loader
        test: /\.(m?js|node)$/,
        parser: { amd: false },
        use: {
          loader: '@marshallofsound/webpack-asset-relocator-loader',
          options: {
            outputAssetBase: 'native_modules',
          },
        },
      },
      {
        // Typescript loader
        test: /\.tsx?$/,
        exclude: /(node_modules|\.webpack)/,
        use: {
          loader: 'ts-loader',
          options: {
            transpileOnly: true,
          },
        },
      },
      {
        // CSS Loader
        test: /\.css$/,
        use: [{ loader: 'style-loader' }, { loader: 'css-loader' }],
      },
      {
        // Less loader
        test: /\.less$/,
        use: [
          { loader: 'style-loader' },
          { loader: 'css-loader' },
          { loader: 'less-loader' },
        ],
      },
      {
        // Images Loader
        test: /\.(gif|jpe?g|tiff|png|webp|bmp)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              publicPath: 'images',
              outputPath: inDev ? 'images' : './main_window/images',
            },
          },
        ],
      },
    ];

/tools/webpack/webpack.main.js :  

    module.exports = {
      /**
       * This is the main entry point for your application, it's the first file
       * that runs in the main process.
       */
      entry: ['./src/main.ts'],
      // Put your normal webpack config below here
      module: {
        rules: require('./webpack.rules'),
      },
      resolve: {
        extensions: ['.js', '.ts', '.jsx', '.tsx', '.css', '.json'],
        alias: require('./webpack.aliases'),
      },
      // https://github.com/electron/electron/issues/9920
      target: 'electron-renderer'
    };

/tools/webpack/webpack.plugins.js :  

    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

    // https://stackoverflow.com/questions/44008674/how-to-import-the-electron-ipcrenderer-in-a-react-webpack-2-setup
    const webpack = require('webpack');

    module.exports = [
      new ForkTsCheckerWebpackPlugin(),
      new webpack.ExternalsPlugin('commonjs', [
        'electron'
      ])
    ];

devDependencies :

"@electron-forge/cli": "6.0.0-beta.53",
"@electron-forge/maker-deb": "6.0.0-beta.53",
"@electron-forge/maker-rpm": "6.0.0-beta.53",
"@electron-forge/maker-squirrel": "6.0.0-beta.53",
"@electron-forge/maker-zip": "6.0.0-beta.53",
"@electron-forge/plugin-webpack": "6.0.0-beta.53",
"electron": "^11.2.1",
"typescript": "^4.0.2",
"webpack": "4"

dependencies:

    "libp2p": "^0.30.5",
    "libp2p-bootstrap": "^0.12.1",
    "libp2p-kad-dht": "^0.20.6",
    "libp2p-mplex": "^0.10.1",
    "libp2p-noise": "^2.0.4",
    "libp2p-tcp": "^0.15.2",
    "libp2p-webrtc-star": "^0.21.0",
    "libp2p-websockets": "^0.15.0",

    node version: v14.5.0
    O.S. : Ubuntu 18.04.4 Desktop

**Comment by vasco-santos** [comment]
Thanks for reporting this issue. I will merge a fix soon and you will be able to update libp2p and get it fixed

**Comment by vasco-santos** [comment]
Shipped new libp2p release @raphael10-collab
