### ISSUE TITLE
Expected 2 arguments, but got 5. libp2p.connectionManager.on('peer:connect', (connection)

### ISSUE THREAD

**Issue by raphael10-collab** [libp2p/js-libp2p#879]
In an Electron-Typescript-React app I'm getting these errors:

    TS2554: Expected 2 arguments, but got 5.
        62 | 
        63 |   // Listen for new connections to peers
      > 64 |   libp2p.connectionManager.on('peer:connect', (connection) => {
           |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      > 65 |     log(`Connected to ${connection.remotePeer.toB58String()}`)
           | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      > 66 |   })
           | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      > 67 | 
           | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      > 68 |   // Listen for peers disconnecting
           | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      > 69 |   libp2p.connectionManager.on('peer:disconnect', (connection) => {
           | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      > 70 |     log(`Disconnected from ${connection.remotePeer.toB58String()}`)
           | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      > 71 |   })
           | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      > 72 | 
           | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      > 73 |   await libp2p.start();
           | ^^^^^^^^^^^^^^^^^^^^^^^
        74 |   status.innerText = 'libp2p started!';
        75 |   log(`libp2p id is ${libp2p.peerId.toB58String()}`)
        76 | 

    ERROR in src/app/components/App.tsx:78:10
    TS2339: Property 'libp2p' does not exist on type 'Window & typeof globalThis'.
        76 | 
        77 |   // Export libp2p to the window so you can play with the API
      > 78 |   window.libp2p = libp2p;
           |          ^^^^^^
        79 | 
        80 | })
        81 | 

This is the code in /src/app/components/App.tsx : 

    import Libp2p from 'libp2p'
    import Websockets from 'libp2p-websockets'
    import WebRTCStar from 'libp2p-webrtc-star'
    import { NOISE } from 'libp2p-noise'
    import Mplex from 'libp2p-mplex'
    import Bootstrap from 'libp2p-bootstrap'

    document.addEventListener('DOMContentLoaded', async () => {
      // Create our libp2p node
      const libp2p = await Libp2p.create({
        addresses: {
          listen: [
            '/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star',
            '/dns4/wrtc-star2.sjc.dwebops.pub/tcp/443/wss/p2p-webrtc-star'
          ]
        },
        modules: {
          transport: [Websockets, WebRTCStar],
          connEncryption: [NOISE],
          streamMuxer: [Mplex],
        },
        config: {
          peerDiscovery: {
            // The `tag` property will be searched when creating the instance of your Peer Discovery service.
            // The associated object, will be passed to the service when it is instantiated.
            [Bootstrap.tag]: {
              enabled: true,
              list: [
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp',
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa',
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt'
              ]
            }
          }
        }
      })

      const status = document.getElementById('status');
      const output = document.getElementById('output');

      function log (txt) {
        console.info(txt)
        output.textContent += `${txt.trim()}\n`
      }

      // Listen for new peers
      libp2p.on('peer:discovery', (peerId) => {
        log(`Found peer ${peerId.toB58String()}`)
      }

      // Listen for new connections to peers
      libp2p.connectionManager.on('peer:connect', (connection) => {
        log(`Connected to ${connection.remotePeer.toB58String()}`)
      })

      // Listen for peers disconnecting
      libp2p.connectionManager.on('peer:disconnect', (connection) => {
        log(`Disconnected from ${connection.remotePeer.toB58String()}`)
      })

      await libp2p.start();
      status.innerText = 'libp2p started!';
      log(`libp2p id is ${libp2p.peerId.toB58String()}`)

      // Export libp2p to the window so you can play with the API
      window.libp2p = libp2p;

    })

/tools/webpack/webpack.renderer.js  :  

    const rules = require('./webpack.rules');
    const plugins = require('./webpack.plugins');
    const aliases = require('./webpack.aliases');

    module.exports = {
      // https://github.com/electron/electron/issues/9920
      //target: 'electron-renderer',
      target: 'web',
      module: {
        rules,
      },
      plugins: plugins,
      resolve: {
        extensions: ['.js', '.ts', '.jsx', '.tsx', '.css'],
        alias: {
          // React Hot Loader Patch
          'react-dom': '@hot-loader/react-dom',
          // Custom Aliases
          ...aliases,
        },
      },
    };

/tools/webpack/webpack.rules.js :  

    const inDev = process.env.NODE_ENV === 'development';

    module.exports = [
      {
        // Add support for native node modules
        test: /\.node$/,
        use: 'node-loader',
      },
      {
        // Webpack asset relocator loader
        test: /\.(m?js|node)$/,
        parser: { amd: false },
        use: {
          loader: '@marshallofsound/webpack-asset-relocator-loader',
          options: {
            outputAssetBase: 'native_modules',
          },
        },
      },
      {
        // Typescript loader
        test: /\.tsx?$/,
        exclude: /(node_modules|\.webpack)/,
        use: {
          loader: 'ts-loader',
          options: {
            transpileOnly: true,
          },
        },
      },
      {
        // CSS Loader
        test: /\.css$/,
        use: [{ loader: 'style-loader' }, { loader: 'css-loader' }],
      },
      {
        // Less loader
        test: /\.less$/,
        use: [
          { loader: 'style-loader' },
          { loader: 'css-loader' },
          { loader: 'less-loader' },
        ],
      },
      {
        // Images Loader
        test: /\.(gif|jpe?g|tiff|png|webp|bmp)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              publicPath: 'images',
              outputPath: inDev ? 'images' : './main_window/images',
            },
          },
        ],
      },
    ];

/tools/webpack/webpack.main.js :  

    module.exports = {
      /**
       * This is the main entry point for your application, it's the first file
       * that runs in the main process.
       */
      entry: ['./src/main.ts'],
      // Put your normal webpack config below here
      module: {
        rules: require('./webpack.rules'),
      },
      resolve: {
        extensions: ['.js', '.ts', '.jsx', '.tsx', '.css', '.json'],
        alias: require('./webpack.aliases'),
      },
      // https://github.com/electron/electron/issues/9920
      target: 'electron-renderer'
    };

/tools/webpack/webpack.plugins.js :  

    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

    // https://stackoverflow.com/questions/44008674/how-to-import-the-electron-ipcrenderer-in-a-react-webpack-2-setup
    const webpack = require('webpack');

    module.exports = [
      new ForkTsCheckerWebpackPlugin(),
      new webpack.ExternalsPlugin('commonjs', [
        'electron'
      ])
    ];

devDependencies :

    "@electron-forge/cli": "6.0.0-beta.53",
    "@electron-forge/maker-deb": "6.0.0-beta.53",
    "@electron-forge/maker-rpm": "6.0.0-beta.53",
    "@electron-forge/maker-squirrel": "6.0.0-beta.53",
    "@electron-forge/maker-zip": "6.0.0-beta.53",
    "@electron-forge/plugin-webpack": "6.0.0-beta.53",
    "electron": "^11.2.1",
    "typescript": "^4.0.2",
    "webpack": "4"

dependencies:

    "libp2p": "^0.30.6",
    "libp2p-bootstrap": "^0.12.1",
    "libp2p-kad-dht": "^0.20.6",
    "libp2p-mplex": "^0.10.2",
    "libp2p-noise": "^2.0.4",
    "libp2p-tcp": "^0.15.2",
    "libp2p-webrtc-star": "^0.21.0",
    "libp2p-websockets": "^0.15.0",

- node version: v14.5.0
- O.S. : Ubuntu 18.04.4 Desktop

**Comment by vasco-santos** [comment]
Do you have any repository I can try this out? I cannot replicate this in my local libp2p typescript local project.

`libp2p.connectionManager.on('peer:connect', () => {})` this only have 2 arguments, not 5. The error looks strange.

Regarding ` window.libp2p = libp2p;` it fails because window as no libp2p as the error mentions. You will need to add a ts ignore comment on this to go around the issue

**Comment by raphael10-collab** [comment]
@vasco-santos I've put the simple repo here: https://github.com/raphael10-collab/Libp2pPlaying

Just git clone it ----> yarn ---> yarn start

**Comment by vasco-santos** [comment]
There is an issue in the code, more precisely:

```js
// Listen for new peers
  libp2p.on('peer:discovery', (peerId) => {
    log(`Found peer ${peerId.toB58String()}`)
  }
```

Should be

```js
// Listen for new peers
  libp2p.on('peer:discovery', (peerId) => {
    log(`Found peer ${peerId.toB58String()}`)
  })
```

This is basically making all further lines part of this function

**Comment by raphael10-collab** [comment]
@vasco-santos Solved. It was my mistake.

Thank you very much for your kind support
