### ISSUE TITLE
Warning ipfs > ipfs-core > libp2p > promisify-es6@1.0.3: Unmaintained

### ISSUE THREAD

**Issue by raphael10-collab** [libp2p/js-libp2p#888]
Installing ipfs : 

Warning ipfs > ipfs-core > libp2p > promisify-es6@1.0.3: Unmaintained

- O.S. : Ubuntu 18.04 Desktop
- node: v14.5.0

**Comment by vasco-santos** [comment]
Thanks for reporting. Would you like to PR libp2p and change this?

**Comment by raphael10-collab** [comment]
@vasco-santos 

Yesterday, which was Sunday, I wrote SIX of those upgrading requests. And received for most of them a "send a PR" as response.
If the library's maintainer thinks it's a low priority to upgrade/maintain her/his library's packages, why its users should send a PR?
Shouldn't be the duty and responsability of the library's maintainers to keep library' packages upgraded/maintained?
It's like my children's room: it' true, we live in the same house, but it's their duty and responsability to keep their room tidy.
If everyone does his/her duty, the house keeps going safe and tidy.

Anyway, if you still think I, as final user of YOUR library, has to make the PR for upgrading the packages your library relies on, whenever I will have spare time, I will do it

**Comment by TJKoury** [comment]
Just submitted a pull. Tests work on my machine, pretty straightforward.

**Comment by BigLep** [comment]
Closing since PR was merged
