### ISSUE TITLE
[Cordova] Cordova + Phonegap TCP Transport

### ISSUE THREAD

**Issue by victorb** [libp2p/js-libp2p#89]
In the browser, we don't have access to TCP Sockets as we do with nodejs. However, when in cordova/phonegap environment, you have access to a webview for running JS but also a plugin architecture, where you can expose native functionality as a JS API. Hence, there could be a transport written for cordova/phonegap in Android/iOS that enables us to have a nodejs-like js-ipfs instance in a webview.

This would help with developing mobile applications for JS developers.

There are some prior art with this as well, https://www.npmjs.com/package/cordova-plugin-chrome-apps-sockets-tcp comes from Google and exposes a sockets API whose interface can be seen here: https://developer.chrome.com/apps/sockets_tcp

There is also https://github.com/blocshop/sockets-for-cordova 

Ideally, the interface exposed by the plugin would be identical to the nodejs interface for sockets, and then https://github.com/libp2p/js-libp2p-tcp could be easily adapted to work.

Existing, similar issues:

- Daemon on Cordova - Android - https://github.com/ipfs/js-ipfs/issues/834
- `ipfs.files.add` callbacks and promises do not resolve on Ionic2 platform - https://github.com/ipfs/js-ipfs/issues/802

**Comment by dryajov** [comment]
Seems like the APIs are quite different among those plugins and the on that js-libp2p-tcp uses -which is Node's. We can either write a new transport specific for cordova or shim the node api on top of one of those plugins.

**Comment by dryajov** [comment]
Looks like there is a node api plugin for cordova already - https://github.com/feross/chrome-net :)

**Comment by diasdavid** [comment]
That chrome net is a great find @dryajov. We can actually enable js-ipfs to just take in a whole custom libp2p instance so that runtimes like Cordoba can use the caps they have.

@xSkyripper, how does that sound? This shouldn't be hard to make it happen.

**Comment by jayarjo** [comment]
Is this still actual? I'd like to familiarize myself with the whole thing on a deeper level and looking for an entry point. I could try to implement this one.

**Comment by jacobheun** [comment]
Having bridges for native transport and peer discovery support would be great, there still currently isn't any. While there are jvm and swift implementations of libp2p in early phases, there would still need to be bridges built for things like Cordova / React Native. 

In theory we should be able to use websockets to run things in a browser build, although I don't believe that's been tested in Cordova. @jayarjo if you'd like to look into getting libp2p running in a mobile build that would be a nice tool for mobile app development.

I think starting with a browser build of libp2p and integrating in native components as needed, or to enhance the experience would be a good path.

**Comment by p-shahi** [comment]
> This would help with developing mobile applications for JS developers.

For now, you can use WebRTC or WebSocket on mobile devices. We're not officially supporting Cordova anytime soon (if community members want to hack it to work, we're happy to review PRs/provide assistance.)
