### ISSUE TITLE
libp2p in docker - Error occurred during XX handshake

### ISSUE THREAD

**Issue by pascalverlinden** [libp2p/js-libp2p#892]
- **Version**: 0.30.8
- **Platform**: docker / Ubuntu 
- **Subsystem**:

#### Description:
Trying out the tutorial of js-libp2p in docker, in order to ping a libp2p node from another one.
The problem I'm facing is apparently related to the use of the multiaddresses if running in a docker container. 
Any help would be much appreciated. 

One node is listening, below is the log:

```
libp2p has started
listening on addresses:
/ip4/127.0.0.1/tcp/3000/p2p/QmTVVgVqWtU2uqxMsumxh8nFKmQdRSZTbCcCFmmTktQ6Vk
 ```
Then I start the other node and pass the address of the first one:

```
npm start /ip4/127.0.0.1/tcp/3000/p2p/QmTVVgVqWtU2uqxMsumxh8nFKmQdRSZTbCcCFmmTktQ6Vk

> p2plib-test@1.0.0 start /home/app
> node src/ "/ip4/127.0.0.1/tcp/3000/p2p/QmTVVgVqWtU2uqxMsumxh8nFKmQdRSZTbCcCFmmTktQ6Vk"

libp2p has started
listening on addresses:
/ip4/127.0.0.1/tcp/3000/p2p/QmWGHNfjdVE5xAfHrJNYqnspQWfbxgdJGK4f2f2FpDjtUu
pinging remote peer at /ip4/127.0.0.1/tcp/3000/p2p/QmTVVgVqWtU2uqxMsumxh8nFKmQdRSZTbCcCFmmTktQ6Vk
(node:65) UnhandledPromiseRejectionWarning: AggregateError: 
    Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Peer ID doesn't match libp2p public key.
        at Noise.performXXHandshake (/home/app/node_modules/libp2p-noise/dist/src/noise.js:169:19)
        at async Noise.performHandshake (/home/app/node_modules/libp2p-noise/dist/src/noise.js:140:20)
        at async Noise.secureOutbound (/home/app/node_modules/libp2p-noise/dist/src/noise.js:63:27)
        at async Upgrader._encryptOutbound (/home/app/node_modules/libp2p/src/upgrader.js:394:12)
        at async Upgrader.upgradeOutbound (/home/app/node_modules/libp2p/src/upgrader.js:167:11)
        at async ClassIsWrapper.dial (/home/app/node_modules/libp2p-tcp/src/index.js:42:18)
        at async TransportManager.dial (/home/app/node_modules/libp2p/src/transport-manager.js:111:14)
        at async /home/app/node_modules/libp2p/src/dialer/dial-request.js:70:18
        at async /home/app/node_modules/p-some/index.js:53:19
    at maybeSettle (/home/app/node_modules/p-some/index.js:31:11)
    at /home/app/node_modules/p-some/index.js:69:23

```

#### Steps to reproduce the error:

I use docker and docker-compose. 
Instead of using 1 single docker-compose file with the 2 services (which I tried also, without result either), one for each node, I separated them in 2 distinct repo's with their own docker-compose file. I created a network p2p-net and use this in both docker-compose files
Then I start the 2 nodes, each in a terminal, as shown above.

I did another test replacing the port 3000 by the port on the host it is mapped to, as defined in the docker-compose file, which also fails.

In another setup with 1 docker-compose file I also tried to use dns4 instead of ip4, again without result.

Attached are the 2 docker-compose files (changed the extension because it seems I cannot upload a .yml file)

[docker-compose.yml.txt](https://github.com/libp2p/js-libp2p/files/6037052/docker-compose.yml.txt)
[docker-compose.yml.txt](https://github.com/libp2p/js-libp2p/files/6037056/docker-compose.yml.txt)

**Comment by jacobheun** [comment]
In addition to replacing the port of the other container did you also replace the IP? 

The first error you linked is because the node doing the dialing ends up dialing itself, which fails because it's not the peer it's expecting. `127.0.0.1` is always local to the container so it won't dial another one. In order to connect to the other container you need its correct IP address on your network.

When you setup `p2p-net` did you get different addresses listed by libp2p when it started? You're going to need to replace `127.0.0.1` with the IP of the `p2p-net` network, I'm not sure if that network interface is picked up by Node.js when libp2p starts. If it's not listed in the startup log then Node.js isn't detecting the interface.

**Comment by pascalverlinden** [comment]
Thanks @jacobheun !
I looked up the IP address of the containers in the docker network, and changed the listen address in the source code to use that IP, e.g. `listen: ['/ip4/172.29.0.2/tcp/3001']` with `3001` being the port of the container.
Did that in the other node as well. 
The first node reports it is listening at `/ip4/172.29.0.2/tcp/3001/p2p/QmbqAopEXhTmPpUABLg4BSC4SV9hYsqdEEvmAVW2qqMmwj`
And when I pass this to the second node, it was able to ping the first node at that address.
