### ISSUE TITLE
Uncaught Error: Cannot find module 'multicodec/src/base-table.js'

### ISSUE THREAD

**Issue by Funarp** [libp2p/js-libp2p#895]
Node: v14.15.4
OS: Linux 5.9.16-1-MANJARO
libp2p: ^0.30.9
when i enter: `const Libp2p = require('libp2p')`
I got errors:

Uncaught Error: Cannot find module 'multicodec/src/base-table.js'
Require stack:
- /home/funarp/learn/libp2p/node_modules/cids/src/index.js
- /home/funarp/learn/libp2p/node_modules/peer-id/src/index.js
- /home/funarp/learn/libp2p/node_modules/libp2p/src/index.js
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/funarp/learn/libp2p/node_modules/cids/src/index.js',
    '/home/funarp/learn/libp2p/node_modules/peer-id/src/index.js',
    '/home/funarp/learn/libp2p/node_modules/libp2p/src/index.js',
    '<repl>'
  ]
}

what should i do?

**Comment by jacobheun** [comment]
Can you list your package.json dependencies? You may have a version conflict

**Comment by Funarp** [comment]
> Can you list your package.json dependencies? You may have a version conflict

I just installed libp2p

{
  "name": "libp2p_learn",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "libp2p": "^0.30.9"
  }
}

**Comment by Funarp** [comment]
and I try both `npm install libp2p` and `yarn add libp2p`, and node 15 or 14(LTS), I also have C/C++ build tools installed

**Comment by jacobheun** [comment]
`multicodec` accidentally released a breaking change in a patch, coordinating with them on a fix

**Comment by Funarp** [comment]
> `multicodec` accidentally released a breaking change in a patch, coordinating with them on a fix

should I downgrade multicodec or wait for libp2p to fix this?

**Comment by Funarp** [comment]
I found a way to fix this: `npm install multicodec@2.1.0` after `npm install libp2p`, but why? npm should handle multicodec version problem, and libp2p's package.json is multicodec with 2.1.0 version

**Comment by jacobheun** [comment]
A patch was released in multicodec, 2.1.3 that fixes the issue. So you can remove multicodec from your modules list and just install libp2p.

Your fix works because you're effectively locking multicodec @2.1.0, npm will avoid installing the broken patch. libp2p doesn't lock dependency versions, so when a patch release comes out and you install, you get that version, this is intended.

Closing this as the underlying issue with multicodec was resolved.
