### ISSUE TITLE
Metrics movingAverages getter not returning a proper clone

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#898]
https://github.com/libp2p/js-libp2p/blob/v0.30.9/src/metrics/stats.js#L87

A manual clone should be created. Referenced in https://github.com/libp2p/js-libp2p/pull/897#discussion_r590484228

**Comment by koozcoo** [comment]
Hello, is this issue still relevant ? I am interested to be involved in this repo. Is there any live chat where we can discuss such things ? The discord invite seems outdated and on matrix #libp2p I can't reach anyone related to this project. Thank you

**Comment by maschad** [comment]
Closing as this no longer relevant
