### ISSUE TITLE
findProviders should return PeerIDs

### ISSUE THREAD

**Issue by Gozala** [libp2p/js-libp2p#899]
findProviders returns `{ id: PeerId, multiaddrs: Multiaddr[] }`

https://github.com/libp2p/js-libp2p/blob/8e1fc78353cba194c86102dafcd68373b3f9a796/src/content-routing/index.js#L43-L52

While bitswap seems to assume it returns `PeerId`s instead. For more context please see

https://github.com/ipfs/js-ipfs-bitswap/pull/261/files#r587862380

**Comment by vasco-santos** [comment]
The link does not properly route me to the correct place I think.

This returns an async iterable if `{{ id: PeerId, multiaddrs: Multiaddr[] }`. In bitswap it seems to return `@returns {AsyncIterable<Provider>}` where Provider is:

```
 * @typedef {Object} Provider
 * @property {PeerId} id
 * @property {Multiaddr[]} multiaddrs
```

I did not understand the inconsistency here. Let me know what I am missing

**Comment by Gozala** [comment]
Here is the snapshot of the conversation in that pull 

![image](https://user-images.githubusercontent.com/21236/110823974-73155980-8247-11eb-83d3-e5b018fe0c51.png)

As per @achingbrain comment

> `libp2p.contentRouting.findProviders` should return only PeerIDs.
> 
> The idea is that libp2p manages the actual multiaddrs internally and we don't worry about them at this level.

Maybe it's all correct, because types seem to align now https://github.com/ipfs/js-ipfs-bitswap/pull/304

**Comment by vasco-santos** [comment]
I did not see that comment. So, you mean that `findProviders` should return `{AsyncIterable<{peerId: PeerId>}`

Ok, so @achingbrain is right in the sense that libp2p should handle internally the multiaddrs storage in the AddressBook, which is what we currently do.

The [interface](https://github.com/libp2p/js-libp2p-interfaces/tree/master/src/content-routing#findproviders) for contentRouting and peerRouting returns `{AsyncIterable<{peerId: PeerId, multiaddrs: Multiaddr[]>}`

We should discuss this further, I would like to keep the multiaddrs to be returned. Currently, libp2p will auto-dial when multiaddrs are added to the `PeerStore` (and is a new peer). But this will hopefully be removed later on in favour of the connection manager overhaul with proactive dial strategies. With this in mind, it is worth to return the multiaddrs to enable the user to be able to select a specific multiaddr if the user wants to do it. The drawback here is that we might know other multiaddrs from the peer that will not be returned (only the router provider records are returned).

Ideally, users will just dial with `peerId` and libp2p will handle everything given that we in theory will have addresses. But, we might also discover peers that are not advertising any multiaddr, so we will have no multiaddrs for it, and the user can try to dial it and libp2p will fail with "no addresses for the peer", which will be odd.

With all things considered, and as bitswap is not blocked on this, I would punt a decision here for after the connManager work + rendezvous/DHT

**Comment by vasco-santos** [comment]
I will move the issue to the interfaces repo, as this will mean changing the interface
