### ISSUE TITLE
Libp2p dialer should try to find multiaddrs for a given peer if it does not know any

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p#901]
- **Version**:  N/A
- **Platform**: N/A
- **Subsystem**: Dialer

#### Description:

We currently recommend users to do `libp2p.dial(peerId)` to dial peers. This will obviously fail if multiaddrs for the given peer were not previously added to the addressBook (either manually, or via a discovery mechanism/DHT/rendezvous...)

If libp2p has a `peer-routing` module, it should perform a lookup in order to try to find multiaddrs for the given peer, before simply failing with "no available multiaddrs for the given peer"

Context: https://github.com/libp2p/js-libp2p-interfaces/issues/85

**Comment by maschad** [comment]
This beyond the scope of the dial functionality, will not fix.
