### ISSUE TITLE
libp2p-noise Can't download

### ISSUE THREAD

**Issue by xzy-96** [libp2p/js-libp2p#907]
![image](https://user-images.githubusercontent.com/51942062/112776816-3cc34100-9073-11eb-9414-805a74c1856b.png)

**Comment by vasco-santos** [comment]
Hello @xzy-96 
Libp2p uses `node-gyp` for compiling native addon modules for Node.js. Python is required as you can see in [nodejs/node-gyp#on-unix](https://github.com/nodejs/node-gyp#on-unix). You will need to install it to properly install libp2p's dependencies

**Comment by vasco-santos** [comment]
@xzy-96 
Could you get this fixed?

**Comment by vasco-santos** [comment]
Closing this. Feel free to reopen if this is still a problem
