### ISSUE TITLE
Triggering protocol once identify is done

### ISSUE THREAD

**Issue by D4nte** [libp2p/js-libp2p#908]
- **Version**: 0.30.10
- **Platform**: Linux 5.10.19-1-MANJARO #1 SMP PREEMPT Fri Feb 26 11:38:34 UTC 2021 x86_64 GNU/Linux
- **Subsystem**: Identify

#### Description:

When Alice connects to a peer that support protocol `/foo/1.0.0`, Alice wants to automatically initiate the message request for said protocol.

Alice dials Bob, once done, Alice triggers the identify protocol with Bob.
Until the identify protocol is done, Alice does not know what protocol Bob implements.
On Alice side, there is no event emitted once the identify protocol is done.
All we can do is check that Alice's `peerStore` now contains Bob's protocols.

I would like to propose emitting an event `peer:identify` once the identify protocol is done and the peer's protocols are now.

Please let me know your thought, am I missing a more obvious solution to my issue?

**Comment by vasco-santos** [comment]
Hello @D4nte 
Once your peer establishes a connection with another peer and the identify protocol finishes, the peer protocols are stored in the Protobook. You can listen for [these changes](https://github.com/libp2p/js-libp2p/blob/master/doc/API.md#known-protocols-for-a-peer-change):

```js
libp2p.peerStore.on('change:protocols', ({ peerId, protocols}) => {
  if (protocols.includes('/foo/1.0.0') { }
})
```

**Comment by D4nte** [comment]
Indeed, I missed this one. Thanks!
