### ISSUE TITLE
Module not found: Can't resolve 'dgram'

### ISSUE THREAD

**Issue by joowh85** [libp2p/js-libp2p#91]
I install some libp2p's packages on my Node.js project and I wrote some codes like below.

const libp2p = require('libp2p')
const TCP = require('libp2p-tcp')
const WS = require('libp2p-websockets')
const spdy = require('libp2p-spdy')
const secio = require('libp2p-secio')
const MulticastDNS = require('libp2p-mdns')
const DHT = require('libp2p-kad-dht')

But the multicast-dns module was occurs some error.

./~/multicast-dns/index.js
Module not found: Can't resolve 'dgram' in '/Users/sangwoojoo/Documents/work/clock-core/node_modules/multicast-dns'

**Comment by diasdavid** [comment]
Which version of npm and nodejs are you using?

**Comment by diasdavid** [comment]
@joowh85 not being able to replicate this one. Could to try with a fresh npm install?
