### ISSUE TITLE
Thinking of using js-libp2p directly in IPFS

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p#92]
Instead of using separate modules ([libp2p-ipfs-nodejs]() and [libp2p-ipfs-browser]()) I'm thinking in just using the base class from within js-ipfs. 

This would mean:

- Fewer points, less maintenance
- Examples would live in this repo
- All the tests would be here, easier to find and maintain
- Easy to ramp up new contributors and users.

Thoughts?

**Comment by dryajov** [comment]
Yeah, it seems like at this point most of the code is pretty portable across node and browsers, so I see no reason for having two distinct entry points in libp2p.

**Comment by pgte** [comment]
In principle I agree, the code in both looks very similar.

**Comment by diasdavid** [comment]
Awesome, thanks for the feedback @pgte and @dryajov. Work is happening here:

- https://github.com/ipfs/js-ipfs/pull/895
- https://github.com/libp2p/js-libp2p/pull/94

Closing this one 👍
