### ISSUE TITLE
Secure WebSockets

### ISSUE THREAD

**Issue by D4nte** [libp2p/js-libp2p#931]
- **Version**: 0.31.0-rc.7
- **Platform**: Linux 5.10.30-1-MANJARO #1 SMP Wed Apr 14 08:07:27 UTC 2021 x86_64 GNU/Linux
- **Subsystem**: Transports (libp2p-websockets)

#### Steps to reproduce the error:

See #930 for the code reproducing the issue.

When trying to setup secure websockets after following the libp2p-websockets test setup: https://github.com/libp2p/js-libp2p-websockets/blob/e9291044a731ee7ba83455b134c3141182073e4f/test/node.js#L296

I am getting the following error:

```
> npm run test ./transports

4.js
node 1 is listening on:
/ip4/127.0.0.1/tcp/10000/ws/p2p/QmTSzDAPTJRqgkG8P6BAhHPvhnbiCRgjf47TPxrgow6PrX
node 2 is listening on:
/home/froyer/src/libp2p/js-libp2p/node_modules/p-some/index.js:31
                        reject(new AggregateError(errors));
                               ^

AggregateError: 
    Error: socket hang up
        at Array.map (<anonymous>)
        at maybeSettle (/home/froyer/src/libp2p/js-libp2p/node_modules/p-some/index.js:31:11)
        at /home/froyer/src/libp2p/js-libp2p/node_modules/p-some/index.js:69:23
        at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at maybeSettle (/home/froyer/src/libp2p/js-libp2p/node_modules/p-some/index.js:31:11)
    at /home/froyer/src/libp2p/js-libp2p/node_modules/p-some/index.js:69:23
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

```

**Comment by BigLep** [comment]
Thanks for letting know.  We'll followup in https://github.com/libp2p/js-libp2p/pull/930
