### ISSUE TITLE
"Error: no protocol with name: chat" when running the chat protocol example

### ISSUE THREAD

**Issue by CluEleSsUK** [libp2p/js-libp2p#932]
- **Version**:
0.31.0-rc.6

- **Platform**:
MacOS Big Sur

- **Subsystem**:
Firefox

#### Type:
High

#### Description:
Hi there,
I'm attempting to implement my own protocol using libp2p, and stumbled across the example chat protocol here: https://github.com/libp2p/js-libp2p/blob/v0.27.3/examples/chat/src/dialer.js and the corresponding listener.
I've tried using the code here but am receiving "Error: no protocol with name: chat" in the console.  

Stack trace:
```
Uncaught (in promise) Error: no protocol with name: chat
    Protocols protocols-table.js:22
    stringToStringTuples codec.js:48
    stringToBytes codec.js:220
    fromString codec.js:231
    Multiaddr index.js:55
    getPeer get-peer.js:18
    _dial index.js:494
    dialProtocol index.js:483
    MessageView MessageView.tsx:40
    MessageView MessageView.tsx:46
    React 5
    unstable_runWithPriority scheduler.development.js:468
    React 3
    workLoop scheduler.development.js:417
    flushWork scheduler.development.js:390
    performWorkUntilDeadline scheduler.development.js:157
    js scheduler.development.js:180
    js scheduler.development.js:645
    Webpack 21
```

I noticed that the current version of the `multiaddr` library has a fixed set of protocols it supports, and blows up if you try and construct one using `multiaddr("/my/cool/multi/addr/here")` - could this be related? 

I tried both `dial` and `dialProtocol` to no avail:
```
      const signallingServer = libp2p.transportManager.getAddrs()[0];
      const peerAddr = `${signallingServer}/p2p/${recipient.toB58String()}/chat/1.0.0`
      const { stream, protocol }= await libp2p.dialProtocol(peerAddr, "/chat/1.0.0")
```

and tried implementing a handler like so: (albeit this isn't necessary to dial, is it?)

```
  await myLibp2p.handle("/chat/1.0.0", async ({ stream }) => {
    console.log("testing 1 2 3")
  })
 ```

I looked for a way to add protocols in both libp2p and multiaddr and couldn't see anything, but I apologise if I've missed something obvious!

#### Steps to reproduce the error:
Attempt to dial a peer with a `/chat/1.0.0` multiaddr

**Comment by CluEleSsUK** [comment]
Another code snippet of my creation of a libp2p instance, in case I've done something incorrect there:
```
const bootstrapMultiAddrs = [
  "/dns4/wrtc-star1.par.dwebops.pub/tcp/443/wss/p2p-webrtc-star/p2p/237239857289375235",
  "/dns4/star-signal.cloud.ipfs.team/wss/p2p-webrtc-star",
  "/ip4/127.0.0.1/tcp/13579/http/libp2p-webrtc-star/p2p",
]

async function createLibp2pNode() {
  const node = await libp2p.create({
    addresses: {
      listen: [
        "/ip4/127.0.0.1/tcp/13579/ws/p2p-webrtc-star/",
      ],
    },
    modules: {
      connEncryption: [NOISE],
      streamMuxer: [MPLEX],
      transport: [WebSockets, WebRTCStar],
      peerDiscovery: [Bootstrap],
    },
    config: {
      peerDiscovery: {
        autoDial: true,
        [Bootstrap.tag]: {
          enabled: true,
          list: bootstrapMultiAddrs
        }
      }
    }
  })
  }
  ```

**Comment by vasco-santos** [comment]
Hello @CluEleSsUK 

The libp2p protocol is not part of a multiaddr. A multiaddr in libp2p will be the address of a peer to reach to and establish a libp2p connection in a given transport.

You can see a libp2p protocol handling in the same way as a rest endpoint. A node supporting a given protocol (chat in this case), will need to call `libp2p.handle` where you will code what happens when a connection to another peer as a stream opened with this protocol.

You can see the chat example in the listener: https://github.com/libp2p/js-libp2p/blob/master/examples/chat/src/listener.js#L24

After the listener is running, it will accept libp2p connections to open streams on that protocol. Does this help?

**Comment by CluEleSsUK** [comment]
I have already implemented the `libp2p.handle` listener, as in my last snippet in the OP - I have pasted it here for posterity:
```
  await myLibp2p.handle("/chat/1.0.0", async ({ stream }) => {
    console.log("testing 1 2 3")
  })
  ```

I understand that libp2p is not a part of multiaddr, but my understanding is that multiaddr is a dependency of libp2p and that both `libp2p.dialProtocol` and `libp2p.dial` create multiaddrs from any string passed in:
```ts
    dialProtocol(peer: PeerId | Multiaddr | string, protocols: string[] | string, options?: {
        signal?: AbortSignal | undefined;
    } | undefined): Promise<{
        stream: import("libp2p-interfaces/src/stream-muxer/types").MuxedStream;
        protocol: string;
    }>;
    
    dial(peer: PeerId | Multiaddr | string, options?: {
        signal?: AbortSignal | undefined;
    } | undefined): Promise<Connection>;

```
  Calling `dialProtocol` blows up, but when doing some multiaddr stuff (as can be seen in the stacktrace in the OP)

**Comment by vasco-santos** [comment]
> I understand that libp2p is not a part of multiaddr, but my understanding is that multiaddr is a dependency of libp2p and that both libp2p.dialProtocol and libp2p.dial create multiaddrs from any string passed in:

Yes, but a libp2p protocol is not part of a multiaddr. Per the [chat example](https://github.com/libp2p/js-libp2p/blob/master/examples/chat/src/dialer.js#L33) you can see the dialled multiaddr is the network address of the peer. This will generate a libp2p connection, where we will be opening a stream with the given protocol.

You are doing:

```js
const signallingServer = libp2p.transportManager.getAddrs()[0];
const peerAddr = `${signallingServer}/p2p/${recipient.toB58String()}/chat/1.0.0`
const { stream, protocol }= await libp2p.dialProtocol(peerAddr, "/chat/1.0.0")
```

instead of:

```js
const signallingServer = libp2p.transportManager.getAddrs()[0];
const peerAddr = `${signallingServer}/p2p/${recipient.toB58String()}`
const { stream, protocol }= await libp2p.dialProtocol(peerAddr, "/chat/1.0.0")
```

or

```js
const signallingServer = libp2p.transportManager.getAddrs()[0];
const peerAddr = `${signallingServer}/p2p/${recipient.toB58String()}`
const conn = await libp2p.dial(peerAddr)
const { stream, protocol }= await conn.newStream("/chat/1.0.0")
```

**Comment by CluEleSsUK** [comment]
Ahhhhh sorry, I see what you mean now! That makes total sense, sorry for the confusion.
