### ISSUE TITLE
WebRTC-Star Example 

### ISSUE THREAD

**Issue by sahilpohare** [libp2p/js-libp2p#936]
Guys please add a webrtc-star example.

**Comment by vasco-santos** [comment]
Hello @sahilpohare 

We have the `libp2p-in-the-browser` example, which should be what you are looking for: https://github.com/libp2p/js-libp2p/tree/master/examples/libp2p-in-the-browser

Let me know if this is not the case.

**Comment by vasco-santos** [comment]
Closing, feel free to reopen if this is not what you were looking for
