### ISSUE TITLE
🌟 Make stellar examples for libp2p fun! 🌟

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p#95]
With https://github.com/libp2p/js-libp2p/pull/94, it is now the perfect opportunity to improve libp2p examples.

We need:
- [x] Make every current example create their own bundle (MVP bundle)
- [ ] Create examples for:
  - [x] [Using multiple transports to dial and listen](https://github.com/libp2p/js-libp2p/tree/master/examples/transports)
  - [x] [Protocol and Stream Muxing](https://github.com/libp2p/js-libp2p/tree/master/examples/protocol-and-stream-muxing)
  - [x] [Encrypted Communications](https://github.com/libp2p/js-libp2p/tree/master/examples/encrypted-communications)
  - [x] [PubSub on libp2p](https://github.com/libp2p/js-libp2p/pull/103)
  - [x] [Discovery mechanisms](https://github.com/libp2p/js-libp2p/tree/master/examples/discovery-mechanisms)
  - [x] [PeerRouting and ContentRouting](https://github.com/libp2p/js-libp2p/pull/107)
  - [x] [Does it work in the browser? woot](https://github.com/libp2p/js-libp2p/tree/master/examples/libp2p-in-the-browser)
  - [x] Circuit Relay https://github.com/ipfs/js-ipfs/tree/master/examples/circuit-relaying
  - [ ] NAT Traversal
  - [x] [Building a chat application](https://github.com/libp2p/js-libp2p/tree/master/examples/chat)
  - [x] Build a whiteboard application -- https://github.com/ipfs-shipyard/p2p-flipchart

**Comment by diasdavid** [comment]
I'm assigning myself for this, but help is also welcome :) It requires a good amount of work and review to create powerful examples.

**Comment by VictorBjelkholm** [comment]
As a reference, @whyrusleeping also created a thread on discuss.ipfs.io for collecting this: https://discuss.ipfs.io/t/call-for-libp2p-demos/677/1

I think it'll be really good to have the same examples for both go-libp2p as js-libp2p, so we could write language-independent documentation for libp2p. Bonus points if the examples also work js <> go

We should also flesh out the examples a bit more, "PubSub on libp2p" is a good, broad topic and it'll be more helpful and easier to contribute if we could have some minimal description like "A small chat application that uses pubsub on libp2p to send messages to different channels"

**Comment by diasdavid** [comment]
Thanks @VictorBjelkholm 

> I think it'll be really good to have the same examples for both go-libp2p as js-libp2p

Agreed!

**Comment by diasdavid** [comment]
Cross referencing to: https://github.com/libp2p/go-libp2p/issues/202

**Comment by VictorBjelkholm** [comment]
More examples:

- VOIP
- Webcam sharing ala talky.io

**Comment by diasdavid** [comment]
The ones made so far:

  - [x] [Using multiple transports to dial and listen](https://github.com/libp2p/js-libp2p/tree/master/examples/transports)
  - [x] [Protocol and Stream Muxing](https://github.com/libp2p/js-libp2p/tree/master/examples/protocol-and-stream-muxing)
  - [x] [Encrypted Communications](https://github.com/libp2p/js-libp2p/tree/master/examples/encrypted-communications)
  - [x] [Discovery mechanisms](https://github.com/libp2p/js-libp2p/tree/master/examples/discovery-mechanisms)

**Comment by diasdavid** [comment]
[WIP PubSub](https://github.com/libp2p/js-libp2p/pull/103)

**Comment by diasdavid** [comment]
Another one bites the dust! 
- [x] [Does it work in the browser? woot](https://github.com/libp2p/js-libp2p/tree/master/examples/libp2p-in-the-browser)

**Comment by diasdavid** [comment]
Coming hot right from the Oven!

- [x] [PeerRouting and ContentRouting](https://github.com/libp2p/js-libp2p/pull/107)

**Comment by diasdavid** [comment]
This one is hawt right now

- [x] [PubSub on libp2p](https://github.com/libp2p/js-libp2p/pull/103)

**Comment by diasdavid** [comment]
Pinging @dryajov to see if he would be interested in making the Circuit example :)

**Comment by dryajov** [comment]
@diasdavid absolutely, been putting it off too long already :)

**Comment by sylar217** [comment]
Do we have plans to have example for WebCam/LiveStreaming/VoIP on libp2p?
