### ISSUE TITLE
On opening stream with dialProtocol, a few bytes of random garbage are inserted

### ISSUE THREAD

**Issue by mcclure** [libp2p/js-libp2p#959]
Hello,
I am creating a test app that runs in a browser. A client browser-tab looks up a provider browser-tab using libp2p-kad-dht, then dials it up on a custom protocol using libp2p-mplex. The client tab sends a short query on the stream using it-pipe, and the provider tab reads the query then sends a response on the stream using it-pipe. What I find is that in my tests, one side or the other receives a couple of bytes of garbage before seeing the data the other tab sent.

I don't know if this should be filed as a bug on mplex or on js-libp2p or what. (And I understand communicating using content routing is preferred on web to opening streams, but this is a simple use of the library and should work— and the streams do open, there's just garbage).

**The test**

The test is the [dht-stream-garbage-bytes branch here](https://github.com/mcclure/ts-hello-bug/tree/dht-stream-garbage-bytes). It is a little complicated to run but if you want to run it yourself the instructions are in run.txt. You have to run a webrtc server and a bootstrap node on a server, then put the IP address and multihash of that server in the file BOUNCE-SERVER.js. Open the web app in 2 tabs and open the javascript console in each. After logging in, each tab will print "Encoded:" in the console.log followed by three lines of unicode. This is an encoded DHT key. Copy one of the three lines (they mean the same thing) out of one tab and into the other tab's "connect" box.

At this point:
* The client tab will print "SEARCHING" and the byte array it sent.
* The provider tab will print "KEY QUERY" the byte array it received.
* The provider tab will print "Sending this many bytes of data" and a one or two byte array (it will be longer if the message you typed in was longer).
* The client tab will print "Uleb debug" and the first byte it received.

The "expected behavior" is that "SEARCHING" should equal "KEY QUERY" and "Sending this many bytes of data" should equal "Uleb debug".

But the "Observed behavior":

In my tests, for a brief period the "KEY QUERY" array [received] was the "SEARCHING" array [sent] BUT it was prefixed by two bytes of garbage. The two bytes of garbage were different every time. Eventually, after one recompile, this symptom went away completely and never came back.

Since then, I see a different symptom: "KEY QUERY" is correctly equal to "SEARCHING", but when the provider tab sends its one or two byte array, it is not the value that is seen by the client tab. Instead the client tab sees a garbage byte (this seems to almost always be either 17 or 41— I don't know the significance). Because the app does not understand this byte, it does not look for a second byte.

This is very mysterious, I don't know how to proceed. What should I do to debug this?

Within the code of the demo, [here](https://github.com/mcclure/ts-hello-bug/blob/dht-stream-garbage-bytes/src/index.tsx#L345) is the code path of the "client" (dht search, dial, query) and [here](https://github.com/mcclure/ts-hello-bug/blob/dht-stream-garbage-bytes/src/index.tsx#L133) is the code path for the "provider".

**Comment by mcclure** [comment]
Sorry, i forgot to mention my versions. The versions in my package-lock are:
* Libp2p: 0.31.6
* Libp2p-kad-dht: 0.22.0
* Libp2p-mplex: 0.10.3

**Comment by vasco-santos** [comment]
Hello @mcclure 

On a quick check (not tested at all), I believe you are missing to encode/decode the length-prefixed data in https://github.com/mcclure/ts-hello-bug/blob/dht-stream-garbage-bytes/src/index.tsx#L138

Have a look into the chat example https://github.com/libp2p/js-libp2p/blob/master/examples/chat/src/stream.js#L25  , probably also needs to the write side

**Comment by mcclure** [comment]
Hi @vasco-santos , thank you.

So, I think this misunderstands what the code is doing. I am not using it-length-prefixed. I am prefixing the length myself, using "uleb" (a [variable length int encoding](https://en.wikipedia.org/wiki/LEB128)). The sender [sends itPipe first the uleb-encoded length then the payload](https://github.com/mcclure/ts-hello-bug/blob/dht-stream-garbage-bytes/src/index.tsx#L167), and the receiver [reads the uleb length one byte at a time](https://github.com/mcclure/ts-hello-bug/blob/dht-stream-garbage-bytes/src/index.tsx#L380), then reads a full message of the decoded length.

Is what you are saying that it-pipe **inherently** length-prefixes messages sent to it, and therefore (1) my manual length prefixing is redundant (2) it-length-prefixed is needed to read the length prefixing which is already present?

Note: Because my uleb encoder *is* a relatively complex piece of code which could be a source of bugs, I will try to replace the uleb encoder with a "plain" 32-bit length prefix and post back here.

**Comment by mcclure** [comment]
@vasco-santos , to update , I have simplified the example further. [Here is the new branch](https://github.com/mcclure/ts-hello-bug/tree/dht-stream-garbage-bytes-no-uleb).

The length encoder now encodes a single-byte Uint8Array containing a single number for the length prefix. In this simplified version I still get garbage as the first received byte. So I now have on the sending side:

```
console.log("Sending this many bytes of data", data.byteLength, lengthBuffer[0], lengthBuffer)
return itPipe(
  [lengthBuffer, data],
  stream
)
```

This prints
> Sending this many bytes of data 115 115 Uint8Array [...]
In other words it sends the byte 115 followed by 115 bytes of data. At the receiving end it runs

```
const byteReader = new ItBlByteReader(source)
console.log("RECEIVING FROM FOLLOW")
const length = await ulebLengthFromStream(byteReader)
```
Here ulebLengthFromStream reads one byte and prints out what the byte was, and ItBlByteReader is [this minimal wrapper on AsyncGenerator](https://github.com/mcclure/ts-hello-bug/blob/dht-stream-garbage-bytes-no-uleb/src/bin/byteStream.ts#L109).

When I run this it prints

> RECEIVING FROM FOLLOW
> Fake-uleb debug: Got byte 33

In other words, when I read the length prefix (expected value 115), I got a garbage byte instead of the length prefix.

I also tried sending a 1-length array containing the number "1" as a test. The other side received the byte "33" in this case also (but I imagine it would have been a different random byte if I tried it a few more times).

Unless itPipe is length-prefixing without me asking for length prefixing I don't know where this byte is coming from.

**Comment by vasco-santos** [comment]
Hey @mcclure 

From your stdout it seems like it would be only the first entry of lengthBuffer:

```
console.log("Sending this many bytes of data", data.byteLength, lengthBuffer[0], lengthBuffer)
return itPipe(
  [lengthBuffer[0], data],
  stream
)
```

Anyway, I just did a small test case:

```js
const Libp2p = require('libp2p')
const TCP = require('libp2p-tcp')
const MPLEX = require('libp2p-mplex')
const { NOISE } = require('@chainsafe/libp2p-noise')

const pipe = require('it-pipe')

const createNode = async () => {
  const node = await Libp2p.create({
    addresses: {
      listen: ['/ip4/0.0.0.0/tcp/0']
    },
    modules: {
      transport: [TCP],
      streamMuxer: [MPLEX],
      connEncryption: [NOISE]
    }
  })

  await node.start()

  return node
}

;(async () => {
  const [node1, node2] = await Promise.all([
    createNode(),
    createNode()
  ])

  // Add node's 2 data to the PeerStore
  node1.peerStore.addressBook.set(node2.peerId, node2.multiaddrs)

  // exact matching
  node2.handle('/your-protocol', async ({ stream }) => {
    await pipe(
      stream,
      async function (source) {
        for await (const msg of source) {
          console.log('msg', msg)
        }
      }
    )
  })

  const { stream } = await node1.dialProtocol(node2.peerId, ['/your-protocol'])
  await pipe(
    [new Uint8Array([5]), new Uint8Array([1, 2, 3, 4, 5])],
    stream
  )
})();
```

Which logs:

```
msg BufferList { _bufs: [ <Buffer 05> ], length: 1 }
msg BufferList { _bufs: [ <Buffer 01 02 03 04 05> ], length: 5 }
```

Could you get this example script and change it to try to replicate your situation? It will be easier to diagnose in an isolated stream usage

**Comment by mcclure** [comment]
Thank you, I will attempt this.
I do have a question.
When I run this script locally by itself, it does indeed print:
>> msg BufferList { _bufs: [ <Buffer 05> ], length: 1 }
>> msg BufferList { _bufs: [ <Buffer 01 02 03 04 05> ], length: 5 }
I notice the lengths of the received objects are the same as the length of the sent objects.
Is js-libp2p-mplex a stream of *bytes*?
Or is it a stream of known-length *byte arrays*?
I had been assuming it was a stream of bytes and therefore message length must be encoded separately.
Is js-libp2p-mplex encoding the length of messages *already*?
I do not find an unambiguous answer to that question in either the [js-libp2p-mplex README](https://github.com/libp2p/js-libp2p-mplex) or the [linked stream muxer docs](https://github.com/libp2p/interface-stream-muxer).

**Comment by vasco-santos** [comment]
> Or is it a stream of known-length byte arrays?

Yes, by the protocol itself: https://github.com/libp2p/specs/tree/master/mplex#message-format The message size is also restricted https://github.com/libp2p/js-libp2p-mplex/blob/master/src/restrict-size.js

> Is js-libp2p-mplex transmitting the length of messages already?

So per above yes, but it is transparent for the user. If you want for some reason to also know the lenght, you need to pass it as well.

**Comment by vasco-santos** [comment]
I think the overall problem with your solution is that you are providing a number? to the source:

```js
itPipe(
  [lengthBuffer, data],
  stream
)
```

And it is transformed from number on the wire.

**Comment by mcclure** [comment]
Vasco, I modified your script into a truly minimal example with DHT and web support added (to match the conditions where I saw the garbage bytes). This modified test **worked** without bugs. This implies strongly that the bug is at my end and not in libp2p, probably in my byte-reader wrapper.

(The new/minimal app is at the updated [no-uleb](https://github.com/mcclure/ts-hello-bug/tree/dht-stream-garbage-bytes-no-uleb) branch but it is not useful to look at since it simply works.)

I will do some more testing to make certain of this and then I will close this bug. Thanks so much for the help, sorry to have taken your time over this.

There are some changes that could maybe be made to the documentation that would have helped me understand how to use this correctly earlier. I will file bugs if I can think of any useful suggestions.

> I think the overall problem with your solution is that you are providing a number? to the source:

I don't think this is it, lengthBuffer and data are both Uint8Arrays, it's just that lengthBuffer contains a byte-encoded length. The stdout output "Sending this many bytes of data 115 115 Uint8Array [...]" I posted earlier is posting data.byteLength, then `lengthBuffer[0]`, then lengthBuffer. `lengthBuffer[0]` would be sending a number (115) so `lengthBuffer` unindexed is what I would want to send. I think the error is mine but it is elsewhere, probably in the ItBlByteReader class I wrote.

**Comment by vasco-santos** [comment]
Happy that helped decreasing the debugging surface. Feel free to re-open if you need further discussion regarding this.

I don't have any other ideas of where you should look into without going through all your codebase. So, I would suggest incremental adding your code on top of the branch working until you get to the root issue.

> There are some changes that could maybe be made to the documentation that would have helped me understand how to use this correctly earlier. I will file bugs if I can think of any useful suggestions.

Yes please!
