### ISSUE TITLE
[bug] wrong dependency declaration

### ISSUE THREAD

**Issue by onichandame** [libp2p/js-libp2p#986]
### Problem

The `abortable-iterator` package is a direct dependency as it is required by `src/dialer/index.js`. But it is declared in the `devDependencies` section which results in a missing module error.

### Solution

move `abortable-iterator` from devDeps to deps

**Comment by itseasy21** [comment]
bump

`D:/React-WorkSpace/COSC2410_SEM_2_2021/.yarn/cache/libp2p-npm-0.32.4-fe607aff53-99957c9e00.zip/node_modules/libp2p/src/dialer/index.js
Module not found: libp2p tried to access abortable-iterator, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
`

**Comment by achingbrain** [comment]
Could you open a PR that fixes this please?

**Comment by onichandame** [comment]
I'd like to, but before that, I need to know whether `abortable-iterator` should be a `dependencies` or `peerDependencies`

**Comment by achingbrain** [comment]
`dependencies`
